/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source open api file,
 * and elastic/elastic-client-generator-js to regenerate this file again.
 */

import type { JsonSchemaObject } from '../../../json-schema.ts'
import _inputSchemaRaw from '../../../kibana/json/bulk_upsert_asset_criticality_records.request.json' with { type: 'json' }
import type { KbApiDefinition } from '../types.ts'

const _inputSchema = _inputSchemaRaw as unknown as JsonSchemaObject

export const bulk_upsert_asset_criticality_recordsDefinitions: KbApiDefinition[] = [
  {
    name: 'bulk-upsert-asset-criticality-records',
    namespace: 'security-entity-analytics-api',
    description: 'Bulk upsert asset criticality records',
    method: 'POST',
    path: '/api/asset_criticality/bulk',
    destructive: true,
    input: _inputSchema,
  },
]
