/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source open api file,
 * and elastic/elastic-client-generator-js to regenerate this file again.
 */

import type { KbApiDefinition } from '../types.ts'

export const create_endpoint_listDefinitions: KbApiDefinition[] = [
  {
    name: 'create-endpoint-list',
    namespace: 'security-endpoint-exceptions-api',
    description: 'Create an Elastic Endpoint rule exception list',
    method: 'POST',
    path: '/api/endpoint_list',
    destructive: false,
  },
]
