/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source open api file,
 * and elastic/elastic-client-generator-js to regenerate this file again.
 */

import type { JsonSchemaObject } from '../../../json-schema.ts'
import _inputSchemaRaw from '../../../kibana/json/create_endpoint_list_item.request.json' with { type: 'json' }
import type { KbApiDefinition } from '../types.ts'

const _inputSchema = _inputSchemaRaw as unknown as JsonSchemaObject

export const create_endpoint_list_itemDefinitions: KbApiDefinition[] = [
  {
    name: 'create-endpoint-list-item',
    namespace: 'security-endpoint-exceptions-api',
    description: 'Create an Elastic Endpoint rule exception list item',
    method: 'POST',
    path: '/api/endpoint_list/items',
    destructive: false,
    input: _inputSchema,
  },
]
