/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source open api file,
 * and elastic/elastic-client-generator-js to regenerate this file again.
 */

import type { JsonSchemaObject } from '../../../json-schema.ts'
import _inputSchemaRaw from '../../../kibana/json/security-exceptions-api.create-exception-list.request.json' with { type: 'json' }
import type { KbApiDefinition } from '../types.ts'

const _inputSchema = _inputSchemaRaw as unknown as JsonSchemaObject

export const create_exception_listDefinitions: KbApiDefinition[] = [
  {
    name: 'create-exception-list',
    namespace: 'security-exceptions-api',
    description: 'Create an exception list',
    method: 'POST',
    path: '/api/exception_lists',
    destructive: false,
    input: _inputSchema,
  },
]
