/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source open api file,
 * and elastic/elastic-client-generator-js to regenerate this file again.
 */

import type { JsonSchemaObject } from '../../../json-schema.ts'
import _inputSchemaRaw from '../../../kibana/json/delete_fleet_package_policies_packagepolicyid.request.json' with { type: 'json' }
import type { KbApiDefinition } from '../types.ts'

const _inputSchema = _inputSchemaRaw as unknown as JsonSchemaObject

export const delete_fleet_package_policies_packagepolicyidDefinitions: KbApiDefinition[] = [
  {
    name: 'delete-fleet-package-policies-packagepolicyid',
    namespace: 'fleet-package-policies',
    description: 'Delete a package policy',
    method: 'DELETE',
    path: '/api/fleet/package_policies/{packagePolicyId}',
    destructive: true,
    input: _inputSchema,
  },
]
