/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source open api file,
 * and elastic/elastic-client-generator-js to regenerate this file again.
 */

import type { JsonSchemaObject } from '../../../json-schema.ts'
import _inputSchemaRaw from '../../../kibana/json/security-entity-store.delete-security-entity-store-entities.request.json' with { type: 'json' }
import type { KbApiDefinition } from '../types.ts'

const _inputSchema = _inputSchemaRaw as unknown as JsonSchemaObject

export const delete_security_entity_store_entitiesDefinitions: KbApiDefinition[] = [
  {
    name: 'delete-security-entity-store-entities',
    namespace: 'security-entity-store',
    description: 'Delete an entity',
    method: 'DELETE',
    path: '/api/security/entity_store/entities/',
    destructive: true,
    input: _inputSchema,
  },
]
