/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source open api file,
 * and elastic/elastic-client-generator-js to regenerate this file again.
 */

import type { JsonSchemaObject } from '../../../json-schema.ts'
import _inputSchemaRaw from '../../../kibana/json/slo.delete-rollup-data-op.request.json' with { type: 'json' }
import type { KbApiDefinition } from '../types.ts'

const _inputSchema = _inputSchemaRaw as unknown as JsonSchemaObject

export const delete_rollup_data_opDefinitions: KbApiDefinition[] = [
  {
    name: 'delete-rollup-data-op',
    namespace: 'slo',
    description: 'Batch delete rollup and summary data',
    method: 'POST',
    path: '/s/{spaceId}/api/observability/slos/_bulk_purge_rollup',
    destructive: true,
    input: _inputSchema,
  },
]
