/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source open api file,
 * and elastic/elastic-client-generator-js to regenerate this file again.
 */

import type { JsonSchemaObject } from '../../../json-schema.ts'
import _inputSchemaRaw from '../../../kibana/json/fleet-cloud-connectors.delete-fleet-cloud-connectors-cloudconnectorid.request.json' with { type: 'json' }
import type { KbApiDefinition } from '../types.ts'

const _inputSchema = _inputSchemaRaw as unknown as JsonSchemaObject

export const delete_fleet_cloud_connectors_cloudconnectoridDefinitions: KbApiDefinition[] = [
  {
    name: 'delete-fleet-cloud-connectors-cloudconnectorid',
    namespace: 'fleet-cloud-connectors',
    description: 'Delete cloud connector (supports force deletion)',
    method: 'DELETE',
    path: '/api/fleet/cloud_connectors/{cloudConnectorId}',
    destructive: true,
    input: _inputSchema,
  },
]
