/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source open api file,
 * and elastic/elastic-client-generator-js to regenerate this file again.
 */

import type { JsonSchemaObject } from '../../../json-schema.ts'
import _inputSchemaRaw from '../../../kibana/json/delete_fleet_agents_files_fileid.request.json' with { type: 'json' }
import type { KbApiDefinition } from '../types.ts'

const _inputSchema = _inputSchemaRaw as unknown as JsonSchemaObject

export const delete_fleet_agents_files_fileidDefinitions: KbApiDefinition[] = [
  {
    name: 'delete-fleet-agents-files-fileid',
    namespace: 'elastic-agents',
    description: 'Delete an uploaded file',
    method: 'DELETE',
    path: '/api/fleet/agents/files/{fileId}',
    destructive: true,
    input: _inputSchema,
  },
]
