/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source open api file,
 * and elastic/elastic-client-generator-js to regenerate this file again.
 */

import type { JsonSchemaObject } from '../../../json-schema.ts'
import _inputSchemaRaw from '../../../kibana/json/delete_note.request.json' with { type: 'json' }
import type { KbApiDefinition } from '../types.ts'

const _inputSchema = _inputSchemaRaw as unknown as JsonSchemaObject

export const delete_noteDefinitions: KbApiDefinition[] = [
  {
    name: 'delete-note',
    namespace: 'security-timeline-api',
    description: 'Delete one or more notes',
    method: 'DELETE',
    path: '/api/note',
    destructive: true,
    input: _inputSchema,
  },
]
