/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source open api file,
 * and elastic/elastic-client-generator-js to regenerate this file again.
 */

import type { JsonSchemaObject } from '../../../json-schema.ts'
import _inputSchemaRaw from '../../../kibana/json/find_knowledge_base_entries.request.json' with { type: 'json' }
import type { KbApiDefinition } from '../types.ts'

const _inputSchema = _inputSchemaRaw as unknown as JsonSchemaObject

export const find_knowledge_base_entriesDefinitions: KbApiDefinition[] = [
  {
    name: 'find-knowledge-base-entries',
    namespace: 'security-ai-assistant-api',
    description: 'Finds Knowledge Base Entries that match the given query.',
    method: 'GET',
    path: '/api/security_ai_assistant/knowledge_base/entries/_find',
    destructive: false,
    input: _inputSchema,
  },
]
