/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source open api file,
 * and elastic/elastic-client-generator-js to regenerate this file again.
 */

import type { JsonSchemaObject } from '../../../json-schema.ts'
import _inputSchemaRaw from '../../../kibana/json/fleet-enrollment-api-keys.get-fleet-enrollment-api-keys.request.json' with { type: 'json' }
import type { KbApiDefinition } from '../types.ts'

const _inputSchema = _inputSchemaRaw as unknown as JsonSchemaObject

export const get_fleet_enrollment_api_keysDefinitions: KbApiDefinition[] = [
  {
    name: 'get-fleet-enrollment-api-keys',
    namespace: 'fleet-enrollment-api-keys',
    description: 'Get enrollment API keys',
    method: 'GET',
    path: '/api/fleet/enrollment_api_keys',
    destructive: false,
    input: _inputSchema,
  },
]
