/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source open api file,
 * and elastic/elastic-client-generator-js to regenerate this file again.
 */

import type { JsonSchemaObject } from '../../../json-schema.ts'
import _inputSchemaRaw from '../../../kibana/json/get_workflows_aggs.request.json' with { type: 'json' }
import type { KbApiDefinition } from '../types.ts'

const _inputSchema = _inputSchemaRaw as unknown as JsonSchemaObject

export const get_workflows_aggsDefinitions: KbApiDefinition[] = [
  {
    name: 'get-workflows-aggs',
    namespace: 'workflows',
    description: 'Get workflow aggregations',
    method: 'GET',
    path: '/api/workflows/aggs',
    destructive: false,
    input: _inputSchema,
  },
]
