/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source open api file,
 * and elastic/elastic-client-generator-js to regenerate this file again.
 */

import type { JsonSchemaObject } from '../../../json-schema.ts'
import _inputSchemaRaw from '../../../kibana/json/get_security_entity_store_resolution_group.request.json' with { type: 'json' }
import type { KbApiDefinition } from '../types.ts'

const _inputSchema = _inputSchemaRaw as unknown as JsonSchemaObject

export const get_security_entity_store_resolution_groupDefinitions: KbApiDefinition[] = [
  {
    name: 'get-security-entity-store-resolution-group',
    namespace: 'security-entity-store',
    description: 'Get resolution group',
    method: 'GET',
    path: '/api/security/entity_store/resolution/group',
    destructive: false,
    input: _inputSchema,
  },
]
