/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source open api file,
 * and elastic/elastic-client-generator-js to regenerate this file again.
 */

import type { KbApiDefinition } from '../types.ts'

export const get_default_data_view_defaultDefinitions: KbApiDefinition[] = [
  {
    name: 'get-default-data-view-default',
    namespace: 'data-views',
    description: 'Get the default data view',
    method: 'GET',
    path: '/api/data_views/default',
    destructive: false,
  },
]
