/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source open api file,
 * and elastic/elastic-client-generator-js to regenerate this file again.
 */

import type { JsonSchemaObject } from '../../../json-schema.ts'
import _inputSchemaRaw from '../../../kibana/json/security-entity-analytics-api.get-entity-store-status.request.json' with { type: 'json' }
import type { KbApiDefinition } from '../types.ts'

const _inputSchema = _inputSchemaRaw as unknown as JsonSchemaObject

export const get_entity_store_statusDefinitions: KbApiDefinition[] = [
  {
    name: 'get-entity-store-status',
    namespace: 'security-entity-analytics-api',
    description: 'Get the status of the Entity Store',
    method: 'GET',
    path: '/api/entity_store/status',
    destructive: false,
    input: _inputSchema,
  },
]
