/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source open api file,
 * and elastic/elastic-client-generator-js to regenerate this file again.
 */

import type { JsonSchemaObject } from '../../../json-schema.ts'
import _inputSchemaRaw from '../../../kibana/json/fleet-managed-integrations.get-fleet-managed-integrations-policyid.request.json' with { type: 'json' }
import type { KbApiDefinition } from '../types.ts'

const _inputSchema = _inputSchemaRaw as unknown as JsonSchemaObject

export const get_fleet_managed_integrations_policyidDefinitions: KbApiDefinition[] = [
  {
    name: 'get-fleet-managed-integrations-policyid',
    namespace: 'fleet-managed-integrations',
    description: 'Get a managed integration',
    method: 'GET',
    path: '/api/fleet/managed_integrations/{policyId}',
    destructive: false,
    input: _inputSchema,
  },
]
