/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source open api file,
 * and elastic/elastic-client-generator-js to regenerate this file again.
 */

import type { JsonSchemaObject } from '../../../json-schema.ts'
import _inputSchemaRaw from '../../../kibana/json/connectors.get-actions-connector-connectorid-oauth-start.request.json' with { type: 'json' }
import type { KbApiDefinition } from '../types.ts'

const _inputSchema = _inputSchemaRaw as unknown as JsonSchemaObject

export const get_actions_connector_connectorid_oauth_startDefinitions: KbApiDefinition[] = [
  {
    name: 'get-actions-connector-connectorid-oauth-start',
    namespace: 'connectors',
    description: 'Start OAuth authorization (redirects to the identity provider)',
    method: 'GET',
    path: '/api/actions/connector/{connectorId}/oauth/start',
    destructive: false,
    input: _inputSchema,
  },
]
