/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source open api file,
 * and elastic/elastic-client-generator-js to regenerate this file again.
 */

import type { JsonSchemaObject } from '../../../json-schema.ts'
import _inputSchemaRaw from '../../../kibana/json/maintenance-window.get-maintenance-window-find.request.json' with { type: 'json' }
import type { KbApiDefinition } from '../types.ts'

const _inputSchema = _inputSchemaRaw as unknown as JsonSchemaObject

export const get_maintenance_window_findDefinitions: KbApiDefinition[] = [
  {
    name: 'get-maintenance-window-find',
    namespace: 'maintenance-window',
    description: 'Search for a maintenance window.',
    method: 'GET',
    path: '/api/maintenance_window/_find',
    destructive: false,
    input: _inputSchema,
  },
]
