/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source open api file,
 * and elastic/elastic-client-generator-js to regenerate this file again.
 */

import type { JsonSchemaObject } from '../../../json-schema.ts'
import _inputSchemaRaw from '../../../kibana/json/alerting-v2.get-alerting-v2-action-policies-id.request.json' with { type: 'json' }
import type { KbApiDefinition } from '../types.ts'

const _inputSchema = _inputSchemaRaw as unknown as JsonSchemaObject

export const get_alerting_v2_action_policies_idDefinitions: KbApiDefinition[] = [
  {
    name: 'get-alerting-v2-action-policies-id',
    namespace: 'alerting-v2',
    description: 'Get an action policy',
    method: 'GET',
    path: '/api/alerting/v2/action_policies/{id}',
    destructive: false,
    input: _inputSchema,
  },
]
