/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source open api file,
 * and elastic/elastic-client-generator-js to regenerate this file again.
 */

import type { KbApiDefinition } from '../types.ts'

export const get_agent_configurationsDefinitions: KbApiDefinition[] = [
  {
    name: 'get-agent-configurations',
    namespace: 'apm-agent-configuration',
    description: 'Get a list of agent configurations',
    method: 'GET',
    path: '/api/apm/settings/agent-configuration',
    destructive: false,
  },
]
