/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source open api file,
 * and elastic/elastic-client-generator-js to regenerate this file again.
 */

import type { JsonSchemaObject } from '../../../json-schema.ts'
import _inputSchemaRaw from '../../../kibana/json/fleet-cloud-connectors.get-fleet-cloud-connectors-cloudconnectorid-usage.request.json' with { type: 'json' }
import type { KbApiDefinition } from '../types.ts'

const _inputSchema = _inputSchemaRaw as unknown as JsonSchemaObject

export const get_fleet_cloud_connectors_cloudconnectorid_usageDefinitions: KbApiDefinition[] = [
  {
    name: 'get-fleet-cloud-connectors-cloudconnectorid-usage',
    namespace: 'fleet-cloud-connectors',
    description: 'Get cloud connector usage (package policies using the connector)',
    method: 'GET',
    path: '/api/fleet/cloud_connectors/{cloudConnectorId}/usage',
    destructive: false,
    input: _inputSchema,
  },
]
