/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source open api file,
 * and elastic/elastic-client-generator-js to regenerate this file again.
 */

import type { KbApiDefinition } from '../types.ts'

export const install_privileged_access_detection_packageDefinitions: KbApiDefinition[] = [
  {
    name: 'install-privileged-access-detection-package',
    namespace: 'security-entity-analytics-api',
    description: 'Installs the privileged access detection package for the Entity Analytics privileged user monitoring experience',
    method: 'POST',
    path: '/api/entity_analytics/privileged_user_monitoring/pad/install',
    destructive: true,
  },
]
