/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source open api file,
 * and elastic/elastic-client-generator-js to regenerate this file again.
 */

import type { KbApiDefinition } from '../types.ts'

export const ml_syncDefinitions: KbApiDefinition[] = [
  {
    name: 'ml-sync',
    namespace: 'ml',
    description: 'Sync saved objects in the default space',
    method: 'GET',
    path: '/api/ml/saved_objects/sync',
    destructive: false,
  },
]
