/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source open api file,
 * and elastic/elastic-client-generator-js to regenerate this file again.
 */

import type { JsonSchemaObject } from '../../../json-schema.ts'
import _inputSchemaRaw from '../../../kibana/json/perform_rules_bulk_action.request.json' with { type: 'json' }
import type { KbApiDefinition } from '../types.ts'

const _inputSchema = _inputSchemaRaw as unknown as JsonSchemaObject

export const perform_rules_bulk_actionDefinitions: KbApiDefinition[] = [
  {
    name: 'perform-rules-bulk-action',
    namespace: 'security-detections-api',
    description: 'Apply a bulk action to detection rules',
    method: 'POST',
    path: '/api/detection_engine/rules/_bulk_action',
    destructive: true,
    input: _inputSchema,
  },
]
