/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source open api file,
 * and elastic/elastic-client-generator-js to regenerate this file again.
 */

import type { KbApiDefinition } from '../types.ts'

export const post_saved_objects_resolve_import_errorsDefinitions: KbApiDefinition[] = [
  {
    name: 'post-saved-objects-resolve-import-errors',
    namespace: 'saved-objects',
    description: 'Resolve import errors',
    method: 'POST',
    path: '/api/saved_objects/_resolve_import_errors',
    destructive: true,
    input: { type: 'object', properties: { createNewCopies: { type: 'boolean', description: 'Creates copies of saved objects, regenerates each object ID, and resets the origin.', 'x-found-in': 'query' }, compatibilityMode: { type: 'boolean', description: 'Applies adjustments to maintain compatibility between different Kibana versions.', 'x-found-in': 'query' }, file: { description: '', 'x-found-in': 'body', type: 'string' }, retries: { description: '', 'x-found-in': 'body', type: 'string' } }, required: ['file', 'retries'] },
  },
]
