/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source open api file,
 * and elastic/elastic-client-generator-js to regenerate this file again.
 */

import type { JsonSchemaObject } from '../../../json-schema.ts'
import _inputSchemaRaw from '../../../kibana/json/post_fleet_epm_packages_bulk_rollback.request.json' with { type: 'json' }
import type { KbApiDefinition } from '../types.ts'

const _inputSchema = _inputSchemaRaw as unknown as JsonSchemaObject

export const post_fleet_epm_packages_bulk_rollbackDefinitions: KbApiDefinition[] = [
  {
    name: 'post-fleet-epm-packages-bulk-rollback',
    namespace: 'elastic-package-manager-epm',
    description: 'Bulk rollback packages',
    method: 'POST',
    path: '/api/fleet/epm/packages/_bulk_rollback',
    destructive: true,
    input: _inputSchema,
  },
]
