/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source open api file,
 * and elastic/elastic-client-generator-js to regenerate this file again.
 */

import type { JsonSchemaObject } from '../../../json-schema.ts'
import _inputSchemaRaw from '../../../kibana/json/elastic-agent-actions.post-fleet-agents-bulk-update-agent-tags.request.json' with { type: 'json' }
import type { KbApiDefinition } from '../types.ts'

const _inputSchema = _inputSchemaRaw as unknown as JsonSchemaObject

export const post_fleet_agents_bulk_update_agent_tagsDefinitions: KbApiDefinition[] = [
  {
    name: 'post-fleet-agents-bulk-update-agent-tags',
    namespace: 'elastic-agent-actions',
    description: 'Bulk update agent tags',
    method: 'POST',
    path: '/api/fleet/agents/bulk_update_agent_tags',
    destructive: true,
    input: _inputSchema,
  },
]
