/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source open api file,
 * and elastic/elastic-client-generator-js to regenerate this file again.
 */

import type { JsonSchemaObject } from '../../../json-schema.ts'
import _inputSchemaRaw from '../../../kibana/json/post_fleet_agents_agentid_request_diagnostics.request.json' with { type: 'json' }
import type { KbApiDefinition } from '../types.ts'

const _inputSchema = _inputSchemaRaw as unknown as JsonSchemaObject

export const post_fleet_agents_agentid_request_diagnosticsDefinitions: KbApiDefinition[] = [
  {
    name: 'post-fleet-agents-agentid-request-diagnostics',
    namespace: 'elastic-agent-actions',
    description: 'Request agent diagnostics',
    method: 'POST',
    path: '/api/fleet/agents/{agentId}/request_diagnostics',
    destructive: true,
    input: _inputSchema,
  },
]
