/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source open api file,
 * and elastic/elastic-client-generator-js to regenerate this file again.
 */

import type { KbApiDefinition } from '../types.ts'

export const post_saved_objects_importDefinitions: KbApiDefinition[] = [
  {
    name: 'post-saved-objects-import',
    namespace: 'saved-objects',
    description: 'Import saved objects',
    method: 'POST',
    path: '/api/saved_objects/_import',
    destructive: true,
    input: { type: 'object', properties: { overwrite: { type: 'boolean', description: 'Overwrites saved objects when they already exist. When used, potential conflict errors are automatically resolved by overwriting the destination object. NOTE: This option cannot be used with the `createNewCopies` option.', 'x-found-in': 'query' }, createNewCopies: { type: 'boolean', description: 'Creates copies of saved objects, regenerates each object ID, and resets the origin. When used, potential conflict errors are avoided. NOTE: This option cannot be used with the `overwrite` and `compatibilityMode` options.', 'x-found-in': 'query' }, compatibilityMode: { type: 'boolean', description: 'Applies various adjustments to the saved objects that are being imported to maintain compatibility between different Kibana versions. Use this option only if you encounter issues with imported saved objects. NOTE: This option cannot be used with the `createNewCopies` option.', 'x-found-in': 'query' }, file: { description: 'A file exported using the export API. Changing the contents of the exported file in any way before importing it can cause errors, crashes or data loss. NOTE: The `savedObjects.maxImportExportSize` configuration setting limits the number of saved objects which may be included in this file. Similarly, the `savedObjects.maxImportPayloadBytes` setting limits the overall size of the file that can be imported.', 'x-found-in': 'body', type: 'string' } }, required: ['file'] },
  },
]
