/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source open api file,
 * and elastic/elastic-client-generator-js to regenerate this file again.
 */

import type { JsonSchemaObject } from '../../../json-schema.ts'
import _inputSchemaRaw from '../../../kibana/json/agent-builder.post-agent-builder-conversations-conversation-id-attachments.request.json' with { type: 'json' }
import type { KbApiDefinition } from '../types.ts'

const _inputSchema = _inputSchemaRaw as unknown as JsonSchemaObject

export const post_agent_builder_conversations_conversation_id_attachmentsDefinitions: KbApiDefinition[] = [
  {
    name: 'post-agent-builder-conversations-conversation-id-attachments',
    namespace: 'agent-builder',
    description: 'Create conversation attachment',
    method: 'POST',
    path: '/api/agent_builder/conversations/{conversation_id}/attachments',
    destructive: false,
    input: _inputSchema,
  },
]
