/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source open api file,
 * and elastic/elastic-client-generator-js to regenerate this file again.
 */

import type { KbApiDefinition } from '../types.ts'

export const post_streams_name_content_importDefinitions: KbApiDefinition[] = [
  {
    name: 'post-streams-name-content-import',
    namespace: 'streams',
    description: 'Import content into a stream',
    method: 'POST',
    path: '/api/streams/{name}/content/import',
    destructive: true,
    input: { type: 'object', properties: { name: { type: 'string', description: 'The name of the stream to import content into.', 'x-found-in': 'path' }, content: { description: '', 'x-found-in': 'body', type: 'string' }, include: { description: '', 'x-found-in': 'body', type: 'string' } }, required: ['name', 'content', 'include'] },
  },
]
