/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source open api file,
 * and elastic/elastic-client-generator-js to regenerate this file again.
 */

import type { JsonSchemaObject } from '../../../json-schema.ts'
import _inputSchemaRaw from '../../../kibana/json/context-engine.put-context-engine-ai-index-aiindexid.request.json' with { type: 'json' }
import type { KbApiDefinition } from '../types.ts'

const _inputSchema = _inputSchemaRaw as unknown as JsonSchemaObject

export const put_context_engine_ai_index_aiindexidDefinitions: KbApiDefinition[] = [
  {
    name: 'put-context-engine-ai-index-aiindexid',
    namespace: 'context-engine',
    description: 'Create or update an AI Index',
    method: 'PUT',
    path: '/api/context_engine/ai_index/{aiIndexId}',
    destructive: true,
    readOnly: false,
    input: _inputSchema,
  },
]
