/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source open api file,
 * and elastic/elastic-client-generator-js to regenerate this file again.
 */

import type { JsonSchemaObject } from '../../../json-schema.ts'
import _inputSchemaRaw from '../../../kibana/json/put_security_entity_store_entities_bulk.request.json' with { type: 'json' }
import type { KbApiDefinition } from '../types.ts'

const _inputSchema = _inputSchemaRaw as unknown as JsonSchemaObject

export const put_security_entity_store_entities_bulkDefinitions: KbApiDefinition[] = [
  {
    name: 'put-security-entity-store-entities-bulk',
    namespace: 'security-entity-store',
    description: 'Bulk update entities',
    method: 'PUT',
    path: '/api/security/entity_store/entities/bulk',
    destructive: true,
    input: _inputSchema,
  },
]
