/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source open api file,
 * and elastic/elastic-client-generator-js to regenerate this file again.
 */

import type { KbApiDefinition } from '../types.ts'

export const put_saved_objects_bulk_updateDefinitions: KbApiDefinition[] = [
  {
    name: 'put-saved-objects-bulk-update',
    namespace: 'saved-objects',
    description: 'Update saved objects',
    method: 'PUT',
    path: '/api/saved_objects/_bulk_update',
    destructive: true,
    readOnly: false,
  },
]
