/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source open api file,
 * and elastic/elastic-client-generator-js to regenerate this file again.
 */

import type { JsonSchemaObject } from '../../../json-schema.ts'
import _inputSchemaRaw from '../../../kibana/json/put_fleet_space_settings.request.json' with { type: 'json' }
import type { KbApiDefinition } from '../types.ts'

const _inputSchema = _inputSchemaRaw as unknown as JsonSchemaObject

export const put_fleet_space_settingsDefinitions: KbApiDefinition[] = [
  {
    name: 'put-fleet-space-settings',
    namespace: 'misc',
    description: 'Create space settings',
    method: 'PUT',
    path: '/api/fleet/space_settings',
    destructive: false,
    input: _inputSchema,
  },
]
