/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source open api file,
 * and elastic/elastic-client-generator-js to regenerate this file again.
 */

import type { JsonSchemaObject } from '../../../json-schema.ts'
import _inputSchemaRaw from '../../../kibana/json/put_agent_builder_tools_toolid.request.json' with { type: 'json' }
import type { KbApiDefinition } from '../types.ts'

const _inputSchema = _inputSchemaRaw as unknown as JsonSchemaObject

export const put_agent_builder_tools_toolidDefinitions: KbApiDefinition[] = [
  {
    name: 'put-agent-builder-tools-toolid',
    namespace: 'agent-builder',
    description: 'Update a tool',
    method: 'PUT',
    path: '/api/agent_builder/tools/{toolId}',
    destructive: true,
    input: _inputSchema,
  },
]
