/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source open api file,
 * and elastic/elastic-client-generator-js to regenerate this file again.
 */

import type { JsonSchemaObject } from '../../../json-schema.ts'
import _inputSchemaRaw from '../../../kibana/json/fleet-cloud-onboarding-deployments.put-fleet-cloud-onboarding-deployments-id.request.json' with { type: 'json' }
import type { KbApiDefinition } from '../types.ts'

const _inputSchema = _inputSchemaRaw as unknown as JsonSchemaObject

export const put_fleet_cloud_onboarding_deployments_idDefinitions: KbApiDefinition[] = [
  {
    name: 'put-fleet-cloud-onboarding-deployments-id',
    namespace: 'fleet-cloud-onboarding-deployments',
    description: 'Update cloud onboarding deployment',
    method: 'PUT',
    path: '/api/fleet/cloud_onboarding_deployments/{id}',
    destructive: true,
    input: _inputSchema,
  },
]
