/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source open api file,
 * and elastic/elastic-client-generator-js to regenerate this file again.
 */

import type { KbApiDefinition } from '../types.ts'

export const read_privilegesDefinitions: KbApiDefinition[] = [
  {
    name: 'read-privileges',
    namespace: 'security-detections-api',
    description: 'Returns user privileges for the Kibana space',
    method: 'GET',
    path: '/api/detection_engine/privileges',
    destructive: false,
  },
]
