/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source open api file,
 * and elastic/elastic-client-generator-js to regenerate this file again.
 */

import type { JsonSchemaObject } from '../../../json-schema.ts'
import _inputSchemaRaw from '../../../kibana/json/rule_preview.request.json' with { type: 'json' }
import type { KbApiDefinition } from '../types.ts'

const _inputSchema = _inputSchemaRaw as unknown as JsonSchemaObject

export const rule_previewDefinitions: KbApiDefinition[] = [
  {
    name: 'rule-preview',
    namespace: 'security-detections-api',
    description: 'Preview rule alerts generated on specified time range',
    method: 'POST',
    path: '/api/detection_engine/rules/preview',
    destructive: true,
    input: _inputSchema,
  },
]
