/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source open api file,
 * and elastic/elastic-client-generator-js to regenerate this file again.
 */

import type { JsonSchemaObject } from '../../../json-schema.ts'
import _inputSchemaRaw from '../../../kibana/json/security-detections-api.search-alerts.request.json' with { type: 'json' }
import type { KbApiDefinition } from '../types.ts'

const _inputSchema = _inputSchemaRaw as unknown as JsonSchemaObject

export const search_alertsDefinitions: KbApiDefinition[] = [
  {
    name: 'search-alerts',
    namespace: 'security-detections-api',
    description: 'Find and/or aggregate detection alerts',
    method: 'POST',
    path: '/api/detection_engine/signals/search',
    destructive: true,
    input: _inputSchema,
  },
]
