/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source open api file,
 * and elastic/elastic-client-generator-js to regenerate this file again.
 */

import type { KbApiDefinition } from '../types.ts'

export const sloDefinitions: KbApiDefinition[] = [
  {
    name: 'find-slos-op',
    namespace: 'slo',
    description: 'Get a paginated list of SLOs',
    method: 'GET',
    path: '/s/{spaceId}/api/observability/slos',
    input: { type: 'object', properties: { spaceId: { type: 'string', description: 'The spaceId parameter', 'x-found-in': 'path' }, kqlQuery: { type: 'string', description: 'A valid kql query to filter the SLO with', 'x-found-in': 'query' }, size: { type: 'number', description: 'The page size to use for cursor-based pagination, must be greater or equal than 1', 'x-found-in': 'query' }, searchAfter: { type: 'string', description: 'The cursor to use for fetching the results from, when using a cursor-base pagination.', 'x-found-in': 'query' }, page: { type: 'number', description: 'The page to use for pagination, must be greater or equal than 1', 'x-found-in': 'query' }, perPage: { type: 'number', description: 'Number of SLOs returned by page', 'x-found-in': 'query' }, sortBy: { type: 'string', description: 'Sort by field', 'x-found-in': 'query' }, sortDirection: { type: 'string', description: 'Sort order', 'x-found-in': 'query' }, hideStale: { type: 'boolean', description: 'Hide stale SLOs from the list as defined by stale SLO threshold in SLO settings', 'x-found-in': 'query' } }, required: ['spaceId'] },
  },
  {
    name: 'create-slo-op',
    namespace: 'slo',
    description: 'Create an SLO',
    method: 'POST',
    path: '/s/{spaceId}/api/observability/slos',
    input: { type: 'object', properties: { spaceId: { type: 'string', description: 'The spaceId parameter', 'x-found-in': 'path' }, artifacts: { description: 'Links to related assets for the SLO', 'x-found-in': 'body', type: 'object' }, budgetingMethod: { description: 'The budgeting method to use when computing the rollup data.', 'x-found-in': 'body', type: 'string' }, description: { description: 'A description for the SLO.', 'x-found-in': 'body', type: 'string' }, groupBy: { description: 'optional group by field or fields to use to generate an SLO per distinct value', 'x-found-in': 'body', type: 'object' }, id: { description: 'A optional and unique identifier for the SLO. Must be between 8 and 36 chars', 'x-found-in': 'body', type: 'string' }, indicator: { description: '', 'x-found-in': 'body', type: 'object' }, name: { description: 'A name for the SLO.', 'x-found-in': 'body', type: 'string' }, objective: { description: 'Defines properties for the SLO objective', 'x-found-in': 'body', type: 'object' }, settings: { description: 'Defines properties for SLO settings.', 'x-found-in': 'body', type: 'object' }, tags: { description: 'List of tags', 'x-found-in': 'body' }, timeWindow: { description: 'Defines properties for the SLO time window', 'x-found-in': 'body', type: 'object' } }, required: ['spaceId', 'budgetingMethod', 'description', 'indicator', 'name', 'objective', 'timeWindow'] },
  },
  {
    name: 'bulk-delete-op',
    namespace: 'slo',
    description: 'Bulk delete SLO definitions and their associated summary and rollup data.',
    method: 'POST',
    path: '/s/{spaceId}/api/observability/slos/_bulk_delete',
    input: { type: 'object', properties: { spaceId: { type: 'string', description: 'The spaceId parameter', 'x-found-in': 'path' }, list: { description: 'An array of SLO Definition id', 'x-found-in': 'body' } }, required: ['spaceId', 'list'] },
  },
  {
    name: 'bulk-delete-status-op',
    namespace: 'slo',
    description: 'Retrieve the status of the bulk deletion',
    method: 'GET',
    path: '/s/{spaceId}/api/observability/slos/_bulk_delete/{taskId}',
    input: { type: 'object', properties: { taskId: { type: 'string', description: 'The task id of the bulk delete operation', 'x-found-in': 'path' }, spaceId: { type: 'string', description: 'The spaceId parameter', 'x-found-in': 'path' } }, required: ['taskId', 'spaceId'] },
  },
  {
    name: 'delete-rollup-data-op',
    namespace: 'slo',
    description: 'Batch delete rollup and summary data',
    method: 'POST',
    path: '/s/{spaceId}/api/observability/slos/_bulk_purge_rollup',
    input: { type: 'object', properties: { spaceId: { type: 'string', description: 'The spaceId parameter', 'x-found-in': 'path' }, list: { description: 'An array of slo ids', 'x-found-in': 'body' }, purgePolicy: { description: 'Policy that dictates which SLI documents to purge based on age', 'x-found-in': 'body', type: 'object' } }, required: ['spaceId', 'list', 'purgePolicy'] },
  },
  {
    name: 'delete-slo-instances-op',
    namespace: 'slo',
    description: 'Batch delete rollup and summary data',
    method: 'POST',
    path: '/s/{spaceId}/api/observability/slos/_delete_instances',
    input: { type: 'object', properties: { spaceId: { type: 'string', description: 'The spaceId parameter', 'x-found-in': 'path' }, list: { description: 'An array of slo id and instance id', 'x-found-in': 'body' } }, required: ['spaceId', 'list'] },
  },
  {
    name: 'delete-slo-op',
    namespace: 'slo',
    description: 'Delete an SLO',
    method: 'DELETE',
    path: '/s/{spaceId}/api/observability/slos/{sloId}',
    input: { type: 'object', properties: { spaceId: { type: 'string', description: 'The spaceId parameter', 'x-found-in': 'path' }, sloId: { type: 'string', description: 'The sloId parameter', 'x-found-in': 'path' } }, required: ['spaceId', 'sloId'] },
  },
  {
    name: 'get-slo-op',
    namespace: 'slo',
    description: 'Get an SLO',
    method: 'GET',
    path: '/s/{spaceId}/api/observability/slos/{sloId}',
    input: { type: 'object', properties: { spaceId: { type: 'string', description: 'The spaceId parameter', 'x-found-in': 'path' }, sloId: { type: 'string', description: 'The sloId parameter', 'x-found-in': 'path' }, instanceId: { type: 'string', description: 'the specific instanceId used by the summary calculation', 'x-found-in': 'query' } }, required: ['spaceId', 'sloId'] },
  },
  {
    name: 'update-slo-op',
    namespace: 'slo',
    description: 'Update an SLO',
    method: 'PUT',
    path: '/s/{spaceId}/api/observability/slos/{sloId}',
    input: { type: 'object', properties: { spaceId: { type: 'string', description: 'The spaceId parameter', 'x-found-in': 'path' }, sloId: { type: 'string', description: 'The sloId parameter', 'x-found-in': 'path' }, artifacts: { description: 'Links to related assets for the SLO', 'x-found-in': 'body', type: 'object' }, budgetingMethod: { description: 'The budgeting method to use when computing the rollup data.', 'x-found-in': 'body', type: 'string' }, description: { description: 'A description for the SLO.', 'x-found-in': 'body', type: 'string' }, groupBy: { description: 'optional group by field or fields to use to generate an SLO per distinct value', 'x-found-in': 'body', type: 'object' }, indicator: { description: '', 'x-found-in': 'body', type: 'object' }, name: { description: 'A name for the SLO.', 'x-found-in': 'body', type: 'string' }, objective: { description: 'Defines properties for the SLO objective', 'x-found-in': 'body', type: 'object' }, settings: { description: 'Defines properties for SLO settings.', 'x-found-in': 'body', type: 'object' }, tags: { description: 'List of tags', 'x-found-in': 'body' }, timeWindow: { description: 'Defines properties for the SLO time window', 'x-found-in': 'body', type: 'object' } }, required: ['spaceId', 'sloId'] },
  },
  {
    name: 'reset-slo-op',
    namespace: 'slo',
    description: 'Reset an SLO',
    method: 'POST',
    path: '/s/{spaceId}/api/observability/slos/{sloId}/_reset',
    input: { type: 'object', properties: { spaceId: { type: 'string', description: 'The spaceId parameter', 'x-found-in': 'path' }, sloId: { type: 'string', description: 'The sloId parameter', 'x-found-in': 'path' } }, required: ['spaceId', 'sloId'] },
  },
  {
    name: 'disable-slo-op',
    namespace: 'slo',
    description: 'Disable an SLO',
    method: 'POST',
    path: '/s/{spaceId}/api/observability/slos/{sloId}/disable',
    input: { type: 'object', properties: { spaceId: { type: 'string', description: 'The spaceId parameter', 'x-found-in': 'path' }, sloId: { type: 'string', description: 'The sloId parameter', 'x-found-in': 'path' } }, required: ['spaceId', 'sloId'] },
  },
  {
    name: 'enable-slo-op',
    namespace: 'slo',
    description: 'Enable an SLO',
    method: 'POST',
    path: '/s/{spaceId}/api/observability/slos/{sloId}/enable',
    input: { type: 'object', properties: { spaceId: { type: 'string', description: 'The spaceId parameter', 'x-found-in': 'path' }, sloId: { type: 'string', description: 'The sloId parameter', 'x-found-in': 'path' } }, required: ['spaceId', 'sloId'] },
  },
  {
    name: 'get-definitions-op',
    namespace: 'slo',
    description: 'Get the SLO definitions',
    method: 'GET',
    path: '/s/{spaceId}/internal/observability/slos/_definitions',
    input: { type: 'object', properties: { spaceId: { type: 'string', description: 'The spaceId parameter', 'x-found-in': 'path' }, includeOutdatedOnly: { type: 'boolean', description: 'Indicates if the API returns only outdated SLO or all SLO definitions', 'x-found-in': 'query' }, includeHealth: { type: 'boolean', description: 'Indicates if the API returns SLO health data with definitions', 'x-found-in': 'query' }, tags: { type: 'string', description: 'Filters the SLOs by tag', 'x-found-in': 'query' }, search: { type: 'string', description: 'Filters the SLOs by name', 'x-found-in': 'query' }, page: { type: 'number', description: 'The page to use for pagination, must be greater or equal than 1', 'x-found-in': 'query' }, perPage: { type: 'number', description: 'Number of SLOs returned by page', 'x-found-in': 'query' } }, required: ['spaceId'] },
  },
]
