/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source open api file,
 * and elastic/elastic-client-generator-js to regenerate this file again.
 */

import type { KbApiDefinition } from '../types.ts'

export const spacesDefinitions: KbApiDefinition[] = [
  {
    name: 'get-spaces-space',
    namespace: 'spaces',
    description: 'Get all spaces',
    method: 'GET',
    path: '/api/spaces/space',
    input: { type: 'object', properties: { purpose: { type: 'string', description: 'Specifies which authorization checks are applied to the API call. The default value is `any`.', 'x-found-in': 'query' }, include_authorized_purposes: { type: 'boolean', description: 'When enabled, the API returns any spaces the user is authorized to access in any capacity, each including the purposes for which the user is authorized. This is useful for identifying spaces the user can read but is not authorized for a given purpose. Without the security plugin, this parameter has no effect, because no authorization checks are performed. This parameter cannot be used together with the `purpose` parameter.', 'x-found-in': 'query' } } },
  },
  {
    name: 'post-spaces-space',
    namespace: 'spaces',
    description: 'Create a space',
    method: 'POST',
    path: '/api/spaces/space',
    input: { type: 'object', properties: { _reserved: { description: '', 'x-found-in': 'body', type: 'boolean' }, color: { description: 'The hexadecimal color code used in the space avatar. By default, the color is automatically generated from the space name.', 'x-found-in': 'body', type: 'string' }, description: { description: 'A description for the space.', 'x-found-in': 'body', type: 'string' }, disabledFeatures: { description: '', 'x-found-in': 'body' }, id: { description: 'The space ID that is part of the Kibana URL when inside the space. Space IDs are limited to lowercase alphanumeric, underscore, and hyphen characters (a-z, 0-9, _, and -). You are cannot change the ID with the update operation.', 'x-found-in': 'body', type: 'string' }, imageUrl: { description: 'The data-URL encoded image to display in the space avatar. If specified, initials will not be displayed and the color will be visible as the background color for transparent images. For best results, your image should be 64x64. Images will not be optimized by this API call, so care should be taken when using custom images.', 'x-found-in': 'body', type: 'string' }, initials: { description: 'One or two characters that are shown in the space avatar. By default, the initials are automatically generated from the space name.', 'x-found-in': 'body', type: 'string' }, name: { description: 'The display name for the space.', 'x-found-in': 'body', type: 'string' }, projectRouting: { description: 'Cross-project search default routing configuration for this space. Controls whether searches are scoped to a single project or span multiple projects in serverless environments.', 'x-found-in': 'body', type: 'string' } }, required: ['id', 'name'] },
  },
  {
    name: 'delete-spaces-space-id',
    namespace: 'spaces',
    description: 'Delete a space',
    method: 'DELETE',
    path: '/api/spaces/space/{id}',
    input: { type: 'object', properties: { id: { type: 'string', description: 'The space identifier.', 'x-found-in': 'path' } }, required: ['id'] },
  },
  {
    name: 'get-spaces-space-id',
    namespace: 'spaces',
    description: 'Get a space',
    method: 'GET',
    path: '/api/spaces/space/{id}',
    input: { type: 'object', properties: { id: { type: 'string', description: 'The space identifier.', 'x-found-in': 'path' } }, required: ['id'] },
  },
  {
    name: 'put-spaces-space-id',
    namespace: 'spaces',
    description: 'Update a space',
    method: 'PUT',
    path: '/api/spaces/space/{id}',
    input: { type: 'object', properties: { id: { description: 'The space ID that is part of the Kibana URL when inside the space. Space IDs are limited to lowercase alphanumeric, underscore, and hyphen characters (a-z, 0-9, _, and -). You are cannot change the ID with the update operation.', 'x-found-in': 'body', type: 'string' }, _reserved: { description: '', 'x-found-in': 'body', type: 'boolean' }, color: { description: 'The hexadecimal color code used in the space avatar. By default, the color is automatically generated from the space name.', 'x-found-in': 'body', type: 'string' }, description: { description: 'A description for the space.', 'x-found-in': 'body', type: 'string' }, disabledFeatures: { description: '', 'x-found-in': 'body' }, imageUrl: { description: 'The data-URL encoded image to display in the space avatar. If specified, initials will not be displayed and the color will be visible as the background color for transparent images. For best results, your image should be 64x64. Images will not be optimized by this API call, so care should be taken when using custom images.', 'x-found-in': 'body', type: 'string' }, initials: { description: 'One or two characters that are shown in the space avatar. By default, the initials are automatically generated from the space name.', 'x-found-in': 'body', type: 'string' }, name: { description: 'The display name for the space.', 'x-found-in': 'body', type: 'string' }, projectRouting: { description: 'Cross-project search default routing configuration for this space. Controls whether searches are scoped to a single project or span multiple projects in serverless environments.', 'x-found-in': 'body', type: 'string' } }, required: ['id', 'id', 'name'] },
  },
]
