/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source open api file,
 * and elastic/elastic-client-generator-js to regenerate this file again.
 */

import type { JsonSchemaObject } from '../../../json-schema.ts'
import _inputSchemaRaw from '../../../kibana/json/cases.update-case-template-default-space.request.json' with { type: 'json' }
import type { KbApiDefinition } from '../types.ts'

const _inputSchema = _inputSchemaRaw as unknown as JsonSchemaObject

export const update_case_template_default_spaceDefinitions: KbApiDefinition[] = [
  {
    name: 'update-case-template-default-space',
    namespace: 'cases',
    description: 'Update a case template',
    method: 'PUT',
    path: '/api/cases/templates/{template_id}',
    destructive: true,
    input: _inputSchema,
  },
]
