/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source open api file,
 * and elastic/elastic-client-generator-js to regenerate this file again.
 */

import type { JsonSchemaObject } from '../../../json-schema.ts'
import _inputSchemaRaw from '../../../kibana/json/update_runtime_field_default.request.json' with { type: 'json' }
import type { KbApiDefinition } from '../types.ts'

const _inputSchema = _inputSchemaRaw as unknown as JsonSchemaObject

export const update_runtime_field_defaultDefinitions: KbApiDefinition[] = [
  {
    name: 'update-runtime-field-default',
    namespace: 'data-views',
    description: 'Update a runtime field',
    method: 'POST',
    path: '/api/data_views/data_view/{viewId}/runtime_field/{fieldName}',
    destructive: true,
    input: _inputSchema,
  },
]
