/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source open api file,
 * and elastic/elastic-client-generator-js to regenerate this file again.
 */

import type { JsonSchemaObject } from '../../../json-schema.ts'
import _inputSchemaRaw from '../../../kibana/json/security-ai-assistant-api.update-conversation.request.json' with { type: 'json' }
import type { KbApiDefinition } from '../types.ts'

const _inputSchema = _inputSchemaRaw as unknown as JsonSchemaObject

export const update_conversationDefinitions: KbApiDefinition[] = [
  {
    name: 'update-conversation',
    namespace: 'security-ai-assistant-api',
    description: 'Update a conversation',
    method: 'PUT',
    path: '/api/security_ai_assistant/current_user/conversations/{id}',
    destructive: true,
    input: _inputSchema,
  },
]
