/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source open api file,
 * and elastic/elastic-client-generator-js to regenerate this file again.
 */

import type { KbApiDefinition } from '../types.ts'

export const upload_source_mapDefinitions: KbApiDefinition[] = [
  {
    name: 'upload-source-map',
    namespace: 'apm-sourcemaps',
    description: 'Upload a source map',
    method: 'POST',
    path: '/api/apm/sourcemaps',
    destructive: true,
    readOnly: false,
    input: { type: 'object', properties: { bundle_filepath: { description: 'The absolute path of the final bundle as used in the web application.', 'x-found-in': 'body', type: 'string' }, service_name: { description: 'The name of the service that the service map should apply to.', 'x-found-in': 'body', type: 'string' }, service_version: { description: 'The version of the service that the service map should apply to.', 'x-found-in': 'body', type: 'string' }, sourcemap: { description: 'The source map. It can be a string or file upload. It must follow the', 'x-found-in': 'body', type: 'string' } }, required: ['bundle_filepath', 'service_name', 'service_version', 'sourcemap'] },
  },
]
