/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source open api file,
 * and elastic/elastic-client-generator-js to regenerate this file again.
 */

/* eslint-disable @typescript-eslint/no-redeclare */
import { z } from 'zod'

import { DeploymentRoleAssignment } from './definitions/deployment.js'
import { EmptyResponse, PlatformRoleAssignment, ProjectRoleAssignment, ProjectRoleAssignments } from './definitions/misc.js'
import { OrganizationRoleAssignment } from './definitions/organization.js'
import { RoleAssignments, RoleMapping, RoleMappingPropertyRule, RoleMappingRule } from './definitions/role.js'

export const AddRoleMappingRequest = z.object({
  mappings: z.array(RoleMapping)
}).meta({ id: 'AddRoleMappingRequest' })
export type AddRoleMappingRequest = z.infer<typeof AddRoleMappingRequest>

export const AddRoleMappingsIndividuallyRequest = AddRoleMappingRequest
export type AddRoleMappingsIndividuallyRequest = AddRoleMappingRequest

export const AddRoleMappingsIndividuallyResponse = EmptyResponse
export type AddRoleMappingsIndividuallyResponse = EmptyResponse
