/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source open api file,
 * and elastic/elastic-client-generator-js to regenerate this file again.
 */

/* eslint-disable @typescript-eslint/no-redeclare */
import { z } from 'zod'

import { TrafficFilterEgressRule, TrafficFilterRule, TrafficFilterRulesetRequest, TrafficFilterRulesetResponse } from './definitions/traffic.js'

export const CreateTrafficFilterRulesetRequest = TrafficFilterRulesetRequest
export type CreateTrafficFilterRulesetRequest = TrafficFilterRulesetRequest

export const CreateTrafficFilterRulesetResponse = TrafficFilterRulesetResponse
export type CreateTrafficFilterRulesetResponse = TrafficFilterRulesetResponse
