/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source open api file,
 * and elastic/elastic-client-generator-js to regenerate this file again.
 */

/* eslint-disable @typescript-eslint/no-redeclare */
import { z } from 'zod'

import { EmptyResponse } from './definitions/misc.js'

export const DeleteDomainClaimRequest = z.object({
  domain_claim_request: z.string()
}).meta({ id: 'DeleteDomainClaimRequest' })
export type DeleteDomainClaimRequest = z.infer<typeof DeleteDomainClaimRequest>

export const DomainClaimDeleteRequest = DeleteDomainClaimRequest
export type DomainClaimDeleteRequest = DeleteDomainClaimRequest

export const DomainClaimDeleteResponse = EmptyResponse
export type DomainClaimDeleteResponse = EmptyResponse
