/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source open api file,
 * and elastic/elastic-client-generator-js to regenerate this file again.
 */

/* eslint-disable @typescript-eslint/no-redeclare */
import { z } from 'zod'

import { AppSearchConfiguration, AppSearchInfo, AppSearchNodeTypes, AppSearchPlan, AppSearchPlanControlConfiguration, AppSearchPlanInfo, AppSearchPlansInfo, AppSearchResourceInfo, AppSearchSettings, AppSearchSystemSettings, AppSearchTopologyElement } from './definitions/app.js'
import { ClusterInstanceConfigurationInfo, ClusterInstanceDiskInfo, ClusterInstanceInfo, ClusterInstanceMemoryInfo, ClusterMetadataInfo, ClusterMetadataPortInfo, ClusterMetadataSettings, ClusterPlanAttemptError, ClusterPlanStepInfo, ClusterPlanStepLogMessageInfo, ClusterPlanWarning, ClusterTopologyInfo } from './definitions/cluster.js'
import { AllocatorMoveRequest, AutodetectStrategyConfig, ChangeSourceInfo, ExternalHyperlink, GrowShrinkStrategyConfig, Hyperlink, InstanceMoveRequest, InstanceOverrides, PlanStrategy, RollingGrowShrinkStrategyConfig, RollingStrategyConfig, ServiceUrl, TargetElasticsearchCluster, TopologySize, TransientAppSearchPlanConfiguration } from './definitions/misc.js'

export const GetDeploymentAppsearchResourceInfoResponse = AppSearchResourceInfo
export type GetDeploymentAppsearchResourceInfoResponse = AppSearchResourceInfo
