/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source open api file,
 * and elastic/elastic-client-generator-js to regenerate this file again.
 */

/* eslint-disable @typescript-eslint/no-redeclare */
import { z } from 'zod'

export const KeystoreSecret = z.object({
  value: z.object({}).optional(),
  as_file: z.boolean().optional(),
  is_allowlisted: z.boolean().optional(),
  is_reloadable: z.boolean().optional()
}).meta({ id: 'KeystoreSecret' })
export type KeystoreSecret = z.infer<typeof KeystoreSecret>

export const KeystoreContents = z.object({
  secrets: z.record(z.string(), KeystoreSecret)
}).meta({ id: 'KeystoreContents' })
export type KeystoreContents = z.infer<typeof KeystoreContents>

export const GetDeploymentEsResourceKeystoreResponse = KeystoreContents
export type GetDeploymentEsResourceKeystoreResponse = KeystoreContents
