/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source open api file,
 * and elastic/elastic-client-generator-js to regenerate this file again.
 */

/* eslint-disable @typescript-eslint/no-redeclare */
import { z } from 'zod'

export const MetadataItem = z.object({
  key: z.string(),
  value: z.string()
}).meta({ id: 'MetadataItem' })
export type MetadataItem = z.infer<typeof MetadataItem>

export const DeploymentTagsResponse = z.object({
  tags: z.array(MetadataItem).optional()
}).meta({ id: 'DeploymentTagsResponse' })
export type DeploymentTagsResponse = z.infer<typeof DeploymentTagsResponse>

export const GetDeploymentTagsResponse = DeploymentTagsResponse
export type GetDeploymentTagsResponse = DeploymentTagsResponse
