/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source open api file,
 * and elastic/elastic-client-generator-js to regenerate this file again.
 */

/* eslint-disable @typescript-eslint/no-redeclare */
import { z } from 'zod'

import { FilterAssociation } from './definitions/misc.js'
import { TrafficFilterEgressRule, TrafficFilterRule, TrafficFilterRulesetInfo } from './definitions/traffic.js'

export const TrafficFilterRulesets = z.object({
  rulesets: z.array(TrafficFilterRulesetInfo)
}).meta({ id: 'TrafficFilterRulesets' })
export type TrafficFilterRulesets = z.infer<typeof TrafficFilterRulesets>

export const GetTrafficFilterRulesetsResponse = TrafficFilterRulesets
export type GetTrafficFilterRulesetsResponse = TrafficFilterRulesets
