/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source open api file,
 * and elastic/elastic-client-generator-js to regenerate this file again.
 */

/* eslint-disable @typescript-eslint/no-redeclare */
import { z } from 'zod'

import { TrafficFilterClaimedLinkIdInfo } from './definitions/traffic.js'

export const TrafficFilterClaimedLinkIds = z.object({
  claimed_link_ids: z.array(TrafficFilterClaimedLinkIdInfo)
}).meta({ id: 'TrafficFilterClaimedLinkIds' })
export type TrafficFilterClaimedLinkIds = z.infer<typeof TrafficFilterClaimedLinkIds>

export const GetTrafficFilterClaimedLinkIdsResponse = TrafficFilterClaimedLinkIds
export type GetTrafficFilterClaimedLinkIdsResponse = TrafficFilterClaimedLinkIds
