/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source open api file,
 * and elastic/elastic-client-generator-js to regenerate this file again.
 */

/* eslint-disable @typescript-eslint/no-redeclare */
import { z } from 'zod'

export const ProjectRoleAssignment = z.object({
  role_id: z.string(),
  organization_id: z.string(),
  all: z.boolean().optional(),
  project_ids: z.array(z.string()).optional(),
  application_roles: z.array(z.string()).optional()
}).meta({ id: 'ProjectRoleAssignment' })
export type ProjectRoleAssignment = z.infer<typeof ProjectRoleAssignment>

export const DeploymentRoleAssignment = z.object({
  role_id: z.string(),
  organization_id: z.string(),
  all: z.boolean().optional(),
  deployment_ids: z.array(z.string()).optional(),
  application_roles: z.array(z.string()).optional()
}).meta({ id: 'DeploymentRoleAssignment' })
export type DeploymentRoleAssignment = z.infer<typeof DeploymentRoleAssignment>

export const OrganizationRoleAssignment = z.object({
  role_id: z.string(),
  organization_id: z.string(),
  application_roles: z.array(z.string()).optional()
}).meta({ id: 'OrganizationRoleAssignment' })
export type OrganizationRoleAssignment = z.infer<typeof OrganizationRoleAssignment>

export const PlatformRoleAssignment = z.object({
  role_id: z.string()
}).meta({ id: 'PlatformRoleAssignment' })
export type PlatformRoleAssignment = z.infer<typeof PlatformRoleAssignment>

export const Organization = z.object({
  id: z.string(),
  name: z.string(),
  default_disk_usage_alerts_enabled: z.boolean().optional(),
  notifications_allowed_email_domains: z.array(z.string()).optional(),
  billing_contacts: z.array(z.string()).optional(),
  operational_contacts: z.array(z.string()).optional(),
  sso_login_identifier: z.string().optional()
}).meta({ id: 'Organization' })
export type Organization = z.infer<typeof Organization>

export const ProjectRoleAssignments = z.object({
  elasticsearch: z.array(ProjectRoleAssignment).optional(),
  observability: z.array(ProjectRoleAssignment).optional(),
  security: z.array(ProjectRoleAssignment).optional(),
  workplaceai: z.array(ProjectRoleAssignment).optional()
}).meta({ id: 'ProjectRoleAssignments' })
export type ProjectRoleAssignments = z.infer<typeof ProjectRoleAssignments>

export const RoleAssignments = z.object({
  platform: z.array(PlatformRoleAssignment).optional(),
  organization: z.array(OrganizationRoleAssignment).optional(),
  deployment: z.array(DeploymentRoleAssignment).optional(),
  project: ProjectRoleAssignments.optional()
}).meta({ id: 'RoleAssignments' })
export type RoleAssignments = z.infer<typeof RoleAssignments>

export const OrganizationInvitation = z.object({
  token: z.string(),
  email: z.string(),
  created_at: z.string(),
  expires_at: z.string(),
  expired: z.boolean(),
  accepted_at: z.string().optional(),
  organization: Organization,
  role_assignments: RoleAssignments.optional()
}).meta({ id: 'OrganizationInvitation' })
export type OrganizationInvitation = z.infer<typeof OrganizationInvitation>

export const OrganizationInvitations = z.object({
  invitations: z.array(OrganizationInvitation)
}).meta({ id: 'OrganizationInvitations' })
export type OrganizationInvitations = z.infer<typeof OrganizationInvitations>

export const ListOrganizationInvitationsResponse = OrganizationInvitations
export type ListOrganizationInvitationsResponse = OrganizationInvitations
