import { z } from 'zod';
/**
 * We are still working on this type, it will arrive soon.
 * If it's critical for you, please open an issue.
 * https://github.com/elastic/elasticsearch-specification
 */
export declare const TODO: z.ZodRecord<z.ZodString, z.ZodAny>;
export type TODO = z.infer<typeof TODO>;
export declare const long: z.ZodNumber;
export type long = z.infer<typeof long>;
export declare const ByteSize: z.ZodUnion<readonly [z.ZodNumber, z.ZodString]>;
export type ByteSize = z.infer<typeof ByteSize>;
export declare const EpochTime: z.ZodAny;
export type EpochTime = z.infer<typeof EpochTime>;
/**
 * A date and time, either as a string whose format can depend on the context (defaulting to ISO 8601), or a
 * number of milliseconds since the Epoch. Elasticsearch accepts both as input, but will generally output a string
 * representation.
 */
export declare const DateTime: z.ZodUnion<readonly [z.ZodString, z.ZodAny]>;
export type DateTime = z.infer<typeof DateTime>;
export declare const Id: z.ZodString;
export type Id = z.infer<typeof Id>;
export declare const RequestBase: z.ZodObject<{}, z.core.$strip>;
export type RequestBase = z.infer<typeof RequestBase>;
export declare const VersionString: z.ZodString;
export type VersionString = z.infer<typeof VersionString>;
export declare const integer: z.ZodNumber;
export type integer = z.infer<typeof integer>;
export declare const CatCatRequestBase: z.ZodObject<{}, z.core.$strip>;
export type CatCatRequestBase = z.infer<typeof CatCatRequestBase>;
export declare const CatCatTrainedModelsColumn: z.ZodEnum<{
    license: "license";
    id: "id";
    description: "description";
    df: "df";
    version: "version";
    operations: "operations";
    ip: "ip";
    l: "l";
    o: "o";
    v: "v";
    create_time: "create_time";
    ct: "ct";
    d: "d";
    created_by: "created_by";
    c: "c";
    createdBy: "createdBy";
    data_frame_analytics_id: "data_frame_analytics_id";
    dataFrameAnalytics: "dataFrameAnalytics";
    dfid: "dfid";
    heap_size: "heap_size";
    hs: "hs";
    modelHeapSize: "modelHeapSize";
    "ingest.count": "ingest.count";
    ic: "ic";
    ingestCount: "ingestCount";
    "ingest.current": "ingest.current";
    icurr: "icurr";
    ingestCurrent: "ingestCurrent";
    "ingest.failed": "ingest.failed";
    if: "if";
    ingestFailed: "ingestFailed";
    "ingest.pipelines": "ingest.pipelines";
    ingestPipelines: "ingestPipelines";
    "ingest.time": "ingest.time";
    it: "it";
    ingestTime: "ingestTime";
    modelOperations: "modelOperations";
}>;
export type CatCatTrainedModelsColumn = z.infer<typeof CatCatTrainedModelsColumn>;
export declare const CatCatTrainedModelsColumns: z.ZodUnion<readonly [z.ZodEnum<{
    license: "license";
    id: "id";
    description: "description";
    df: "df";
    version: "version";
    operations: "operations";
    ip: "ip";
    l: "l";
    o: "o";
    v: "v";
    create_time: "create_time";
    ct: "ct";
    d: "d";
    created_by: "created_by";
    c: "c";
    createdBy: "createdBy";
    data_frame_analytics_id: "data_frame_analytics_id";
    dataFrameAnalytics: "dataFrameAnalytics";
    dfid: "dfid";
    heap_size: "heap_size";
    hs: "hs";
    modelHeapSize: "modelHeapSize";
    "ingest.count": "ingest.count";
    ic: "ic";
    ingestCount: "ingestCount";
    "ingest.current": "ingest.current";
    icurr: "icurr";
    ingestCurrent: "ingestCurrent";
    "ingest.failed": "ingest.failed";
    if: "if";
    ingestFailed: "ingestFailed";
    "ingest.pipelines": "ingest.pipelines";
    ingestPipelines: "ingestPipelines";
    "ingest.time": "ingest.time";
    it: "it";
    ingestTime: "ingestTime";
    modelOperations: "modelOperations";
}>, z.ZodArray<z.ZodEnum<{
    license: "license";
    id: "id";
    description: "description";
    df: "df";
    version: "version";
    operations: "operations";
    ip: "ip";
    l: "l";
    o: "o";
    v: "v";
    create_time: "create_time";
    ct: "ct";
    d: "d";
    created_by: "created_by";
    c: "c";
    createdBy: "createdBy";
    data_frame_analytics_id: "data_frame_analytics_id";
    dataFrameAnalytics: "dataFrameAnalytics";
    dfid: "dfid";
    heap_size: "heap_size";
    hs: "hs";
    modelHeapSize: "modelHeapSize";
    "ingest.count": "ingest.count";
    ic: "ic";
    ingestCount: "ingestCount";
    "ingest.current": "ingest.current";
    icurr: "icurr";
    ingestCurrent: "ingestCurrent";
    "ingest.failed": "ingest.failed";
    if: "if";
    ingestFailed: "ingestFailed";
    "ingest.pipelines": "ingest.pipelines";
    ingestPipelines: "ingestPipelines";
    "ingest.time": "ingest.time";
    it: "it";
    ingestTime: "ingestTime";
    modelOperations: "modelOperations";
}>>]>;
export type CatCatTrainedModelsColumns = z.infer<typeof CatCatTrainedModelsColumns>;
/**
 * Get trained models.
 *
 * Get configuration and usage information about inference trained models.
 *
 * IMPORTANT: CAT APIs are only intended for human consumption using the Kibana
 * console or command line. They are not intended for use by applications. For
 * application consumption, use the get trained models statistics API.
 */
export declare const CatMlTrainedModelsRequest: z.ZodObject<{
    model_id: z.ZodOptional<z.ZodString>;
    allow_no_match: z.ZodOptional<z.ZodBoolean>;
    h: z.ZodOptional<z.ZodUnion<readonly [z.ZodEnum<{
        license: "license";
        id: "id";
        description: "description";
        df: "df";
        version: "version";
        operations: "operations";
        ip: "ip";
        l: "l";
        o: "o";
        v: "v";
        create_time: "create_time";
        ct: "ct";
        d: "d";
        created_by: "created_by";
        c: "c";
        createdBy: "createdBy";
        data_frame_analytics_id: "data_frame_analytics_id";
        dataFrameAnalytics: "dataFrameAnalytics";
        dfid: "dfid";
        heap_size: "heap_size";
        hs: "hs";
        modelHeapSize: "modelHeapSize";
        "ingest.count": "ingest.count";
        ic: "ic";
        ingestCount: "ingestCount";
        "ingest.current": "ingest.current";
        icurr: "icurr";
        ingestCurrent: "ingestCurrent";
        "ingest.failed": "ingest.failed";
        if: "if";
        ingestFailed: "ingestFailed";
        "ingest.pipelines": "ingest.pipelines";
        ingestPipelines: "ingestPipelines";
        "ingest.time": "ingest.time";
        it: "it";
        ingestTime: "ingestTime";
        modelOperations: "modelOperations";
    }>, z.ZodArray<z.ZodEnum<{
        license: "license";
        id: "id";
        description: "description";
        df: "df";
        version: "version";
        operations: "operations";
        ip: "ip";
        l: "l";
        o: "o";
        v: "v";
        create_time: "create_time";
        ct: "ct";
        d: "d";
        created_by: "created_by";
        c: "c";
        createdBy: "createdBy";
        data_frame_analytics_id: "data_frame_analytics_id";
        dataFrameAnalytics: "dataFrameAnalytics";
        dfid: "dfid";
        heap_size: "heap_size";
        hs: "hs";
        modelHeapSize: "modelHeapSize";
        "ingest.count": "ingest.count";
        ic: "ic";
        ingestCount: "ingestCount";
        "ingest.current": "ingest.current";
        icurr: "icurr";
        ingestCurrent: "ingestCurrent";
        "ingest.failed": "ingest.failed";
        if: "if";
        ingestFailed: "ingestFailed";
        "ingest.pipelines": "ingest.pipelines";
        ingestPipelines: "ingestPipelines";
        "ingest.time": "ingest.time";
        it: "it";
        ingestTime: "ingestTime";
        modelOperations: "modelOperations";
    }>>]>>;
    s: z.ZodOptional<z.ZodUnion<readonly [z.ZodEnum<{
        license: "license";
        id: "id";
        description: "description";
        df: "df";
        version: "version";
        operations: "operations";
        ip: "ip";
        l: "l";
        o: "o";
        v: "v";
        create_time: "create_time";
        ct: "ct";
        d: "d";
        created_by: "created_by";
        c: "c";
        createdBy: "createdBy";
        data_frame_analytics_id: "data_frame_analytics_id";
        dataFrameAnalytics: "dataFrameAnalytics";
        dfid: "dfid";
        heap_size: "heap_size";
        hs: "hs";
        modelHeapSize: "modelHeapSize";
        "ingest.count": "ingest.count";
        ic: "ic";
        ingestCount: "ingestCount";
        "ingest.current": "ingest.current";
        icurr: "icurr";
        ingestCurrent: "ingestCurrent";
        "ingest.failed": "ingest.failed";
        if: "if";
        ingestFailed: "ingestFailed";
        "ingest.pipelines": "ingest.pipelines";
        ingestPipelines: "ingestPipelines";
        "ingest.time": "ingest.time";
        it: "it";
        ingestTime: "ingestTime";
        modelOperations: "modelOperations";
    }>, z.ZodArray<z.ZodEnum<{
        license: "license";
        id: "id";
        description: "description";
        df: "df";
        version: "version";
        operations: "operations";
        ip: "ip";
        l: "l";
        o: "o";
        v: "v";
        create_time: "create_time";
        ct: "ct";
        d: "d";
        created_by: "created_by";
        c: "c";
        createdBy: "createdBy";
        data_frame_analytics_id: "data_frame_analytics_id";
        dataFrameAnalytics: "dataFrameAnalytics";
        dfid: "dfid";
        heap_size: "heap_size";
        hs: "hs";
        modelHeapSize: "modelHeapSize";
        "ingest.count": "ingest.count";
        ic: "ic";
        ingestCount: "ingestCount";
        "ingest.current": "ingest.current";
        icurr: "icurr";
        ingestCurrent: "ingestCurrent";
        "ingest.failed": "ingest.failed";
        if: "if";
        ingestFailed: "ingestFailed";
        "ingest.pipelines": "ingest.pipelines";
        ingestPipelines: "ingestPipelines";
        "ingest.time": "ingest.time";
        it: "it";
        ingestTime: "ingestTime";
        modelOperations: "modelOperations";
    }>>]>>;
    from: z.ZodOptional<z.ZodNumber>;
    size: z.ZodOptional<z.ZodNumber>;
}, z.core.$strip>;
export type CatMlTrainedModelsRequest = z.infer<typeof CatMlTrainedModelsRequest>;
export declare const CatMlTrainedModelsTrainedModelsRecord: z.ZodObject<{
    id: z.ZodOptional<z.ZodString>;
    created_by: z.ZodOptional<z.ZodString>;
    c: z.ZodOptional<z.ZodString>;
    createdBy: z.ZodOptional<z.ZodString>;
    heap_size: z.ZodOptional<z.ZodUnion<readonly [z.ZodNumber, z.ZodString]>>;
    hs: z.ZodOptional<z.ZodUnion<readonly [z.ZodNumber, z.ZodString]>>;
    modelHeapSize: z.ZodOptional<z.ZodUnion<readonly [z.ZodNumber, z.ZodString]>>;
    operations: z.ZodOptional<z.ZodString>;
    o: z.ZodOptional<z.ZodString>;
    modelOperations: z.ZodOptional<z.ZodString>;
    license: z.ZodOptional<z.ZodString>;
    l: z.ZodOptional<z.ZodString>;
    create_time: z.ZodOptional<z.ZodUnion<readonly [z.ZodString, z.ZodAny]>>;
    ct: z.ZodOptional<z.ZodUnion<readonly [z.ZodString, z.ZodAny]>>;
    version: z.ZodOptional<z.ZodString>;
    v: z.ZodOptional<z.ZodString>;
    description: z.ZodOptional<z.ZodString>;
    d: z.ZodOptional<z.ZodString>;
    'ingest.pipelines': z.ZodOptional<z.ZodString>;
    ip: z.ZodOptional<z.ZodString>;
    ingestPipelines: z.ZodOptional<z.ZodString>;
    'ingest.count': z.ZodOptional<z.ZodString>;
    ic: z.ZodOptional<z.ZodString>;
    ingestCount: z.ZodOptional<z.ZodString>;
    'ingest.time': z.ZodOptional<z.ZodString>;
    it: z.ZodOptional<z.ZodString>;
    ingestTime: z.ZodOptional<z.ZodString>;
    'ingest.current': z.ZodOptional<z.ZodString>;
    icurr: z.ZodOptional<z.ZodString>;
    ingestCurrent: z.ZodOptional<z.ZodString>;
    'ingest.failed': z.ZodOptional<z.ZodString>;
    if: z.ZodOptional<z.ZodString>;
    ingestFailed: z.ZodOptional<z.ZodString>;
    'data_frame.id': z.ZodOptional<z.ZodString>;
    dfid: z.ZodOptional<z.ZodString>;
    dataFrameAnalytics: z.ZodOptional<z.ZodString>;
    'data_frame.create_time': z.ZodOptional<z.ZodString>;
    dft: z.ZodOptional<z.ZodString>;
    dataFrameAnalyticsTime: z.ZodOptional<z.ZodString>;
    'data_frame.source_index': z.ZodOptional<z.ZodString>;
    dfsi: z.ZodOptional<z.ZodString>;
    dataFrameAnalyticsSrcIndex: z.ZodOptional<z.ZodString>;
    'data_frame.analysis': z.ZodOptional<z.ZodString>;
    dfa: z.ZodOptional<z.ZodString>;
    dataFrameAnalyticsAnalysis: z.ZodOptional<z.ZodString>;
    type: z.ZodOptional<z.ZodString>;
}, z.core.$strip>;
export type CatMlTrainedModelsTrainedModelsRecord = z.infer<typeof CatMlTrainedModelsTrainedModelsRecord>;
export declare const CatMlTrainedModelsResponse: z.ZodArray<z.ZodObject<{
    id: z.ZodOptional<z.ZodString>;
    created_by: z.ZodOptional<z.ZodString>;
    c: z.ZodOptional<z.ZodString>;
    createdBy: z.ZodOptional<z.ZodString>;
    heap_size: z.ZodOptional<z.ZodUnion<readonly [z.ZodNumber, z.ZodString]>>;
    hs: z.ZodOptional<z.ZodUnion<readonly [z.ZodNumber, z.ZodString]>>;
    modelHeapSize: z.ZodOptional<z.ZodUnion<readonly [z.ZodNumber, z.ZodString]>>;
    operations: z.ZodOptional<z.ZodString>;
    o: z.ZodOptional<z.ZodString>;
    modelOperations: z.ZodOptional<z.ZodString>;
    license: z.ZodOptional<z.ZodString>;
    l: z.ZodOptional<z.ZodString>;
    create_time: z.ZodOptional<z.ZodUnion<readonly [z.ZodString, z.ZodAny]>>;
    ct: z.ZodOptional<z.ZodUnion<readonly [z.ZodString, z.ZodAny]>>;
    version: z.ZodOptional<z.ZodString>;
    v: z.ZodOptional<z.ZodString>;
    description: z.ZodOptional<z.ZodString>;
    d: z.ZodOptional<z.ZodString>;
    'ingest.pipelines': z.ZodOptional<z.ZodString>;
    ip: z.ZodOptional<z.ZodString>;
    ingestPipelines: z.ZodOptional<z.ZodString>;
    'ingest.count': z.ZodOptional<z.ZodString>;
    ic: z.ZodOptional<z.ZodString>;
    ingestCount: z.ZodOptional<z.ZodString>;
    'ingest.time': z.ZodOptional<z.ZodString>;
    it: z.ZodOptional<z.ZodString>;
    ingestTime: z.ZodOptional<z.ZodString>;
    'ingest.current': z.ZodOptional<z.ZodString>;
    icurr: z.ZodOptional<z.ZodString>;
    ingestCurrent: z.ZodOptional<z.ZodString>;
    'ingest.failed': z.ZodOptional<z.ZodString>;
    if: z.ZodOptional<z.ZodString>;
    ingestFailed: z.ZodOptional<z.ZodString>;
    'data_frame.id': z.ZodOptional<z.ZodString>;
    dfid: z.ZodOptional<z.ZodString>;
    dataFrameAnalytics: z.ZodOptional<z.ZodString>;
    'data_frame.create_time': z.ZodOptional<z.ZodString>;
    dft: z.ZodOptional<z.ZodString>;
    dataFrameAnalyticsTime: z.ZodOptional<z.ZodString>;
    'data_frame.source_index': z.ZodOptional<z.ZodString>;
    dfsi: z.ZodOptional<z.ZodString>;
    dataFrameAnalyticsSrcIndex: z.ZodOptional<z.ZodString>;
    'data_frame.analysis': z.ZodOptional<z.ZodString>;
    dfa: z.ZodOptional<z.ZodString>;
    dataFrameAnalyticsAnalysis: z.ZodOptional<z.ZodString>;
    type: z.ZodOptional<z.ZodString>;
}, z.core.$strip>>;
export type CatMlTrainedModelsResponse = z.infer<typeof CatMlTrainedModelsResponse>;
//# sourceMappingURL=cat_ml_trained_models.d.ts.map