import { z } from 'zod';
/**
 * We are still working on this type, it will arrive soon.
 * If it's critical for you, please open an issue.
 * https://github.com/elastic/elasticsearch-specification
 */
export declare const TODO: z.ZodRecord<z.ZodString, z.ZodAny>;
export type TODO = z.infer<typeof TODO>;
/**
 * A duration. Units can be `nanos`, `micros`, `ms` (milliseconds), `s` (seconds), `m` (minutes), `h` (hours) and
 * `d` (days). Also accepts "0" without a unit and "-1" to indicate an unspecified value.
 */
export declare const Duration: z.ZodUnion<readonly [z.ZodString, z.ZodLiteral<-1>, z.ZodLiteral<0>]>;
export type Duration = z.infer<typeof Duration>;
export declare const Name: z.ZodString;
export type Name = z.infer<typeof Name>;
export declare const Names: z.ZodUnion<readonly [z.ZodString, z.ZodArray<z.ZodString>]>;
export type Names = z.infer<typeof Names>;
export declare const NodeId: z.ZodString;
export type NodeId = z.infer<typeof NodeId>;
export declare const RequestBase: z.ZodObject<{}, z.core.$strip>;
export type RequestBase = z.infer<typeof RequestBase>;
export declare const CatCatRequestBase: z.ZodObject<{}, z.core.$strip>;
export type CatCatRequestBase = z.infer<typeof CatCatRequestBase>;
export declare const CatCatThreadPoolColumn: z.ZodUnion<readonly [z.ZodEnum<{
    id: "id";
    keep_alive: "keep_alive";
    q: "q";
    type: "type";
    k: "k";
    name: "name";
    size: "size";
    max: "max";
    a: "a";
    i: "i";
    h: "h";
    node_id: "node_id";
    host: "host";
    ip: "ip";
    r: "r";
    node_name: "node_name";
    l: "l";
    t: "t";
    p: "p";
    c: "c";
    pid: "pid";
    port: "port";
    po: "po";
    active: "active";
    completed: "completed";
    core: "core";
    cr: "cr";
    ephemeral_id: "ephemeral_id";
    eid: "eid";
    largest: "largest";
    mx: "mx";
    pool_size: "pool_size";
    psz: "psz";
    queue: "queue";
    queue_size: "queue_size";
    qs: "qs";
    rejected: "rejected";
    sz: "sz";
}>, z.ZodString]>;
export type CatCatThreadPoolColumn = z.infer<typeof CatCatThreadPoolColumn>;
export declare const CatCatThreadPoolColumns: z.ZodUnion<readonly [z.ZodUnion<readonly [z.ZodEnum<{
    id: "id";
    keep_alive: "keep_alive";
    q: "q";
    type: "type";
    k: "k";
    name: "name";
    size: "size";
    max: "max";
    a: "a";
    i: "i";
    h: "h";
    node_id: "node_id";
    host: "host";
    ip: "ip";
    r: "r";
    node_name: "node_name";
    l: "l";
    t: "t";
    p: "p";
    c: "c";
    pid: "pid";
    port: "port";
    po: "po";
    active: "active";
    completed: "completed";
    core: "core";
    cr: "cr";
    ephemeral_id: "ephemeral_id";
    eid: "eid";
    largest: "largest";
    mx: "mx";
    pool_size: "pool_size";
    psz: "psz";
    queue: "queue";
    queue_size: "queue_size";
    qs: "qs";
    rejected: "rejected";
    sz: "sz";
}>, z.ZodString]>, z.ZodArray<z.ZodUnion<readonly [z.ZodEnum<{
    id: "id";
    keep_alive: "keep_alive";
    q: "q";
    type: "type";
    k: "k";
    name: "name";
    size: "size";
    max: "max";
    a: "a";
    i: "i";
    h: "h";
    node_id: "node_id";
    host: "host";
    ip: "ip";
    r: "r";
    node_name: "node_name";
    l: "l";
    t: "t";
    p: "p";
    c: "c";
    pid: "pid";
    port: "port";
    po: "po";
    active: "active";
    completed: "completed";
    core: "core";
    cr: "cr";
    ephemeral_id: "ephemeral_id";
    eid: "eid";
    largest: "largest";
    mx: "mx";
    pool_size: "pool_size";
    psz: "psz";
    queue: "queue";
    queue_size: "queue_size";
    qs: "qs";
    rejected: "rejected";
    sz: "sz";
}>, z.ZodString]>>]>;
export type CatCatThreadPoolColumns = z.infer<typeof CatCatThreadPoolColumns>;
/**
 * Get thread pool statistics.
 *
 * Get thread pool statistics for each node in a cluster.
 * Returned information includes all built-in thread pools and custom thread pools.
 * IMPORTANT: cat APIs are only intended for human consumption using the command line or Kibana console. They are not intended for use by applications. For application consumption, use the nodes info API.
 */
export declare const CatThreadPoolRequest: z.ZodObject<{
    thread_pool_patterns: z.ZodOptional<z.ZodUnion<readonly [z.ZodString, z.ZodArray<z.ZodString>]>>;
    h: z.ZodOptional<z.ZodUnion<readonly [z.ZodUnion<readonly [z.ZodEnum<{
        id: "id";
        keep_alive: "keep_alive";
        q: "q";
        type: "type";
        k: "k";
        name: "name";
        size: "size";
        max: "max";
        a: "a";
        i: "i";
        h: "h";
        node_id: "node_id";
        host: "host";
        ip: "ip";
        r: "r";
        node_name: "node_name";
        l: "l";
        t: "t";
        p: "p";
        c: "c";
        pid: "pid";
        port: "port";
        po: "po";
        active: "active";
        completed: "completed";
        core: "core";
        cr: "cr";
        ephemeral_id: "ephemeral_id";
        eid: "eid";
        largest: "largest";
        mx: "mx";
        pool_size: "pool_size";
        psz: "psz";
        queue: "queue";
        queue_size: "queue_size";
        qs: "qs";
        rejected: "rejected";
        sz: "sz";
    }>, z.ZodString]>, z.ZodArray<z.ZodUnion<readonly [z.ZodEnum<{
        id: "id";
        keep_alive: "keep_alive";
        q: "q";
        type: "type";
        k: "k";
        name: "name";
        size: "size";
        max: "max";
        a: "a";
        i: "i";
        h: "h";
        node_id: "node_id";
        host: "host";
        ip: "ip";
        r: "r";
        node_name: "node_name";
        l: "l";
        t: "t";
        p: "p";
        c: "c";
        pid: "pid";
        port: "port";
        po: "po";
        active: "active";
        completed: "completed";
        core: "core";
        cr: "cr";
        ephemeral_id: "ephemeral_id";
        eid: "eid";
        largest: "largest";
        mx: "mx";
        pool_size: "pool_size";
        psz: "psz";
        queue: "queue";
        queue_size: "queue_size";
        qs: "qs";
        rejected: "rejected";
        sz: "sz";
    }>, z.ZodString]>>]>>;
    s: z.ZodOptional<z.ZodUnion<readonly [z.ZodString, z.ZodArray<z.ZodString>]>>;
    local: z.ZodOptional<z.ZodBoolean>;
    master_timeout: z.ZodOptional<z.ZodUnion<readonly [z.ZodString, z.ZodLiteral<-1>, z.ZodLiteral<0>]>>;
}, z.core.$strip>;
export type CatThreadPoolRequest = z.infer<typeof CatThreadPoolRequest>;
export declare const CatThreadPoolThreadPoolRecord: z.ZodObject<{
    node_name: z.ZodOptional<z.ZodString>;
    nn: z.ZodOptional<z.ZodString>;
    node_id: z.ZodOptional<z.ZodString>;
    id: z.ZodOptional<z.ZodString>;
    ephemeral_node_id: z.ZodOptional<z.ZodString>;
    eid: z.ZodOptional<z.ZodString>;
    pid: z.ZodOptional<z.ZodString>;
    p: z.ZodOptional<z.ZodString>;
    host: z.ZodOptional<z.ZodString>;
    h: z.ZodOptional<z.ZodString>;
    ip: z.ZodOptional<z.ZodString>;
    i: z.ZodOptional<z.ZodString>;
    port: z.ZodOptional<z.ZodString>;
    po: z.ZodOptional<z.ZodString>;
    name: z.ZodOptional<z.ZodString>;
    n: z.ZodOptional<z.ZodString>;
    type: z.ZodOptional<z.ZodString>;
    t: z.ZodOptional<z.ZodString>;
    active: z.ZodOptional<z.ZodString>;
    a: z.ZodOptional<z.ZodString>;
    pool_size: z.ZodOptional<z.ZodString>;
    psz: z.ZodOptional<z.ZodString>;
    queue: z.ZodOptional<z.ZodString>;
    q: z.ZodOptional<z.ZodString>;
    queue_size: z.ZodOptional<z.ZodString>;
    qs: z.ZodOptional<z.ZodString>;
    rejected: z.ZodOptional<z.ZodString>;
    r: z.ZodOptional<z.ZodString>;
    largest: z.ZodOptional<z.ZodString>;
    l: z.ZodOptional<z.ZodString>;
    completed: z.ZodOptional<z.ZodString>;
    c: z.ZodOptional<z.ZodString>;
    core: z.ZodOptional<z.ZodUnion<readonly [z.ZodString, z.ZodNull]>>;
    cr: z.ZodOptional<z.ZodUnion<readonly [z.ZodString, z.ZodNull]>>;
    max: z.ZodOptional<z.ZodUnion<readonly [z.ZodString, z.ZodNull]>>;
    mx: z.ZodOptional<z.ZodUnion<readonly [z.ZodString, z.ZodNull]>>;
    size: z.ZodOptional<z.ZodUnion<readonly [z.ZodString, z.ZodNull]>>;
    sz: z.ZodOptional<z.ZodUnion<readonly [z.ZodString, z.ZodNull]>>;
    keep_alive: z.ZodOptional<z.ZodUnion<readonly [z.ZodString, z.ZodNull]>>;
    ka: z.ZodOptional<z.ZodUnion<readonly [z.ZodString, z.ZodNull]>>;
}, z.core.$strip>;
export type CatThreadPoolThreadPoolRecord = z.infer<typeof CatThreadPoolThreadPoolRecord>;
export declare const CatThreadPoolResponse: z.ZodArray<z.ZodObject<{
    node_name: z.ZodOptional<z.ZodString>;
    nn: z.ZodOptional<z.ZodString>;
    node_id: z.ZodOptional<z.ZodString>;
    id: z.ZodOptional<z.ZodString>;
    ephemeral_node_id: z.ZodOptional<z.ZodString>;
    eid: z.ZodOptional<z.ZodString>;
    pid: z.ZodOptional<z.ZodString>;
    p: z.ZodOptional<z.ZodString>;
    host: z.ZodOptional<z.ZodString>;
    h: z.ZodOptional<z.ZodString>;
    ip: z.ZodOptional<z.ZodString>;
    i: z.ZodOptional<z.ZodString>;
    port: z.ZodOptional<z.ZodString>;
    po: z.ZodOptional<z.ZodString>;
    name: z.ZodOptional<z.ZodString>;
    n: z.ZodOptional<z.ZodString>;
    type: z.ZodOptional<z.ZodString>;
    t: z.ZodOptional<z.ZodString>;
    active: z.ZodOptional<z.ZodString>;
    a: z.ZodOptional<z.ZodString>;
    pool_size: z.ZodOptional<z.ZodString>;
    psz: z.ZodOptional<z.ZodString>;
    queue: z.ZodOptional<z.ZodString>;
    q: z.ZodOptional<z.ZodString>;
    queue_size: z.ZodOptional<z.ZodString>;
    qs: z.ZodOptional<z.ZodString>;
    rejected: z.ZodOptional<z.ZodString>;
    r: z.ZodOptional<z.ZodString>;
    largest: z.ZodOptional<z.ZodString>;
    l: z.ZodOptional<z.ZodString>;
    completed: z.ZodOptional<z.ZodString>;
    c: z.ZodOptional<z.ZodString>;
    core: z.ZodOptional<z.ZodUnion<readonly [z.ZodString, z.ZodNull]>>;
    cr: z.ZodOptional<z.ZodUnion<readonly [z.ZodString, z.ZodNull]>>;
    max: z.ZodOptional<z.ZodUnion<readonly [z.ZodString, z.ZodNull]>>;
    mx: z.ZodOptional<z.ZodUnion<readonly [z.ZodString, z.ZodNull]>>;
    size: z.ZodOptional<z.ZodUnion<readonly [z.ZodString, z.ZodNull]>>;
    sz: z.ZodOptional<z.ZodUnion<readonly [z.ZodString, z.ZodNull]>>;
    keep_alive: z.ZodOptional<z.ZodUnion<readonly [z.ZodString, z.ZodNull]>>;
    ka: z.ZodOptional<z.ZodUnion<readonly [z.ZodString, z.ZodNull]>>;
}, z.core.$strip>>;
export type CatThreadPoolResponse = z.infer<typeof CatThreadPoolResponse>;
//# sourceMappingURL=cat_thread_pool.d.ts.map