import { z } from 'zod';
/**
 * We are still working on this type, it will arrive soon.
 * If it's critical for you, please open an issue.
 * https://github.com/elastic/elasticsearch-specification
 */
export declare const TODO: z.ZodRecord<z.ZodString, z.ZodAny>;
export type TODO = z.infer<typeof TODO>;
/**
 * Some APIs will return values such as numbers also as a string (notably epoch timestamps). This behavior
 * is used to capture this behavior while keeping the semantics of the field type.
 *
 * Depending on the target language, code generators can keep the union or remove it and leniently parse
 * strings to the target type.
 */
export declare const SpecUtilsStringified: z.ZodUnion<readonly [z.ZodAny, z.ZodString]>;
export type SpecUtilsStringified = z.infer<typeof SpecUtilsStringified>;
export declare const Name: z.ZodString;
export type Name = z.infer<typeof Name>;
export declare const Names: z.ZodUnion<readonly [z.ZodString, z.ZodArray<z.ZodString>]>;
export type Names = z.infer<typeof Names>;
export declare const RequestBase: z.ZodObject<{}, z.core.$strip>;
export type RequestBase = z.infer<typeof RequestBase>;
/** Time of day, expressed as HH:MM:SS */
export declare const TimeOfDay: z.ZodString;
export type TimeOfDay = z.infer<typeof TimeOfDay>;
export declare const CatCatHealthColumn: z.ZodUnion<readonly [z.ZodEnum<{
    status: "status";
    shards: "shards";
    cluster: "cluster";
    i: "i";
    r: "r";
    t: "t";
    epoch: "epoch";
    time: "time";
    timestamp: "timestamp";
    ts: "ts";
    hms: "hms";
    hhmmss: "hhmmss";
    cl: "cl";
    st: "st";
    "node.total": "node.total";
    nt: "nt";
    nodeTotal: "nodeTotal";
    "node.data": "node.data";
    nd: "nd";
    nodeData: "nodeData";
    sh: "sh";
    "shards.total": "shards.total";
    shardsTotal: "shardsTotal";
    pri: "pri";
    p: "p";
    "shards.primary": "shards.primary";
    shardsPrimary: "shardsPrimary";
    relo: "relo";
    "shards.relocating": "shards.relocating";
    shardsRelocating: "shardsRelocating";
    init: "init";
    "shards.initializing": "shards.initializing";
    shardsInitializing: "shardsInitializing";
    unassign: "unassign";
    u: "u";
    "shards.unassigned": "shards.unassigned";
    shardsUnassigned: "shardsUnassigned";
    "unassign.pri": "unassign.pri";
    up: "up";
    "shards.unassigned.primary": "shards.unassigned.primary";
    shardsUnassignedPrimary: "shardsUnassignedPrimary";
    pending_tasks: "pending_tasks";
    pt: "pt";
    pendingTasks: "pendingTasks";
    max_task_wait_time: "max_task_wait_time";
    mtwt: "mtwt";
    maxTaskWaitTime: "maxTaskWaitTime";
    active_shards_percent: "active_shards_percent";
    asp: "asp";
    activeShardsPercent: "activeShardsPercent";
}>, z.ZodString]>;
export type CatCatHealthColumn = z.infer<typeof CatCatHealthColumn>;
export declare const CatCatHealthColumns: z.ZodUnion<readonly [z.ZodUnion<readonly [z.ZodEnum<{
    status: "status";
    shards: "shards";
    cluster: "cluster";
    i: "i";
    r: "r";
    t: "t";
    epoch: "epoch";
    time: "time";
    timestamp: "timestamp";
    ts: "ts";
    hms: "hms";
    hhmmss: "hhmmss";
    cl: "cl";
    st: "st";
    "node.total": "node.total";
    nt: "nt";
    nodeTotal: "nodeTotal";
    "node.data": "node.data";
    nd: "nd";
    nodeData: "nodeData";
    sh: "sh";
    "shards.total": "shards.total";
    shardsTotal: "shardsTotal";
    pri: "pri";
    p: "p";
    "shards.primary": "shards.primary";
    shardsPrimary: "shardsPrimary";
    relo: "relo";
    "shards.relocating": "shards.relocating";
    shardsRelocating: "shardsRelocating";
    init: "init";
    "shards.initializing": "shards.initializing";
    shardsInitializing: "shardsInitializing";
    unassign: "unassign";
    u: "u";
    "shards.unassigned": "shards.unassigned";
    shardsUnassigned: "shardsUnassigned";
    "unassign.pri": "unassign.pri";
    up: "up";
    "shards.unassigned.primary": "shards.unassigned.primary";
    shardsUnassignedPrimary: "shardsUnassignedPrimary";
    pending_tasks: "pending_tasks";
    pt: "pt";
    pendingTasks: "pendingTasks";
    max_task_wait_time: "max_task_wait_time";
    mtwt: "mtwt";
    maxTaskWaitTime: "maxTaskWaitTime";
    active_shards_percent: "active_shards_percent";
    asp: "asp";
    activeShardsPercent: "activeShardsPercent";
}>, z.ZodString]>, z.ZodArray<z.ZodUnion<readonly [z.ZodEnum<{
    status: "status";
    shards: "shards";
    cluster: "cluster";
    i: "i";
    r: "r";
    t: "t";
    epoch: "epoch";
    time: "time";
    timestamp: "timestamp";
    ts: "ts";
    hms: "hms";
    hhmmss: "hhmmss";
    cl: "cl";
    st: "st";
    "node.total": "node.total";
    nt: "nt";
    nodeTotal: "nodeTotal";
    "node.data": "node.data";
    nd: "nd";
    nodeData: "nodeData";
    sh: "sh";
    "shards.total": "shards.total";
    shardsTotal: "shardsTotal";
    pri: "pri";
    p: "p";
    "shards.primary": "shards.primary";
    shardsPrimary: "shardsPrimary";
    relo: "relo";
    "shards.relocating": "shards.relocating";
    shardsRelocating: "shardsRelocating";
    init: "init";
    "shards.initializing": "shards.initializing";
    shardsInitializing: "shardsInitializing";
    unassign: "unassign";
    u: "u";
    "shards.unassigned": "shards.unassigned";
    shardsUnassigned: "shardsUnassigned";
    "unassign.pri": "unassign.pri";
    up: "up";
    "shards.unassigned.primary": "shards.unassigned.primary";
    shardsUnassignedPrimary: "shardsUnassignedPrimary";
    pending_tasks: "pending_tasks";
    pt: "pt";
    pendingTasks: "pendingTasks";
    max_task_wait_time: "max_task_wait_time";
    mtwt: "mtwt";
    maxTaskWaitTime: "maxTaskWaitTime";
    active_shards_percent: "active_shards_percent";
    asp: "asp";
    activeShardsPercent: "activeShardsPercent";
}>, z.ZodString]>>]>;
export type CatCatHealthColumns = z.infer<typeof CatCatHealthColumns>;
export declare const CatCatRequestBase: z.ZodObject<{}, z.core.$strip>;
export type CatCatRequestBase = z.infer<typeof CatCatRequestBase>;
export declare const CatHealthHealthRecord: z.ZodObject<{
    epoch: z.ZodOptional<z.ZodUnion<readonly [z.ZodAny, z.ZodString]>>;
    time: z.ZodOptional<z.ZodUnion<readonly [z.ZodAny, z.ZodString]>>;
    timestamp: z.ZodOptional<z.ZodString>;
    ts: z.ZodOptional<z.ZodString>;
    hms: z.ZodOptional<z.ZodString>;
    hhmmss: z.ZodOptional<z.ZodString>;
    cluster: z.ZodOptional<z.ZodString>;
    cl: z.ZodOptional<z.ZodString>;
    status: z.ZodOptional<z.ZodString>;
    st: z.ZodOptional<z.ZodString>;
    'node.total': z.ZodOptional<z.ZodString>;
    nt: z.ZodOptional<z.ZodString>;
    nodeTotal: z.ZodOptional<z.ZodString>;
    'node.data': z.ZodOptional<z.ZodString>;
    nd: z.ZodOptional<z.ZodString>;
    nodeData: z.ZodOptional<z.ZodString>;
    shards: z.ZodOptional<z.ZodString>;
    t: z.ZodOptional<z.ZodString>;
    sh: z.ZodOptional<z.ZodString>;
    'shards.total': z.ZodOptional<z.ZodString>;
    shardsTotal: z.ZodOptional<z.ZodString>;
    pri: z.ZodOptional<z.ZodString>;
    p: z.ZodOptional<z.ZodString>;
    'shards.primary': z.ZodOptional<z.ZodString>;
    shardsPrimary: z.ZodOptional<z.ZodString>;
    relo: z.ZodOptional<z.ZodString>;
    r: z.ZodOptional<z.ZodString>;
    'shards.relocating': z.ZodOptional<z.ZodString>;
    shardsRelocating: z.ZodOptional<z.ZodString>;
    init: z.ZodOptional<z.ZodString>;
    i: z.ZodOptional<z.ZodString>;
    'shards.initializing': z.ZodOptional<z.ZodString>;
    shardsInitializing: z.ZodOptional<z.ZodString>;
    'unassign.pri': z.ZodOptional<z.ZodString>;
    up: z.ZodOptional<z.ZodString>;
    'shards.unassigned.primary': z.ZodOptional<z.ZodString>;
    shardsUnassignedPrimary: z.ZodOptional<z.ZodString>;
    unassign: z.ZodOptional<z.ZodString>;
    u: z.ZodOptional<z.ZodString>;
    'shards.unassigned': z.ZodOptional<z.ZodString>;
    shardsUnassigned: z.ZodOptional<z.ZodString>;
    pending_tasks: z.ZodOptional<z.ZodString>;
    pt: z.ZodOptional<z.ZodString>;
    pendingTasks: z.ZodOptional<z.ZodString>;
    max_task_wait_time: z.ZodOptional<z.ZodString>;
    mtwt: z.ZodOptional<z.ZodString>;
    maxTaskWaitTime: z.ZodOptional<z.ZodString>;
    active_shards_percent: z.ZodOptional<z.ZodString>;
    asp: z.ZodOptional<z.ZodString>;
    activeShardsPercent: z.ZodOptional<z.ZodString>;
}, z.core.$strip>;
export type CatHealthHealthRecord = z.infer<typeof CatHealthHealthRecord>;
/**
 * Get the cluster health status.
 *
 * IMPORTANT: CAT APIs are only intended for human consumption using the command line or Kibana console.
 * They are not intended for use by applications. For application consumption, use the cluster health API.
 * This API is often used to check malfunctioning clusters.
 * To help you track cluster health alongside log files and alerting systems, the API returns timestamps in two formats:
 * `HH:MM:SS`, which is human-readable but includes no date information;
 * `Unix epoch time`, which is machine-sortable and includes date information.
 * The latter format is useful for cluster recoveries that take multiple days.
 * You can use the cat health API to verify cluster health across multiple nodes.
 * You also can use the API to track the recovery of a large cluster over a longer period of time.
 */
export declare const CatHealthRequest: z.ZodObject<{
    ts: z.ZodOptional<z.ZodBoolean>;
    h: z.ZodOptional<z.ZodUnion<readonly [z.ZodUnion<readonly [z.ZodEnum<{
        status: "status";
        shards: "shards";
        cluster: "cluster";
        i: "i";
        r: "r";
        t: "t";
        epoch: "epoch";
        time: "time";
        timestamp: "timestamp";
        ts: "ts";
        hms: "hms";
        hhmmss: "hhmmss";
        cl: "cl";
        st: "st";
        "node.total": "node.total";
        nt: "nt";
        nodeTotal: "nodeTotal";
        "node.data": "node.data";
        nd: "nd";
        nodeData: "nodeData";
        sh: "sh";
        "shards.total": "shards.total";
        shardsTotal: "shardsTotal";
        pri: "pri";
        p: "p";
        "shards.primary": "shards.primary";
        shardsPrimary: "shardsPrimary";
        relo: "relo";
        "shards.relocating": "shards.relocating";
        shardsRelocating: "shardsRelocating";
        init: "init";
        "shards.initializing": "shards.initializing";
        shardsInitializing: "shardsInitializing";
        unassign: "unassign";
        u: "u";
        "shards.unassigned": "shards.unassigned";
        shardsUnassigned: "shardsUnassigned";
        "unassign.pri": "unassign.pri";
        up: "up";
        "shards.unassigned.primary": "shards.unassigned.primary";
        shardsUnassignedPrimary: "shardsUnassignedPrimary";
        pending_tasks: "pending_tasks";
        pt: "pt";
        pendingTasks: "pendingTasks";
        max_task_wait_time: "max_task_wait_time";
        mtwt: "mtwt";
        maxTaskWaitTime: "maxTaskWaitTime";
        active_shards_percent: "active_shards_percent";
        asp: "asp";
        activeShardsPercent: "activeShardsPercent";
    }>, z.ZodString]>, z.ZodArray<z.ZodUnion<readonly [z.ZodEnum<{
        status: "status";
        shards: "shards";
        cluster: "cluster";
        i: "i";
        r: "r";
        t: "t";
        epoch: "epoch";
        time: "time";
        timestamp: "timestamp";
        ts: "ts";
        hms: "hms";
        hhmmss: "hhmmss";
        cl: "cl";
        st: "st";
        "node.total": "node.total";
        nt: "nt";
        nodeTotal: "nodeTotal";
        "node.data": "node.data";
        nd: "nd";
        nodeData: "nodeData";
        sh: "sh";
        "shards.total": "shards.total";
        shardsTotal: "shardsTotal";
        pri: "pri";
        p: "p";
        "shards.primary": "shards.primary";
        shardsPrimary: "shardsPrimary";
        relo: "relo";
        "shards.relocating": "shards.relocating";
        shardsRelocating: "shardsRelocating";
        init: "init";
        "shards.initializing": "shards.initializing";
        shardsInitializing: "shardsInitializing";
        unassign: "unassign";
        u: "u";
        "shards.unassigned": "shards.unassigned";
        shardsUnassigned: "shardsUnassigned";
        "unassign.pri": "unassign.pri";
        up: "up";
        "shards.unassigned.primary": "shards.unassigned.primary";
        shardsUnassignedPrimary: "shardsUnassignedPrimary";
        pending_tasks: "pending_tasks";
        pt: "pt";
        pendingTasks: "pendingTasks";
        max_task_wait_time: "max_task_wait_time";
        mtwt: "mtwt";
        maxTaskWaitTime: "maxTaskWaitTime";
        active_shards_percent: "active_shards_percent";
        asp: "asp";
        activeShardsPercent: "activeShardsPercent";
    }>, z.ZodString]>>]>>;
    s: z.ZodOptional<z.ZodUnion<readonly [z.ZodString, z.ZodArray<z.ZodString>]>>;
}, z.core.$strip>;
export type CatHealthRequest = z.infer<typeof CatHealthRequest>;
export declare const CatHealthResponse: z.ZodArray<z.ZodObject<{
    epoch: z.ZodOptional<z.ZodUnion<readonly [z.ZodAny, z.ZodString]>>;
    time: z.ZodOptional<z.ZodUnion<readonly [z.ZodAny, z.ZodString]>>;
    timestamp: z.ZodOptional<z.ZodString>;
    ts: z.ZodOptional<z.ZodString>;
    hms: z.ZodOptional<z.ZodString>;
    hhmmss: z.ZodOptional<z.ZodString>;
    cluster: z.ZodOptional<z.ZodString>;
    cl: z.ZodOptional<z.ZodString>;
    status: z.ZodOptional<z.ZodString>;
    st: z.ZodOptional<z.ZodString>;
    'node.total': z.ZodOptional<z.ZodString>;
    nt: z.ZodOptional<z.ZodString>;
    nodeTotal: z.ZodOptional<z.ZodString>;
    'node.data': z.ZodOptional<z.ZodString>;
    nd: z.ZodOptional<z.ZodString>;
    nodeData: z.ZodOptional<z.ZodString>;
    shards: z.ZodOptional<z.ZodString>;
    t: z.ZodOptional<z.ZodString>;
    sh: z.ZodOptional<z.ZodString>;
    'shards.total': z.ZodOptional<z.ZodString>;
    shardsTotal: z.ZodOptional<z.ZodString>;
    pri: z.ZodOptional<z.ZodString>;
    p: z.ZodOptional<z.ZodString>;
    'shards.primary': z.ZodOptional<z.ZodString>;
    shardsPrimary: z.ZodOptional<z.ZodString>;
    relo: z.ZodOptional<z.ZodString>;
    r: z.ZodOptional<z.ZodString>;
    'shards.relocating': z.ZodOptional<z.ZodString>;
    shardsRelocating: z.ZodOptional<z.ZodString>;
    init: z.ZodOptional<z.ZodString>;
    i: z.ZodOptional<z.ZodString>;
    'shards.initializing': z.ZodOptional<z.ZodString>;
    shardsInitializing: z.ZodOptional<z.ZodString>;
    'unassign.pri': z.ZodOptional<z.ZodString>;
    up: z.ZodOptional<z.ZodString>;
    'shards.unassigned.primary': z.ZodOptional<z.ZodString>;
    shardsUnassignedPrimary: z.ZodOptional<z.ZodString>;
    unassign: z.ZodOptional<z.ZodString>;
    u: z.ZodOptional<z.ZodString>;
    'shards.unassigned': z.ZodOptional<z.ZodString>;
    shardsUnassigned: z.ZodOptional<z.ZodString>;
    pending_tasks: z.ZodOptional<z.ZodString>;
    pt: z.ZodOptional<z.ZodString>;
    pendingTasks: z.ZodOptional<z.ZodString>;
    max_task_wait_time: z.ZodOptional<z.ZodString>;
    mtwt: z.ZodOptional<z.ZodString>;
    maxTaskWaitTime: z.ZodOptional<z.ZodString>;
    active_shards_percent: z.ZodOptional<z.ZodString>;
    asp: z.ZodOptional<z.ZodString>;
    activeShardsPercent: z.ZodOptional<z.ZodString>;
}, z.core.$strip>>;
export type CatHealthResponse = z.infer<typeof CatHealthResponse>;
//# sourceMappingURL=cat_health.d.ts.map