import { z } from 'zod';
/**
 * We are still working on this type, it will arrive soon.
 * If it's critical for you, please open an issue.
 * https://github.com/elastic/elasticsearch-specification
 */
export declare const TODO: z.ZodRecord<z.ZodString, z.ZodAny>;
export type TODO = z.infer<typeof TODO>;
export declare const Id: z.ZodString;
export type Id = z.infer<typeof Id>;
export declare const IndexName: z.ZodString;
export type IndexName = z.infer<typeof IndexName>;
export declare const Name: z.ZodString;
export type Name = z.infer<typeof Name>;
export declare const RequestBase: z.ZodObject<{}, z.core.$strip>;
export type RequestBase = z.infer<typeof RequestBase>;
export declare const VersionString: z.ZodString;
export type VersionString = z.infer<typeof VersionString>;
export declare const CatCatDfaColumn: z.ZodEnum<{
    state: "state";
    id: "id";
    description: "description";
    type: "type";
    version: "version";
    s: "s";
    di: "di";
    nn: "nn";
    t: "t";
    v: "v";
    p: "p";
    assignment_explanation: "assignment_explanation";
    ae: "ae";
    create_time: "create_time";
    ct: "ct";
    createTime: "createTime";
    d: "d";
    dest_index: "dest_index";
    destIndex: "destIndex";
    failure_reason: "failure_reason";
    fr: "fr";
    failureReason: "failureReason";
    model_memory_limit: "model_memory_limit";
    mml: "mml";
    modelMemoryLimit: "modelMemoryLimit";
    "node.address": "node.address";
    na: "na";
    nodeAddress: "nodeAddress";
    "node.ephemeral_id": "node.ephemeral_id";
    ne: "ne";
    nodeEphemeralId: "nodeEphemeralId";
    "node.id": "node.id";
    ni: "ni";
    nodeId: "nodeId";
    "node.name": "node.name";
    nodeName: "nodeName";
    progress: "progress";
    source_index: "source_index";
    si: "si";
    sourceIndex: "sourceIndex";
}>;
export type CatCatDfaColumn = z.infer<typeof CatCatDfaColumn>;
export declare const CatCatDfaColumns: z.ZodUnion<readonly [z.ZodEnum<{
    state: "state";
    id: "id";
    description: "description";
    type: "type";
    version: "version";
    s: "s";
    di: "di";
    nn: "nn";
    t: "t";
    v: "v";
    p: "p";
    assignment_explanation: "assignment_explanation";
    ae: "ae";
    create_time: "create_time";
    ct: "ct";
    createTime: "createTime";
    d: "d";
    dest_index: "dest_index";
    destIndex: "destIndex";
    failure_reason: "failure_reason";
    fr: "fr";
    failureReason: "failureReason";
    model_memory_limit: "model_memory_limit";
    mml: "mml";
    modelMemoryLimit: "modelMemoryLimit";
    "node.address": "node.address";
    na: "na";
    nodeAddress: "nodeAddress";
    "node.ephemeral_id": "node.ephemeral_id";
    ne: "ne";
    nodeEphemeralId: "nodeEphemeralId";
    "node.id": "node.id";
    ni: "ni";
    nodeId: "nodeId";
    "node.name": "node.name";
    nodeName: "nodeName";
    progress: "progress";
    source_index: "source_index";
    si: "si";
    sourceIndex: "sourceIndex";
}>, z.ZodArray<z.ZodEnum<{
    state: "state";
    id: "id";
    description: "description";
    type: "type";
    version: "version";
    s: "s";
    di: "di";
    nn: "nn";
    t: "t";
    v: "v";
    p: "p";
    assignment_explanation: "assignment_explanation";
    ae: "ae";
    create_time: "create_time";
    ct: "ct";
    createTime: "createTime";
    d: "d";
    dest_index: "dest_index";
    destIndex: "destIndex";
    failure_reason: "failure_reason";
    fr: "fr";
    failureReason: "failureReason";
    model_memory_limit: "model_memory_limit";
    mml: "mml";
    modelMemoryLimit: "modelMemoryLimit";
    "node.address": "node.address";
    na: "na";
    nodeAddress: "nodeAddress";
    "node.ephemeral_id": "node.ephemeral_id";
    ne: "ne";
    nodeEphemeralId: "nodeEphemeralId";
    "node.id": "node.id";
    ni: "ni";
    nodeId: "nodeId";
    "node.name": "node.name";
    nodeName: "nodeName";
    progress: "progress";
    source_index: "source_index";
    si: "si";
    sourceIndex: "sourceIndex";
}>>]>;
export type CatCatDfaColumns = z.infer<typeof CatCatDfaColumns>;
export declare const CatCatRequestBase: z.ZodObject<{}, z.core.$strip>;
export type CatCatRequestBase = z.infer<typeof CatCatRequestBase>;
export declare const CatMlDataFrameAnalyticsDataFrameAnalyticsRecord: z.ZodObject<{
    id: z.ZodOptional<z.ZodString>;
    type: z.ZodOptional<z.ZodString>;
    t: z.ZodOptional<z.ZodString>;
    create_time: z.ZodOptional<z.ZodString>;
    ct: z.ZodOptional<z.ZodString>;
    createTime: z.ZodOptional<z.ZodString>;
    version: z.ZodOptional<z.ZodString>;
    v: z.ZodOptional<z.ZodString>;
    source_index: z.ZodOptional<z.ZodString>;
    si: z.ZodOptional<z.ZodString>;
    sourceIndex: z.ZodOptional<z.ZodString>;
    dest_index: z.ZodOptional<z.ZodString>;
    di: z.ZodOptional<z.ZodString>;
    destIndex: z.ZodOptional<z.ZodString>;
    description: z.ZodOptional<z.ZodString>;
    d: z.ZodOptional<z.ZodString>;
    model_memory_limit: z.ZodOptional<z.ZodString>;
    mml: z.ZodOptional<z.ZodString>;
    modelMemoryLimit: z.ZodOptional<z.ZodString>;
    state: z.ZodOptional<z.ZodString>;
    s: z.ZodOptional<z.ZodString>;
    failure_reason: z.ZodOptional<z.ZodString>;
    fr: z.ZodOptional<z.ZodString>;
    failureReason: z.ZodOptional<z.ZodString>;
    progress: z.ZodOptional<z.ZodString>;
    p: z.ZodOptional<z.ZodString>;
    assignment_explanation: z.ZodOptional<z.ZodString>;
    ae: z.ZodOptional<z.ZodString>;
    assignmentExplanation: z.ZodOptional<z.ZodString>;
    'node.id': z.ZodOptional<z.ZodString>;
    ni: z.ZodOptional<z.ZodString>;
    nodeId: z.ZodOptional<z.ZodString>;
    'node.name': z.ZodOptional<z.ZodString>;
    nn: z.ZodOptional<z.ZodString>;
    nodeName: z.ZodOptional<z.ZodString>;
    'node.ephemeral_id': z.ZodOptional<z.ZodString>;
    ne: z.ZodOptional<z.ZodString>;
    nodeEphemeralId: z.ZodOptional<z.ZodString>;
    'node.address': z.ZodOptional<z.ZodString>;
    na: z.ZodOptional<z.ZodString>;
    nodeAddress: z.ZodOptional<z.ZodString>;
}, z.core.$strip>;
export type CatMlDataFrameAnalyticsDataFrameAnalyticsRecord = z.infer<typeof CatMlDataFrameAnalyticsDataFrameAnalyticsRecord>;
/**
 * Get data frame analytics jobs.
 *
 * Get configuration and usage information about data frame analytics jobs.
 *
 * IMPORTANT: CAT APIs are only intended for human consumption using the Kibana
 * console or command line. They are not intended for use by applications. For
 * application consumption, use the get data frame analytics jobs statistics API.
 */
export declare const CatMlDataFrameAnalyticsRequest: z.ZodObject<{
    id: z.ZodOptional<z.ZodString>;
    allow_no_match: z.ZodOptional<z.ZodBoolean>;
    h: z.ZodOptional<z.ZodUnion<readonly [z.ZodEnum<{
        state: "state";
        id: "id";
        description: "description";
        type: "type";
        version: "version";
        s: "s";
        di: "di";
        nn: "nn";
        t: "t";
        v: "v";
        p: "p";
        assignment_explanation: "assignment_explanation";
        ae: "ae";
        create_time: "create_time";
        ct: "ct";
        createTime: "createTime";
        d: "d";
        dest_index: "dest_index";
        destIndex: "destIndex";
        failure_reason: "failure_reason";
        fr: "fr";
        failureReason: "failureReason";
        model_memory_limit: "model_memory_limit";
        mml: "mml";
        modelMemoryLimit: "modelMemoryLimit";
        "node.address": "node.address";
        na: "na";
        nodeAddress: "nodeAddress";
        "node.ephemeral_id": "node.ephemeral_id";
        ne: "ne";
        nodeEphemeralId: "nodeEphemeralId";
        "node.id": "node.id";
        ni: "ni";
        nodeId: "nodeId";
        "node.name": "node.name";
        nodeName: "nodeName";
        progress: "progress";
        source_index: "source_index";
        si: "si";
        sourceIndex: "sourceIndex";
    }>, z.ZodArray<z.ZodEnum<{
        state: "state";
        id: "id";
        description: "description";
        type: "type";
        version: "version";
        s: "s";
        di: "di";
        nn: "nn";
        t: "t";
        v: "v";
        p: "p";
        assignment_explanation: "assignment_explanation";
        ae: "ae";
        create_time: "create_time";
        ct: "ct";
        createTime: "createTime";
        d: "d";
        dest_index: "dest_index";
        destIndex: "destIndex";
        failure_reason: "failure_reason";
        fr: "fr";
        failureReason: "failureReason";
        model_memory_limit: "model_memory_limit";
        mml: "mml";
        modelMemoryLimit: "modelMemoryLimit";
        "node.address": "node.address";
        na: "na";
        nodeAddress: "nodeAddress";
        "node.ephemeral_id": "node.ephemeral_id";
        ne: "ne";
        nodeEphemeralId: "nodeEphemeralId";
        "node.id": "node.id";
        ni: "ni";
        nodeId: "nodeId";
        "node.name": "node.name";
        nodeName: "nodeName";
        progress: "progress";
        source_index: "source_index";
        si: "si";
        sourceIndex: "sourceIndex";
    }>>]>>;
    s: z.ZodOptional<z.ZodUnion<readonly [z.ZodEnum<{
        state: "state";
        id: "id";
        description: "description";
        type: "type";
        version: "version";
        s: "s";
        di: "di";
        nn: "nn";
        t: "t";
        v: "v";
        p: "p";
        assignment_explanation: "assignment_explanation";
        ae: "ae";
        create_time: "create_time";
        ct: "ct";
        createTime: "createTime";
        d: "d";
        dest_index: "dest_index";
        destIndex: "destIndex";
        failure_reason: "failure_reason";
        fr: "fr";
        failureReason: "failureReason";
        model_memory_limit: "model_memory_limit";
        mml: "mml";
        modelMemoryLimit: "modelMemoryLimit";
        "node.address": "node.address";
        na: "na";
        nodeAddress: "nodeAddress";
        "node.ephemeral_id": "node.ephemeral_id";
        ne: "ne";
        nodeEphemeralId: "nodeEphemeralId";
        "node.id": "node.id";
        ni: "ni";
        nodeId: "nodeId";
        "node.name": "node.name";
        nodeName: "nodeName";
        progress: "progress";
        source_index: "source_index";
        si: "si";
        sourceIndex: "sourceIndex";
    }>, z.ZodArray<z.ZodEnum<{
        state: "state";
        id: "id";
        description: "description";
        type: "type";
        version: "version";
        s: "s";
        di: "di";
        nn: "nn";
        t: "t";
        v: "v";
        p: "p";
        assignment_explanation: "assignment_explanation";
        ae: "ae";
        create_time: "create_time";
        ct: "ct";
        createTime: "createTime";
        d: "d";
        dest_index: "dest_index";
        destIndex: "destIndex";
        failure_reason: "failure_reason";
        fr: "fr";
        failureReason: "failureReason";
        model_memory_limit: "model_memory_limit";
        mml: "mml";
        modelMemoryLimit: "modelMemoryLimit";
        "node.address": "node.address";
        na: "na";
        nodeAddress: "nodeAddress";
        "node.ephemeral_id": "node.ephemeral_id";
        ne: "ne";
        nodeEphemeralId: "nodeEphemeralId";
        "node.id": "node.id";
        ni: "ni";
        nodeId: "nodeId";
        "node.name": "node.name";
        nodeName: "nodeName";
        progress: "progress";
        source_index: "source_index";
        si: "si";
        sourceIndex: "sourceIndex";
    }>>]>>;
}, z.core.$strip>;
export type CatMlDataFrameAnalyticsRequest = z.infer<typeof CatMlDataFrameAnalyticsRequest>;
export declare const CatMlDataFrameAnalyticsResponse: z.ZodArray<z.ZodObject<{
    id: z.ZodOptional<z.ZodString>;
    type: z.ZodOptional<z.ZodString>;
    t: z.ZodOptional<z.ZodString>;
    create_time: z.ZodOptional<z.ZodString>;
    ct: z.ZodOptional<z.ZodString>;
    createTime: z.ZodOptional<z.ZodString>;
    version: z.ZodOptional<z.ZodString>;
    v: z.ZodOptional<z.ZodString>;
    source_index: z.ZodOptional<z.ZodString>;
    si: z.ZodOptional<z.ZodString>;
    sourceIndex: z.ZodOptional<z.ZodString>;
    dest_index: z.ZodOptional<z.ZodString>;
    di: z.ZodOptional<z.ZodString>;
    destIndex: z.ZodOptional<z.ZodString>;
    description: z.ZodOptional<z.ZodString>;
    d: z.ZodOptional<z.ZodString>;
    model_memory_limit: z.ZodOptional<z.ZodString>;
    mml: z.ZodOptional<z.ZodString>;
    modelMemoryLimit: z.ZodOptional<z.ZodString>;
    state: z.ZodOptional<z.ZodString>;
    s: z.ZodOptional<z.ZodString>;
    failure_reason: z.ZodOptional<z.ZodString>;
    fr: z.ZodOptional<z.ZodString>;
    failureReason: z.ZodOptional<z.ZodString>;
    progress: z.ZodOptional<z.ZodString>;
    p: z.ZodOptional<z.ZodString>;
    assignment_explanation: z.ZodOptional<z.ZodString>;
    ae: z.ZodOptional<z.ZodString>;
    assignmentExplanation: z.ZodOptional<z.ZodString>;
    'node.id': z.ZodOptional<z.ZodString>;
    ni: z.ZodOptional<z.ZodString>;
    nodeId: z.ZodOptional<z.ZodString>;
    'node.name': z.ZodOptional<z.ZodString>;
    nn: z.ZodOptional<z.ZodString>;
    nodeName: z.ZodOptional<z.ZodString>;
    'node.ephemeral_id': z.ZodOptional<z.ZodString>;
    ne: z.ZodOptional<z.ZodString>;
    nodeEphemeralId: z.ZodOptional<z.ZodString>;
    'node.address': z.ZodOptional<z.ZodString>;
    na: z.ZodOptional<z.ZodString>;
    nodeAddress: z.ZodOptional<z.ZodString>;
}, z.core.$strip>>;
export type CatMlDataFrameAnalyticsResponse = z.infer<typeof CatMlDataFrameAnalyticsResponse>;
//# sourceMappingURL=cat_ml_data_frame_analytics.d.ts.map