import { z } from 'zod';
/**
 * We are still working on this type, it will arrive soon.
 * If it's critical for you, please open an issue.
 * https://github.com/elastic/elasticsearch-specification
 */
export declare const TODO: z.ZodRecord<z.ZodString, z.ZodAny>;
export type TODO = z.infer<typeof TODO>;
/**
 * A duration. Units can be `nanos`, `micros`, `ms` (milliseconds), `s` (seconds), `m` (minutes), `h` (hours) and
 * `d` (days). Also accepts "0" without a unit and "-1" to indicate an unspecified value.
 */
export declare const Duration: z.ZodUnion<readonly [z.ZodString, z.ZodLiteral<-1>, z.ZodLiteral<0>]>;
export type Duration = z.infer<typeof Duration>;
export declare const Id: z.ZodString;
export type Id = z.infer<typeof Id>;
export declare const Name: z.ZodString;
export type Name = z.infer<typeof Name>;
export declare const Names: z.ZodUnion<readonly [z.ZodString, z.ZodArray<z.ZodString>]>;
export type Names = z.infer<typeof Names>;
export declare const NodeId: z.ZodString;
export type NodeId = z.infer<typeof NodeId>;
export declare const RequestBase: z.ZodObject<{}, z.core.$strip>;
export type RequestBase = z.infer<typeof RequestBase>;
export declare const VersionString: z.ZodString;
export type VersionString = z.infer<typeof VersionString>;
export declare const CatCatRequestBase: z.ZodObject<{}, z.core.$strip>;
export type CatCatRequestBase = z.infer<typeof CatCatRequestBase>;
export declare const CatCatTasksColumn: z.ZodUnion<readonly [z.ZodEnum<{
    start: "start";
    id: "id";
    type: "type";
    version: "version";
    task_id: "task_id";
    i: "i";
    node_id: "node_id";
    ip: "ip";
    node: "node";
    n: "n";
    v: "v";
    time: "time";
    timestamp: "timestamp";
    ts: "ts";
    hms: "hms";
    hhmmss: "hhmmss";
    ni: "ni";
    port: "port";
    po: "po";
    start_time: "start_time";
    ti: "ti";
    ty: "ty";
    parent_task_id: "parent_task_id";
    action: "action";
    ac: "ac";
    pti: "pti";
    running_time_ns: "running_time_ns";
    running_time: "running_time";
    x_opaque_id: "x_opaque_id";
    x: "x";
}>, z.ZodString]>;
export type CatCatTasksColumn = z.infer<typeof CatCatTasksColumn>;
export declare const CatCatTasksColumns: z.ZodUnion<readonly [z.ZodUnion<readonly [z.ZodEnum<{
    start: "start";
    id: "id";
    type: "type";
    version: "version";
    task_id: "task_id";
    i: "i";
    node_id: "node_id";
    ip: "ip";
    node: "node";
    n: "n";
    v: "v";
    time: "time";
    timestamp: "timestamp";
    ts: "ts";
    hms: "hms";
    hhmmss: "hhmmss";
    ni: "ni";
    port: "port";
    po: "po";
    start_time: "start_time";
    ti: "ti";
    ty: "ty";
    parent_task_id: "parent_task_id";
    action: "action";
    ac: "ac";
    pti: "pti";
    running_time_ns: "running_time_ns";
    running_time: "running_time";
    x_opaque_id: "x_opaque_id";
    x: "x";
}>, z.ZodString]>, z.ZodArray<z.ZodUnion<readonly [z.ZodEnum<{
    start: "start";
    id: "id";
    type: "type";
    version: "version";
    task_id: "task_id";
    i: "i";
    node_id: "node_id";
    ip: "ip";
    node: "node";
    n: "n";
    v: "v";
    time: "time";
    timestamp: "timestamp";
    ts: "ts";
    hms: "hms";
    hhmmss: "hhmmss";
    ni: "ni";
    port: "port";
    po: "po";
    start_time: "start_time";
    ti: "ti";
    ty: "ty";
    parent_task_id: "parent_task_id";
    action: "action";
    ac: "ac";
    pti: "pti";
    running_time_ns: "running_time_ns";
    running_time: "running_time";
    x_opaque_id: "x_opaque_id";
    x: "x";
}>, z.ZodString]>>]>;
export type CatCatTasksColumns = z.infer<typeof CatCatTasksColumns>;
/**
 * Get task information.
 *
 * Get information about tasks currently running in the cluster.
 * IMPORTANT: cat APIs are only intended for human consumption using the command line or Kibana console. They are not intended for use by applications. For application consumption, use the task management API.
 */
export declare const CatTasksRequest: z.ZodObject<{
    actions: z.ZodOptional<z.ZodArray<z.ZodString>>;
    detailed: z.ZodOptional<z.ZodBoolean>;
    nodes: z.ZodOptional<z.ZodArray<z.ZodString>>;
    parent_task_id: z.ZodOptional<z.ZodString>;
    h: z.ZodOptional<z.ZodUnion<readonly [z.ZodUnion<readonly [z.ZodEnum<{
        start: "start";
        id: "id";
        type: "type";
        version: "version";
        task_id: "task_id";
        i: "i";
        node_id: "node_id";
        ip: "ip";
        node: "node";
        n: "n";
        v: "v";
        time: "time";
        timestamp: "timestamp";
        ts: "ts";
        hms: "hms";
        hhmmss: "hhmmss";
        ni: "ni";
        port: "port";
        po: "po";
        start_time: "start_time";
        ti: "ti";
        ty: "ty";
        parent_task_id: "parent_task_id";
        action: "action";
        ac: "ac";
        pti: "pti";
        running_time_ns: "running_time_ns";
        running_time: "running_time";
        x_opaque_id: "x_opaque_id";
        x: "x";
    }>, z.ZodString]>, z.ZodArray<z.ZodUnion<readonly [z.ZodEnum<{
        start: "start";
        id: "id";
        type: "type";
        version: "version";
        task_id: "task_id";
        i: "i";
        node_id: "node_id";
        ip: "ip";
        node: "node";
        n: "n";
        v: "v";
        time: "time";
        timestamp: "timestamp";
        ts: "ts";
        hms: "hms";
        hhmmss: "hhmmss";
        ni: "ni";
        port: "port";
        po: "po";
        start_time: "start_time";
        ti: "ti";
        ty: "ty";
        parent_task_id: "parent_task_id";
        action: "action";
        ac: "ac";
        pti: "pti";
        running_time_ns: "running_time_ns";
        running_time: "running_time";
        x_opaque_id: "x_opaque_id";
        x: "x";
    }>, z.ZodString]>>]>>;
    s: z.ZodOptional<z.ZodUnion<readonly [z.ZodString, z.ZodArray<z.ZodString>]>>;
    timeout: z.ZodOptional<z.ZodUnion<readonly [z.ZodString, z.ZodLiteral<-1>, z.ZodLiteral<0>]>>;
    wait_for_completion: z.ZodOptional<z.ZodBoolean>;
}, z.core.$strip>;
export type CatTasksRequest = z.infer<typeof CatTasksRequest>;
export declare const CatTasksTasksRecord: z.ZodObject<{
    id: z.ZodOptional<z.ZodString>;
    action: z.ZodOptional<z.ZodString>;
    ac: z.ZodOptional<z.ZodString>;
    task_id: z.ZodOptional<z.ZodString>;
    ti: z.ZodOptional<z.ZodString>;
    parent_task_id: z.ZodOptional<z.ZodString>;
    pti: z.ZodOptional<z.ZodString>;
    type: z.ZodOptional<z.ZodString>;
    ty: z.ZodOptional<z.ZodString>;
    start_time: z.ZodOptional<z.ZodString>;
    start: z.ZodOptional<z.ZodString>;
    timestamp: z.ZodOptional<z.ZodString>;
    ts: z.ZodOptional<z.ZodString>;
    hms: z.ZodOptional<z.ZodString>;
    hhmmss: z.ZodOptional<z.ZodString>;
    running_time_ns: z.ZodOptional<z.ZodString>;
    running_time: z.ZodOptional<z.ZodString>;
    time: z.ZodOptional<z.ZodString>;
    node_id: z.ZodOptional<z.ZodString>;
    ni: z.ZodOptional<z.ZodString>;
    ip: z.ZodOptional<z.ZodString>;
    i: z.ZodOptional<z.ZodString>;
    port: z.ZodOptional<z.ZodString>;
    po: z.ZodOptional<z.ZodString>;
    node: z.ZodOptional<z.ZodString>;
    n: z.ZodOptional<z.ZodString>;
    version: z.ZodOptional<z.ZodString>;
    v: z.ZodOptional<z.ZodString>;
    x_opaque_id: z.ZodOptional<z.ZodString>;
    x: z.ZodOptional<z.ZodString>;
    description: z.ZodOptional<z.ZodString>;
    desc: z.ZodOptional<z.ZodString>;
}, z.core.$strip>;
export type CatTasksTasksRecord = z.infer<typeof CatTasksTasksRecord>;
export declare const CatTasksResponse: z.ZodArray<z.ZodObject<{
    id: z.ZodOptional<z.ZodString>;
    action: z.ZodOptional<z.ZodString>;
    ac: z.ZodOptional<z.ZodString>;
    task_id: z.ZodOptional<z.ZodString>;
    ti: z.ZodOptional<z.ZodString>;
    parent_task_id: z.ZodOptional<z.ZodString>;
    pti: z.ZodOptional<z.ZodString>;
    type: z.ZodOptional<z.ZodString>;
    ty: z.ZodOptional<z.ZodString>;
    start_time: z.ZodOptional<z.ZodString>;
    start: z.ZodOptional<z.ZodString>;
    timestamp: z.ZodOptional<z.ZodString>;
    ts: z.ZodOptional<z.ZodString>;
    hms: z.ZodOptional<z.ZodString>;
    hhmmss: z.ZodOptional<z.ZodString>;
    running_time_ns: z.ZodOptional<z.ZodString>;
    running_time: z.ZodOptional<z.ZodString>;
    time: z.ZodOptional<z.ZodString>;
    node_id: z.ZodOptional<z.ZodString>;
    ni: z.ZodOptional<z.ZodString>;
    ip: z.ZodOptional<z.ZodString>;
    i: z.ZodOptional<z.ZodString>;
    port: z.ZodOptional<z.ZodString>;
    po: z.ZodOptional<z.ZodString>;
    node: z.ZodOptional<z.ZodString>;
    n: z.ZodOptional<z.ZodString>;
    version: z.ZodOptional<z.ZodString>;
    v: z.ZodOptional<z.ZodString>;
    x_opaque_id: z.ZodOptional<z.ZodString>;
    x: z.ZodOptional<z.ZodString>;
    description: z.ZodOptional<z.ZodString>;
    desc: z.ZodOptional<z.ZodString>;
}, z.core.$strip>>;
export type CatTasksResponse = z.infer<typeof CatTasksResponse>;
//# sourceMappingURL=cat_tasks.d.ts.map