import { z } from 'zod';
/**
 * We are still working on this type, it will arrive soon.
 * If it's critical for you, please open an issue.
 * https://github.com/elastic/elasticsearch-specification
 */
export declare const TODO: z.ZodRecord<z.ZodString, z.ZodAny>;
export type TODO = z.infer<typeof TODO>;
export declare const EpochTime: z.ZodAny;
export type EpochTime = z.infer<typeof EpochTime>;
/**
 * A date and time, either as a string whose format can depend on the context (defaulting to ISO 8601), or a
 * number of milliseconds since the Epoch. Elasticsearch accepts both as input, but will generally output a string
 * representation.
 */
export declare const DateTime: z.ZodUnion<readonly [z.ZodString, z.ZodAny]>;
export type DateTime = z.infer<typeof DateTime>;
/**
 * A duration. Units can be `nanos`, `micros`, `ms` (milliseconds), `s` (seconds), `m` (minutes), `h` (hours) and
 * `d` (days). Also accepts "0" without a unit and "-1" to indicate an unspecified value.
 */
export declare const Duration: z.ZodUnion<readonly [z.ZodString, z.ZodLiteral<-1>, z.ZodLiteral<0>]>;
export type Duration = z.infer<typeof Duration>;
export declare const IndexName: z.ZodString;
export type IndexName = z.infer<typeof IndexName>;
export declare const Indices: z.ZodUnion<readonly [z.ZodString, z.ZodArray<z.ZodString>]>;
export type Indices = z.infer<typeof Indices>;
export declare const Name: z.ZodString;
export type Name = z.infer<typeof Name>;
export declare const Names: z.ZodUnion<readonly [z.ZodString, z.ZodArray<z.ZodString>]>;
export type Names = z.infer<typeof Names>;
export declare const float: z.ZodNumber;
export type float = z.infer<typeof float>;
export declare const Percentage: z.ZodUnion<readonly [z.ZodString, z.ZodNumber]>;
export type Percentage = z.infer<typeof Percentage>;
export declare const RequestBase: z.ZodObject<{}, z.core.$strip>;
export type RequestBase = z.infer<typeof RequestBase>;
export declare const CatCatRecoveryColumn: z.ZodUnion<readonly [z.ZodEnum<{
    start: "start";
    stop: "stop";
    index: "index";
    snapshot: "snapshot";
    type: "type";
    i: "i";
    idx: "idx";
    f: "f";
    s: "s";
    br: "br";
    t: "t";
    time: "time";
    st: "st";
    sh: "sh";
    rep: "rep";
    fr: "fr";
    b: "b";
    shard: "shard";
    start_time: "start_time";
    start_time_millis: "start_time_millis";
    start_millis: "start_millis";
    stop_time: "stop_time";
    stop_time_millis: "stop_time_millis";
    stop_millis: "stop_millis";
    ti: "ti";
    ty: "ty";
    stage: "stage";
    source_host: "source_host";
    shost: "shost";
    source_node: "source_node";
    snode: "snode";
    target_host: "target_host";
    thost: "thost";
    target_node: "target_node";
    tnode: "tnode";
    repository: "repository";
    snap: "snap";
    files: "files";
    files_recovered: "files_recovered";
    files_percent: "files_percent";
    fp: "fp";
    files_total: "files_total";
    tf: "tf";
    bytes: "bytes";
    bytes_recovered: "bytes_recovered";
    bytes_percent: "bytes_percent";
    bp: "bp";
    bytes_total: "bytes_total";
    tb: "tb";
    translog_ops: "translog_ops";
    to: "to";
    translog_ops_recovered: "translog_ops_recovered";
    tor: "tor";
    translog_ops_percent: "translog_ops_percent";
    top: "top";
}>, z.ZodString]>;
export type CatCatRecoveryColumn = z.infer<typeof CatCatRecoveryColumn>;
export declare const CatCatRecoveryColumns: z.ZodUnion<readonly [z.ZodUnion<readonly [z.ZodEnum<{
    start: "start";
    stop: "stop";
    index: "index";
    snapshot: "snapshot";
    type: "type";
    i: "i";
    idx: "idx";
    f: "f";
    s: "s";
    br: "br";
    t: "t";
    time: "time";
    st: "st";
    sh: "sh";
    rep: "rep";
    fr: "fr";
    b: "b";
    shard: "shard";
    start_time: "start_time";
    start_time_millis: "start_time_millis";
    start_millis: "start_millis";
    stop_time: "stop_time";
    stop_time_millis: "stop_time_millis";
    stop_millis: "stop_millis";
    ti: "ti";
    ty: "ty";
    stage: "stage";
    source_host: "source_host";
    shost: "shost";
    source_node: "source_node";
    snode: "snode";
    target_host: "target_host";
    thost: "thost";
    target_node: "target_node";
    tnode: "tnode";
    repository: "repository";
    snap: "snap";
    files: "files";
    files_recovered: "files_recovered";
    files_percent: "files_percent";
    fp: "fp";
    files_total: "files_total";
    tf: "tf";
    bytes: "bytes";
    bytes_recovered: "bytes_recovered";
    bytes_percent: "bytes_percent";
    bp: "bp";
    bytes_total: "bytes_total";
    tb: "tb";
    translog_ops: "translog_ops";
    to: "to";
    translog_ops_recovered: "translog_ops_recovered";
    tor: "tor";
    translog_ops_percent: "translog_ops_percent";
    top: "top";
}>, z.ZodString]>, z.ZodArray<z.ZodUnion<readonly [z.ZodEnum<{
    start: "start";
    stop: "stop";
    index: "index";
    snapshot: "snapshot";
    type: "type";
    i: "i";
    idx: "idx";
    f: "f";
    s: "s";
    br: "br";
    t: "t";
    time: "time";
    st: "st";
    sh: "sh";
    rep: "rep";
    fr: "fr";
    b: "b";
    shard: "shard";
    start_time: "start_time";
    start_time_millis: "start_time_millis";
    start_millis: "start_millis";
    stop_time: "stop_time";
    stop_time_millis: "stop_time_millis";
    stop_millis: "stop_millis";
    ti: "ti";
    ty: "ty";
    stage: "stage";
    source_host: "source_host";
    shost: "shost";
    source_node: "source_node";
    snode: "snode";
    target_host: "target_host";
    thost: "thost";
    target_node: "target_node";
    tnode: "tnode";
    repository: "repository";
    snap: "snap";
    files: "files";
    files_recovered: "files_recovered";
    files_percent: "files_percent";
    fp: "fp";
    files_total: "files_total";
    tf: "tf";
    bytes: "bytes";
    bytes_recovered: "bytes_recovered";
    bytes_percent: "bytes_percent";
    bp: "bp";
    bytes_total: "bytes_total";
    tb: "tb";
    translog_ops: "translog_ops";
    to: "to";
    translog_ops_recovered: "translog_ops_recovered";
    tor: "tor";
    translog_ops_percent: "translog_ops_percent";
    top: "top";
}>, z.ZodString]>>]>;
export type CatCatRecoveryColumns = z.infer<typeof CatCatRecoveryColumns>;
export declare const CatCatRequestBase: z.ZodObject<{}, z.core.$strip>;
export type CatCatRequestBase = z.infer<typeof CatCatRequestBase>;
export declare const CatRecoveryRecoveryRecord: z.ZodObject<{
    index: z.ZodOptional<z.ZodString>;
    i: z.ZodOptional<z.ZodString>;
    idx: z.ZodOptional<z.ZodString>;
    shard: z.ZodOptional<z.ZodString>;
    s: z.ZodOptional<z.ZodString>;
    sh: z.ZodOptional<z.ZodString>;
    start_time: z.ZodOptional<z.ZodUnion<readonly [z.ZodString, z.ZodAny]>>;
    start: z.ZodOptional<z.ZodUnion<readonly [z.ZodString, z.ZodAny]>>;
    start_time_millis: z.ZodOptional<z.ZodAny>;
    start_millis: z.ZodOptional<z.ZodAny>;
    stop_time: z.ZodOptional<z.ZodUnion<readonly [z.ZodString, z.ZodAny]>>;
    stop: z.ZodOptional<z.ZodUnion<readonly [z.ZodString, z.ZodAny]>>;
    stop_time_millis: z.ZodOptional<z.ZodAny>;
    stop_millis: z.ZodOptional<z.ZodAny>;
    time: z.ZodOptional<z.ZodUnion<readonly [z.ZodString, z.ZodLiteral<-1>, z.ZodLiteral<0>]>>;
    t: z.ZodOptional<z.ZodUnion<readonly [z.ZodString, z.ZodLiteral<-1>, z.ZodLiteral<0>]>>;
    ti: z.ZodOptional<z.ZodUnion<readonly [z.ZodString, z.ZodLiteral<-1>, z.ZodLiteral<0>]>>;
    type: z.ZodOptional<z.ZodString>;
    ty: z.ZodOptional<z.ZodString>;
    stage: z.ZodOptional<z.ZodString>;
    st: z.ZodOptional<z.ZodString>;
    source_host: z.ZodOptional<z.ZodString>;
    shost: z.ZodOptional<z.ZodString>;
    source_node: z.ZodOptional<z.ZodString>;
    snode: z.ZodOptional<z.ZodString>;
    target_host: z.ZodOptional<z.ZodString>;
    thost: z.ZodOptional<z.ZodString>;
    target_node: z.ZodOptional<z.ZodString>;
    tnode: z.ZodOptional<z.ZodString>;
    repository: z.ZodOptional<z.ZodString>;
    rep: z.ZodOptional<z.ZodString>;
    snapshot: z.ZodOptional<z.ZodString>;
    snap: z.ZodOptional<z.ZodString>;
    files: z.ZodOptional<z.ZodString>;
    f: z.ZodOptional<z.ZodString>;
    files_recovered: z.ZodOptional<z.ZodString>;
    fr: z.ZodOptional<z.ZodString>;
    files_percent: z.ZodOptional<z.ZodUnion<readonly [z.ZodString, z.ZodNumber]>>;
    fp: z.ZodOptional<z.ZodUnion<readonly [z.ZodString, z.ZodNumber]>>;
    files_total: z.ZodOptional<z.ZodString>;
    tf: z.ZodOptional<z.ZodString>;
    bytes: z.ZodOptional<z.ZodString>;
    b: z.ZodOptional<z.ZodString>;
    bytes_recovered: z.ZodOptional<z.ZodString>;
    br: z.ZodOptional<z.ZodString>;
    bytes_percent: z.ZodOptional<z.ZodUnion<readonly [z.ZodString, z.ZodNumber]>>;
    bp: z.ZodOptional<z.ZodUnion<readonly [z.ZodString, z.ZodNumber]>>;
    bytes_total: z.ZodOptional<z.ZodString>;
    tb: z.ZodOptional<z.ZodString>;
    translog_ops: z.ZodOptional<z.ZodString>;
    to: z.ZodOptional<z.ZodString>;
    translog_ops_recovered: z.ZodOptional<z.ZodString>;
    tor: z.ZodOptional<z.ZodString>;
    translog_ops_percent: z.ZodOptional<z.ZodUnion<readonly [z.ZodString, z.ZodNumber]>>;
    top: z.ZodOptional<z.ZodUnion<readonly [z.ZodString, z.ZodNumber]>>;
}, z.core.$strip>;
export type CatRecoveryRecoveryRecord = z.infer<typeof CatRecoveryRecoveryRecord>;
/**
 * Get shard recovery information.
 *
 * Get information about ongoing and completed shard recoveries.
 * Shard recovery is the process of initializing a shard copy, such as restoring a primary shard from a snapshot or syncing a replica shard from a primary shard. When a shard recovery completes, the recovered shard is available for search and indexing.
 * For data streams, the API returns information about the stream’s backing indices.
 * IMPORTANT: cat APIs are only intended for human consumption using the command line or Kibana console. They are not intended for use by applications. For application consumption, use the index recovery API.
 */
export declare const CatRecoveryRequest: z.ZodObject<{
    index: z.ZodOptional<z.ZodUnion<readonly [z.ZodString, z.ZodArray<z.ZodString>]>>;
    active_only: z.ZodOptional<z.ZodBoolean>;
    detailed: z.ZodOptional<z.ZodBoolean>;
    h: z.ZodOptional<z.ZodUnion<readonly [z.ZodUnion<readonly [z.ZodEnum<{
        start: "start";
        stop: "stop";
        index: "index";
        snapshot: "snapshot";
        type: "type";
        i: "i";
        idx: "idx";
        f: "f";
        s: "s";
        br: "br";
        t: "t";
        time: "time";
        st: "st";
        sh: "sh";
        rep: "rep";
        fr: "fr";
        b: "b";
        shard: "shard";
        start_time: "start_time";
        start_time_millis: "start_time_millis";
        start_millis: "start_millis";
        stop_time: "stop_time";
        stop_time_millis: "stop_time_millis";
        stop_millis: "stop_millis";
        ti: "ti";
        ty: "ty";
        stage: "stage";
        source_host: "source_host";
        shost: "shost";
        source_node: "source_node";
        snode: "snode";
        target_host: "target_host";
        thost: "thost";
        target_node: "target_node";
        tnode: "tnode";
        repository: "repository";
        snap: "snap";
        files: "files";
        files_recovered: "files_recovered";
        files_percent: "files_percent";
        fp: "fp";
        files_total: "files_total";
        tf: "tf";
        bytes: "bytes";
        bytes_recovered: "bytes_recovered";
        bytes_percent: "bytes_percent";
        bp: "bp";
        bytes_total: "bytes_total";
        tb: "tb";
        translog_ops: "translog_ops";
        to: "to";
        translog_ops_recovered: "translog_ops_recovered";
        tor: "tor";
        translog_ops_percent: "translog_ops_percent";
        top: "top";
    }>, z.ZodString]>, z.ZodArray<z.ZodUnion<readonly [z.ZodEnum<{
        start: "start";
        stop: "stop";
        index: "index";
        snapshot: "snapshot";
        type: "type";
        i: "i";
        idx: "idx";
        f: "f";
        s: "s";
        br: "br";
        t: "t";
        time: "time";
        st: "st";
        sh: "sh";
        rep: "rep";
        fr: "fr";
        b: "b";
        shard: "shard";
        start_time: "start_time";
        start_time_millis: "start_time_millis";
        start_millis: "start_millis";
        stop_time: "stop_time";
        stop_time_millis: "stop_time_millis";
        stop_millis: "stop_millis";
        ti: "ti";
        ty: "ty";
        stage: "stage";
        source_host: "source_host";
        shost: "shost";
        source_node: "source_node";
        snode: "snode";
        target_host: "target_host";
        thost: "thost";
        target_node: "target_node";
        tnode: "tnode";
        repository: "repository";
        snap: "snap";
        files: "files";
        files_recovered: "files_recovered";
        files_percent: "files_percent";
        fp: "fp";
        files_total: "files_total";
        tf: "tf";
        bytes: "bytes";
        bytes_recovered: "bytes_recovered";
        bytes_percent: "bytes_percent";
        bp: "bp";
        bytes_total: "bytes_total";
        tb: "tb";
        translog_ops: "translog_ops";
        to: "to";
        translog_ops_recovered: "translog_ops_recovered";
        tor: "tor";
        translog_ops_percent: "translog_ops_percent";
        top: "top";
    }>, z.ZodString]>>]>>;
    s: z.ZodOptional<z.ZodUnion<readonly [z.ZodString, z.ZodArray<z.ZodString>]>>;
}, z.core.$strip>;
export type CatRecoveryRequest = z.infer<typeof CatRecoveryRequest>;
export declare const CatRecoveryResponse: z.ZodArray<z.ZodObject<{
    index: z.ZodOptional<z.ZodString>;
    i: z.ZodOptional<z.ZodString>;
    idx: z.ZodOptional<z.ZodString>;
    shard: z.ZodOptional<z.ZodString>;
    s: z.ZodOptional<z.ZodString>;
    sh: z.ZodOptional<z.ZodString>;
    start_time: z.ZodOptional<z.ZodUnion<readonly [z.ZodString, z.ZodAny]>>;
    start: z.ZodOptional<z.ZodUnion<readonly [z.ZodString, z.ZodAny]>>;
    start_time_millis: z.ZodOptional<z.ZodAny>;
    start_millis: z.ZodOptional<z.ZodAny>;
    stop_time: z.ZodOptional<z.ZodUnion<readonly [z.ZodString, z.ZodAny]>>;
    stop: z.ZodOptional<z.ZodUnion<readonly [z.ZodString, z.ZodAny]>>;
    stop_time_millis: z.ZodOptional<z.ZodAny>;
    stop_millis: z.ZodOptional<z.ZodAny>;
    time: z.ZodOptional<z.ZodUnion<readonly [z.ZodString, z.ZodLiteral<-1>, z.ZodLiteral<0>]>>;
    t: z.ZodOptional<z.ZodUnion<readonly [z.ZodString, z.ZodLiteral<-1>, z.ZodLiteral<0>]>>;
    ti: z.ZodOptional<z.ZodUnion<readonly [z.ZodString, z.ZodLiteral<-1>, z.ZodLiteral<0>]>>;
    type: z.ZodOptional<z.ZodString>;
    ty: z.ZodOptional<z.ZodString>;
    stage: z.ZodOptional<z.ZodString>;
    st: z.ZodOptional<z.ZodString>;
    source_host: z.ZodOptional<z.ZodString>;
    shost: z.ZodOptional<z.ZodString>;
    source_node: z.ZodOptional<z.ZodString>;
    snode: z.ZodOptional<z.ZodString>;
    target_host: z.ZodOptional<z.ZodString>;
    thost: z.ZodOptional<z.ZodString>;
    target_node: z.ZodOptional<z.ZodString>;
    tnode: z.ZodOptional<z.ZodString>;
    repository: z.ZodOptional<z.ZodString>;
    rep: z.ZodOptional<z.ZodString>;
    snapshot: z.ZodOptional<z.ZodString>;
    snap: z.ZodOptional<z.ZodString>;
    files: z.ZodOptional<z.ZodString>;
    f: z.ZodOptional<z.ZodString>;
    files_recovered: z.ZodOptional<z.ZodString>;
    fr: z.ZodOptional<z.ZodString>;
    files_percent: z.ZodOptional<z.ZodUnion<readonly [z.ZodString, z.ZodNumber]>>;
    fp: z.ZodOptional<z.ZodUnion<readonly [z.ZodString, z.ZodNumber]>>;
    files_total: z.ZodOptional<z.ZodString>;
    tf: z.ZodOptional<z.ZodString>;
    bytes: z.ZodOptional<z.ZodString>;
    b: z.ZodOptional<z.ZodString>;
    bytes_recovered: z.ZodOptional<z.ZodString>;
    br: z.ZodOptional<z.ZodString>;
    bytes_percent: z.ZodOptional<z.ZodUnion<readonly [z.ZodString, z.ZodNumber]>>;
    bp: z.ZodOptional<z.ZodUnion<readonly [z.ZodString, z.ZodNumber]>>;
    bytes_total: z.ZodOptional<z.ZodString>;
    tb: z.ZodOptional<z.ZodString>;
    translog_ops: z.ZodOptional<z.ZodString>;
    to: z.ZodOptional<z.ZodString>;
    translog_ops_recovered: z.ZodOptional<z.ZodString>;
    tor: z.ZodOptional<z.ZodString>;
    translog_ops_percent: z.ZodOptional<z.ZodUnion<readonly [z.ZodString, z.ZodNumber]>>;
    top: z.ZodOptional<z.ZodUnion<readonly [z.ZodString, z.ZodNumber]>>;
}, z.core.$strip>>;
export type CatRecoveryResponse = z.infer<typeof CatRecoveryResponse>;
//# sourceMappingURL=cat_recovery.d.ts.map