import { z } from 'zod';
/**
 * We are still working on this type, it will arrive soon.
 * If it's critical for you, please open an issue.
 * https://github.com/elastic/elasticsearch-specification
 */
export declare const TODO: z.ZodRecord<z.ZodString, z.ZodAny>;
export type TODO = z.infer<typeof TODO>;
export declare const Id: z.ZodString;
export type Id = z.infer<typeof Id>;
export declare const RequestBase: z.ZodObject<{}, z.core.$strip>;
export type RequestBase = z.infer<typeof RequestBase>;
export declare const CatCatDatafeedColumn: z.ZodEnum<{
    state: "state";
    id: "id";
    s: "s";
    nn: "nn";
    st: "st";
    sc: "sc";
    assignment_explanation: "assignment_explanation";
    ae: "ae";
    "node.address": "node.address";
    na: "na";
    nodeAddress: "nodeAddress";
    "node.ephemeral_id": "node.ephemeral_id";
    ne: "ne";
    nodeEphemeralId: "nodeEphemeralId";
    "node.id": "node.id";
    ni: "ni";
    nodeId: "nodeId";
    "node.name": "node.name";
    nodeName: "nodeName";
    bc: "bc";
    "buckets.count": "buckets.count";
    bucketsCount: "bucketsCount";
    sba: "sba";
    "search.bucket_avg": "search.bucket_avg";
    searchBucketAvg: "searchBucketAvg";
    "search.count": "search.count";
    searchCount: "searchCount";
    seah: "seah";
    "search.exp_avg_hour": "search.exp_avg_hour";
    searchExpAvgHour: "searchExpAvgHour";
    "search.time": "search.time";
    searchTime: "searchTime";
}>;
export type CatCatDatafeedColumn = z.infer<typeof CatCatDatafeedColumn>;
export declare const CatCatDatafeedColumns: z.ZodUnion<readonly [z.ZodEnum<{
    state: "state";
    id: "id";
    s: "s";
    nn: "nn";
    st: "st";
    sc: "sc";
    assignment_explanation: "assignment_explanation";
    ae: "ae";
    "node.address": "node.address";
    na: "na";
    nodeAddress: "nodeAddress";
    "node.ephemeral_id": "node.ephemeral_id";
    ne: "ne";
    nodeEphemeralId: "nodeEphemeralId";
    "node.id": "node.id";
    ni: "ni";
    nodeId: "nodeId";
    "node.name": "node.name";
    nodeName: "nodeName";
    bc: "bc";
    "buckets.count": "buckets.count";
    bucketsCount: "bucketsCount";
    sba: "sba";
    "search.bucket_avg": "search.bucket_avg";
    searchBucketAvg: "searchBucketAvg";
    "search.count": "search.count";
    searchCount: "searchCount";
    seah: "seah";
    "search.exp_avg_hour": "search.exp_avg_hour";
    searchExpAvgHour: "searchExpAvgHour";
    "search.time": "search.time";
    searchTime: "searchTime";
}>, z.ZodArray<z.ZodEnum<{
    state: "state";
    id: "id";
    s: "s";
    nn: "nn";
    st: "st";
    sc: "sc";
    assignment_explanation: "assignment_explanation";
    ae: "ae";
    "node.address": "node.address";
    na: "na";
    nodeAddress: "nodeAddress";
    "node.ephemeral_id": "node.ephemeral_id";
    ne: "ne";
    nodeEphemeralId: "nodeEphemeralId";
    "node.id": "node.id";
    ni: "ni";
    nodeId: "nodeId";
    "node.name": "node.name";
    nodeName: "nodeName";
    bc: "bc";
    "buckets.count": "buckets.count";
    bucketsCount: "bucketsCount";
    sba: "sba";
    "search.bucket_avg": "search.bucket_avg";
    searchBucketAvg: "searchBucketAvg";
    "search.count": "search.count";
    searchCount: "searchCount";
    seah: "seah";
    "search.exp_avg_hour": "search.exp_avg_hour";
    searchExpAvgHour: "searchExpAvgHour";
    "search.time": "search.time";
    searchTime: "searchTime";
}>>]>;
export type CatCatDatafeedColumns = z.infer<typeof CatCatDatafeedColumns>;
export declare const CatCatRequestBase: z.ZodObject<{}, z.core.$strip>;
export type CatCatRequestBase = z.infer<typeof CatCatRequestBase>;
export declare const MlDatafeedState: z.ZodEnum<{
    started: "started";
    starting: "starting";
    stopping: "stopping";
    stopped: "stopped";
}>;
export type MlDatafeedState = z.infer<typeof MlDatafeedState>;
export declare const CatMlDatafeedsDatafeedsRecord: z.ZodObject<{
    id: z.ZodOptional<z.ZodString>;
    state: z.ZodOptional<z.ZodEnum<{
        started: "started";
        starting: "starting";
        stopping: "stopping";
        stopped: "stopped";
    }>>;
    s: z.ZodOptional<z.ZodEnum<{
        started: "started";
        starting: "starting";
        stopping: "stopping";
        stopped: "stopped";
    }>>;
    assignment_explanation: z.ZodOptional<z.ZodString>;
    ae: z.ZodOptional<z.ZodString>;
    'buckets.count': z.ZodOptional<z.ZodString>;
    bc: z.ZodOptional<z.ZodString>;
    bucketsCount: z.ZodOptional<z.ZodString>;
    'search.count': z.ZodOptional<z.ZodString>;
    sc: z.ZodOptional<z.ZodString>;
    searchCount: z.ZodOptional<z.ZodString>;
    'search.time': z.ZodOptional<z.ZodString>;
    st: z.ZodOptional<z.ZodString>;
    searchTime: z.ZodOptional<z.ZodString>;
    'search.bucket_avg': z.ZodOptional<z.ZodString>;
    sba: z.ZodOptional<z.ZodString>;
    searchBucketAvg: z.ZodOptional<z.ZodString>;
    'search.exp_avg_hour': z.ZodOptional<z.ZodString>;
    seah: z.ZodOptional<z.ZodString>;
    searchExpAvgHour: z.ZodOptional<z.ZodString>;
    'node.id': z.ZodOptional<z.ZodString>;
    ni: z.ZodOptional<z.ZodString>;
    nodeId: z.ZodOptional<z.ZodString>;
    'node.name': z.ZodOptional<z.ZodString>;
    nn: z.ZodOptional<z.ZodString>;
    nodeName: z.ZodOptional<z.ZodString>;
    'node.ephemeral_id': z.ZodOptional<z.ZodString>;
    ne: z.ZodOptional<z.ZodString>;
    nodeEphemeralId: z.ZodOptional<z.ZodString>;
    'node.address': z.ZodOptional<z.ZodString>;
    na: z.ZodOptional<z.ZodString>;
    nodeAddress: z.ZodOptional<z.ZodString>;
}, z.core.$strip>;
export type CatMlDatafeedsDatafeedsRecord = z.infer<typeof CatMlDatafeedsDatafeedsRecord>;
/**
 * Get datafeeds.
 *
 * Get configuration and usage information about datafeeds.
 * This API returns a maximum of 10,000 datafeeds.
 * If the Elasticsearch security features are enabled, you must have `monitor_ml`, `monitor`, `manage_ml`, or `manage`
 * cluster privileges to use this API.
 *
 * IMPORTANT: CAT APIs are only intended for human consumption using the Kibana
 * console or command line. They are not intended for use by applications. For
 * application consumption, use the get datafeed statistics API.
 */
export declare const CatMlDatafeedsRequest: z.ZodObject<{
    datafeed_id: z.ZodOptional<z.ZodString>;
    allow_no_match: z.ZodOptional<z.ZodBoolean>;
    h: z.ZodOptional<z.ZodUnion<readonly [z.ZodEnum<{
        state: "state";
        id: "id";
        s: "s";
        nn: "nn";
        st: "st";
        sc: "sc";
        assignment_explanation: "assignment_explanation";
        ae: "ae";
        "node.address": "node.address";
        na: "na";
        nodeAddress: "nodeAddress";
        "node.ephemeral_id": "node.ephemeral_id";
        ne: "ne";
        nodeEphemeralId: "nodeEphemeralId";
        "node.id": "node.id";
        ni: "ni";
        nodeId: "nodeId";
        "node.name": "node.name";
        nodeName: "nodeName";
        bc: "bc";
        "buckets.count": "buckets.count";
        bucketsCount: "bucketsCount";
        sba: "sba";
        "search.bucket_avg": "search.bucket_avg";
        searchBucketAvg: "searchBucketAvg";
        "search.count": "search.count";
        searchCount: "searchCount";
        seah: "seah";
        "search.exp_avg_hour": "search.exp_avg_hour";
        searchExpAvgHour: "searchExpAvgHour";
        "search.time": "search.time";
        searchTime: "searchTime";
    }>, z.ZodArray<z.ZodEnum<{
        state: "state";
        id: "id";
        s: "s";
        nn: "nn";
        st: "st";
        sc: "sc";
        assignment_explanation: "assignment_explanation";
        ae: "ae";
        "node.address": "node.address";
        na: "na";
        nodeAddress: "nodeAddress";
        "node.ephemeral_id": "node.ephemeral_id";
        ne: "ne";
        nodeEphemeralId: "nodeEphemeralId";
        "node.id": "node.id";
        ni: "ni";
        nodeId: "nodeId";
        "node.name": "node.name";
        nodeName: "nodeName";
        bc: "bc";
        "buckets.count": "buckets.count";
        bucketsCount: "bucketsCount";
        sba: "sba";
        "search.bucket_avg": "search.bucket_avg";
        searchBucketAvg: "searchBucketAvg";
        "search.count": "search.count";
        searchCount: "searchCount";
        seah: "seah";
        "search.exp_avg_hour": "search.exp_avg_hour";
        searchExpAvgHour: "searchExpAvgHour";
        "search.time": "search.time";
        searchTime: "searchTime";
    }>>]>>;
    s: z.ZodOptional<z.ZodUnion<readonly [z.ZodEnum<{
        state: "state";
        id: "id";
        s: "s";
        nn: "nn";
        st: "st";
        sc: "sc";
        assignment_explanation: "assignment_explanation";
        ae: "ae";
        "node.address": "node.address";
        na: "na";
        nodeAddress: "nodeAddress";
        "node.ephemeral_id": "node.ephemeral_id";
        ne: "ne";
        nodeEphemeralId: "nodeEphemeralId";
        "node.id": "node.id";
        ni: "ni";
        nodeId: "nodeId";
        "node.name": "node.name";
        nodeName: "nodeName";
        bc: "bc";
        "buckets.count": "buckets.count";
        bucketsCount: "bucketsCount";
        sba: "sba";
        "search.bucket_avg": "search.bucket_avg";
        searchBucketAvg: "searchBucketAvg";
        "search.count": "search.count";
        searchCount: "searchCount";
        seah: "seah";
        "search.exp_avg_hour": "search.exp_avg_hour";
        searchExpAvgHour: "searchExpAvgHour";
        "search.time": "search.time";
        searchTime: "searchTime";
    }>, z.ZodArray<z.ZodEnum<{
        state: "state";
        id: "id";
        s: "s";
        nn: "nn";
        st: "st";
        sc: "sc";
        assignment_explanation: "assignment_explanation";
        ae: "ae";
        "node.address": "node.address";
        na: "na";
        nodeAddress: "nodeAddress";
        "node.ephemeral_id": "node.ephemeral_id";
        ne: "ne";
        nodeEphemeralId: "nodeEphemeralId";
        "node.id": "node.id";
        ni: "ni";
        nodeId: "nodeId";
        "node.name": "node.name";
        nodeName: "nodeName";
        bc: "bc";
        "buckets.count": "buckets.count";
        bucketsCount: "bucketsCount";
        sba: "sba";
        "search.bucket_avg": "search.bucket_avg";
        searchBucketAvg: "searchBucketAvg";
        "search.count": "search.count";
        searchCount: "searchCount";
        seah: "seah";
        "search.exp_avg_hour": "search.exp_avg_hour";
        searchExpAvgHour: "searchExpAvgHour";
        "search.time": "search.time";
        searchTime: "searchTime";
    }>>]>>;
}, z.core.$strip>;
export type CatMlDatafeedsRequest = z.infer<typeof CatMlDatafeedsRequest>;
export declare const CatMlDatafeedsResponse: z.ZodArray<z.ZodObject<{
    id: z.ZodOptional<z.ZodString>;
    state: z.ZodOptional<z.ZodEnum<{
        started: "started";
        starting: "starting";
        stopping: "stopping";
        stopped: "stopped";
    }>>;
    s: z.ZodOptional<z.ZodEnum<{
        started: "started";
        starting: "starting";
        stopping: "stopping";
        stopped: "stopped";
    }>>;
    assignment_explanation: z.ZodOptional<z.ZodString>;
    ae: z.ZodOptional<z.ZodString>;
    'buckets.count': z.ZodOptional<z.ZodString>;
    bc: z.ZodOptional<z.ZodString>;
    bucketsCount: z.ZodOptional<z.ZodString>;
    'search.count': z.ZodOptional<z.ZodString>;
    sc: z.ZodOptional<z.ZodString>;
    searchCount: z.ZodOptional<z.ZodString>;
    'search.time': z.ZodOptional<z.ZodString>;
    st: z.ZodOptional<z.ZodString>;
    searchTime: z.ZodOptional<z.ZodString>;
    'search.bucket_avg': z.ZodOptional<z.ZodString>;
    sba: z.ZodOptional<z.ZodString>;
    searchBucketAvg: z.ZodOptional<z.ZodString>;
    'search.exp_avg_hour': z.ZodOptional<z.ZodString>;
    seah: z.ZodOptional<z.ZodString>;
    searchExpAvgHour: z.ZodOptional<z.ZodString>;
    'node.id': z.ZodOptional<z.ZodString>;
    ni: z.ZodOptional<z.ZodString>;
    nodeId: z.ZodOptional<z.ZodString>;
    'node.name': z.ZodOptional<z.ZodString>;
    nn: z.ZodOptional<z.ZodString>;
    nodeName: z.ZodOptional<z.ZodString>;
    'node.ephemeral_id': z.ZodOptional<z.ZodString>;
    ne: z.ZodOptional<z.ZodString>;
    nodeEphemeralId: z.ZodOptional<z.ZodString>;
    'node.address': z.ZodOptional<z.ZodString>;
    na: z.ZodOptional<z.ZodString>;
    nodeAddress: z.ZodOptional<z.ZodString>;
}, z.core.$strip>>;
export type CatMlDatafeedsResponse = z.infer<typeof CatMlDatafeedsResponse>;
//# sourceMappingURL=cat_ml_datafeeds.d.ts.map