import { z } from 'zod';
/**
 * We are still working on this type, it will arrive soon.
 * If it's critical for you, please open an issue.
 * https://github.com/elastic/elasticsearch-specification
 */
export declare const TODO: z.ZodRecord<z.ZodString, z.ZodAny>;
export type TODO = z.infer<typeof TODO>;
export declare const IndexName: z.ZodString;
export type IndexName = z.infer<typeof IndexName>;
export declare const RequestBase: z.ZodObject<{}, z.core.$strip>;
export type RequestBase = z.infer<typeof RequestBase>;
export declare const SecurityClusterPrivilege: z.ZodUnion<readonly [z.ZodEnum<{
    all: "all";
    none: "none";
    cancel_task: "cancel_task";
    create_snapshot: "create_snapshot";
    cross_cluster_replication: "cross_cluster_replication";
    cross_cluster_search: "cross_cluster_search";
    delegate_pki: "delegate_pki";
    grant_api_key: "grant_api_key";
    manage: "manage";
    manage_api_key: "manage_api_key";
    manage_autoscaling: "manage_autoscaling";
    manage_behavioral_analytics: "manage_behavioral_analytics";
    manage_ccr: "manage_ccr";
    manage_data_frame_transforms: "manage_data_frame_transforms";
    manage_data_stream_global_retention: "manage_data_stream_global_retention";
    manage_enrich: "manage_enrich";
    manage_esql: "manage_esql";
    manage_ilm: "manage_ilm";
    manage_index_templates: "manage_index_templates";
    manage_inference: "manage_inference";
    manage_ingest_pipelines: "manage_ingest_pipelines";
    manage_logstash_pipelines: "manage_logstash_pipelines";
    manage_ml: "manage_ml";
    manage_oidc: "manage_oidc";
    manage_own_api_key: "manage_own_api_key";
    manage_pipeline: "manage_pipeline";
    manage_reindex: "manage_reindex";
    manage_rollup: "manage_rollup";
    manage_saml: "manage_saml";
    manage_search_application: "manage_search_application";
    manage_search_query_rules: "manage_search_query_rules";
    manage_search_synonyms: "manage_search_synonyms";
    manage_security: "manage_security";
    manage_service_account: "manage_service_account";
    manage_slm: "manage_slm";
    manage_token: "manage_token";
    manage_transform: "manage_transform";
    manage_user_profile: "manage_user_profile";
    manage_watcher: "manage_watcher";
    monitor: "monitor";
    monitor_data_frame_transforms: "monitor_data_frame_transforms";
    monitor_data_stream_global_retention: "monitor_data_stream_global_retention";
    monitor_enrich: "monitor_enrich";
    monitor_esql: "monitor_esql";
    monitor_inference: "monitor_inference";
    monitor_ml: "monitor_ml";
    monitor_reindex: "monitor_reindex";
    monitor_rollup: "monitor_rollup";
    monitor_snapshot: "monitor_snapshot";
    monitor_stats: "monitor_stats";
    monitor_text_structure: "monitor_text_structure";
    monitor_transform: "monitor_transform";
    monitor_watcher: "monitor_watcher";
    post_behavioral_analytics_event: "post_behavioral_analytics_event";
    read_ccr: "read_ccr";
    read_fleet_secrets: "read_fleet_secrets";
    read_ilm: "read_ilm";
    read_pipeline: "read_pipeline";
    read_security: "read_security";
    read_slm: "read_slm";
    transport_client: "transport_client";
    write_connector_secrets: "write_connector_secrets";
    write_fleet_secrets: "write_fleet_secrets";
    read_project_routing: "read_project_routing";
    manage_project_routing: "manage_project_routing";
}>, z.ZodString]>;
export type SecurityClusterPrivilege = z.infer<typeof SecurityClusterPrivilege>;
/**
 * Get builtin privileges.
 *
 * Get the list of cluster privileges and index privileges that are available in this version of Elasticsearch.
 */
export declare const SecurityGetBuiltinPrivilegesRequest: z.ZodObject<{}, z.core.$strip>;
export type SecurityGetBuiltinPrivilegesRequest = z.infer<typeof SecurityGetBuiltinPrivilegesRequest>;
export declare const SecurityGetBuiltinPrivilegesResponse: z.ZodObject<{
    cluster: z.ZodArray<z.ZodUnion<readonly [z.ZodEnum<{
        all: "all";
        none: "none";
        cancel_task: "cancel_task";
        create_snapshot: "create_snapshot";
        cross_cluster_replication: "cross_cluster_replication";
        cross_cluster_search: "cross_cluster_search";
        delegate_pki: "delegate_pki";
        grant_api_key: "grant_api_key";
        manage: "manage";
        manage_api_key: "manage_api_key";
        manage_autoscaling: "manage_autoscaling";
        manage_behavioral_analytics: "manage_behavioral_analytics";
        manage_ccr: "manage_ccr";
        manage_data_frame_transforms: "manage_data_frame_transforms";
        manage_data_stream_global_retention: "manage_data_stream_global_retention";
        manage_enrich: "manage_enrich";
        manage_esql: "manage_esql";
        manage_ilm: "manage_ilm";
        manage_index_templates: "manage_index_templates";
        manage_inference: "manage_inference";
        manage_ingest_pipelines: "manage_ingest_pipelines";
        manage_logstash_pipelines: "manage_logstash_pipelines";
        manage_ml: "manage_ml";
        manage_oidc: "manage_oidc";
        manage_own_api_key: "manage_own_api_key";
        manage_pipeline: "manage_pipeline";
        manage_reindex: "manage_reindex";
        manage_rollup: "manage_rollup";
        manage_saml: "manage_saml";
        manage_search_application: "manage_search_application";
        manage_search_query_rules: "manage_search_query_rules";
        manage_search_synonyms: "manage_search_synonyms";
        manage_security: "manage_security";
        manage_service_account: "manage_service_account";
        manage_slm: "manage_slm";
        manage_token: "manage_token";
        manage_transform: "manage_transform";
        manage_user_profile: "manage_user_profile";
        manage_watcher: "manage_watcher";
        monitor: "monitor";
        monitor_data_frame_transforms: "monitor_data_frame_transforms";
        monitor_data_stream_global_retention: "monitor_data_stream_global_retention";
        monitor_enrich: "monitor_enrich";
        monitor_esql: "monitor_esql";
        monitor_inference: "monitor_inference";
        monitor_ml: "monitor_ml";
        monitor_reindex: "monitor_reindex";
        monitor_rollup: "monitor_rollup";
        monitor_snapshot: "monitor_snapshot";
        monitor_stats: "monitor_stats";
        monitor_text_structure: "monitor_text_structure";
        monitor_transform: "monitor_transform";
        monitor_watcher: "monitor_watcher";
        post_behavioral_analytics_event: "post_behavioral_analytics_event";
        read_ccr: "read_ccr";
        read_fleet_secrets: "read_fleet_secrets";
        read_ilm: "read_ilm";
        read_pipeline: "read_pipeline";
        read_security: "read_security";
        read_slm: "read_slm";
        transport_client: "transport_client";
        write_connector_secrets: "write_connector_secrets";
        write_fleet_secrets: "write_fleet_secrets";
        read_project_routing: "read_project_routing";
        manage_project_routing: "manage_project_routing";
    }>, z.ZodString]>>;
    index: z.ZodArray<z.ZodString>;
}, z.core.$strip>;
export type SecurityGetBuiltinPrivilegesResponse = z.infer<typeof SecurityGetBuiltinPrivilegesResponse>;
//# sourceMappingURL=security_get_builtin_privileges.d.ts.map