/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source open api file,
 * and elastic/elastic-client-generator-js to regenerate this file again.
 */

/* eslint-disable @typescript-eslint/no-redeclare */
import { z } from 'zod'
import { Data_views_allownoindex, Data_views_fieldattrs, Data_views_fieldformats, Data_views_namespaces, Data_views_runtimefieldmap, Data_views_sourcefilters, Data_views_timefieldname, Data_views_title, Data_views_type, Data_views_typemeta } from './schemas/data.js'

export const Data_views_create_data_view_request_object = z.object({
  data_view: z.object({
    allowNoIndex: Data_views_allownoindex.optional(),
    fieldAttrs: z.record(z.string(), Data_views_fieldattrs).optional(),
    fieldFormats: Data_views_fieldformats.optional(),
    fields: z.object({}).optional(),
    id: z.string().optional(),
    name: z.string().optional(),
    namespaces: Data_views_namespaces.optional(),
    runtimeFieldMap: z.record(z.string(), Data_views_runtimefieldmap).optional(),
    sourceFilters: Data_views_sourcefilters.optional(),
    timeFieldName: Data_views_timefieldname.optional(),
    title: Data_views_title,
    type: Data_views_type.optional(),
    typeMeta: Data_views_typemeta.optional(),
    version: z.string().optional()
  }),
  override: z.boolean().optional()
}).meta({ id: 'Data_views_create_data_view_request_object' })
export type Data_views_create_data_view_request_object = z.infer<typeof Data_views_create_data_view_request_object>

export { Data_views_data_view_response_object } from './schemas/data.js'
export { Data_views_typemeta_response } from './schemas/data.js'
export { Data_views_title } from './schemas/data.js'
export { Data_views_timefieldname } from './schemas/data.js'
export { Data_views_sourcefilters } from './schemas/data.js'
export { Data_views_runtimefieldmap } from './schemas/data.js'
export { Data_views_namespaces } from './schemas/data.js'
export { Data_views_fieldformats } from './schemas/data.js'
export { Data_views_fieldattrs } from './schemas/data.js'
export { Data_views_allownoindex } from './schemas/data.js'
export { Data_views_typemeta } from './schemas/data.js'
export { Data_views_type } from './schemas/data.js'
