/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source open api file,
 * and elastic/elastic-client-generator-js to regenerate this file again.
 */

/* eslint-disable @typescript-eslint/no-redeclare */
import { z } from 'zod'

export const CreateUpdateProtectionUpdatesNoteRequest = z.object({
  note: z.string()
}).meta({ id: 'CreateUpdateProtectionUpdatesNoteRequest' })
export type CreateUpdateProtectionUpdatesNoteRequest = z.infer<typeof CreateUpdateProtectionUpdatesNoteRequest>

export { Security_Endpoint_Management_API_ProtectionUpdatesNoteResponse } from './schemas/security.js'
