/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source open api file,
 * and elastic/elastic-client-generator-js to regenerate this file again.
 */

/* eslint-disable @typescript-eslint/no-redeclare */
import { z } from 'zod'

export const DeleteSingleEntityRequest = z.object({
  id: z.string()
}).meta({ id: 'DeleteSingleEntityRequest' })
export type DeleteSingleEntityRequest = z.infer<typeof DeleteSingleEntityRequest>

export const DeleteSingleEntityResponse = z.object({
  deleted: z.boolean().optional()
}).meta({ id: 'DeleteSingleEntityResponse' })
export type DeleteSingleEntityResponse = z.infer<typeof DeleteSingleEntityResponse>
