/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source open api file,
 * and elastic/elastic-client-generator-js to regenerate this file again.
 */

/* eslint-disable @typescript-eslint/no-redeclare */
import { z } from 'zod'
import { Security_Endpoint_Management_API_ResponseActionDetails } from './schemas/security.js'

export const Security_Endpoint_Management_API_GetEndpointActionListResponse = z.object({
  agentTypes: z.array(z.string()).optional(),
  commands: z.array(z.string()).optional(),
  data: z.array(Security_Endpoint_Management_API_ResponseActionDetails).optional(),
  elasticAgentIds: z.array(z.string()).optional(),
  endDate: z.string().optional(),
  page: z.number().optional(),
  pageSize: z.number().optional(),
  startDate: z.string().optional(),
  statuses: z.array(z.string()).optional(),
  total: z.number().optional(),
  userIds: z.array(z.string()).optional()
}).meta({ id: 'Security_Endpoint_Management_API_GetEndpointActionListResponse' })
export type Security_Endpoint_Management_API_GetEndpointActionListResponse = z.infer<typeof Security_Endpoint_Management_API_GetEndpointActionListResponse>

export { Security_Endpoint_Management_API_ResponseActionDetails } from './schemas/security.js'
export { Security_Endpoint_Management_API_Command } from './schemas/security.js'
export { Security_Endpoint_Management_API_AgentTypes } from './schemas/security.js'
