/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source open api file,
 * and elastic/elastic-client-generator-js to regenerate this file again.
 */

/* eslint-disable @typescript-eslint/no-redeclare */
import { z } from 'zod'

export const Security_Detections_API_MigrationFinalizationResult = z.object({
  completed: z.boolean(),
  destinationIndex: z.string(),
  error: z.object({
    message: z.string(),
    status_code: z.number()
  }).optional(),
  id: z.string(),
  sourceIndex: z.string(),
  status: z.enum(['success', 'failure', 'pending']),
  updated: z.string(),
  version: z.string()
}).meta({ id: 'Security_Detections_API_MigrationFinalizationResult' })
export type Security_Detections_API_MigrationFinalizationResult = z.infer<typeof Security_Detections_API_MigrationFinalizationResult>

export const FinalizeAlertsMigrationRequest = z.object({
  migration_ids: z.array(z.string())
}).meta({ id: 'FinalizeAlertsMigrationRequest' })
export type FinalizeAlertsMigrationRequest = z.infer<typeof FinalizeAlertsMigrationRequest>

export const FinalizeAlertsMigrationResponse = z.array(Security_Detections_API_MigrationFinalizationResult).meta({ id: 'FinalizeAlertsMigrationResponse' })
export type FinalizeAlertsMigrationResponse = z.infer<typeof FinalizeAlertsMigrationResponse>
