/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source open api file,
 * and elastic/elastic-client-generator-js to regenerate this file again.
 */

/* eslint-disable @typescript-eslint/no-redeclare */
import { z } from 'zod'
import { Security_Lists_API_ListItem } from './schemas/security.js'

export const Security_Lists_API_FindListItemsCursor = z.string().meta({ id: 'Security_Lists_API_FindListItemsCursor' })
export type Security_Lists_API_FindListItemsCursor = z.infer<typeof Security_Lists_API_FindListItemsCursor>

export const FindListItemsResponse = z.object({
  cursor: Security_Lists_API_FindListItemsCursor,
  data: z.array(Security_Lists_API_ListItem),
  page: z.number(),
  per_page: z.number(),
  total: z.number()
}).meta({ id: 'FindListItemsResponse' })
export type FindListItemsResponse = z.infer<typeof FindListItemsResponse>

export { Security_Lists_API_ListItem } from './schemas/security.js'
export { Security_Lists_API_ListItemValue } from './schemas/security.js'
export { Security_Lists_API_ListType } from './schemas/security.js'
export { Security_Lists_API_ListItemMetadata } from './schemas/security.js'
export { Security_Lists_API_ListId } from './schemas/security.js'
export { Security_Lists_API_ListItemId } from './schemas/security.js'
export { Security_Lists_API_ListVersionId } from './schemas/security.js'
