/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source open api file,
 * and elastic/elastic-client-generator-js to regenerate this file again.
 */

/* eslint-disable @typescript-eslint/no-redeclare */
import { z } from 'zod'
import { Security_Timeline_API_TimelineResponse } from './schemas/security.js'

export const GetTimelinesResponse = z.object({
  customTemplateTimelineCount: z.number().optional(),
  defaultTimelineCount: z.number().optional(),
  elasticTemplateTimelineCount: z.number().optional(),
  favoriteCount: z.number().optional(),
  templateTimelineCount: z.number().optional(),
  timeline: z.array(Security_Timeline_API_TimelineResponse),
  totalCount: z.number()
}).meta({ id: 'GetTimelinesResponse' })
export type GetTimelinesResponse = z.infer<typeof GetTimelinesResponse>

export { Security_Timeline_API_TimelineResponse } from './schemas/security.js'
export { Security_Timeline_API_PinnedEvent } from './schemas/security.js'
export { Security_Timeline_API_BarePinnedEvent } from './schemas/security.js'
export { Security_Timeline_API_PinnedEventCreatedAndUpdatedMetadata } from './schemas/security.js'
export { Security_Timeline_API_Note } from './schemas/security.js'
export { Security_Timeline_API_BareNote } from './schemas/security.js'
export { Security_Timeline_API_NoteCreatedAndUpdatedMetadata } from './schemas/security.js'
export { Security_Timeline_API_SavedTimelineWithSavedObjectId } from './schemas/security.js'
export { Security_Timeline_API_SavedTimeline } from './schemas/security.js'
export { Security_Timeline_API_TimelineType } from './schemas/security.js'
export { Security_Timeline_API_TimelineStatus } from './schemas/security.js'
export { Security_Timeline_API_Sort } from './schemas/security.js'
export { Security_Timeline_API_SortObject } from './schemas/security.js'
export { Security_Timeline_API_SerializedFilterQueryResult } from './schemas/security.js'
export { Security_Timeline_API_FilterTimelineResult } from './schemas/security.js'
export { Security_Timeline_API_FavoriteTimelineResult } from './schemas/security.js'
export { Security_Timeline_API_RowRendererId } from './schemas/security.js'
export { Security_Timeline_API_DataProviderResult } from './schemas/security.js'
export { Security_Timeline_API_DataProviderType } from './schemas/security.js'
export { Security_Timeline_API_QueryMatchResult } from './schemas/security.js'
export { Security_Timeline_API_DataProviderQueryMatch } from './schemas/security.js'
export { Security_Timeline_API_ColumnHeaderResult } from './schemas/security.js'
