/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source open api file,
 * and elastic/elastic-client-generator-js to regenerate this file again.
 */

/* eslint-disable @typescript-eslint/no-redeclare */
import { z } from 'zod'

export const APM_UI_settings_object = z.record(z.string(), z.string()).meta({ id: 'APM_UI_settings_object' })
export type APM_UI_settings_object = z.infer<typeof APM_UI_settings_object>

export const APM_UI_service_object = z.object({
  environment: z.string().optional(),
  name: z.string().optional()
}).meta({ id: 'APM_UI_service_object' })
export type APM_UI_service_object = z.infer<typeof APM_UI_service_object>

export const APM_UI_agent_configuration_object = z.object({
  '@timestamp': z.number(),
  agent_name: z.string().optional(),
  applied_by_agent: z.boolean().optional(),
  etag: z.string(),
  service: APM_UI_service_object,
  settings: APM_UI_settings_object
}).meta({ id: 'APM_UI_agent_configuration_object' })
export type APM_UI_agent_configuration_object = z.infer<typeof APM_UI_agent_configuration_object>

export const APM_UI_agent_configurations_response = z.object({
  configurations: z.array(APM_UI_agent_configuration_object).optional()
}).meta({ id: 'APM_UI_agent_configurations_response' })
export type APM_UI_agent_configurations_response = z.infer<typeof APM_UI_agent_configurations_response>
