/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source open api file,
 * and elastic/elastic-client-generator-js to regenerate this file again.
 */

/* eslint-disable @typescript-eslint/no-redeclare */
import { z } from 'zod'

export const APM_UI_service_environment_object = z.object({
  alreadyConfigured: z.boolean().optional(),
  name: z.string().optional()
}).meta({ id: 'APM_UI_service_environment_object' })
export type APM_UI_service_environment_object = z.infer<typeof APM_UI_service_environment_object>

export const APM_UI_service_environments_response = z.object({
  environments: z.array(APM_UI_service_environment_object).optional()
}).meta({ id: 'APM_UI_service_environments_response' })
export type APM_UI_service_environments_response = z.infer<typeof APM_UI_service_environments_response>
