/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source open api file,
 * and elastic/elastic-client-generator-js to regenerate this file again.
 */

/* eslint-disable @typescript-eslint/no-redeclare */
import { z } from 'zod'

export const GetAllDataViewsDefaultResponse = z.object({
  data_view: z.array(z.object({
    id: z.string().optional(),
    name: z.string().optional(),
    namespaces: z.array(z.string()).optional(),
    title: z.string().optional(),
    typeMeta: z.object({}).optional()
  })).optional()
}).meta({ id: 'GetAllDataViewsDefaultResponse' })
export type GetAllDataViewsDefaultResponse = z.infer<typeof GetAllDataViewsDefaultResponse>
