/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source open api file,
 * and elastic/elastic-client-generator-js to regenerate this file again.
 */

/* eslint-disable @typescript-eslint/no-redeclare */
import { z } from 'zod'

export const GetContextEngineAiIndexResponse = z.object({
  ai_indices: z.array(z.object({
    automations: z.array(z.object({
      type: z.enum(['workflow']),
      value: z.string()
    })),
    date_created: z.string(),
    date_modified: z.string(),
    description: z.string().optional(),
    dest: z.object({
      type: z.enum(['data_stream', 'index']),
      value: z.string()
    }),
    feedback_analysis: z.object({
      agent_id: z.string().optional(),
      allowed_actions: z.array(z.enum(['add_ki', 'edit_ki', 'remove_ki', 'add_workflow', 'edit_workflow', 'remove_workflow', 'add_source', 'edit_source', 'remove_source'])).optional(),
      enabled: z.boolean(),
      schedule: z.object({
        interval: z.string()
      }).optional(),
      signal_filter: z.string().optional(),
      signal_time_range: z.union([z.object({
        from: z.string(),
        type: z.enum(['relative'])
      }), z.object({
        from: z.string(),
        type: z.enum(['absolute'])
      })]).optional()
    }).optional(),
    id: z.string(),
    managed: z.boolean(),
    sources: z.array(z.object({
      type: z.enum(['esql', 'connector']),
      value: z.string()
    })),
    traces: z.array(z.object({
      query: z.string(),
      type: z.enum(['elastic_agent', 'index', 'esql']),
      value: z.string()
    }))
  }))
}).meta({ id: 'GetContextEngineAiIndexResponse' })
export type GetContextEngineAiIndexResponse = z.infer<typeof GetContextEngineAiIndexResponse>
