/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source open api file,
 * and elastic/elastic-client-generator-js to regenerate this file again.
 */

/* eslint-disable @typescript-eslint/no-redeclare */
import { z } from 'zod'

export const Security_Entity_Analytics_API_EntityType = z.enum(['user', 'host', 'service', 'generic']).meta({ id: 'Security_Entity_Analytics_API_EntityType' })
export type Security_Entity_Analytics_API_EntityType = z.infer<typeof Security_Entity_Analytics_API_EntityType>

export const Security_Entity_Analytics_API_EngineStatus = z.enum(['installing', 'started', 'stopped', 'updating', 'error']).meta({ id: 'Security_Entity_Analytics_API_EngineStatus' })
export type Security_Entity_Analytics_API_EngineStatus = z.infer<typeof Security_Entity_Analytics_API_EngineStatus>

export const Security_Entity_Analytics_API_IndexPattern = z.string().meta({ id: 'Security_Entity_Analytics_API_IndexPattern' })
export type Security_Entity_Analytics_API_IndexPattern = z.infer<typeof Security_Entity_Analytics_API_IndexPattern>

export const Security_Entity_Analytics_API_EngineDescriptor = z.object({
  delay: z.string().optional(),
  docsPerSecond: z.number().optional(),
  error: z.object({
    action: z.enum(['init']),
    message: z.string()
  }).optional(),
  fieldHistoryLength: z.number(),
  filter: z.string().optional(),
  frequency: z.string().optional(),
  indexPattern: Security_Entity_Analytics_API_IndexPattern,
  lookbackPeriod: z.string().optional(),
  status: Security_Entity_Analytics_API_EngineStatus,
  timeout: z.string().optional(),
  timestampField: z.string().optional(),
  type: Security_Entity_Analytics_API_EntityType
}).meta({ id: 'Security_Entity_Analytics_API_EngineDescriptor' })
export type Security_Entity_Analytics_API_EngineDescriptor = z.infer<typeof Security_Entity_Analytics_API_EngineDescriptor>
