/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source open api file,
 * and elastic/elastic-client-generator-js to regenerate this file again.
 */

/* eslint-disable @typescript-eslint/no-redeclare */
import { z } from 'zod'

export const Kibana_HTTP_APIs_get_inputs_response = z.object({
  connectors: z.record(z.string(), z.unknown().nullable()).optional(),
  exporters: z.record(z.string(), z.unknown().nullable()).optional(),
  extensions: z.record(z.string(), z.unknown().nullable()).optional(),
  inputs: z.array(z.object({
    id: z.string(),
    streams: z.array(z.object({
      data_stream: z.object({
        dataset: z.string(),
        type: z.string().optional()
      }).passthrough(),
      id: z.string()
    }).passthrough()).optional(),
    type: z.string()
  })),
  processors: z.record(z.string(), z.unknown().nullable()).optional(),
  receivers: z.record(z.string(), z.unknown().nullable()).optional(),
  service: z.object({
    extensions: z.array(z.string()).optional(),
    pipelines: z.record(z.string(), z.object({
      exporters: z.array(z.string()).optional(),
      processors: z.array(z.string()).optional(),
      receivers: z.array(z.string()).optional()
    })).optional()
  }).optional()
}).meta({ id: 'Kibana_HTTP_APIs_get_inputs_response' })
export type Kibana_HTTP_APIs_get_inputs_response = z.infer<typeof Kibana_HTTP_APIs_get_inputs_response>

export const GetFleetEpmTemplatesPkgnamePkgversionInputsResponse = z.union([z.string(), Kibana_HTTP_APIs_get_inputs_response]).meta({ id: 'GetFleetEpmTemplatesPkgnamePkgversionInputsResponse' })
export type GetFleetEpmTemplatesPkgnamePkgversionInputsResponse = z.infer<typeof GetFleetEpmTemplatesPkgnamePkgversionInputsResponse>
