/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source open api file,
 * and elastic/elastic-client-generator-js to regenerate this file again.
 */

/* eslint-disable @typescript-eslint/no-redeclare */
import { z } from 'zod'

export const GetAlertingRuleIdQueryInspectorResponse = z.object({
  queries: z.array(z.object({
    index: z.string(),
    label: z.string().optional(),
    request: z.record(z.string(), z.unknown().nullable()),
    response: z.record(z.string(), z.unknown().nullable()).optional()
  }))
}).meta({ id: 'GetAlertingRuleIdQueryInspectorResponse' })
export type GetAlertingRuleIdQueryInspectorResponse = z.infer<typeof GetAlertingRuleIdQueryInspectorResponse>
