/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source open api file,
 * and elastic/elastic-client-generator-js to regenerate this file again.
 */

/* eslint-disable @typescript-eslint/no-redeclare */
import { z } from 'zod'

export const APM_UI_annotation_search_response = z.object({
  annotations: z.array(z.object({
    '@timestamp': z.number().optional(),
    id: z.string().optional(),
    text: z.string().optional(),
    type: z.enum(['version']).optional()
  })).optional()
}).meta({ id: 'APM_UI_annotation_search_response' })
export type APM_UI_annotation_search_response = z.infer<typeof APM_UI_annotation_search_response>
