/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source open api file,
 * and elastic/elastic-client-generator-js to regenerate this file again.
 */

/* eslint-disable @typescript-eslint/no-redeclare */
import { z } from 'zod'

export const GetPrivilegedAccessDetectionPackageStatusResponse = z.object({
  jobs: z.array(z.object({
    description: z.string().optional(),
    job_id: z.string(),
    state: z.enum(['closing', 'closed', 'opened', 'failed', 'opening'])
  })),
  ml_module_setup_status: z.enum(['complete', 'incomplete']),
  package_installation_status: z.enum(['complete', 'incomplete'])
}).meta({ id: 'GetPrivilegedAccessDetectionPackageStatusResponse' })
export type GetPrivilegedAccessDetectionPackageStatusResponse = z.infer<typeof GetPrivilegedAccessDetectionPackageStatusResponse>
