/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source open api file,
 * and elastic/elastic-client-generator-js to regenerate this file again.
 */

/* eslint-disable @typescript-eslint/no-redeclare */
import { z } from 'zod'
import { Cases_field_definition_response } from './schemas/misc.js'

export const Cases_get_case_field_definitions_response = z.object({
  fieldDefinitions: z.array(Cases_field_definition_response),
  page: z.number(),
  perPage: z.number(),
  total: z.number()
}).meta({ id: 'Cases_get_case_field_definitions_response' })
export type Cases_get_case_field_definitions_response = z.infer<typeof Cases_get_case_field_definitions_response>

export { Cases_field_definition_response } from './schemas/misc.js'
