/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source open api file,
 * and elastic/elastic-client-generator-js to regenerate this file again.
 */

/* eslint-disable @typescript-eslint/no-redeclare */
import { z } from 'zod'

export const GetFleetCloudOnboardingDeploymentsConnectorConnectoridResponse = z.object({
  items: z.array(z.object({
    agentPolicyId: z.string().optional(),
    apiKeyId: z.string().optional(),
    attemptCount: z.number(),
    authMethod: z.enum(['identity_federation', 'static_keys']).optional(),
    connectorId: z.string().optional(),
    dataFormat: z.enum(['ecs', 'otel']).optional(),
    deploymentId: z.string().optional(),
    deploymentName: z.string().optional(),
    ecfStacks: z.array(z.object({
      family: z.enum(['unified', 'otel', 'crowdstrike']),
      stackName: z.string(),
      templateVersion: z.string()
    })).optional(),
    globalRegion: z.string().optional(),
    id: z.string(),
    mechanisms: z.array(z.enum(['managed_integration', 'ecf', 'agent_based'])),
    packagePolicyIds: z.array(z.string()).optional(),
    provider: z.enum(['aws', 'azure', 'gcp']),
    services: z.array(z.string()),
    serviceVars: z.record(z.string(), z.record(z.string(), z.unknown().nullable())).optional(),
    status: z.enum(['pending', 'deploying', 'succeeded', 'failed']),
    statusMessage: z.string().optional()
  }))
}).meta({ id: 'GetFleetCloudOnboardingDeploymentsConnectorConnectoridResponse' })
export type GetFleetCloudOnboardingDeploymentsConnectorConnectoridResponse = z.infer<typeof GetFleetCloudOnboardingDeploymentsConnectorConnectoridResponse>
