/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source open api file,
 * and elastic/elastic-client-generator-js to regenerate this file again.
 */

/* eslint-disable @typescript-eslint/no-redeclare */
import { z } from 'zod'
import { Security_Attack_discovery_API_AttackDiscoveryGeneration } from './schemas/security.js'

export const GetAttackDiscoveryGenerationsResponse = z.object({
  generations: z.array(Security_Attack_discovery_API_AttackDiscoveryGeneration)
}).meta({ id: 'GetAttackDiscoveryGenerationsResponse' })
export type GetAttackDiscoveryGenerationsResponse = z.infer<typeof GetAttackDiscoveryGenerationsResponse>

export { Security_Attack_discovery_API_AttackDiscoveryGeneration } from './schemas/security.js'
export { Security_Attack_discovery_API_WorkflowExecutionsTracking } from './schemas/security.js'
export { Security_Attack_discovery_API_WorkflowExecutionReference } from './schemas/security.js'
