/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source open api file,
 * and elastic/elastic-client-generator-js to regenerate this file again.
 */

/* eslint-disable @typescript-eslint/no-redeclare */
import { z } from 'zod'
import { Kibana_HTTP_APIs_package_policy_response } from './schemas/kibana.js'

export const GetFleetPackagePoliciesPackagepolicyidResponse = z.object({
  item: Kibana_HTTP_APIs_package_policy_response
}).meta({ id: 'GetFleetPackagePoliciesPackagepolicyidResponse' })
export type GetFleetPackagePoliciesPackagepolicyidResponse = z.infer<typeof GetFleetPackagePoliciesPackagepolicyidResponse>

export { Kibana_HTTP_APIs_package_policy_response } from './schemas/kibana.js'
export { Kibana_HTTP_APIs_package_policy_package } from './schemas/kibana.js'
export { Kibana_HTTP_APIs_simplified_package_policy_stream_deprecation_info } from './schemas/kibana.js'
export { Kibana_HTTP_APIs_simplified_package_policy_input_deprecation_info } from './schemas/kibana.js'
export { Kibana_HTTP_APIs_package_policy_stream_deprecation_info } from './schemas/kibana.js'
export { Kibana_HTTP_APIs_package_policy_input_deprecation_info } from './schemas/kibana.js'
