/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source open api file,
 * and elastic/elastic-client-generator-js to regenerate this file again.
 */

/* eslint-disable @typescript-eslint/no-redeclare */
import { z } from 'zod'
import { Cases_template_v2_response } from './schemas/misc.js'

export const Cases_get_case_templates_response = z.object({
  page: z.number(),
  perPage: z.number(),
  templates: z.array(Cases_template_v2_response.merge(z.object({
    fieldSearchMatches: z.boolean()
  }))),
  total: z.number()
}).meta({ id: 'Cases_get_case_templates_response' })
export type Cases_get_case_templates_response = z.infer<typeof Cases_get_case_templates_response>

export { Cases_template_v2_response } from './schemas/misc.js'
export { Cases_template_tags } from './schemas/misc.js'
