/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source open api file,
 * and elastic/elastic-client-generator-js to regenerate this file again.
 */

/* eslint-disable @typescript-eslint/no-redeclare */
import { z } from 'zod'

export const PostSecuritySessionInvalidateRequest = z.object({
  match: z.enum(['all', 'query']),
  query: z.object({
    provider: z.object({
      name: z.string().optional(),
      type: z.string()
    }),
    username: z.string().optional()
  }).optional()
}).meta({ id: 'PostSecuritySessionInvalidateRequest' })
export type PostSecuritySessionInvalidateRequest = z.infer<typeof PostSecuritySessionInvalidateRequest>

export const PostSecuritySessionInvalidateResponse = z.object({
  total: z.number().optional()
}).meta({ id: 'PostSecuritySessionInvalidateResponse' })
export type PostSecuritySessionInvalidateResponse = z.infer<typeof PostSecuritySessionInvalidateResponse>
