/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source open api file,
 * and elastic/elastic-client-generator-js to regenerate this file again.
 */

/* eslint-disable @typescript-eslint/no-redeclare */
import { z } from 'zod'

export const Kibana_HTTP_APIs_reauthorize_transform_request = z.object({
  transforms: z.array(z.object({
    transformId: z.string()
  }))
}).meta({ id: 'Kibana_HTTP_APIs_reauthorize_transform_request' })
export type Kibana_HTTP_APIs_reauthorize_transform_request = z.infer<typeof Kibana_HTTP_APIs_reauthorize_transform_request>

export const PostFleetEpmPackagesPkgnamePkgversionTransformsAuthorizeResponse = z.array(z.object({
  error: z.unknown().nullable(),
  success: z.boolean(),
  transformId: z.string()
})).meta({ id: 'PostFleetEpmPackagesPkgnamePkgversionTransformsAuthorizeResponse' })
export type PostFleetEpmPackagesPkgnamePkgversionTransformsAuthorizeResponse = z.infer<typeof PostFleetEpmPackagesPkgnamePkgversionTransformsAuthorizeResponse>
