/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source open api file,
 * and elastic/elastic-client-generator-js to regenerate this file again.
 */

/* eslint-disable @typescript-eslint/no-redeclare */
import { z } from 'zod'

export const PostContextEngineAiIndexQueryRequest = z.object({
  limit: z.number().optional(),
  params: z.record(z.string(), z.union([z.string(), z.number(), z.boolean()])).optional(),
  query: z.string()
}).meta({ id: 'PostContextEngineAiIndexQueryRequest' })
export type PostContextEngineAiIndexQueryRequest = z.infer<typeof PostContextEngineAiIndexQueryRequest>

export const PostContextEngineAiIndexQueryResponse = z.object({
  columns: z.array(z.object({
    name: z.string(),
    type: z.string()
  }).passthrough()),
  values: z.array(z.array(z.unknown().nullable()))
}).meta({ id: 'PostContextEngineAiIndexQueryResponse' })
export type PostContextEngineAiIndexQueryResponse = z.infer<typeof PostContextEngineAiIndexQueryResponse>
