/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source open api file,
 * and elastic/elastic-client-generator-js to regenerate this file again.
 */

/* eslint-disable @typescript-eslint/no-redeclare */
import { z } from 'zod'

export const PostChatMessageRequest = z.object({
  agent_id: z.string().optional(),
  conversation_id: z.string().optional(),
  message: z.string()
}).meta({ id: 'PostChatMessageRequest' })
export type PostChatMessageRequest = z.infer<typeof PostChatMessageRequest>

export const PostChatMessageResponse = z.object({
  answer: z.string(),
  conversation_id: z.string(),
  declined_prompts: z.array(z.object({
    message: z.string(),
    tool_id: z.string()
  })).optional()
}).meta({ id: 'PostChatMessageResponse' })
export type PostChatMessageResponse = z.infer<typeof PostChatMessageResponse>
