/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source open api file,
 * and elastic/elastic-client-generator-js to regenerate this file again.
 */

/* eslint-disable @typescript-eslint/no-redeclare */
import { z } from 'zod'
import { Kibana_HTTP_APIs_action_id_response, Kibana_HTTP_APIs_action_message_response } from './schemas/kibana.js'

export const PostFleetAgentsBulkRestartRequest = z.object({
  agents: z.union([z.array(z.string()), z.string()]),
  batchSize: z.number().optional(),
  includeInactive: z.boolean().optional()
}).meta({ id: 'PostFleetAgentsBulkRestartRequest' })
export type PostFleetAgentsBulkRestartRequest = z.infer<typeof PostFleetAgentsBulkRestartRequest>

export const PostFleetAgentsBulkRestartResponse = z.union([Kibana_HTTP_APIs_action_id_response, Kibana_HTTP_APIs_action_message_response]).meta({ id: 'PostFleetAgentsBulkRestartResponse' })
export type PostFleetAgentsBulkRestartResponse = z.infer<typeof PostFleetAgentsBulkRestartResponse>

export { Kibana_HTTP_APIs_action_message_response } from './schemas/kibana.js'
export { Kibana_HTTP_APIs_action_id_response } from './schemas/kibana.js'
