/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source open api file,
 * and elastic/elastic-client-generator-js to regenerate this file again.
 */

/* eslint-disable @typescript-eslint/no-redeclare */
import { z } from 'zod'

export const Kibana_HTTP_APIs_review_upgrade_response = z.object({
  success: z.boolean()
}).meta({ id: 'Kibana_HTTP_APIs_review_upgrade_response' })
export type Kibana_HTTP_APIs_review_upgrade_response = z.infer<typeof Kibana_HTTP_APIs_review_upgrade_response>

export const Kibana_HTTP_APIs_review_upgrade_request = z.object({
  action: z.enum(['accept', 'decline', 'pending']),
  target_version: z.string()
}).meta({ id: 'Kibana_HTTP_APIs_review_upgrade_request' })
export type Kibana_HTTP_APIs_review_upgrade_request = z.infer<typeof Kibana_HTTP_APIs_review_upgrade_request>
