/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source open api file,
 * and elastic/elastic-client-generator-js to regenerate this file again.
 */

/* eslint-disable @typescript-eslint/no-redeclare */
import { z } from 'zod'

export const PostFleetHealthCheckRequest = z.object({
  id: z.string()
}).meta({ id: 'PostFleetHealthCheckRequest' })
export type PostFleetHealthCheckRequest = z.infer<typeof PostFleetHealthCheckRequest>

export const PostFleetHealthCheckResponse = z.object({
  host_id: z.string().optional(),
  name: z.string().optional(),
  status: z.string()
}).meta({ id: 'PostFleetHealthCheckResponse' })
export type PostFleetHealthCheckResponse = z.infer<typeof PostFleetHealthCheckResponse>
