/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source open api file,
 * and elastic/elastic-client-generator-js to regenerate this file again.
 */

/* eslint-disable @typescript-eslint/no-redeclare */
import { z } from 'zod'

export const Kibana_HTTP_APIs_managed_integration_package = z.object({
  name: z.string(),
  title: z.string(),
  version: z.string()
}).meta({ id: 'Kibana_HTTP_APIs_managed_integration_package' })
export type Kibana_HTTP_APIs_managed_integration_package = z.infer<typeof Kibana_HTTP_APIs_managed_integration_package>

export const Kibana_HTTP_APIs_simplified_package_policy_stream_deprecation_info = z.object({
  description: z.string(),
  replaced_by: z.record(z.string(), z.string()).optional(),
  since: z.string().optional()
}).meta({ id: 'Kibana_HTTP_APIs_simplified_package_policy_stream_deprecation_info' })
export type Kibana_HTTP_APIs_simplified_package_policy_stream_deprecation_info = z.infer<typeof Kibana_HTTP_APIs_simplified_package_policy_stream_deprecation_info>

export const Kibana_HTTP_APIs_simplified_package_policy_input_deprecation_info = z.object({
  description: z.string(),
  replaced_by: z.record(z.string(), z.string()).optional(),
  since: z.string().optional()
}).meta({ id: 'Kibana_HTTP_APIs_simplified_package_policy_input_deprecation_info' })
export type Kibana_HTTP_APIs_simplified_package_policy_input_deprecation_info = z.infer<typeof Kibana_HTTP_APIs_simplified_package_policy_input_deprecation_info>

export const Kibana_HTTP_APIs_managed_integration_cloud_connector = z.object({
  cloud_connector_id: z.string(),
  enabled: z.boolean()
}).meta({ id: 'Kibana_HTTP_APIs_managed_integration_cloud_connector' })
export type Kibana_HTTP_APIs_managed_integration_cloud_connector = z.infer<typeof Kibana_HTTP_APIs_managed_integration_cloud_connector>

export const Kibana_HTTP_APIs_managed_integration_upgrade_dry_run_request = z.object({
  pkgVersion: z.string().optional(),
  policyIds: z.array(z.string())
}).meta({ id: 'Kibana_HTTP_APIs_managed_integration_upgrade_dry_run_request' })
export type Kibana_HTTP_APIs_managed_integration_upgrade_dry_run_request = z.infer<typeof Kibana_HTTP_APIs_managed_integration_upgrade_dry_run_request>

export const Kibana_HTTP_APIs_managed_integration = z.object({
  additional_datastreams_permissions: z.array(z.string()).optional(),
  cloud_connector: Kibana_HTTP_APIs_managed_integration_cloud_connector.nullable().optional(),
  created_at: z.string(),
  created_by: z.string(),
  description: z.string().optional(),
  global_data_tags: z.array(z.object({
    name: z.string(),
    value: z.union([z.string(), z.number()])
  })).optional(),
  id: z.string(),
  inputs: z.record(z.string(), z.object({
    condition: z.string().nullable().optional(),
    deprecated: Kibana_HTTP_APIs_simplified_package_policy_input_deprecation_info.optional(),
    enabled: z.boolean().optional(),
    streams: z.record(z.string(), z.object({
      condition: z.string().nullable().optional(),
      deprecated: Kibana_HTTP_APIs_simplified_package_policy_stream_deprecation_info.optional(),
      enabled: z.boolean().optional(),
      var_group_selections: z.record(z.string(), z.string()).optional(),
      vars: z.record(z.string(), z.union([z.string(), z.number(), z.boolean(), z.array(z.string()), z.array(z.number()), z.object({
        id: z.string(),
        isSecretRef: z.boolean()
      })]).nullable()).optional()
    })).optional(),
    vars: z.record(z.string(), z.union([z.string(), z.number(), z.boolean(), z.array(z.string()), z.array(z.number()), z.object({
      id: z.string(),
      isSecretRef: z.boolean()
    })]).nullable()).optional()
  })),
  name: z.string(),
  namespace: z.string().optional(),
  package: Kibana_HTTP_APIs_managed_integration_package,
  updated_at: z.string(),
  updated_by: z.string(),
  var_group_selections: z.record(z.string(), z.string()).optional(),
  vars: z.record(z.string(), z.union([z.string(), z.number(), z.boolean(), z.array(z.string()), z.array(z.number()), z.object({
    id: z.string(),
    isSecretRef: z.boolean()
  })]).nullable()).optional()
}).meta({ id: 'Kibana_HTTP_APIs_managed_integration' })
export type Kibana_HTTP_APIs_managed_integration = z.infer<typeof Kibana_HTTP_APIs_managed_integration>

export const Kibana_HTTP_APIs_managed_integration_upgrade_dry_run_result = z.object({
  body: z.object({
    message: z.string()
  }).optional(),
  currentVersion: z.string().optional(),
  errors: z.array(z.object({
    message: z.string()
  })).optional(),
  hasErrors: z.boolean(),
  id: z.string(),
  name: z.string().optional(),
  proposedPolicy: Kibana_HTTP_APIs_managed_integration.optional(),
  proposedVersion: z.string().optional(),
  statusCode: z.number().optional()
}).meta({ id: 'Kibana_HTTP_APIs_managed_integration_upgrade_dry_run_result' })
export type Kibana_HTTP_APIs_managed_integration_upgrade_dry_run_result = z.infer<typeof Kibana_HTTP_APIs_managed_integration_upgrade_dry_run_result>

export const PostFleetManagedIntegrationsUpgradeDryrunResponse = z.array(Kibana_HTTP_APIs_managed_integration_upgrade_dry_run_result).meta({ id: 'PostFleetManagedIntegrationsUpgradeDryrunResponse' })
export type PostFleetManagedIntegrationsUpgradeDryrunResponse = z.infer<typeof PostFleetManagedIntegrationsUpgradeDryrunResponse>
