/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source open api file,
 * and elastic/elastic-client-generator-js to regenerate this file again.
 */

/* eslint-disable @typescript-eslint/no-redeclare */
import { z } from 'zod'

export const PostSecurityEntityStoreEntitiesEntitytypeRequest = z.union([z.object({
  '@timestamp': z.string().optional(),
  asset: z.object({
    business_unit: z.string().optional(),
    criticality: z.union([z.enum(['low_impact', 'medium_impact', 'high_impact', 'extreme_impact']), z.unknown().nullable()]).optional(),
    environment: z.string().optional(),
    id: z.string().optional(),
    model: z.string().optional(),
    name: z.string().optional(),
    owner: z.string().optional(),
    serial_number: z.string().optional(),
    vendor: z.string().optional()
  }).optional(),
  entity: z.object({
    attributes: z.object({
      asset: z.boolean().optional(),
      known_redirects: z.array(z.string()).optional(),
      managed: z.boolean().optional(),
      mfa_enabled: z.boolean().optional(),
      oauth_consent_restriction: z.string().optional(),
      permissions: z.array(z.string()).optional(),
      storage_class: z.string().optional(),
      watchlists: z.array(z.string()).optional()
    }).optional(),
    behaviors: z.object({
      anomaly_job_ids: z.array(z.string()).optional(),
      rule_names: z.array(z.string()).optional()
    }).optional(),
    EngineMetadata: z.object({
      Type: z.string().optional()
    }).optional(),
    id: z.string().optional(),
    lifecycle: z.object({
      first_seen: z.string().optional(),
      last_activity: z.string().optional(),
      last_seen: z.string().optional()
    }).optional(),
    name: z.string().optional(),
    relationships: z.object({
      accesses_frequently: z.object({
        ids: z.array(z.string()).optional(),
        raw_identifiers: z.object({
          'entity.id': z.array(z.string()).optional(),
          'host.id': z.array(z.string()).optional(),
          'host.name': z.array(z.string()).optional(),
          'service.name': z.array(z.string()).optional(),
          'user.email': z.array(z.string()).optional(),
          'user.id': z.array(z.string()).optional(),
          'user.name': z.array(z.string()).optional()
        }).optional()
      }).optional(),
      accesses_infrequently: z.object({
        ids: z.array(z.string()).optional(),
        raw_identifiers: z.object({
          'entity.id': z.array(z.string()).optional(),
          'host.id': z.array(z.string()).optional(),
          'host.name': z.array(z.string()).optional(),
          'service.name': z.array(z.string()).optional(),
          'user.email': z.array(z.string()).optional(),
          'user.id': z.array(z.string()).optional(),
          'user.name': z.array(z.string()).optional()
        }).optional()
      }).optional(),
      administers: z.object({
        ids: z.array(z.string()).optional(),
        raw_identifiers: z.object({
          'entity.id': z.array(z.string()).optional(),
          'host.id': z.array(z.string()).optional(),
          'host.name': z.array(z.string()).optional(),
          'service.name': z.array(z.string()).optional(),
          'user.email': z.array(z.string()).optional(),
          'user.id': z.array(z.string()).optional(),
          'user.name': z.array(z.string()).optional()
        }).optional()
      }).optional(),
      communicates_with: z.object({
        ids: z.array(z.string()).optional(),
        raw_identifiers: z.object({
          'entity.id': z.array(z.string()).optional(),
          'host.id': z.array(z.string()).optional(),
          'host.name': z.array(z.string()).optional(),
          'service.name': z.array(z.string()).optional(),
          'user.email': z.array(z.string()).optional(),
          'user.id': z.array(z.string()).optional(),
          'user.name': z.array(z.string()).optional()
        }).optional()
      }).optional(),
      depends_on: z.object({
        ids: z.array(z.string()).optional(),
        raw_identifiers: z.object({
          'entity.id': z.array(z.string()).optional(),
          'host.id': z.array(z.string()).optional(),
          'host.name': z.array(z.string()).optional(),
          'service.name': z.array(z.string()).optional(),
          'user.email': z.array(z.string()).optional(),
          'user.id': z.array(z.string()).optional(),
          'user.name': z.array(z.string()).optional()
        }).optional()
      }).optional(),
      owns: z.object({
        ids: z.array(z.string()).optional(),
        raw_identifiers: z.object({
          'entity.id': z.array(z.string()).optional(),
          'host.id': z.array(z.string()).optional(),
          'host.name': z.array(z.string()).optional(),
          'service.name': z.array(z.string()).optional(),
          'user.email': z.array(z.string()).optional(),
          'user.id': z.array(z.string()).optional(),
          'user.name': z.array(z.string()).optional()
        }).optional()
      }).optional(),
      owns_inferred: z.object({
        ids: z.array(z.string()).optional(),
        raw_identifiers: z.object({
          'entity.id': z.array(z.string()).optional(),
          'host.id': z.array(z.string()).optional(),
          'host.name': z.array(z.string()).optional(),
          'service.name': z.array(z.string()).optional(),
          'user.email': z.array(z.string()).optional(),
          'user.id': z.array(z.string()).optional(),
          'user.name': z.array(z.string()).optional()
        }).optional()
      }).optional(),
      resolution: z.object({
        resolved_to: z.string().optional(),
        risk: z.object({
          calculated_level: z.enum(['Unknown', 'Low', 'Moderate', 'High', 'Critical']).optional(),
          calculated_score: z.number().optional(),
          calculated_score_norm: z.number().optional()
        }).optional()
      }).optional(),
      supervises: z.object({
        ids: z.array(z.string()).optional(),
        raw_identifiers: z.object({
          'entity.id': z.array(z.string()).optional(),
          'host.id': z.array(z.string()).optional(),
          'host.name': z.array(z.string()).optional(),
          'service.name': z.array(z.string()).optional(),
          'user.email': z.array(z.string()).optional(),
          'user.id': z.array(z.string()).optional(),
          'user.name': z.array(z.string()).optional()
        }).optional()
      }).optional()
    }).optional(),
    risk: z.object({
      calculated_level: z.enum(['Unknown', 'Low', 'Moderate', 'High', 'Critical']).optional(),
      calculated_score: z.number().optional(),
      calculated_score_norm: z.number().optional()
    }).optional(),
    schema_version: z.string().optional(),
    source: z.array(z.string()).optional(),
    sub_type: z.string().optional(),
    type: z.string().optional(),
    url: z.string().optional()
  }).optional(),
  event: z.object({
    ingested: z.string().optional()
  }).optional(),
  labels: z.object({

  }).passthrough().optional(),
  tags: z.array(z.string()).optional(),
  user: z.object({
    domain: z.array(z.string()).optional(),
    email: z.array(z.string()).optional(),
    full_name: z.array(z.string()).optional(),
    hash: z.array(z.string()).optional(),
    id: z.array(z.string()).optional(),
    name: z.string().optional(),
    risk: z.object({
      calculated_level: z.enum(['Unknown', 'Low', 'Moderate', 'High', 'Critical']).optional(),
      calculated_score: z.number().optional(),
      calculated_score_norm: z.number().optional()
    }).optional(),
    roles: z.array(z.string()).optional()
  }).optional()
}), z.object({
  '@timestamp': z.string().optional(),
  asset: z.object({
    business_unit: z.string().optional(),
    criticality: z.union([z.enum(['low_impact', 'medium_impact', 'high_impact', 'extreme_impact']), z.unknown().nullable()]).optional(),
    environment: z.string().optional(),
    id: z.string().optional(),
    model: z.string().optional(),
    name: z.string().optional(),
    owner: z.string().optional(),
    serial_number: z.string().optional(),
    vendor: z.string().optional()
  }).optional(),
  entity: z.object({
    attributes: z.object({
      asset: z.boolean().optional(),
      known_redirects: z.array(z.string()).optional(),
      managed: z.boolean().optional(),
      mfa_enabled: z.boolean().optional(),
      oauth_consent_restriction: z.string().optional(),
      permissions: z.array(z.string()).optional(),
      storage_class: z.string().optional(),
      watchlists: z.array(z.string()).optional()
    }).optional(),
    behaviors: z.object({
      anomaly_job_ids: z.array(z.string()).optional(),
      rule_names: z.array(z.string()).optional()
    }).optional(),
    EngineMetadata: z.object({
      Type: z.string().optional()
    }).optional(),
    id: z.string().optional(),
    lifecycle: z.object({
      first_seen: z.string().optional(),
      last_activity: z.string().optional(),
      last_seen: z.string().optional()
    }).optional(),
    name: z.string().optional(),
    relationships: z.object({
      accesses_frequently: z.object({
        ids: z.array(z.string()).optional(),
        raw_identifiers: z.object({
          'entity.id': z.array(z.string()).optional(),
          'host.id': z.array(z.string()).optional(),
          'host.name': z.array(z.string()).optional(),
          'service.name': z.array(z.string()).optional(),
          'user.email': z.array(z.string()).optional(),
          'user.id': z.array(z.string()).optional(),
          'user.name': z.array(z.string()).optional()
        }).optional()
      }).optional(),
      accesses_infrequently: z.object({
        ids: z.array(z.string()).optional(),
        raw_identifiers: z.object({
          'entity.id': z.array(z.string()).optional(),
          'host.id': z.array(z.string()).optional(),
          'host.name': z.array(z.string()).optional(),
          'service.name': z.array(z.string()).optional(),
          'user.email': z.array(z.string()).optional(),
          'user.id': z.array(z.string()).optional(),
          'user.name': z.array(z.string()).optional()
        }).optional()
      }).optional(),
      administers: z.object({
        ids: z.array(z.string()).optional(),
        raw_identifiers: z.object({
          'entity.id': z.array(z.string()).optional(),
          'host.id': z.array(z.string()).optional(),
          'host.name': z.array(z.string()).optional(),
          'service.name': z.array(z.string()).optional(),
          'user.email': z.array(z.string()).optional(),
          'user.id': z.array(z.string()).optional(),
          'user.name': z.array(z.string()).optional()
        }).optional()
      }).optional(),
      communicates_with: z.object({
        ids: z.array(z.string()).optional(),
        raw_identifiers: z.object({
          'entity.id': z.array(z.string()).optional(),
          'host.id': z.array(z.string()).optional(),
          'host.name': z.array(z.string()).optional(),
          'service.name': z.array(z.string()).optional(),
          'user.email': z.array(z.string()).optional(),
          'user.id': z.array(z.string()).optional(),
          'user.name': z.array(z.string()).optional()
        }).optional()
      }).optional(),
      depends_on: z.object({
        ids: z.array(z.string()).optional(),
        raw_identifiers: z.object({
          'entity.id': z.array(z.string()).optional(),
          'host.id': z.array(z.string()).optional(),
          'host.name': z.array(z.string()).optional(),
          'service.name': z.array(z.string()).optional(),
          'user.email': z.array(z.string()).optional(),
          'user.id': z.array(z.string()).optional(),
          'user.name': z.array(z.string()).optional()
        }).optional()
      }).optional(),
      owns: z.object({
        ids: z.array(z.string()).optional(),
        raw_identifiers: z.object({
          'entity.id': z.array(z.string()).optional(),
          'host.id': z.array(z.string()).optional(),
          'host.name': z.array(z.string()).optional(),
          'service.name': z.array(z.string()).optional(),
          'user.email': z.array(z.string()).optional(),
          'user.id': z.array(z.string()).optional(),
          'user.name': z.array(z.string()).optional()
        }).optional()
      }).optional(),
      owns_inferred: z.object({
        ids: z.array(z.string()).optional(),
        raw_identifiers: z.object({
          'entity.id': z.array(z.string()).optional(),
          'host.id': z.array(z.string()).optional(),
          'host.name': z.array(z.string()).optional(),
          'service.name': z.array(z.string()).optional(),
          'user.email': z.array(z.string()).optional(),
          'user.id': z.array(z.string()).optional(),
          'user.name': z.array(z.string()).optional()
        }).optional()
      }).optional(),
      resolution: z.object({
        resolved_to: z.string().optional(),
        risk: z.object({
          calculated_level: z.enum(['Unknown', 'Low', 'Moderate', 'High', 'Critical']).optional(),
          calculated_score: z.number().optional(),
          calculated_score_norm: z.number().optional()
        }).optional()
      }).optional(),
      supervises: z.object({
        ids: z.array(z.string()).optional(),
        raw_identifiers: z.object({
          'entity.id': z.array(z.string()).optional(),
          'host.id': z.array(z.string()).optional(),
          'host.name': z.array(z.string()).optional(),
          'service.name': z.array(z.string()).optional(),
          'user.email': z.array(z.string()).optional(),
          'user.id': z.array(z.string()).optional(),
          'user.name': z.array(z.string()).optional()
        }).optional()
      }).optional()
    }).optional(),
    risk: z.object({
      calculated_level: z.enum(['Unknown', 'Low', 'Moderate', 'High', 'Critical']).optional(),
      calculated_score: z.number().optional(),
      calculated_score_norm: z.number().optional()
    }).optional(),
    schema_version: z.string().optional(),
    source: z.array(z.string()).optional(),
    sub_type: z.string().optional(),
    type: z.string().optional(),
    url: z.string().optional()
  }).optional(),
  event: z.object({
    ingested: z.string().optional()
  }).optional(),
  host: z.object({
    architecture: z.array(z.string()).optional(),
    domain: z.array(z.string()).optional(),
    hostname: z.array(z.string()).optional(),
    id: z.array(z.string()).optional(),
    ip: z.array(z.string()).optional(),
    mac: z.array(z.string()).optional(),
    name: z.string().optional(),
    os: z.object({
      family: z.string().optional(),
      full: z.string().optional(),
      kernel: z.string().optional(),
      name: z.union([z.string(), z.array(z.string())]).optional(),
      platform: z.string().optional(),
      type: z.union([z.string(), z.array(z.string())]).optional(),
      version: z.string().optional()
    }).optional(),
    risk: z.object({
      calculated_level: z.enum(['Unknown', 'Low', 'Moderate', 'High', 'Critical']).optional(),
      calculated_score: z.number().optional(),
      calculated_score_norm: z.number().optional()
    }).optional(),
    type: z.array(z.string()).optional()
  }).optional(),
  labels: z.object({

  }).passthrough().optional(),
  tags: z.array(z.string()).optional()
}), z.object({
  '@timestamp': z.string().optional(),
  asset: z.object({
    business_unit: z.string().optional(),
    criticality: z.union([z.enum(['low_impact', 'medium_impact', 'high_impact', 'extreme_impact']), z.unknown().nullable()]).optional(),
    environment: z.string().optional(),
    id: z.string().optional(),
    model: z.string().optional(),
    name: z.string().optional(),
    owner: z.string().optional(),
    serial_number: z.string().optional(),
    vendor: z.string().optional()
  }).optional(),
  entity: z.object({
    attributes: z.object({
      asset: z.boolean().optional(),
      known_redirects: z.array(z.string()).optional(),
      managed: z.boolean().optional(),
      mfa_enabled: z.boolean().optional(),
      oauth_consent_restriction: z.string().optional(),
      permissions: z.array(z.string()).optional(),
      storage_class: z.string().optional(),
      watchlists: z.array(z.string()).optional()
    }).optional(),
    behaviors: z.object({
      anomaly_job_ids: z.array(z.string()).optional(),
      rule_names: z.array(z.string()).optional()
    }).optional(),
    EngineMetadata: z.object({
      Type: z.string().optional()
    }).optional(),
    id: z.string().optional(),
    lifecycle: z.object({
      first_seen: z.string().optional(),
      last_activity: z.string().optional(),
      last_seen: z.string().optional()
    }).optional(),
    name: z.string().optional(),
    relationships: z.object({
      accesses_frequently: z.object({
        ids: z.array(z.string()).optional(),
        raw_identifiers: z.object({
          'entity.id': z.array(z.string()).optional(),
          'host.id': z.array(z.string()).optional(),
          'host.name': z.array(z.string()).optional(),
          'service.name': z.array(z.string()).optional(),
          'user.email': z.array(z.string()).optional(),
          'user.id': z.array(z.string()).optional(),
          'user.name': z.array(z.string()).optional()
        }).optional()
      }).optional(),
      accesses_infrequently: z.object({
        ids: z.array(z.string()).optional(),
        raw_identifiers: z.object({
          'entity.id': z.array(z.string()).optional(),
          'host.id': z.array(z.string()).optional(),
          'host.name': z.array(z.string()).optional(),
          'service.name': z.array(z.string()).optional(),
          'user.email': z.array(z.string()).optional(),
          'user.id': z.array(z.string()).optional(),
          'user.name': z.array(z.string()).optional()
        }).optional()
      }).optional(),
      administers: z.object({
        ids: z.array(z.string()).optional(),
        raw_identifiers: z.object({
          'entity.id': z.array(z.string()).optional(),
          'host.id': z.array(z.string()).optional(),
          'host.name': z.array(z.string()).optional(),
          'service.name': z.array(z.string()).optional(),
          'user.email': z.array(z.string()).optional(),
          'user.id': z.array(z.string()).optional(),
          'user.name': z.array(z.string()).optional()
        }).optional()
      }).optional(),
      communicates_with: z.object({
        ids: z.array(z.string()).optional(),
        raw_identifiers: z.object({
          'entity.id': z.array(z.string()).optional(),
          'host.id': z.array(z.string()).optional(),
          'host.name': z.array(z.string()).optional(),
          'service.name': z.array(z.string()).optional(),
          'user.email': z.array(z.string()).optional(),
          'user.id': z.array(z.string()).optional(),
          'user.name': z.array(z.string()).optional()
        }).optional()
      }).optional(),
      depends_on: z.object({
        ids: z.array(z.string()).optional(),
        raw_identifiers: z.object({
          'entity.id': z.array(z.string()).optional(),
          'host.id': z.array(z.string()).optional(),
          'host.name': z.array(z.string()).optional(),
          'service.name': z.array(z.string()).optional(),
          'user.email': z.array(z.string()).optional(),
          'user.id': z.array(z.string()).optional(),
          'user.name': z.array(z.string()).optional()
        }).optional()
      }).optional(),
      owns: z.object({
        ids: z.array(z.string()).optional(),
        raw_identifiers: z.object({
          'entity.id': z.array(z.string()).optional(),
          'host.id': z.array(z.string()).optional(),
          'host.name': z.array(z.string()).optional(),
          'service.name': z.array(z.string()).optional(),
          'user.email': z.array(z.string()).optional(),
          'user.id': z.array(z.string()).optional(),
          'user.name': z.array(z.string()).optional()
        }).optional()
      }).optional(),
      owns_inferred: z.object({
        ids: z.array(z.string()).optional(),
        raw_identifiers: z.object({
          'entity.id': z.array(z.string()).optional(),
          'host.id': z.array(z.string()).optional(),
          'host.name': z.array(z.string()).optional(),
          'service.name': z.array(z.string()).optional(),
          'user.email': z.array(z.string()).optional(),
          'user.id': z.array(z.string()).optional(),
          'user.name': z.array(z.string()).optional()
        }).optional()
      }).optional(),
      resolution: z.object({
        resolved_to: z.string().optional(),
        risk: z.object({
          calculated_level: z.enum(['Unknown', 'Low', 'Moderate', 'High', 'Critical']).optional(),
          calculated_score: z.number().optional(),
          calculated_score_norm: z.number().optional()
        }).optional()
      }).optional(),
      supervises: z.object({
        ids: z.array(z.string()).optional(),
        raw_identifiers: z.object({
          'entity.id': z.array(z.string()).optional(),
          'host.id': z.array(z.string()).optional(),
          'host.name': z.array(z.string()).optional(),
          'service.name': z.array(z.string()).optional(),
          'user.email': z.array(z.string()).optional(),
          'user.id': z.array(z.string()).optional(),
          'user.name': z.array(z.string()).optional()
        }).optional()
      }).optional()
    }).optional(),
    risk: z.object({
      calculated_level: z.enum(['Unknown', 'Low', 'Moderate', 'High', 'Critical']).optional(),
      calculated_score: z.number().optional(),
      calculated_score_norm: z.number().optional()
    }).optional(),
    schema_version: z.string().optional(),
    source: z.array(z.string()).optional(),
    sub_type: z.string().optional(),
    type: z.string().optional(),
    url: z.string().optional()
  }).optional(),
  event: z.object({
    ingested: z.string().optional()
  }).optional(),
  labels: z.object({

  }).passthrough().optional(),
  service: z.object({
    address: z.string().optional(),
    environment: z.string().optional(),
    ephemeral_id: z.string().optional(),
    id: z.string().optional(),
    name: z.string().optional(),
    node: z.object({
      name: z.string().optional(),
      role: z.string().optional(),
      roles: z.array(z.string()).optional()
    }).optional(),
    risk: z.object({
      calculated_level: z.enum(['Unknown', 'Low', 'Moderate', 'High', 'Critical']).optional(),
      calculated_score: z.number().optional(),
      calculated_score_norm: z.number().optional()
    }).optional(),
    state: z.string().optional(),
    type: z.string().optional(),
    version: z.string().optional()
  }).optional(),
  tags: z.array(z.string()).optional()
}), z.object({
  '@timestamp': z.string().optional(),
  asset: z.object({
    business_unit: z.string().optional(),
    criticality: z.union([z.enum(['low_impact', 'medium_impact', 'high_impact', 'extreme_impact']), z.unknown().nullable()]).optional(),
    environment: z.string().optional(),
    id: z.string().optional(),
    model: z.string().optional(),
    name: z.string().optional(),
    owner: z.string().optional(),
    serial_number: z.string().optional(),
    vendor: z.string().optional()
  }).optional(),
  cloud: z.object({
    account: z.object({
      id: z.string().optional(),
      name: z.string().optional()
    }).optional(),
    availability_zone: z.string().optional(),
    instance: z.object({
      id: z.string().optional(),
      name: z.string().optional()
    }).optional(),
    machine: z.object({
      type: z.string().optional()
    }).optional(),
    project: z.object({
      id: z.string().optional(),
      name: z.string().optional()
    }).optional(),
    provider: z.string().optional(),
    region: z.string().optional(),
    service: z.object({
      name: z.string().optional()
    }).optional()
  }).optional(),
  entity: z.object({
    attributes: z.object({
      asset: z.boolean().optional(),
      known_redirects: z.array(z.string()).optional(),
      managed: z.boolean().optional(),
      mfa_enabled: z.boolean().optional(),
      oauth_consent_restriction: z.string().optional(),
      permissions: z.array(z.string()).optional(),
      storage_class: z.string().optional(),
      watchlists: z.array(z.string()).optional()
    }).optional(),
    behaviors: z.object({
      anomaly_job_ids: z.array(z.string()).optional(),
      rule_names: z.array(z.string()).optional()
    }).optional(),
    EngineMetadata: z.object({
      Type: z.string().optional()
    }).optional(),
    id: z.string().optional(),
    lifecycle: z.object({
      first_seen: z.string().optional(),
      last_activity: z.string().optional(),
      last_seen: z.string().optional()
    }).optional(),
    name: z.string().optional(),
    relationships: z.object({
      accesses_frequently: z.object({
        ids: z.array(z.string()).optional(),
        raw_identifiers: z.object({
          'entity.id': z.array(z.string()).optional(),
          'host.id': z.array(z.string()).optional(),
          'host.name': z.array(z.string()).optional(),
          'service.name': z.array(z.string()).optional(),
          'user.email': z.array(z.string()).optional(),
          'user.id': z.array(z.string()).optional(),
          'user.name': z.array(z.string()).optional()
        }).optional()
      }).optional(),
      accesses_infrequently: z.object({
        ids: z.array(z.string()).optional(),
        raw_identifiers: z.object({
          'entity.id': z.array(z.string()).optional(),
          'host.id': z.array(z.string()).optional(),
          'host.name': z.array(z.string()).optional(),
          'service.name': z.array(z.string()).optional(),
          'user.email': z.array(z.string()).optional(),
          'user.id': z.array(z.string()).optional(),
          'user.name': z.array(z.string()).optional()
        }).optional()
      }).optional(),
      administers: z.object({
        ids: z.array(z.string()).optional(),
        raw_identifiers: z.object({
          'entity.id': z.array(z.string()).optional(),
          'host.id': z.array(z.string()).optional(),
          'host.name': z.array(z.string()).optional(),
          'service.name': z.array(z.string()).optional(),
          'user.email': z.array(z.string()).optional(),
          'user.id': z.array(z.string()).optional(),
          'user.name': z.array(z.string()).optional()
        }).optional()
      }).optional(),
      communicates_with: z.object({
        ids: z.array(z.string()).optional(),
        raw_identifiers: z.object({
          'entity.id': z.array(z.string()).optional(),
          'host.id': z.array(z.string()).optional(),
          'host.name': z.array(z.string()).optional(),
          'service.name': z.array(z.string()).optional(),
          'user.email': z.array(z.string()).optional(),
          'user.id': z.array(z.string()).optional(),
          'user.name': z.array(z.string()).optional()
        }).optional()
      }).optional(),
      depends_on: z.object({
        ids: z.array(z.string()).optional(),
        raw_identifiers: z.object({
          'entity.id': z.array(z.string()).optional(),
          'host.id': z.array(z.string()).optional(),
          'host.name': z.array(z.string()).optional(),
          'service.name': z.array(z.string()).optional(),
          'user.email': z.array(z.string()).optional(),
          'user.id': z.array(z.string()).optional(),
          'user.name': z.array(z.string()).optional()
        }).optional()
      }).optional(),
      owns: z.object({
        ids: z.array(z.string()).optional(),
        raw_identifiers: z.object({
          'entity.id': z.array(z.string()).optional(),
          'host.id': z.array(z.string()).optional(),
          'host.name': z.array(z.string()).optional(),
          'service.name': z.array(z.string()).optional(),
          'user.email': z.array(z.string()).optional(),
          'user.id': z.array(z.string()).optional(),
          'user.name': z.array(z.string()).optional()
        }).optional()
      }).optional(),
      owns_inferred: z.object({
        ids: z.array(z.string()).optional(),
        raw_identifiers: z.object({
          'entity.id': z.array(z.string()).optional(),
          'host.id': z.array(z.string()).optional(),
          'host.name': z.array(z.string()).optional(),
          'service.name': z.array(z.string()).optional(),
          'user.email': z.array(z.string()).optional(),
          'user.id': z.array(z.string()).optional(),
          'user.name': z.array(z.string()).optional()
        }).optional()
      }).optional(),
      resolution: z.object({
        resolved_to: z.string().optional(),
        risk: z.object({
          calculated_level: z.enum(['Unknown', 'Low', 'Moderate', 'High', 'Critical']).optional(),
          calculated_score: z.number().optional(),
          calculated_score_norm: z.number().optional()
        }).optional()
      }).optional(),
      supervises: z.object({
        ids: z.array(z.string()).optional(),
        raw_identifiers: z.object({
          'entity.id': z.array(z.string()).optional(),
          'host.id': z.array(z.string()).optional(),
          'host.name': z.array(z.string()).optional(),
          'service.name': z.array(z.string()).optional(),
          'user.email': z.array(z.string()).optional(),
          'user.id': z.array(z.string()).optional(),
          'user.name': z.array(z.string()).optional()
        }).optional()
      }).optional()
    }).optional(),
    risk: z.object({
      calculated_level: z.enum(['Unknown', 'Low', 'Moderate', 'High', 'Critical']).optional(),
      calculated_score: z.number().optional(),
      calculated_score_norm: z.number().optional()
    }).optional(),
    schema_version: z.string().optional(),
    source: z.array(z.string()).optional(),
    sub_type: z.string().optional(),
    type: z.string().optional(),
    url: z.string().optional()
  }).optional(),
  event: z.object({
    ingested: z.string().optional()
  }).optional(),
  labels: z.object({

  }).passthrough().optional(),
  orchestrator: z.object({
    api_version: z.string().optional(),
    cluster: z.object({
      id: z.string().optional(),
      name: z.string().optional(),
      url: z.string().optional(),
      version: z.string().optional()
    }).optional(),
    namespace: z.string().optional(),
    organization: z.string().optional(),
    resource: z.object({
      annotation: z.string().optional(),
      id: z.string().optional(),
      ip: z.string().optional(),
      label: z.string().optional(),
      name: z.string().optional(),
      parent: z.object({
        type: z.string().optional()
      }).optional(),
      type: z.string().optional()
    }).optional(),
    type: z.string().optional()
  }).optional(),
  tags: z.array(z.string()).optional()
})]).meta({ id: 'PostSecurityEntityStoreEntitiesEntitytypeRequest' })
export type PostSecurityEntityStoreEntitiesEntitytypeRequest = z.infer<typeof PostSecurityEntityStoreEntitiesEntitytypeRequest>
