/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source open api file,
 * and elastic/elastic-client-generator-js to regenerate this file again.
 */

/* eslint-disable @typescript-eslint/no-redeclare */
import { z } from 'zod'

export const PreviewSwapDataViewsDefaultResponse = z.object({
  result: z.array(z.object({
    id: z.string().optional(),
    type: z.string().optional()
  })).optional()
}).meta({ id: 'PreviewSwapDataViewsDefaultResponse' })
export type PreviewSwapDataViewsDefaultResponse = z.infer<typeof PreviewSwapDataViewsDefaultResponse>

export { Data_views_swap_data_view_request_object } from './schemas/data.js'
