/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source open api file,
 * and elastic/elastic-client-generator-js to regenerate this file again.
 */

/* eslint-disable @typescript-eslint/no-redeclare */
import { z } from 'zod'

export const PutAgentBuilderConversationsConversationIdAttachmentsAttachmentIdRequest = z.object({
  data: z.unknown().nullable(),
  description: z.string().optional()
}).meta({ id: 'PutAgentBuilderConversationsConversationIdAttachmentsAttachmentIdRequest' })
export type PutAgentBuilderConversationsConversationIdAttachmentsAttachmentIdRequest = z.infer<typeof PutAgentBuilderConversationsConversationIdAttachmentsAttachmentIdRequest>
