/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source open api file,
 * and elastic/elastic-client-generator-js to regenerate this file again.
 */

/* eslint-disable @typescript-eslint/no-redeclare */
import { z } from 'zod'
import { Kibana_HTTP_APIs_ClassicFieldDefinition, Kibana_HTTP_APIs_Condition, Kibana_HTTP_APIs_FailureStore, Kibana_HTTP_APIs_FieldDefinition, Kibana_HTTP_APIs_IngestStreamLifecycle, Kibana_HTTP_APIs_StreamlangStep } from './schemas/kibana.js'

export const PutStreamsNameIngestRequest = z.object({
  ingest: z.union([z.object({
    failure_store: Kibana_HTTP_APIs_FailureStore,
    lifecycle: Kibana_HTTP_APIs_IngestStreamLifecycle,
    processing: z.object({
      steps: z.array(z.lazy(() => Kibana_HTTP_APIs_StreamlangStep))
    }),
    settings: z.object({
      'index.number_of_replicas': z.object({
        value: z.number()
      }).optional(),
      'index.number_of_shards': z.object({
        value: z.number()
      }).optional(),
      'index.refresh_interval': z.object({
        value: z.union([z.string(), z.literal(-1)])
      }).optional()
    }),
    wired: z.object({
      draft: z.boolean().optional(),
      fields: Kibana_HTTP_APIs_FieldDefinition,
      routing: z.array(z.object({
        destination: z.string(),
        draft: z.boolean().optional(),
        status: z.enum(['enabled', 'disabled']).optional(),
        where: z.lazy(() => Kibana_HTTP_APIs_Condition)
      }))
    })
  }), z.object({
    classic: z.object({
      field_overrides: Kibana_HTTP_APIs_ClassicFieldDefinition.optional()
    }),
    failure_store: Kibana_HTTP_APIs_FailureStore,
    lifecycle: Kibana_HTTP_APIs_IngestStreamLifecycle,
    processing: z.union([z.object({
      steps: z.array(z.lazy(() => Kibana_HTTP_APIs_StreamlangStep))
    }), z.object({
      processors: z.array(z.record(z.string(), z.unknown()))
    })]),
    settings: z.object({
      'index.number_of_replicas': z.object({
        value: z.number()
      }).optional(),
      'index.number_of_shards': z.object({
        value: z.number()
      }).optional(),
      'index.refresh_interval': z.object({
        value: z.union([z.string(), z.literal(-1)])
      }).optional()
    })
  })])
}).meta({ id: 'PutStreamsNameIngestRequest' })
export type PutStreamsNameIngestRequest = z.infer<typeof PutStreamsNameIngestRequest>

export { Kibana_HTTP_APIs_ClassicFieldDefinition } from './schemas/kibana.js'
export { Kibana_HTTP_APIs_ClassicFieldDefinitionConfig } from './schemas/kibana.js'
export { Kibana_HTTP_APIs_RecursiveRecord } from './schemas/kibana.js'
export { Kibana_HTTP_APIs_Condition } from './schemas/kibana.js'
export { Kibana_HTTP_APIs_FilterCondition } from './schemas/kibana.js'
export { Kibana_HTTP_APIs_FieldDefinition } from './schemas/kibana.js'
export { Kibana_HTTP_APIs_FieldDefinitionConfig } from './schemas/kibana.js'
export { Kibana_HTTP_APIs_StreamlangStep } from './schemas/kibana.js'
export { Kibana_HTTP_APIs_StreamlangConditionBlock } from './schemas/kibana.js'
export { Kibana_HTTP_APIs_ConditionWithSteps } from './schemas/kibana.js'
export { Kibana_HTTP_APIs_IngestStreamLifecycle } from './schemas/kibana.js'
export { Kibana_HTTP_APIs_FailureStore } from './schemas/kibana.js'
