/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source open api file,
 * and elastic/elastic-client-generator-js to regenerate this file again.
 */

/* eslint-disable @typescript-eslint/no-redeclare */
import { z } from 'zod'
import { Security_Timeline_API_TimelineSavedToReturnObject } from './schemas/security.js'

export const Security_Timeline_API_SavedObjectResolveAliasPurpose = z.enum(['savedObjectConversion', 'savedObjectImport']).meta({ id: 'Security_Timeline_API_SavedObjectResolveAliasPurpose' })
export type Security_Timeline_API_SavedObjectResolveAliasPurpose = z.infer<typeof Security_Timeline_API_SavedObjectResolveAliasPurpose>

export const Security_Timeline_API_SavedObjectResolveOutcome = z.enum(['exactMatch', 'aliasMatch', 'conflict']).meta({ id: 'Security_Timeline_API_SavedObjectResolveOutcome' })
export type Security_Timeline_API_SavedObjectResolveOutcome = z.infer<typeof Security_Timeline_API_SavedObjectResolveOutcome>

export const Security_Timeline_API_ResolvedTimeline = z.object({
  alias_purpose: Security_Timeline_API_SavedObjectResolveAliasPurpose.optional(),
  alias_target_id: z.string().optional(),
  outcome: Security_Timeline_API_SavedObjectResolveOutcome,
  timeline: Security_Timeline_API_TimelineSavedToReturnObject
}).meta({ id: 'Security_Timeline_API_ResolvedTimeline' })
export type Security_Timeline_API_ResolvedTimeline = z.infer<typeof Security_Timeline_API_ResolvedTimeline>

export { Security_Timeline_API_TimelineSavedToReturnObject } from './schemas/security.js'
export { Security_Timeline_API_PinnedEvent } from './schemas/security.js'
export { Security_Timeline_API_BarePinnedEvent } from './schemas/security.js'
export { Security_Timeline_API_PinnedEventCreatedAndUpdatedMetadata } from './schemas/security.js'
export { Security_Timeline_API_Note } from './schemas/security.js'
export { Security_Timeline_API_BareNote } from './schemas/security.js'
export { Security_Timeline_API_NoteCreatedAndUpdatedMetadata } from './schemas/security.js'
export { Security_Timeline_API_SavedTimeline } from './schemas/security.js'
export { Security_Timeline_API_TimelineType } from './schemas/security.js'
export { Security_Timeline_API_TimelineStatus } from './schemas/security.js'
export { Security_Timeline_API_Sort } from './schemas/security.js'
export { Security_Timeline_API_SortObject } from './schemas/security.js'
export { Security_Timeline_API_SerializedFilterQueryResult } from './schemas/security.js'
export { Security_Timeline_API_FilterTimelineResult } from './schemas/security.js'
export { Security_Timeline_API_FavoriteTimelineResult } from './schemas/security.js'
export { Security_Timeline_API_RowRendererId } from './schemas/security.js'
export { Security_Timeline_API_DataProviderResult } from './schemas/security.js'
export { Security_Timeline_API_DataProviderType } from './schemas/security.js'
export { Security_Timeline_API_QueryMatchResult } from './schemas/security.js'
export { Security_Timeline_API_DataProviderQueryMatch } from './schemas/security.js'
export { Security_Timeline_API_ColumnHeaderResult } from './schemas/security.js'
