/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source open api file,
 * and elastic/elastic-client-generator-js to regenerate this file again.
 */

/* eslint-disable @typescript-eslint/no-redeclare */
import { z } from 'zod'
import { Security_Detections_API_AlertIds, Security_Detections_API_SetAlertTags } from './schemas/security.js'

export const Security_Detections_API_SetAlertTagsBody = z.object({
  ids: Security_Detections_API_AlertIds,
  tags: Security_Detections_API_SetAlertTags
}).meta({ id: 'Security_Detections_API_SetAlertTagsBody' })
export type Security_Detections_API_SetAlertTagsBody = z.infer<typeof Security_Detections_API_SetAlertTagsBody>

export const SetAlertTagsResponse = z.record(z.string(), z.unknown()).meta({ id: 'SetAlertTagsResponse' })
export type SetAlertTagsResponse = z.infer<typeof SetAlertTagsResponse>

export { Security_Detections_API_SetAlertTags } from './schemas/security.js'
export { Security_Detections_API_AlertTags } from './schemas/security.js'
export { Security_Detections_API_AlertTag } from './schemas/security.js'
export { Security_Detections_API_AlertIds } from './schemas/security.js'
