/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source open api file,
 * and elastic/elastic-client-generator-js to regenerate this file again.
 */

/* eslint-disable @typescript-eslint/no-redeclare */
import { z } from 'zod'
import { Security_Detections_API_AlertIds, Security_Detections_API_AlertStatusExceptClosed, Security_Detections_API_Reason, Security_Detections_API_UpdateRelatedAlerts } from './schemas/security.js'

export const Security_Detections_API_SetAttacksStatusByIdsBase = z.object({
  ids: Security_Detections_API_AlertIds,
  status: Security_Detections_API_AlertStatusExceptClosed,
  update_related_alerts: Security_Detections_API_UpdateRelatedAlerts.optional()
}).meta({ id: 'Security_Detections_API_SetAttacksStatusByIdsBase' })
export type Security_Detections_API_SetAttacksStatusByIdsBase = z.infer<typeof Security_Detections_API_SetAttacksStatusByIdsBase>

export const Security_Detections_API_CloseAttacksByIds = z.object({
  ids: Security_Detections_API_AlertIds,
  reason: Security_Detections_API_Reason.optional(),
  status: z.enum(['closed']),
  update_related_alerts: Security_Detections_API_UpdateRelatedAlerts.optional()
}).meta({ id: 'Security_Detections_API_CloseAttacksByIds' })
export type Security_Detections_API_CloseAttacksByIds = z.infer<typeof Security_Detections_API_CloseAttacksByIds>

export const Security_Detections_API_SetAttacksStatusByIds = z.discriminatedUnion('status', [Security_Detections_API_CloseAttacksByIds, Security_Detections_API_SetAttacksStatusByIdsBase]).meta({ id: 'Security_Detections_API_SetAttacksStatusByIds' })
export type Security_Detections_API_SetAttacksStatusByIds = z.infer<typeof Security_Detections_API_SetAttacksStatusByIds>

export const SetAttacksStatusResponse = z.record(z.string(), z.unknown()).meta({ id: 'SetAttacksStatusResponse' })
export type SetAttacksStatusResponse = z.infer<typeof SetAttacksStatusResponse>

export { Security_Detections_API_UpdateRelatedAlerts } from './schemas/security.js'
export { Security_Detections_API_AlertStatusExceptClosed } from './schemas/security.js'
export { Security_Detections_API_AlertIds } from './schemas/security.js'
export { Security_Detections_API_Reason } from './schemas/security.js'
export { Security_Detections_API_ReasonEnum } from './schemas/security.js'
