/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source open api file,
 * and elastic/elastic-client-generator-js to regenerate this file again.
 */

/* eslint-disable @typescript-eslint/no-redeclare */
import { z } from 'zod'
import { Cases_closure_types, Cases_connector_types, Cases_owner, Cases_templates } from './schemas/misc.js'

export const Cases_set_case_configuration_request = z.object({
  closure_type: Cases_closure_types,
  connector: z.object({
    fields: z.object({}).nullable(),
    id: z.string(),
    name: z.string(),
    type: Cases_connector_types
  }),
  customFields: z.array(z.object({
    defaultValue: z.union([z.string(), z.boolean()]).optional(),
    key: z.string(),
    label: z.string(),
    type: z.enum(['text', 'toggle']),
    required: z.boolean()
  })).optional(),
  owner: Cases_owner,
  templates: Cases_templates.optional()
}).meta({ id: 'Cases_set_case_configuration_request' })
export type Cases_set_case_configuration_request = z.infer<typeof Cases_set_case_configuration_request>

export const SetCaseConfigurationDefaultSpaceResponse = z.object({
  closure_type: Cases_closure_types.optional(),
  connector: z.object({
    fields: z.object({}).nullable().optional(),
    id: z.string().optional(),
    name: z.string().optional(),
    type: Cases_connector_types.optional()
  }).optional(),
  created_at: z.string().optional(),
  created_by: z.object({
    email: z.string().nullable(),
    full_name: z.string().nullable(),
    profile_uid: z.string().optional(),
    username: z.string().nullable()
  }).optional(),
  customFields: z.array(z.object({
    defaultValue: z.union([z.string(), z.boolean()]).optional(),
    key: z.string().optional(),
    label: z.string().optional(),
    type: z.enum(['text', 'toggle']).optional(),
    required: z.boolean().optional()
  })).optional(),
  error: z.string().nullable().optional(),
  id: z.string().optional(),
  mappings: z.array(z.object({
    action_type: z.string().optional(),
    source: z.string().optional(),
    target: z.string().optional()
  })).optional(),
  observableTypes: z.array(z.object({
    key: z.string().optional(),
    label: z.string().optional()
  })).optional(),
  owner: Cases_owner.optional(),
  templates: Cases_templates.optional(),
  updated_at: z.string().nullable().optional(),
  updated_by: z.object({
    email: z.string().nullable(),
    full_name: z.string().nullable(),
    profile_uid: z.string().optional(),
    username: z.string().nullable()
  }).nullable().optional(),
  version: z.string().optional()
}).meta({ id: 'SetCaseConfigurationDefaultSpaceResponse' })
export type SetCaseConfigurationDefaultSpaceResponse = z.infer<typeof SetCaseConfigurationDefaultSpaceResponse>

export { Cases_templates } from './schemas/misc.js'
export { Cases_template_tags } from './schemas/misc.js'
export { Cases_case_title } from './schemas/misc.js'
export { Cases_case_tags } from './schemas/misc.js'
export { Cases_case_severity } from './schemas/misc.js'
export { Cases_settings } from './schemas/misc.js'
export { Cases_case_description } from './schemas/misc.js'
export { Cases_connector_types } from './schemas/misc.js'
export { Cases_case_category } from './schemas/misc.js'
export { Cases_assignees } from './schemas/misc.js'
export { Cases_owner } from './schemas/misc.js'
export { Cases_closure_types } from './schemas/misc.js'
