/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source open api file,
 * and elastic/elastic-client-generator-js to regenerate this file again.
 */

/* eslint-disable @typescript-eslint/no-redeclare */
import { z } from 'zod'
import { SLOs_artifacts, SLOs_budgeting_method, SLOs_group_by, SLOs_indicator_properties_apm_availability, SLOs_indicator_properties_apm_latency, SLOs_indicator_properties_custom_kql, SLOs_indicator_properties_custom_metric, SLOs_indicator_properties_histogram, SLOs_indicator_properties_timeslice_metric, SLOs_objective, SLOs_settings, SLOs_time_window } from './schemas/slos.js'

export const SLOs_update_slo_request = z.object({
  artifacts: SLOs_artifacts.optional(),
  budgetingMethod: SLOs_budgeting_method.optional(),
  description: z.string().optional(),
  groupBy: SLOs_group_by.optional(),
  indicator: z.union([SLOs_indicator_properties_custom_kql, SLOs_indicator_properties_apm_availability, SLOs_indicator_properties_apm_latency, SLOs_indicator_properties_custom_metric, SLOs_indicator_properties_histogram, SLOs_indicator_properties_timeslice_metric]).optional(),
  name: z.string().optional(),
  objective: SLOs_objective.optional(),
  settings: SLOs_settings.optional(),
  tags: z.array(z.string()).optional(),
  timeWindow: SLOs_time_window.optional()
}).meta({ id: 'SLOs_update_slo_request' })
export type SLOs_update_slo_request = z.infer<typeof SLOs_update_slo_request>

export { SLOs_slo_definition_response } from './schemas/slos.js'
export { SLOs_time_window } from './schemas/slos.js'
export { SLOs_settings } from './schemas/slos.js'
export { SLOs_objective } from './schemas/slos.js'
export { SLOs_indicator_properties_timeslice_metric } from './schemas/slos.js'
export { SLOs_timeslice_metric_doc_count_metric } from './schemas/slos.js'
export { SLOs_timeslice_metric_percentile_metric } from './schemas/slos.js'
export { SLOs_timeslice_metric_basic_metric_with_field } from './schemas/slos.js'
export { SLOs_indicator_properties_histogram } from './schemas/slos.js'
export { SLOs_indicator_properties_custom_metric } from './schemas/slos.js'
export { SLOs_indicator_properties_apm_latency } from './schemas/slos.js'
export { SLOs_indicator_properties_apm_availability } from './schemas/slos.js'
export { SLOs_indicator_properties_custom_kql } from './schemas/slos.js'
export { SLOs_kql_with_filters_total } from './schemas/slos.js'
export { SLOs_filter } from './schemas/slos.js'
export { SLOs_filter_meta } from './schemas/slos.js'
export { SLOs_kql_with_filters_good } from './schemas/slos.js'
export { SLOs_kql_with_filters } from './schemas/slos.js'
export { SLOs_group_by } from './schemas/slos.js'
export { SLOs_budgeting_method } from './schemas/slos.js'
export { SLOs_artifacts } from './schemas/slos.js'
