/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source open api file,
 * and elastic/elastic-client-generator-js to regenerate this file again.
 */

/* eslint-disable @typescript-eslint/no-redeclare */
import { z } from 'zod'
import { Cases_field_definition_response } from './schemas/misc.js'

export const Cases_field_definition_put_request = z.object({
  definition: z.string(),
  description: z.string().optional(),
  isGlobal: z.boolean().optional(),
  name: z.string().optional(),
  owner: z.string()
}).meta({ id: 'Cases_field_definition_put_request' })
export type Cases_field_definition_put_request = z.infer<typeof Cases_field_definition_put_request>

export const UpdateCaseFieldDefinitionDefaultSpaceResponse = z.union([Cases_field_definition_response, z.object({
  valid: z.boolean()
})]).meta({ id: 'UpdateCaseFieldDefinitionDefaultSpaceResponse' })
export type UpdateCaseFieldDefinitionDefaultSpaceResponse = z.infer<typeof UpdateCaseFieldDefinitionDefaultSpaceResponse>

export { Cases_field_definition_response } from './schemas/misc.js'
