/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */
/*
 * This file was automatically generated by elastic/elastic-client-generator-js.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source open api file,
 * and elastic/elastic-client-generator-js to regenerate this file again.
 */
import { z } from 'zod';
import { AsyncSearchSubmitRequest } from "../../../es/schemas/async_search_submit.js";
const _rawSchema = z.toJSONSchema(AsyncSearchSubmitRequest);
const _props = _rawSchema['properties'];
if (_props != null) {
    for (const prop of Object.values(_props)) {
        if (prop['found_in'] != null) {
            prop['x-found-in'] = prop['found_in'];
            delete prop['found_in'];
        }
    }
}
const _inputSchema = _rawSchema;
export const async_search_submit_definitions = [
    {
        name: 'submit',
        namespace: 'async-search',
        description: 'Run an async search.',
        method: 'POST',
        path: '/{index}/_async_search',
        input: _inputSchema,
    },
];
//# sourceMappingURL=async_search_submit.js.map