/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */
/*
 * This file was automatically generated by elastic/elastic-client-generator-js.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source open api file,
 * and elastic/elastic-client-generator-js to regenerate this file again.
 */
import { z } from 'zod';
import { CatHelpRequest } from "../../../es/schemas/cat_help.js";
const _rawSchema = z.toJSONSchema(CatHelpRequest);
const _props = _rawSchema['properties'];
if (_props != null) {
    for (const prop of Object.values(_props)) {
        if (prop['found_in'] != null) {
            prop['x-found-in'] = prop['found_in'];
            delete prop['found_in'];
        }
    }
}
const _inputSchema = _rawSchema;
export const cat_help_definitions = [
    {
        name: 'help',
        namespace: 'cat',
        description: 'Get CAT help.',
        method: 'GET',
        path: '/_cat',
        input: _inputSchema,
        responseType: 'text',
    },
];
//# sourceMappingURL=cat_help.js.map