/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */
/*
 * This file was automatically generated by elastic/elastic-client-generator-js.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source open api file,
 * and elastic/elastic-client-generator-js to regenerate this file again.
 */
import { z } from 'zod';
import { ClusterStateRequest } from "../../../es/schemas/cluster_state.js";
const _rawSchema = z.toJSONSchema(ClusterStateRequest);
const _props = _rawSchema['properties'];
if (_props != null) {
    for (const prop of Object.values(_props)) {
        if (prop['found_in'] != null) {
            prop['x-found-in'] = prop['found_in'];
            delete prop['found_in'];
        }
    }
}
const _inputSchema = _rawSchema;
export const cluster_state_definitions = [
    {
        name: 'state',
        namespace: 'cluster',
        description: 'Get the cluster state.',
        method: 'GET',
        path: '/_cluster/state/{metric}/{index}',
        input: _inputSchema,
    },
];
//# sourceMappingURL=cluster_state.js.map