/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */
/*
 * This file was automatically generated by elastic/elastic-client-generator-js.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source open api file,
 * and elastic/elastic-client-generator-js to regenerate this file again.
 */
import { z } from 'zod';
import { ConnectorUpdateServiceTypeRequest } from "../../../es/schemas/connector_update_service_type.js";
const _rawSchema = z.toJSONSchema(ConnectorUpdateServiceTypeRequest);
const _props = _rawSchema['properties'];
if (_props != null) {
    for (const prop of Object.values(_props)) {
        if (prop['found_in'] != null) {
            prop['x-found-in'] = prop['found_in'];
            delete prop['found_in'];
        }
    }
}
const _inputSchema = _rawSchema;
export const connector_update_service_type_definitions = [
    {
        name: 'update-service-type',
        namespace: 'connector',
        description: 'Update the connector service type.',
        method: 'PUT',
        path: '/_connector/{connector_id}/_service_type',
        input: _inputSchema,
    },
];
//# sourceMappingURL=connector_update_service_type.js.map