/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */
/*
 * This file was automatically generated by elastic/elastic-client-generator-js.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source open api file,
 * and elastic/elastic-client-generator-js to regenerate this file again.
 */
import { z } from 'zod';
import { ConnectorCheckInRequest } from "../../../es/schemas/connector_check_in.js";
const _rawSchema = z.toJSONSchema(ConnectorCheckInRequest);
const _props = _rawSchema['properties'];
if (_props != null) {
    for (const prop of Object.values(_props)) {
        if (prop['found_in'] != null) {
            prop['x-found-in'] = prop['found_in'];
            delete prop['found_in'];
        }
    }
}
const _inputSchema = _rawSchema;
export const connector_check_in_definitions = [
    {
        name: 'check-in',
        namespace: 'connector',
        description: 'Check in a connector.',
        method: 'PUT',
        path: '/_connector/{connector_id}/_check_in',
        input: _inputSchema,
    },
];
//# sourceMappingURL=connector_check_in.js.map