/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */
/*
 * This file was automatically generated by elastic/elastic-client-generator-js.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source open api file,
 * and elastic/elastic-client-generator-js to regenerate this file again.
 */
import { z } from 'zod';
import { DeleteByQueryRethrottleRequest } from "../../../es/schemas/delete_by_query_rethrottle.js";
const _rawSchema = z.toJSONSchema(DeleteByQueryRethrottleRequest);
const _props = _rawSchema['properties'];
if (_props != null) {
    for (const prop of Object.values(_props)) {
        if (prop['found_in'] != null) {
            prop['x-found-in'] = prop['found_in'];
            delete prop['found_in'];
        }
    }
}
const _inputSchema = _rawSchema;
export const delete_by_query_rethrottle_definitions = [
    {
        name: 'delete-by-query-rethrottle',
        description: 'Throttle a delete by query operation.',
        method: 'POST',
        path: '/_delete_by_query/{task_id}/_rethrottle',
        input: _inputSchema,
    },
];
//# sourceMappingURL=delete_by_query_rethrottle.js.map