/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */
/*
 * This file was automatically generated by elastic/elastic-client-generator-js.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source open api file,
 * and elastic/elastic-client-generator-js to regenerate this file again.
 */
import { z } from 'zod';
import { EsqlAsyncQueryGetRequest } from "../../../es/schemas/esql_async_query_get.js";
const _rawSchema = z.toJSONSchema(EsqlAsyncQueryGetRequest);
const _props = _rawSchema['properties'];
if (_props != null) {
    for (const prop of Object.values(_props)) {
        if (prop['found_in'] != null) {
            prop['x-found-in'] = prop['found_in'];
            delete prop['found_in'];
        }
    }
}
const _inputSchema = _rawSchema;
export const esql_async_query_get_definitions = [
    {
        name: 'async-query-get',
        namespace: 'esql',
        description: 'Get async ES|QL query results.',
        method: 'GET',
        path: '/_query/async/{id}',
        input: _inputSchema,
    },
];
//# sourceMappingURL=esql_async_query_get.js.map