/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */
/*
 * This file was automatically generated by elastic/elastic-client-generator-js.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source open api file,
 * and elastic/elastic-client-generator-js to regenerate this file again.
 */
import { z } from 'zod';
import { HealthReportRequest } from "../../../es/schemas/health_report.js";
const _rawSchema = z.toJSONSchema(HealthReportRequest);
const _props = _rawSchema['properties'];
if (_props != null) {
    for (const prop of Object.values(_props)) {
        if (prop['found_in'] != null) {
            prop['x-found-in'] = prop['found_in'];
            delete prop['found_in'];
        }
    }
}
const _inputSchema = _rawSchema;
export const health_report_definitions = [
    {
        name: 'health-report',
        description: 'Get the cluster health.',
        method: 'GET',
        path: '/_health_report/{feature}',
        input: _inputSchema,
    },
];
//# sourceMappingURL=health_report.js.map