/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */
/*
 * This file was automatically generated by elastic/elastic-client-generator-js.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source open api file,
 * and elastic/elastic-client-generator-js to regenerate this file again.
 */
import { z } from 'zod';
import { IndicesExplainDataLifecycleRequest } from "../../../es/schemas/indices_explain_data_lifecycle.js";
const _rawSchema = z.toJSONSchema(IndicesExplainDataLifecycleRequest);
const _props = _rawSchema['properties'];
if (_props != null) {
    for (const prop of Object.values(_props)) {
        if (prop['found_in'] != null) {
            prop['x-found-in'] = prop['found_in'];
            delete prop['found_in'];
        }
    }
}
const _inputSchema = _rawSchema;
export const indices_explain_data_lifecycle_definitions = [
    {
        name: 'explain-data-lifecycle',
        namespace: 'indices',
        description: 'Get the status for a data stream lifecycle.',
        method: 'GET',
        path: '/{index}/_lifecycle/explain',
        input: _inputSchema,
    },
];
//# sourceMappingURL=indices_explain_data_lifecycle.js.map