/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */
/*
 * This file was automatically generated by elastic/elastic-client-generator-js.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source open api file,
 * and elastic/elastic-client-generator-js to regenerate this file again.
 */
import { z } from 'zod';
import { IndicesDeleteDataStreamOptionsRequest } from "../../../es/schemas/indices_delete_data_stream_options.js";
const _rawSchema = z.toJSONSchema(IndicesDeleteDataStreamOptionsRequest);
const _props = _rawSchema['properties'];
if (_props != null) {
    for (const prop of Object.values(_props)) {
        if (prop['found_in'] != null) {
            prop['x-found-in'] = prop['found_in'];
            delete prop['found_in'];
        }
    }
}
const _inputSchema = _rawSchema;
export const indices_delete_data_stream_options_definitions = [
    {
        name: 'delete-data-stream-options',
        namespace: 'indices',
        description: 'Delete data stream options.',
        method: 'DELETE',
        path: '/_data_stream/{name}/_options',
        input: _inputSchema,
    },
];
//# sourceMappingURL=indices_delete_data_stream_options.js.map