/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */
/*
 * This file was automatically generated by elastic/elastic-client-generator-js.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source open api file,
 * and elastic/elastic-client-generator-js to regenerate this file again.
 */
import { z } from 'zod';
import { InferencePutHuggingFaceRequest } from "../../../es/schemas/inference_put_hugging_face.js";
const _rawSchema = z.toJSONSchema(InferencePutHuggingFaceRequest);
const _props = _rawSchema['properties'];
if (_props != null) {
    for (const prop of Object.values(_props)) {
        if (prop['found_in'] != null) {
            prop['x-found-in'] = prop['found_in'];
            delete prop['found_in'];
        }
    }
}
const _inputSchema = _rawSchema;
export const inference_put_hugging_face_definitions = [
    {
        name: 'put-hugging-face',
        namespace: 'inference',
        description: 'Create a Hugging Face inference endpoint.',
        method: 'PUT',
        path: '/_inference/{task_type}/{huggingface_inference_id}',
        input: _inputSchema,
    },
];
//# sourceMappingURL=inference_put_hugging_face.js.map