/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */
/*
 * This file was automatically generated by elastic/elastic-client-generator-js.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source open api file,
 * and elastic/elastic-client-generator-js to regenerate this file again.
 */
import { z } from 'zod';
import { InferenceSparseEmbeddingRequest } from "../../../es/schemas/inference_sparse_embedding.js";
const _rawSchema = z.toJSONSchema(InferenceSparseEmbeddingRequest);
const _props = _rawSchema['properties'];
if (_props != null) {
    for (const prop of Object.values(_props)) {
        if (prop['found_in'] != null) {
            prop['x-found-in'] = prop['found_in'];
            delete prop['found_in'];
        }
    }
}
const _inputSchema = _rawSchema;
export const inference_sparse_embedding_definitions = [
    {
        name: 'sparse-embedding',
        namespace: 'inference',
        description: 'Perform sparse embedding inference on the service.',
        method: 'POST',
        path: '/_inference/sparse_embedding/{inference_id}',
        input: _inputSchema,
    },
];
//# sourceMappingURL=inference_sparse_embedding.js.map