/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */
/*
 * This file was automatically generated by elastic/elastic-client-generator-js.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source open api file,
 * and elastic/elastic-client-generator-js to regenerate this file again.
 */
import { z } from 'zod';
import { IngestGetIpLocationDatabaseRequest } from "../../../es/schemas/ingest_get_ip_location_database.js";
const _rawSchema = z.toJSONSchema(IngestGetIpLocationDatabaseRequest);
const _props = _rawSchema['properties'];
if (_props != null) {
    for (const prop of Object.values(_props)) {
        if (prop['found_in'] != null) {
            prop['x-found-in'] = prop['found_in'];
            delete prop['found_in'];
        }
    }
}
const _inputSchema = _rawSchema;
export const ingest_get_ip_location_database_definitions = [
    {
        name: 'get-ip-location-database',
        namespace: 'ingest',
        description: 'Get IP geolocation database configurations.',
        method: 'GET',
        path: '/_ingest/ip_location/database/{id}',
        input: _inputSchema,
    },
];
//# sourceMappingURL=ingest_get_ip_location_database.js.map