/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */
/*
 * This file was automatically generated by elastic/elastic-client-generator-js.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source open api file,
 * and elastic/elastic-client-generator-js to regenerate this file again.
 */
import { z } from 'zod';
import { LicenseGetRequest } from "../../../es/schemas/license_get.js";
const _rawSchema = z.toJSONSchema(LicenseGetRequest);
const _props = _rawSchema['properties'];
if (_props != null) {
    for (const prop of Object.values(_props)) {
        if (prop['found_in'] != null) {
            prop['x-found-in'] = prop['found_in'];
            delete prop['found_in'];
        }
    }
}
const _inputSchema = _rawSchema;
export const license_get_definitions = [
    {
        name: 'get',
        namespace: 'license',
        description: 'Get license information.',
        method: 'GET',
        path: '/_license',
        input: _inputSchema,
    },
];
//# sourceMappingURL=license_get.js.map