/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */
/*
 * This file was automatically generated by elastic/elastic-client-generator-js.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source open api file,
 * and elastic/elastic-client-generator-js to regenerate this file again.
 */
import { z } from 'zod';
import { MigrationGetFeatureUpgradeStatusRequest } from "../../../es/schemas/migration_get_feature_upgrade_status.js";
const _rawSchema = z.toJSONSchema(MigrationGetFeatureUpgradeStatusRequest);
const _props = _rawSchema['properties'];
if (_props != null) {
    for (const prop of Object.values(_props)) {
        if (prop['found_in'] != null) {
            prop['x-found-in'] = prop['found_in'];
            delete prop['found_in'];
        }
    }
}
const _inputSchema = _rawSchema;
export const migration_get_feature_upgrade_status_definitions = [
    {
        name: 'get-feature-upgrade-status',
        namespace: 'migration',
        description: 'Get feature migration information.',
        method: 'GET',
        path: '/_migration/system_features',
        input: _inputSchema,
    },
];
//# sourceMappingURL=migration_get_feature_upgrade_status.js.map