/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */
/*
 * This file was automatically generated by elastic/elastic-client-generator-js.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source open api file,
 * and elastic/elastic-client-generator-js to regenerate this file again.
 */
import { z } from 'zod';
import { MlClearTrainedModelDeploymentCacheRequest } from "../../../es/schemas/ml_clear_trained_model_deployment_cache.js";
const _rawSchema = z.toJSONSchema(MlClearTrainedModelDeploymentCacheRequest);
const _props = _rawSchema['properties'];
if (_props != null) {
    for (const prop of Object.values(_props)) {
        if (prop['found_in'] != null) {
            prop['x-found-in'] = prop['found_in'];
            delete prop['found_in'];
        }
    }
}
const _inputSchema = _rawSchema;
export const ml_clear_trained_model_deployment_cache_definitions = [
    {
        name: 'clear-trained-model-deployment-cache',
        namespace: 'ml',
        description: 'Clear trained model deployment cache.',
        method: 'POST',
        path: '/_ml/trained_models/{model_id}/deployment/cache/_clear',
        input: _inputSchema,
    },
];
//# sourceMappingURL=ml_clear_trained_model_deployment_cache.js.map