/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */
/*
 * This file was automatically generated by elastic/elastic-client-generator-js.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source open api file,
 * and elastic/elastic-client-generator-js to regenerate this file again.
 */
import { z } from 'zod';
import { MlDeleteTrainedModelRequest } from "../../../es/schemas/ml_delete_trained_model.js";
const _rawSchema = z.toJSONSchema(MlDeleteTrainedModelRequest);
const _props = _rawSchema['properties'];
if (_props != null) {
    for (const prop of Object.values(_props)) {
        if (prop['found_in'] != null) {
            prop['x-found-in'] = prop['found_in'];
            delete prop['found_in'];
        }
    }
}
const _inputSchema = _rawSchema;
export const ml_delete_trained_model_definitions = [
    {
        name: 'delete-trained-model',
        namespace: 'ml',
        description: 'Delete an unreferenced trained model.',
        method: 'DELETE',
        path: '/_ml/trained_models/{model_id}',
        input: _inputSchema,
    },
];
//# sourceMappingURL=ml_delete_trained_model.js.map