/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */
/*
 * This file was automatically generated by elastic/elastic-client-generator-js.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source open api file,
 * and elastic/elastic-client-generator-js to regenerate this file again.
 */
import { z } from 'zod';
import { MlForecastRequest } from "../../../es/schemas/ml_forecast.js";
const _rawSchema = z.toJSONSchema(MlForecastRequest);
const _props = _rawSchema['properties'];
if (_props != null) {
    for (const prop of Object.values(_props)) {
        if (prop['found_in'] != null) {
            prop['x-found-in'] = prop['found_in'];
            delete prop['found_in'];
        }
    }
}
const _inputSchema = _rawSchema;
export const ml_forecast_definitions = [
    {
        name: 'forecast',
        namespace: 'ml',
        description: 'Predict future behavior of a time series.',
        method: 'POST',
        path: '/_ml/anomaly_detectors/{job_id}/_forecast',
        input: _inputSchema,
    },
];
//# sourceMappingURL=ml_forecast.js.map