/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */
/*
 * This file was automatically generated by elastic/elastic-client-generator-js.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source open api file,
 * and elastic/elastic-client-generator-js to regenerate this file again.
 */
import { z } from 'zod';
import { MlGetDatafeedsRequest } from "../../../es/schemas/ml_get_datafeeds.js";
const _rawSchema = z.toJSONSchema(MlGetDatafeedsRequest);
const _props = _rawSchema['properties'];
if (_props != null) {
    for (const prop of Object.values(_props)) {
        if (prop['found_in'] != null) {
            prop['x-found-in'] = prop['found_in'];
            delete prop['found_in'];
        }
    }
}
const _inputSchema = _rawSchema;
export const ml_get_datafeeds_definitions = [
    {
        name: 'get-datafeeds',
        namespace: 'ml',
        description: 'Get datafeeds configuration info.',
        method: 'GET',
        path: '/_ml/datafeeds/{datafeed_id}',
        input: _inputSchema,
    },
];
//# sourceMappingURL=ml_get_datafeeds.js.map