/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */
/*
 * This file was automatically generated by elastic/elastic-client-generator-js.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source open api file,
 * and elastic/elastic-client-generator-js to regenerate this file again.
 */
import { z } from 'zod';
import { MlGetDataFrameAnalyticsStatsRequest } from "../../../es/schemas/ml_get_data_frame_analytics_stats.js";
const _rawSchema = z.toJSONSchema(MlGetDataFrameAnalyticsStatsRequest);
const _props = _rawSchema['properties'];
if (_props != null) {
    for (const prop of Object.values(_props)) {
        if (prop['found_in'] != null) {
            prop['x-found-in'] = prop['found_in'];
            delete prop['found_in'];
        }
    }
}
const _inputSchema = _rawSchema;
export const ml_get_data_frame_analytics_stats_definitions = [
    {
        name: 'get-data-frame-analytics-stats',
        namespace: 'ml',
        description: 'Get data frame analytics job stats.',
        method: 'GET',
        path: '/_ml/data_frame/analytics/{id}/_stats',
        input: _inputSchema,
    },
];
//# sourceMappingURL=ml_get_data_frame_analytics_stats.js.map