/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */
/*
 * This file was automatically generated by elastic/elastic-client-generator-js.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source open api file,
 * and elastic/elastic-client-generator-js to regenerate this file again.
 */
import { z } from 'zod';
import { MlPutCalendarRequest } from "../../../es/schemas/ml_put_calendar.js";
const _rawSchema = z.toJSONSchema(MlPutCalendarRequest);
const _props = _rawSchema['properties'];
if (_props != null) {
    for (const prop of Object.values(_props)) {
        if (prop['found_in'] != null) {
            prop['x-found-in'] = prop['found_in'];
            delete prop['found_in'];
        }
    }
}
const _inputSchema = _rawSchema;
export const ml_put_calendar_definitions = [
    {
        name: 'put-calendar',
        namespace: 'ml',
        description: 'Create a calendar.',
        method: 'PUT',
        path: '/_ml/calendars/{calendar_id}',
        input: _inputSchema,
    },
];
//# sourceMappingURL=ml_put_calendar.js.map