/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */
/*
 * This file was automatically generated by elastic/elastic-client-generator-js.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source open api file,
 * and elastic/elastic-client-generator-js to regenerate this file again.
 */
import { z } from 'zod';
import { MlUpdateDatafeedRequest } from "../../../es/schemas/ml_update_datafeed.js";
const _rawSchema = z.toJSONSchema(MlUpdateDatafeedRequest);
const _props = _rawSchema['properties'];
if (_props != null) {
    for (const prop of Object.values(_props)) {
        if (prop['found_in'] != null) {
            prop['x-found-in'] = prop['found_in'];
            delete prop['found_in'];
        }
    }
}
const _inputSchema = _rawSchema;
export const ml_update_datafeed_definitions = [
    {
        name: 'update-datafeed',
        namespace: 'ml',
        description: 'Update a datafeed.',
        method: 'POST',
        path: '/_ml/datafeeds/{datafeed_id}/_update',
        input: _inputSchema,
    },
];
//# sourceMappingURL=ml_update_datafeed.js.map