/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */
/*
 * This file was automatically generated by elastic/elastic-client-generator-js.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source open api file,
 * and elastic/elastic-client-generator-js to regenerate this file again.
 */
import { z } from 'zod';
import { NodesGetRepositoriesMeteringInfoRequest } from "../../../es/schemas/nodes_get_repositories_metering_info.js";
const _rawSchema = z.toJSONSchema(NodesGetRepositoriesMeteringInfoRequest);
const _props = _rawSchema['properties'];
if (_props != null) {
    for (const prop of Object.values(_props)) {
        if (prop['found_in'] != null) {
            prop['x-found-in'] = prop['found_in'];
            delete prop['found_in'];
        }
    }
}
const _inputSchema = _rawSchema;
export const nodes_get_repositories_metering_info_definitions = [
    {
        name: 'get-repositories-metering-info',
        namespace: 'nodes',
        description: 'Get cluster repositories metering.',
        method: 'GET',
        path: '/_nodes/{node_id}/_repositories_metering',
        input: _inputSchema,
    },
];
//# sourceMappingURL=nodes_get_repositories_metering_info.js.map