/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */
/*
 * This file was automatically generated by elastic/elastic-client-generator-js.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source open api file,
 * and elastic/elastic-client-generator-js to regenerate this file again.
 */
import { z } from 'zod';
import { RollupGetRollupIndexCapsRequest } from "../../../es/schemas/rollup_get_rollup_index_caps.js";
const _rawSchema = z.toJSONSchema(RollupGetRollupIndexCapsRequest);
const _props = _rawSchema['properties'];
if (_props != null) {
    for (const prop of Object.values(_props)) {
        if (prop['found_in'] != null) {
            prop['x-found-in'] = prop['found_in'];
            delete prop['found_in'];
        }
    }
}
const _inputSchema = _rawSchema;
export const rollup_get_rollup_index_caps_definitions = [
    {
        name: 'get-rollup-index-caps',
        namespace: 'rollup',
        description: 'Get the rollup index capabilities.',
        method: 'GET',
        path: '/{index}/_rollup/data',
        input: _inputSchema,
    },
];
//# sourceMappingURL=rollup_get_rollup_index_caps.js.map