/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */
/*
 * This file was automatically generated by elastic/elastic-client-generator-js.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source open api file,
 * and elastic/elastic-client-generator-js to regenerate this file again.
 */
import { z } from 'zod';
import { SearchShardsRequest } from "../../../es/schemas/search_shards.js";
const _rawSchema = z.toJSONSchema(SearchShardsRequest);
const _props = _rawSchema['properties'];
if (_props != null) {
    for (const prop of Object.values(_props)) {
        if (prop['found_in'] != null) {
            prop['x-found-in'] = prop['found_in'];
            delete prop['found_in'];
        }
    }
}
const _inputSchema = _rawSchema;
export const search_shards_definitions = [
    {
        name: 'search-shards',
        description: 'Get the search shards.',
        method: 'GET',
        path: '/{index}/_search_shards',
        input: _inputSchema,
    },
];
//# sourceMappingURL=search_shards.js.map