/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */
/*
 * This file was automatically generated by elastic/elastic-client-generator-js.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source open api file,
 * and elastic/elastic-client-generator-js to regenerate this file again.
 */
import { z } from 'zod';
import { SecurityGetUserProfileRequest } from "../../../es/schemas/security_get_user_profile.js";
const _rawSchema = z.toJSONSchema(SecurityGetUserProfileRequest);
const _props = _rawSchema['properties'];
if (_props != null) {
    for (const prop of Object.values(_props)) {
        if (prop['found_in'] != null) {
            prop['x-found-in'] = prop['found_in'];
            delete prop['found_in'];
        }
    }
}
const _inputSchema = _rawSchema;
export const security_get_user_profile_definitions = [
    {
        name: 'get-user-profile',
        namespace: 'security',
        description: 'Get a user profile.',
        method: 'GET',
        path: '/_security/profile/{uid}',
        input: _inputSchema,
    },
];
//# sourceMappingURL=security_get_user_profile.js.map