/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */
/*
 * This file was automatically generated by elastic/elastic-client-generator-js.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source open api file,
 * and elastic/elastic-client-generator-js to regenerate this file again.
 */
import { z } from 'zod';
import { SecuritySamlServiceProviderMetadataRequest } from "../../../es/schemas/security_saml_service_provider_metadata.js";
const _rawSchema = z.toJSONSchema(SecuritySamlServiceProviderMetadataRequest);
const _props = _rawSchema['properties'];
if (_props != null) {
    for (const prop of Object.values(_props)) {
        if (prop['found_in'] != null) {
            prop['x-found-in'] = prop['found_in'];
            delete prop['found_in'];
        }
    }
}
const _inputSchema = _rawSchema;
export const security_saml_service_provider_metadata_definitions = [
    {
        name: 'saml-service-provider-metadata',
        namespace: 'security',
        description: 'Create SAML service provider metadata.',
        method: 'GET',
        path: '/_security/saml/metadata/{realm_name}',
        input: _inputSchema,
    },
];
//# sourceMappingURL=security_saml_service_provider_metadata.js.map