/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */
/*
 * This file was automatically generated by elastic/elastic-client-generator-js.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source open api file,
 * and elastic/elastic-client-generator-js to regenerate this file again.
 */
import { z } from 'zod';
import { SecurityUpdateUserProfileDataRequest } from "../../../es/schemas/security_update_user_profile_data.js";
const _rawSchema = z.toJSONSchema(SecurityUpdateUserProfileDataRequest);
const _props = _rawSchema['properties'];
if (_props != null) {
    for (const prop of Object.values(_props)) {
        if (prop['found_in'] != null) {
            prop['x-found-in'] = prop['found_in'];
            delete prop['found_in'];
        }
    }
}
const _inputSchema = _rawSchema;
export const security_update_user_profile_data_definitions = [
    {
        name: 'update-user-profile-data',
        namespace: 'security',
        description: 'Update user profile data.',
        method: 'PUT',
        path: '/_security/profile/{uid}/_data',
        input: _inputSchema,
    },
];
//# sourceMappingURL=security_update_user_profile_data.js.map