/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */
/*
 * This file was automatically generated by elastic/elastic-client-generator-js.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source open api file,
 * and elastic/elastic-client-generator-js to regenerate this file again.
 */
import { z } from 'zod';
import { SecurityHasPrivilegesRequest } from "../../../es/schemas/security_has_privileges.js";
const _rawSchema = z.toJSONSchema(SecurityHasPrivilegesRequest);
const _props = _rawSchema['properties'];
if (_props != null) {
    for (const prop of Object.values(_props)) {
        if (prop['found_in'] != null) {
            prop['x-found-in'] = prop['found_in'];
            delete prop['found_in'];
        }
    }
}
const _inputSchema = _rawSchema;
export const security_has_privileges_definitions = [
    {
        name: 'has-privileges',
        namespace: 'security',
        description: 'Check user privileges.',
        method: 'GET',
        path: '/_security/user/{user}/_has_privileges',
        input: _inputSchema,
    },
];
//# sourceMappingURL=security_has_privileges.js.map