/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */
/*
 * This file was automatically generated by elastic/elastic-client-generator-js.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source open api file,
 * and elastic/elastic-client-generator-js to regenerate this file again.
 */
import { z } from 'zod';
import { SimulateIngestRequest } from "../../../es/schemas/simulate_ingest.js";
const _rawSchema = z.toJSONSchema(SimulateIngestRequest);
const _props = _rawSchema['properties'];
if (_props != null) {
    for (const prop of Object.values(_props)) {
        if (prop['found_in'] != null) {
            prop['x-found-in'] = prop['found_in'];
            delete prop['found_in'];
        }
    }
}
const _inputSchema = _rawSchema;
export const simulate_ingest_definitions = [
    {
        name: 'ingest',
        namespace: 'simulate',
        description: 'Simulate data ingestion.',
        method: 'GET',
        path: '/_ingest/{index}/_simulate',
        input: _inputSchema,
    },
];
//# sourceMappingURL=simulate_ingest.js.map