/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */
/*
 * This file was automatically generated by elastic/elastic-client-generator-js.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source open api file,
 * and elastic/elastic-client-generator-js to regenerate this file again.
 */
import { z } from 'zod';
import { SlmGetStatusRequest } from "../../../es/schemas/slm_get_status.js";
const _rawSchema = z.toJSONSchema(SlmGetStatusRequest);
const _props = _rawSchema['properties'];
if (_props != null) {
    for (const prop of Object.values(_props)) {
        if (prop['found_in'] != null) {
            prop['x-found-in'] = prop['found_in'];
            delete prop['found_in'];
        }
    }
}
const _inputSchema = _rawSchema;
export const slm_get_status_definitions = [
    {
        name: 'get-status',
        namespace: 'slm',
        description: 'Get the snapshot lifecycle management status.',
        method: 'GET',
        path: '/_slm/status',
        input: _inputSchema,
    },
];
//# sourceMappingURL=slm_get_status.js.map