/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */
/*
 * This file was automatically generated by elastic/elastic-client-generator-js.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source open api file,
 * and elastic/elastic-client-generator-js to regenerate this file again.
 */
import { z } from 'zod';
import { SqlGetAsyncRequest } from "../../../es/schemas/sql_get_async.js";
const _rawSchema = z.toJSONSchema(SqlGetAsyncRequest);
const _props = _rawSchema['properties'];
if (_props != null) {
    for (const prop of Object.values(_props)) {
        if (prop['found_in'] != null) {
            prop['x-found-in'] = prop['found_in'];
            delete prop['found_in'];
        }
    }
}
const _inputSchema = _rawSchema;
export const sql_get_async_definitions = [
    {
        name: 'get-async',
        namespace: 'sql',
        description: 'Get async SQL search results.',
        method: 'GET',
        path: '/_sql/async/{id}',
        input: _inputSchema,
    },
];
//# sourceMappingURL=sql_get_async.js.map