/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */
/*
 * This file was automatically generated by elastic/elastic-client-generator-js.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source open api file,
 * and elastic/elastic-client-generator-js to regenerate this file again.
 */
import { z } from 'zod';
import { SynonymsGetSynonymRuleRequest } from "../../../es/schemas/synonyms_get_synonym_rule.js";
const _rawSchema = z.toJSONSchema(SynonymsGetSynonymRuleRequest);
const _props = _rawSchema['properties'];
if (_props != null) {
    for (const prop of Object.values(_props)) {
        if (prop['found_in'] != null) {
            prop['x-found-in'] = prop['found_in'];
            delete prop['found_in'];
        }
    }
}
const _inputSchema = _rawSchema;
export const synonyms_get_synonym_rule_definitions = [
    {
        name: 'get-synonym-rule',
        namespace: 'synonyms',
        description: 'Get a synonym rule.',
        method: 'GET',
        path: '/_synonyms/{set_id}/{rule_id}',
        input: _inputSchema,
    },
];
//# sourceMappingURL=synonyms_get_synonym_rule.js.map