/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */
/*
 * This file was automatically generated by elastic/elastic-client-generator-js.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source open api file,
 * and elastic/elastic-client-generator-js to regenerate this file again.
 */
import { z } from 'zod';
import { TasksCancelRequest } from "../../../es/schemas/tasks_cancel.js";
const _rawSchema = z.toJSONSchema(TasksCancelRequest);
const _props = _rawSchema['properties'];
if (_props != null) {
    for (const prop of Object.values(_props)) {
        if (prop['found_in'] != null) {
            prop['x-found-in'] = prop['found_in'];
            delete prop['found_in'];
        }
    }
}
const _inputSchema = _rawSchema;
export const tasks_cancel_definitions = [
    {
        name: 'cancel',
        namespace: 'tasks',
        description: 'Cancel a task.',
        method: 'POST',
        path: '/_tasks/{task_id}/_cancel',
        input: _inputSchema,
    },
];
//# sourceMappingURL=tasks_cancel.js.map