/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */
/*
 * This file was automatically generated by elastic/elastic-client-generator-js.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source open api file,
 * and elastic/elastic-client-generator-js to regenerate this file again.
 */
import { z } from 'zod';
import { TermsEnumRequest } from "../../../es/schemas/terms_enum.js";
const _rawSchema = z.toJSONSchema(TermsEnumRequest);
const _props = _rawSchema['properties'];
if (_props != null) {
    for (const prop of Object.values(_props)) {
        if (prop['found_in'] != null) {
            prop['x-found-in'] = prop['found_in'];
            delete prop['found_in'];
        }
    }
}
const _inputSchema = _rawSchema;
export const terms_enum_definitions = [
    {
        name: 'terms-enum',
        description: 'Get terms in an index.',
        method: 'GET',
        path: '/{index}/_terms_enum',
        input: _inputSchema,
    },
];
//# sourceMappingURL=terms_enum.js.map