/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */
/*
 * This file was automatically generated by elastic/elastic-client-generator-js.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source open api file,
 * and elastic/elastic-client-generator-js to regenerate this file again.
 */
import { z } from 'zod';
import { TermvectorsRequest } from "../../../es/schemas/termvectors.js";
const _rawSchema = z.toJSONSchema(TermvectorsRequest);
const _props = _rawSchema['properties'];
if (_props != null) {
    for (const prop of Object.values(_props)) {
        if (prop['found_in'] != null) {
            prop['x-found-in'] = prop['found_in'];
            delete prop['found_in'];
        }
    }
}
const _inputSchema = _rawSchema;
export const termvectors_definitions = [
    {
        name: 'termvectors',
        description: 'Get term vector information.',
        method: 'GET',
        path: '/{index}/_termvectors/{id}',
        input: _inputSchema,
    },
];
//# sourceMappingURL=termvectors.js.map