/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */
export const agentBuilderDefinitions = [
    {
        name: 'post-agent-builder-a2a-agentid',
        namespace: 'agent-builder',
        description: 'Send A2A task',
        method: 'POST',
        path: '/api/agent_builder/a2a/{agentId}',
        input: { type: 'object', properties: { agentId: { type: 'string', description: 'The unique identifier of the agent to send the A2A task to.', 'x-found-in': 'path' } }, required: ['agentId'] },
    },
    {
        name: 'get-agent-builder-a2a-agentid-json',
        namespace: 'agent-builder',
        description: 'Get A2A agent card',
        method: 'GET',
        path: '/api/agent_builder/a2a/{agentId}.json',
        input: { type: 'object', properties: { agentId: { type: 'string', description: 'The unique identifier of the agent to get A2A metadata for.', 'x-found-in': 'path' } }, required: ['agentId'] },
    },
    {
        name: 'get-agent-builder-agents',
        namespace: 'agent-builder',
        description: 'List agents',
        method: 'GET',
        path: '/api/agent_builder/agents',
    },
    {
        name: 'post-agent-builder-agents',
        namespace: 'agent-builder',
        description: 'Create an agent',
        method: 'POST',
        path: '/api/agent_builder/agents',
        input: { type: 'object', properties: { avatar_color: { description: 'Optional hex color code for the agent avatar.', 'x-found-in': 'body', type: 'string' }, avatar_symbol: { description: 'Optional symbol/initials for the agent avatar.', 'x-found-in': 'body', type: 'string' }, configuration: { description: 'Configuration settings for the agent.', 'x-found-in': 'body', type: 'object' }, description: { description: 'Description of what the agent does.', 'x-found-in': 'body', type: 'string' }, id: { description: 'Unique identifier for the agent.', 'x-found-in': 'body', type: 'string' }, labels: { description: 'Optional labels for categorizing and organizing agents.', 'x-found-in': 'body' }, name: { description: 'Display name for the agent.', 'x-found-in': 'body', type: 'string' }, visibility: { description: '**Technical Preview; added in 9.4.0.** Optional visibility setting: `public` (any privileged user can read/write), `shared` (any privileged user can read, only owner can write), `private` (only owner can read/write).', 'x-found-in': 'body', type: 'string' } }, required: ['configuration', 'description', 'id', 'name'] },
    },
    {
        name: 'post-agent-builder-agents-agent-id-consumption',
        namespace: 'agent-builder',
        description: 'Get agent consumption data',
        method: 'POST',
        path: '/api/agent_builder/agents/{agent_id}/consumption',
        input: { type: 'object', properties: { agent_id: { type: 'string', description: 'The unique identifier of the agent.', 'x-found-in': 'path' }, has_warnings: { description: 'Filter to conversations with or without high-token warnings.', 'x-found-in': 'body', type: 'boolean' }, search: { description: 'Free-text search filter on conversation title.', 'x-found-in': 'body', type: 'string' }, search_after: { description: 'Cursor for pagination. Pass the search_after value from the previous response.', 'x-found-in': 'body' }, size: { description: 'Number of results per page.', 'x-found-in': 'body', type: 'number' }, sort_field: { description: 'Field to sort results by.', 'x-found-in': 'body', type: 'string' }, sort_order: { description: 'Sort direction.', 'x-found-in': 'body', type: 'string' }, usernames: { description: 'Filter results to conversations by these usernames.', 'x-found-in': 'body' } }, required: ['agent_id'] },
    },
    {
        name: 'delete-agent-builder-agents-id',
        namespace: 'agent-builder',
        description: 'Delete an agent',
        method: 'DELETE',
        path: '/api/agent_builder/agents/{id}',
        input: { type: 'object', properties: { id: { type: 'string', description: 'The unique identifier of the agent to delete.', 'x-found-in': 'path' } }, required: ['id'] },
    },
    {
        name: 'get-agent-builder-agents-id',
        namespace: 'agent-builder',
        description: 'Get an agent by ID',
        method: 'GET',
        path: '/api/agent_builder/agents/{id}',
        input: { type: 'object', properties: { id: { type: 'string', description: 'The unique identifier of the agent to retrieve.', 'x-found-in': 'path' } }, required: ['id'] },
    },
    {
        name: 'put-agent-builder-agents-id',
        namespace: 'agent-builder',
        description: 'Update an agent',
        method: 'PUT',
        path: '/api/agent_builder/agents/{id}',
        input: { type: 'object', properties: { id: { type: 'string', description: 'The unique identifier of the agent to update.', 'x-found-in': 'path' }, avatar_color: { description: 'Updated hex color code for the agent avatar.', 'x-found-in': 'body', type: 'string' }, avatar_symbol: { description: 'Updated symbol/initials for the agent avatar.', 'x-found-in': 'body', type: 'string' }, configuration: { description: 'Updated configuration settings for the agent.', 'x-found-in': 'body', type: 'object' }, description: { description: 'Updated description of what the agent does.', 'x-found-in': 'body', type: 'string' }, labels: { description: 'Updated labels for categorizing and organizing agents.', 'x-found-in': 'body' }, name: { description: 'Updated display name for the agent.', 'x-found-in': 'body', type: 'string' }, visibility: { description: '**Technical Preview; added in 9.4.0.** Updated visibility setting: `public` (any privileged user can read/write), `shared` (any privileged user can read, only owner can write), `private` (only owner can read/write).', 'x-found-in': 'body', type: 'string' } }, required: ['id'] },
    },
    {
        name: 'get-agent-builder-agents-id-acl',
        namespace: 'agent-builder',
        description: "Get an agent's access control list",
        method: 'GET',
        path: '/api/agent_builder/agents/{id}/acl',
        input: { type: 'object', properties: { id: { type: 'string', description: 'The unique identifier of the agent whose ACL to retrieve.', 'x-found-in': 'path' } }, required: ['id'] },
    },
    {
        name: 'put-agent-builder-agents-id-acl',
        namespace: 'agent-builder',
        description: "Update an agent's access control list",
        method: 'PUT',
        path: '/api/agent_builder/agents/{id}/acl',
        input: { type: 'object', properties: { id: { type: 'string', description: 'The unique identifier of the agent whose ACL to update.', 'x-found-in': 'path' }, entries: { description: 'Access control entries to apply to the agent. Each entry has a `type` (currently only `user` is supported; role-based grants are planned for a future release), a `name` (the principal username), and a `role`. Submitting this field replaces the existing ACL entirely; submit an empty array to clear all grants.', 'x-found-in': 'body' } }, required: ['id', 'entries'] },
    },
    {
        name: 'get-agent-builder-conversations',
        namespace: 'agent-builder',
        description: 'List conversations',
        method: 'GET',
        path: '/api/agent_builder/conversations',
        input: { type: 'object', properties: { agent_id: { type: 'string', description: 'Optional agent ID to filter conversations by a specific agent.', 'x-found-in': 'query' } } },
    },
    {
        name: 'delete-agent-builder-conversations-conversation-id',
        namespace: 'agent-builder',
        description: 'Delete conversation by ID',
        method: 'DELETE',
        path: '/api/agent_builder/conversations/{conversation_id}',
        input: { type: 'object', properties: { conversation_id: { type: 'string', description: 'The unique identifier of the conversation to delete.', 'x-found-in': 'path' } }, required: ['conversation_id'] },
    },
    {
        name: 'get-agent-builder-conversations-conversation-id',
        namespace: 'agent-builder',
        description: 'Get conversation by ID',
        method: 'GET',
        path: '/api/agent_builder/conversations/{conversation_id}',
        input: { type: 'object', properties: { conversation_id: { type: 'string', description: 'The unique identifier of the conversation to retrieve.', 'x-found-in': 'path' } }, required: ['conversation_id'] },
    },
    {
        name: 'get-agent-builder-conversations-conversation-id-attachments',
        namespace: 'agent-builder',
        description: 'List conversation attachments',
        method: 'GET',
        path: '/api/agent_builder/conversations/{conversation_id}/attachments',
        input: { type: 'object', properties: { conversation_id: { type: 'string', description: 'The unique identifier of the conversation.', 'x-found-in': 'path' }, include_deleted: { type: 'boolean', description: 'Whether to include deleted attachments in the list.', 'x-found-in': 'query' } }, required: ['conversation_id'] },
    },
    {
        name: 'post-agent-builder-conversations-conversation-id-attachments',
        namespace: 'agent-builder',
        description: 'Create conversation attachment',
        method: 'POST',
        path: '/api/agent_builder/conversations/{conversation_id}/attachments',
        input: { type: 'object', properties: { conversation_id: { type: 'string', description: 'The unique identifier of the conversation.', 'x-found-in': 'path' }, data: { description: 'The attachment data/content. Required unless origin is provided.', 'x-found-in': 'body', type: 'string' }, description: { description: 'Human-readable description of the attachment.', 'x-found-in': 'body', type: 'string' }, hidden: { description: 'Whether the attachment should be hidden from the user.', 'x-found-in': 'body', type: 'boolean' }, id: { description: 'Optional custom ID for the attachment.', 'x-found-in': 'body', type: 'string' }, origin: { description: 'Origin string (for example, saved object ID) for by-reference attachments. When provided without data, the content is resolved once at creation time.', 'x-found-in': 'body', type: 'string' }, type: { description: 'The type of the attachment (e.g., text, esql, visualization).', 'x-found-in': 'body', type: 'string' } }, required: ['conversation_id', 'data', 'type'] },
    },
    {
        name: 'delete-agent-builder-conversations-conversation-id-attachments-attachment-id',
        namespace: 'agent-builder',
        description: 'Delete conversation attachment',
        method: 'DELETE',
        path: '/api/agent_builder/conversations/{conversation_id}/attachments/{attachment_id}',
        input: { type: 'object', properties: { conversation_id: { type: 'string', description: 'The unique identifier of the conversation.', 'x-found-in': 'path' }, attachment_id: { type: 'string', description: 'The unique identifier of the attachment to delete.', 'x-found-in': 'path' }, permanent: { type: 'boolean', description: 'If true, permanently removes the attachment (only for unreferenced attachments).', 'x-found-in': 'query' } }, required: ['conversation_id', 'attachment_id'] },
    },
    {
        name: 'patch-agent-builder-conversations-conversation-id-attachments-attachment-id',
        namespace: 'agent-builder',
        description: 'Rename attachment',
        method: 'PATCH',
        path: '/api/agent_builder/conversations/{conversation_id}/attachments/{attachment_id}',
        input: { type: 'object', properties: { conversation_id: { type: 'string', description: 'The unique identifier of the conversation.', 'x-found-in': 'path' }, attachment_id: { type: 'string', description: 'The unique identifier of the attachment to rename.', 'x-found-in': 'path' }, description: { description: 'The new description/name for the attachment.', 'x-found-in': 'body', type: 'string' } }, required: ['conversation_id', 'attachment_id', 'description'] },
    },
    {
        name: 'put-agent-builder-conversations-conversation-id-attachments-attachment-id',
        namespace: 'agent-builder',
        description: 'Update conversation attachment',
        method: 'PUT',
        path: '/api/agent_builder/conversations/{conversation_id}/attachments/{attachment_id}',
        input: { type: 'object', properties: { conversation_id: { type: 'string', description: 'The unique identifier of the conversation.', 'x-found-in': 'path' }, attachment_id: { type: 'string', description: 'The unique identifier of the attachment to update.', 'x-found-in': 'path' }, data: { description: 'The new attachment data/content.', 'x-found-in': 'body', type: 'string' }, description: { description: 'Optional new description for the attachment.', 'x-found-in': 'body', type: 'string' } }, required: ['conversation_id', 'attachment_id', 'data'] },
    },
    {
        name: 'post-agent-builder-conversations-conversation-id-attachments-attachment-id-restore',
        namespace: 'agent-builder',
        description: 'Restore deleted attachment',
        method: 'POST',
        path: '/api/agent_builder/conversations/{conversation_id}/attachments/{attachment_id}/_restore',
        input: { type: 'object', properties: { conversation_id: { type: 'string', description: 'The unique identifier of the conversation.', 'x-found-in': 'path' }, attachment_id: { type: 'string', description: 'The unique identifier of the attachment to restore.', 'x-found-in': 'path' } }, required: ['conversation_id', 'attachment_id'] },
    },
    {
        name: 'put-agent-builder-conversations-conversation-id-attachments-attachment-id-origin',
        namespace: 'agent-builder',
        description: 'Update attachment origin',
        method: 'PUT',
        path: '/api/agent_builder/conversations/{conversation_id}/attachments/{attachment_id}/origin',
        input: { type: 'object', properties: { conversation_id: { type: 'string', description: 'The unique identifier of the conversation.', 'x-found-in': 'path' }, attachment_id: { type: 'string', description: 'The unique identifier of the attachment to update.', 'x-found-in': 'path' }, origin: { description: 'The origin string (e.g., saved object ID for visualizations and dashboards).', 'x-found-in': 'body', type: 'string' } }, required: ['conversation_id', 'attachment_id', 'origin'] },
    },
    {
        name: 'get-agent-builder-conversations-conversation-id-attachments-stale',
        namespace: 'agent-builder',
        description: 'Check attachment staleness',
        method: 'GET',
        path: '/api/agent_builder/conversations/{conversation_id}/attachments/stale',
        input: { type: 'object', properties: { conversation_id: { type: 'string', description: 'The unique identifier of the conversation.', 'x-found-in': 'path' } }, required: ['conversation_id'] },
    },
    {
        name: 'post-agent-builder-converse',
        namespace: 'agent-builder',
        description: 'Send chat message',
        method: 'POST',
        path: '/api/agent_builder/converse',
        input: { type: 'object', properties: { _execution_mode: { description: '**Experimental; added in 9.4.0.** define how to execute the agent (local execution or via task_manager)', 'x-found-in': 'body', type: 'string' }, action: { description: 'The action to perform. "regenerate" re-executes the last round with the original input. Requires conversation_id.', 'x-found-in': 'body', type: 'string' }, agent_id: { description: 'The ID of the agent to chat with. Defaults to the default Elastic AI agent.', 'x-found-in': 'body', type: 'string' }, attachments: { description: '**Technical Preview; added in 9.3.0.** Optional attachments to send with the message.', 'x-found-in': 'body' }, browser_api_tools: { description: 'Optional browser API tools to be registered as LLM tools with browser.* namespace. These tools execute on the client side.', 'x-found-in': 'body' }, capabilities: { description: 'Controls agent capabilities during conversation. Currently supports visualization rendering for tabular tool results.', 'x-found-in': 'body', type: 'object' }, configuration_overrides: { description: 'Runtime configuration overrides. These override the stored agent configuration for this execution only.', 'x-found-in': 'body', type: 'object' }, connector_id: { description: 'Optional connector ID for the agent to use for model routing. Mutually exclusive with `inference_id`; omit or use only one.', 'x-found-in': 'body', type: 'string' }, conversation_id: { description: 'Optional existing conversation ID to continue a previous conversation.', 'x-found-in': 'body', type: 'string' }, execution_id: { description: 'Optional client-generated execution ID. Provide it to address this execution later (for example, to abort it). Must be unique; defaults to a server-generated ID.', 'x-found-in': 'body', type: 'string' }, inference_id: { description: 'Optional inference endpoint ID for model routing (public alias for the same internal identifier as `connector_id`). Mutually exclusive with `connector_id`.', 'x-found-in': 'body', type: 'string' }, input: { description: 'The user input message to send to the agent.', 'x-found-in': 'body', type: 'string' }, prompts: { description: 'Use this field to respond to a `confirmation`, `authorization`, or `ask_user_question` prompt. Send an `allow` boolean to answer a `confirmation` prompt, an `authorized` boolean to answer an `authorization` prompt, or an `answers` array (one entry per question) to answer an `ask_user_question` prompt.', 'x-found-in': 'body', type: 'object' } } },
    },
    {
        name: 'post-agent-builder-converse-async',
        namespace: 'agent-builder',
        description: 'Send chat message (streaming)',
        method: 'POST',
        path: '/api/agent_builder/converse/async',
        input: { type: 'object', properties: { _execution_mode: { description: '**Experimental; added in 9.4.0.** define how to execute the agent (local execution or via task_manager)', 'x-found-in': 'body', type: 'string' }, action: { description: 'The action to perform. "regenerate" re-executes the last round with the original input. Requires conversation_id.', 'x-found-in': 'body', type: 'string' }, agent_id: { description: 'The ID of the agent to chat with. Defaults to the default Elastic AI agent.', 'x-found-in': 'body', type: 'string' }, attachments: { description: '**Technical Preview; added in 9.3.0.** Optional attachments to send with the message.', 'x-found-in': 'body' }, browser_api_tools: { description: 'Optional browser API tools to be registered as LLM tools with browser.* namespace. These tools execute on the client side.', 'x-found-in': 'body' }, capabilities: { description: 'Controls agent capabilities during conversation. Currently supports visualization rendering for tabular tool results.', 'x-found-in': 'body', type: 'object' }, configuration_overrides: { description: 'Runtime configuration overrides. These override the stored agent configuration for this execution only.', 'x-found-in': 'body', type: 'object' }, connector_id: { description: 'Optional connector ID for the agent to use for model routing. Mutually exclusive with `inference_id`; omit or use only one.', 'x-found-in': 'body', type: 'string' }, conversation_id: { description: 'Optional existing conversation ID to continue a previous conversation.', 'x-found-in': 'body', type: 'string' }, execution_id: { description: 'Optional client-generated execution ID. Provide it to address this execution later (for example, to abort it). Must be unique; defaults to a server-generated ID.', 'x-found-in': 'body', type: 'string' }, inference_id: { description: 'Optional inference endpoint ID for model routing (public alias for the same internal identifier as `connector_id`). Mutually exclusive with `connector_id`.', 'x-found-in': 'body', type: 'string' }, input: { description: 'The user input message to send to the agent.', 'x-found-in': 'body', type: 'string' }, prompts: { description: 'Use this field to respond to a `confirmation`, `authorization`, or `ask_user_question` prompt. Send an `allow` boolean to answer a `confirmation` prompt, an `authorized` boolean to answer an `authorization` prompt, or an `answers` array (one entry per question) to answer an `ask_user_question` prompt.', 'x-found-in': 'body', type: 'object' } } },
    },
    {
        name: 'post-agent-builder-mcp',
        namespace: 'agent-builder',
        description: 'MCP server',
        method: 'POST',
        path: '/api/agent_builder/mcp',
        input: { type: 'object', properties: { namespace: { type: 'string', description: 'Comma-separated list of namespaces to filter tools. Only tools matching the specified namespaces will be returned.', 'x-found-in': 'query' } } },
    },
    {
        name: 'get-agent-builder-plugins',
        namespace: 'agent-builder',
        description: 'List plugins',
        method: 'GET',
        path: '/api/agent_builder/plugins',
    },
    {
        name: 'delete-agent-builder-plugins-pluginid',
        namespace: 'agent-builder',
        description: 'Delete a plugin',
        method: 'DELETE',
        path: '/api/agent_builder/plugins/{pluginId}',
        input: { type: 'object', properties: { pluginId: { type: 'string', description: 'The unique identifier of the plugin.', 'x-found-in': 'path' }, force: { type: 'boolean', description: 'If true, removes the plugin skills from agents that use them and then deletes the plugin. If false and any agent uses the plugin skills, the request returns 409 Conflict with the list of agents.', 'x-found-in': 'query' } }, required: ['pluginId'] },
    },
    {
        name: 'get-agent-builder-plugins-pluginid',
        namespace: 'agent-builder',
        description: 'Get a plugin by id',
        method: 'GET',
        path: '/api/agent_builder/plugins/{pluginId}',
        input: { type: 'object', properties: { pluginId: { type: 'string', description: 'The unique identifier of the plugin.', 'x-found-in': 'path' } }, required: ['pluginId'] },
    },
    {
        name: 'post-agent-builder-plugins-install',
        namespace: 'agent-builder',
        description: 'Install a plugin',
        method: 'POST',
        path: '/api/agent_builder/plugins/install',
        input: { type: 'object', properties: { plugin_name: { description: 'Optional name override for the plugin. Defaults to the manifest name.', 'x-found-in': 'body', type: 'string' }, url: { description: 'URL to install the plugin from (GitHub URL or direct zip URL).', 'x-found-in': 'body', type: 'string' } }, required: ['url'] },
    },
    {
        name: 'get-agent-builder-skills',
        namespace: 'agent-builder',
        description: 'List skills',
        method: 'GET',
        path: '/api/agent_builder/skills',
        input: { type: 'object', properties: { include_plugins: { type: 'boolean', description: 'Set to true to include skills from plugins.', 'x-found-in': 'query' } } },
    },
    {
        name: 'post-agent-builder-skills',
        namespace: 'agent-builder',
        description: 'Create a skill',
        method: 'POST',
        path: '/api/agent_builder/skills',
        input: { type: 'object', properties: { content: { description: 'Skill instructions content (markdown).', 'x-found-in': 'body', type: 'string' }, description: { description: 'Description of what the skill does.', 'x-found-in': 'body', type: 'string' }, id: { description: 'Unique identifier for the skill.', 'x-found-in': 'body', type: 'string' }, name: { description: 'Human-readable name for the skill.', 'x-found-in': 'body', type: 'string' }, referenced_content: { description: '', 'x-found-in': 'body' }, tool_ids: { description: 'Tool IDs from the tool registry that this skill references.', 'x-found-in': 'body' } }, required: ['content', 'description', 'id', 'name'] },
    },
    {
        name: 'delete-agent-builder-skills-skillid',
        namespace: 'agent-builder',
        description: 'Delete a skill',
        method: 'DELETE',
        path: '/api/agent_builder/skills/{skillId}',
        input: { type: 'object', properties: { skillId: { type: 'string', description: 'The unique identifier of the skill.', 'x-found-in': 'path' }, force: { type: 'boolean', description: 'If true, removes the skill from agents that use it and then deletes it. If false and any agent uses the skill, the request returns 409 Conflict with the list of agents.', 'x-found-in': 'query' } }, required: ['skillId'] },
    },
    {
        name: 'get-agent-builder-skills-skillid',
        namespace: 'agent-builder',
        description: 'Get a skill by id',
        method: 'GET',
        path: '/api/agent_builder/skills/{skillId}',
        input: { type: 'object', properties: { skillId: { type: 'string', description: 'The unique identifier of the skill.', 'x-found-in': 'path' } }, required: ['skillId'] },
    },
    {
        name: 'put-agent-builder-skills-skillid',
        namespace: 'agent-builder',
        description: 'Update a skill',
        method: 'PUT',
        path: '/api/agent_builder/skills/{skillId}',
        input: { type: 'object', properties: { skillId: { type: 'string', description: 'The unique identifier of the skill.', 'x-found-in': 'path' }, content: { description: 'Updated skill instructions content.', 'x-found-in': 'body', type: 'string' }, description: { description: 'Updated description.', 'x-found-in': 'body', type: 'string' }, name: { description: 'Updated name for the skill.', 'x-found-in': 'body', type: 'string' }, referenced_content: { description: '', 'x-found-in': 'body' }, tool_ids: { description: 'Updated tool IDs from the tool registry.', 'x-found-in': 'body' } }, required: ['skillId'] },
    },
    {
        name: 'get-agent-builder-tools',
        namespace: 'agent-builder',
        description: 'List tools',
        method: 'GET',
        path: '/api/agent_builder/tools',
    },
    {
        name: 'post-agent-builder-tools',
        namespace: 'agent-builder',
        description: 'Create a tool',
        method: 'POST',
        path: '/api/agent_builder/tools',
        input: { type: 'object', properties: { configuration: { description: 'Tool-specific configuration parameters. See examples for details.', 'x-found-in': 'body', type: 'object' }, description: { description: 'Description of what the tool does.', 'x-found-in': 'body', type: 'string' }, id: { description: 'Unique identifier for the tool.', 'x-found-in': 'body', type: 'string' }, tags: { description: 'Optional tags for categorizing and organizing tools.', 'x-found-in': 'body' }, type: { description: 'The type of tool to create (e.g., esql, index_search).', 'x-found-in': 'body', type: 'string' } }, required: ['configuration', 'id', 'type'] },
    },
    {
        name: 'post-agent-builder-tools-execute',
        namespace: 'agent-builder',
        description: 'Run a tool',
        method: 'POST',
        path: '/api/agent_builder/tools/_execute',
        input: { type: 'object', properties: { connector_id: { description: 'Optional connector ID for tools that require external integrations.', 'x-found-in': 'body', type: 'string' }, tool_id: { description: 'The ID of the tool to execute.', 'x-found-in': 'body', type: 'string' }, tool_params: { description: 'Parameters to pass to the tool execution. See examples for details', 'x-found-in': 'body', type: 'object' } }, required: ['tool_id', 'tool_params'] },
    },
    {
        name: 'delete-agent-builder-tools-toolid',
        namespace: 'agent-builder',
        description: 'Delete a tool',
        method: 'DELETE',
        path: '/api/agent_builder/tools/{toolId}',
        input: { type: 'object', properties: { toolId: { type: 'string', description: 'The unique identifier of the tool to delete.', 'x-found-in': 'path' }, force: { type: 'boolean', description: 'If true, removes the tool from agents that use it and then deletes it. If false and any agent uses the tool, the request returns 409 Conflict with the list of agents.', 'x-found-in': 'query' } }, required: ['toolId'] },
    },
    {
        name: 'get-agent-builder-tools-toolid',
        namespace: 'agent-builder',
        description: 'Get a tool by id',
        method: 'GET',
        path: '/api/agent_builder/tools/{toolId}',
        input: { type: 'object', properties: { toolId: { type: 'string', description: 'The unique identifier of the tool to retrieve.', 'x-found-in': 'path' } }, required: ['toolId'] },
    },
    {
        name: 'put-agent-builder-tools-toolid',
        namespace: 'agent-builder',
        description: 'Update a tool',
        method: 'PUT',
        path: '/api/agent_builder/tools/{toolId}',
        input: { type: 'object', properties: { toolId: { type: 'string', description: 'The unique identifier of the tool to update.', 'x-found-in': 'path' }, configuration: { description: 'Updated tool-specific configuration parameters. See examples for details.', 'x-found-in': 'body', type: 'object' }, description: { description: 'Updated description of what the tool does.', 'x-found-in': 'body', type: 'string' }, tags: { description: 'Updated tags for categorizing and organizing tools.', 'x-found-in': 'body' } }, required: ['toolId'] },
    },
];
//# sourceMappingURL=agent-builder.js.map