/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source open api file,
 * and elastic/elastic-client-generator-js to regenerate this file again.
 */

import type { JsonSchemaObject } from '../../../json-schema.ts'
import type { CloudApiDefinition } from '../types.ts'

import _list_elasticsearch_projectsSchemaRaw from '../../../serverless/json/list_elasticsearch_projects.request.json'
import _create_elasticsearch_projectSchemaRaw from '../../../serverless/json/create_elasticsearch_project.request.json'
import _get_elasticsearch_projectSchemaRaw from '../../../serverless/json/get_elasticsearch_project.request.json'
import _delete_elasticsearch_projectSchemaRaw from '../../../serverless/json/delete_elasticsearch_project.request.json'
import _patch_elasticsearch_projectSchemaRaw from '../../../serverless/json/patch_elasticsearch_project.request.json'
import _reset_elasticsearch_project_credentialsSchemaRaw from '../../../serverless/json/reset_elasticsearch_project_credentials.request.json'
import _resume_elasticsearch_projectSchemaRaw from '../../../serverless/json/resume_elasticsearch_project.request.json'
import _get_elasticsearch_project_rolesSchemaRaw from '../../../serverless/json/get_elasticsearch_project_roles.request.json'
import _get_elasticsearch_project_statusSchemaRaw from '../../../serverless/json/get_elasticsearch_project_status.request.json'

const _list_elasticsearch_projectsSchema = _list_elasticsearch_projectsSchemaRaw as unknown as JsonSchemaObject
const _create_elasticsearch_projectSchema = _create_elasticsearch_projectSchemaRaw as unknown as JsonSchemaObject
const _get_elasticsearch_projectSchema = _get_elasticsearch_projectSchemaRaw as unknown as JsonSchemaObject
const _delete_elasticsearch_projectSchema = _delete_elasticsearch_projectSchemaRaw as unknown as JsonSchemaObject
const _patch_elasticsearch_projectSchema = _patch_elasticsearch_projectSchemaRaw as unknown as JsonSchemaObject
const _reset_elasticsearch_project_credentialsSchema = _reset_elasticsearch_project_credentialsSchemaRaw as unknown as JsonSchemaObject
const _resume_elasticsearch_projectSchema = _resume_elasticsearch_projectSchemaRaw as unknown as JsonSchemaObject
const _get_elasticsearch_project_rolesSchema = _get_elasticsearch_project_rolesSchemaRaw as unknown as JsonSchemaObject
const _get_elasticsearch_project_statusSchema = _get_elasticsearch_project_statusSchemaRaw as unknown as JsonSchemaObject

export const elasticsearchProjectsDefinitions: CloudApiDefinition[] = [
  {
    name: 'list-elasticsearch-projects',
    namespace: 'elasticsearch-projects',
    description: 'Get Elasticsearch projects',
    method: 'GET',
    path: '/api/v1/serverless/projects/elasticsearch',
    destructive: false,
    input: _list_elasticsearch_projectsSchema,
  },
  {
    name: 'create-elasticsearch-project',
    namespace: 'elasticsearch-projects',
    description: 'Create an Elasticsearch project',
    method: 'POST',
    path: '/api/v1/serverless/projects/elasticsearch',
    destructive: true,
    input: _create_elasticsearch_projectSchema,
  },
  {
    name: 'get-elasticsearch-project',
    namespace: 'elasticsearch-projects',
    description: 'Get an Elasticsearch project',
    method: 'GET',
    path: '/api/v1/serverless/projects/elasticsearch/{id}',
    destructive: false,
    input: _get_elasticsearch_projectSchema,
  },
  {
    name: 'delete-elasticsearch-project',
    namespace: 'elasticsearch-projects',
    description: 'Delete an Elasticsearch project',
    method: 'DELETE',
    path: '/api/v1/serverless/projects/elasticsearch/{id}',
    destructive: true,
    input: _delete_elasticsearch_projectSchema,
  },
  {
    name: 'patch-elasticsearch-project',
    namespace: 'elasticsearch-projects',
    description: 'Update an Elasticsearch project',
    method: 'PATCH',
    path: '/api/v1/serverless/projects/elasticsearch/{id}',
    destructive: true,
    input: _patch_elasticsearch_projectSchema,
  },
  {
    name: 'reset-elasticsearch-project-credentials',
    namespace: 'elasticsearch-projects',
    description: 'Reset the project credentials',
    method: 'POST',
    path: '/api/v1/serverless/projects/elasticsearch/{id}/_reset-credentials',
    destructive: true,
    input: _reset_elasticsearch_project_credentialsSchema,
  },
  {
    name: 'resume-elasticsearch-project',
    namespace: 'elasticsearch-projects',
    description: 'Resume Elasticsearch project',
    method: 'POST',
    path: '/api/v1/serverless/projects/elasticsearch/{id}/_resume',
    destructive: true,
    input: _resume_elasticsearch_projectSchema,
  },
  {
    name: 'get-elasticsearch-project-roles',
    namespace: 'elasticsearch-projects',
    description: 'Get roles for an Elasticsearch project',
    method: 'GET',
    path: '/api/v1/serverless/projects/elasticsearch/{id}/roles',
    destructive: false,
    input: _get_elasticsearch_project_rolesSchema,
  },
  {
    name: 'get-elasticsearch-project-status',
    namespace: 'elasticsearch-projects',
    description: 'Get the status of an Elasticsearch project',
    method: 'GET',
    path: '/api/v1/serverless/projects/elasticsearch/{id}/status',
    destructive: false,
    input: _get_elasticsearch_project_statusSchema,
  },
]
