/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source open api file,
 * and elastic/elastic-client-generator-js to regenerate this file again.
 */

import type { JsonSchemaObject } from '../../../json-schema.ts'
import type { CloudApiDefinition } from '../types.ts'

import _list_vector_dbprojectsSchemaRaw from '../../../serverless/json/list_vector_dbprojects.request.json' with { type: 'json' }
import _create_vector_dbprojectSchemaRaw from '../../../serverless/json/create_vector_dbproject.request.json' with { type: 'json' }
import _get_vector_dbprojectSchemaRaw from '../../../serverless/json/get_vector_dbproject.request.json' with { type: 'json' }
import _delete_vector_dbprojectSchemaRaw from '../../../serverless/json/delete_vector_dbproject.request.json' with { type: 'json' }
import _patch_vector_dbprojectSchemaRaw from '../../../serverless/json/patch_vector_dbproject.request.json' with { type: 'json' }
import _get_vector_dbproject_can_deleteSchemaRaw from '../../../serverless/json/get_vector_dbproject_can_delete.request.json' with { type: 'json' }
import _reset_vector_dbproject_credentialsSchemaRaw from '../../../serverless/json/reset_vector_dbproject_credentials.request.json' with { type: 'json' }
import _resume_vector_dbprojectSchemaRaw from '../../../serverless/json/resume_vector_dbproject.request.json' with { type: 'json' }
import _get_vector_dbproject_link_candidatesSchemaRaw from '../../../serverless/json/get_vector_dbproject_link_candidates.request.json' with { type: 'json' }
import _get_vector_dbproject_rolesSchemaRaw from '../../../serverless/json/get_vector_dbproject_roles.request.json' with { type: 'json' }
import _get_vector_dbproject_statusSchemaRaw from '../../../serverless/json/get_vector_dbproject_status.request.json' with { type: 'json' }

const _list_vector_dbprojectsSchema = _list_vector_dbprojectsSchemaRaw as unknown as JsonSchemaObject
const _create_vector_dbprojectSchema = _create_vector_dbprojectSchemaRaw as unknown as JsonSchemaObject
const _get_vector_dbprojectSchema = _get_vector_dbprojectSchemaRaw as unknown as JsonSchemaObject
const _delete_vector_dbprojectSchema = _delete_vector_dbprojectSchemaRaw as unknown as JsonSchemaObject
const _patch_vector_dbprojectSchema = _patch_vector_dbprojectSchemaRaw as unknown as JsonSchemaObject
const _get_vector_dbproject_can_deleteSchema = _get_vector_dbproject_can_deleteSchemaRaw as unknown as JsonSchemaObject
const _reset_vector_dbproject_credentialsSchema = _reset_vector_dbproject_credentialsSchemaRaw as unknown as JsonSchemaObject
const _resume_vector_dbprojectSchema = _resume_vector_dbprojectSchemaRaw as unknown as JsonSchemaObject
const _get_vector_dbproject_link_candidatesSchema = _get_vector_dbproject_link_candidatesSchemaRaw as unknown as JsonSchemaObject
const _get_vector_dbproject_rolesSchema = _get_vector_dbproject_rolesSchemaRaw as unknown as JsonSchemaObject
const _get_vector_dbproject_statusSchema = _get_vector_dbproject_statusSchemaRaw as unknown as JsonSchemaObject

export const vectordbProjectsDefinitions: CloudApiDefinition[] = [
  {
    name: 'list-vector-dbprojects',
    namespace: 'vectordb-projects',
    description: 'Get VectorDB projects',
    method: 'GET',
    path: '/api/v1/serverless/projects/vectordb',
    destructive: false,
    input: _list_vector_dbprojectsSchema,
  },
  {
    name: 'create-vector-dbproject',
    namespace: 'vectordb-projects',
    description: 'Create a VectorDB project',
    method: 'POST',
    path: '/api/v1/serverless/projects/vectordb',
    destructive: true,
    input: _create_vector_dbprojectSchema,
  },
  {
    name: 'get-vector-dbproject',
    namespace: 'vectordb-projects',
    description: 'Get a VectorDB project',
    method: 'GET',
    path: '/api/v1/serverless/projects/vectordb/{id}',
    destructive: false,
    input: _get_vector_dbprojectSchema,
  },
  {
    name: 'delete-vector-dbproject',
    namespace: 'vectordb-projects',
    description: 'Delete a VectorDB project',
    method: 'DELETE',
    path: '/api/v1/serverless/projects/vectordb/{id}',
    destructive: true,
    input: _delete_vector_dbprojectSchema,
  },
  {
    name: 'patch-vector-dbproject',
    namespace: 'vectordb-projects',
    description: 'Update a VectorDB project',
    method: 'PATCH',
    path: '/api/v1/serverless/projects/vectordb/{id}',
    destructive: true,
    input: _patch_vector_dbprojectSchema,
  },
  {
    name: 'get-vector-dbproject-can-delete',
    namespace: 'vectordb-projects',
    description: 'Get VectorDB project delete status',
    method: 'GET',
    path: '/api/v1/serverless/projects/vectordb/{id}/_can-delete',
    destructive: false,
    input: _get_vector_dbproject_can_deleteSchema,
  },
  {
    name: 'reset-vector-dbproject-credentials',
    namespace: 'vectordb-projects',
    description: 'Reset the project credentials',
    method: 'POST',
    path: '/api/v1/serverless/projects/vectordb/{id}/_reset-credentials',
    destructive: true,
    input: _reset_vector_dbproject_credentialsSchema,
  },
  {
    name: 'resume-vector-dbproject',
    namespace: 'vectordb-projects',
    description: 'Resume VectorDB project',
    method: 'POST',
    path: '/api/v1/serverless/projects/vectordb/{id}/_resume',
    destructive: true,
    input: _resume_vector_dbprojectSchema,
  },
  {
    name: 'get-vector-dbproject-link-candidates',
    namespace: 'vectordb-projects',
    description: 'Get VectorDB project link candidates',
    method: 'GET',
    path: '/api/v1/serverless/projects/vectordb/{id}/link-candidates',
    destructive: false,
    input: _get_vector_dbproject_link_candidatesSchema,
  },
  {
    name: 'get-vector-dbproject-roles',
    namespace: 'vectordb-projects',
    description: 'Get roles for a VectorDB project',
    method: 'GET',
    path: '/api/v1/serverless/projects/vectordb/{id}/roles',
    destructive: false,
    input: _get_vector_dbproject_rolesSchema,
  },
  {
    name: 'get-vector-dbproject-status',
    namespace: 'vectordb-projects',
    description: 'Get the status of a VectorDB project',
    method: 'GET',
    path: '/api/v1/serverless/projects/vectordb/{id}/status',
    destructive: false,
    input: _get_vector_dbproject_statusSchema,
  },
]
