/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */
/*
 * This file was automatically generated by elastic/elastic-client-generator-js.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source open api file,
 * and elastic/elastic-client-generator-js to regenerate this file again.
 */
/* eslint-disable @typescript-eslint/no-redeclare */
import { z } from 'zod';
export const CreateSnapshotDependencyResponse = z.object({
    message: z.string()
}).meta({ id: 'CreateSnapshotDependencyResponse' });
export const CreateSnapshotDependencyRequest = z.object({
    source_deployment_id: z.string()
}).meta({ id: 'CreateSnapshotDependencyRequest' });
//# sourceMappingURL=create_deployment_es_resource_snapshot_repository.js.map