/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */
/*
 * This file was automatically generated by elastic/elastic-client-generator-js.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source open api file,
 * and elastic/elastic-client-generator-js to regenerate this file again.
 */
/* eslint-disable @typescript-eslint/no-redeclare */
import { z } from 'zod';
export const TierInfo = z.object({
    memory_size: z.number().optional(),
    zone_count: z.number().optional(),
    available_sizes: z.array(z.number()).optional()
}).meta({ id: 'TierInfo' });
export const TiersResponse = z.object({
    hot_content: TierInfo.optional(),
    warm: TierInfo.optional(),
    cold: TierInfo.optional(),
    frozen: TierInfo.optional(),
    master: TierInfo.optional(),
    coordinating: TierInfo.optional(),
    ml: TierInfo.optional()
}).meta({ id: 'TiersResponse' });
//# sourceMappingURL=get_deployment_es_resource_tiers.js.map