/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */
/*
 * This file was automatically generated by elastic/elastic-client-generator-js.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source open api file,
 * and elastic/elastic-client-generator-js to regenerate this file again.
 */
/* eslint-disable @typescript-eslint/no-redeclare */
import { z } from 'zod';
export const ReadOnlyResponse = z.object({
    enabled: z.boolean()
}).meta({ id: 'ReadOnlyResponse' });
//# sourceMappingURL=get_appsearch_read_only_mode.js.map