import { z } from 'zod';
export declare const ProjectRoleAssignment: z.ZodObject<{
    role_id: z.ZodString;
    organization_id: z.ZodString;
    all: z.ZodOptional<z.ZodBoolean>;
    project_ids: z.ZodOptional<z.ZodArray<z.ZodString>>;
    application_roles: z.ZodOptional<z.ZodArray<z.ZodString>>;
}, z.core.$strip>;
export type ProjectRoleAssignment = z.infer<typeof ProjectRoleAssignment>;
export declare const DeploymentRoleAssignment: z.ZodObject<{
    role_id: z.ZodString;
    organization_id: z.ZodString;
    all: z.ZodOptional<z.ZodBoolean>;
    deployment_ids: z.ZodOptional<z.ZodArray<z.ZodString>>;
    application_roles: z.ZodOptional<z.ZodArray<z.ZodString>>;
}, z.core.$strip>;
export type DeploymentRoleAssignment = z.infer<typeof DeploymentRoleAssignment>;
export declare const OrganizationRoleAssignment: z.ZodObject<{
    role_id: z.ZodString;
    organization_id: z.ZodString;
    application_roles: z.ZodOptional<z.ZodArray<z.ZodString>>;
}, z.core.$strip>;
export type OrganizationRoleAssignment = z.infer<typeof OrganizationRoleAssignment>;
export declare const PlatformRoleAssignment: z.ZodObject<{
    role_id: z.ZodString;
}, z.core.$strip>;
export type PlatformRoleAssignment = z.infer<typeof PlatformRoleAssignment>;
export declare const ProjectRoleAssignments: z.ZodObject<{
    elasticsearch: z.ZodOptional<z.ZodArray<z.ZodObject<{
        role_id: z.ZodString;
        organization_id: z.ZodString;
        all: z.ZodOptional<z.ZodBoolean>;
        project_ids: z.ZodOptional<z.ZodArray<z.ZodString>>;
        application_roles: z.ZodOptional<z.ZodArray<z.ZodString>>;
    }, z.core.$strip>>>;
    observability: z.ZodOptional<z.ZodArray<z.ZodObject<{
        role_id: z.ZodString;
        organization_id: z.ZodString;
        all: z.ZodOptional<z.ZodBoolean>;
        project_ids: z.ZodOptional<z.ZodArray<z.ZodString>>;
        application_roles: z.ZodOptional<z.ZodArray<z.ZodString>>;
    }, z.core.$strip>>>;
    security: z.ZodOptional<z.ZodArray<z.ZodObject<{
        role_id: z.ZodString;
        organization_id: z.ZodString;
        all: z.ZodOptional<z.ZodBoolean>;
        project_ids: z.ZodOptional<z.ZodArray<z.ZodString>>;
        application_roles: z.ZodOptional<z.ZodArray<z.ZodString>>;
    }, z.core.$strip>>>;
    workplaceai: z.ZodOptional<z.ZodArray<z.ZodObject<{
        role_id: z.ZodString;
        organization_id: z.ZodString;
        all: z.ZodOptional<z.ZodBoolean>;
        project_ids: z.ZodOptional<z.ZodArray<z.ZodString>>;
        application_roles: z.ZodOptional<z.ZodArray<z.ZodString>>;
    }, z.core.$strip>>>;
}, z.core.$strip>;
export type ProjectRoleAssignments = z.infer<typeof ProjectRoleAssignments>;
export declare const RoleAssignments: z.ZodObject<{
    platform: z.ZodOptional<z.ZodArray<z.ZodObject<{
        role_id: z.ZodString;
    }, z.core.$strip>>>;
    organization: z.ZodOptional<z.ZodArray<z.ZodObject<{
        role_id: z.ZodString;
        organization_id: z.ZodString;
        application_roles: z.ZodOptional<z.ZodArray<z.ZodString>>;
    }, z.core.$strip>>>;
    deployment: z.ZodOptional<z.ZodArray<z.ZodObject<{
        role_id: z.ZodString;
        organization_id: z.ZodString;
        all: z.ZodOptional<z.ZodBoolean>;
        deployment_ids: z.ZodOptional<z.ZodArray<z.ZodString>>;
        application_roles: z.ZodOptional<z.ZodArray<z.ZodString>>;
    }, z.core.$strip>>>;
    project: z.ZodOptional<z.ZodObject<{
        elasticsearch: z.ZodOptional<z.ZodArray<z.ZodObject<{
            role_id: z.ZodString;
            organization_id: z.ZodString;
            all: z.ZodOptional<z.ZodBoolean>;
            project_ids: z.ZodOptional<z.ZodArray<z.ZodString>>;
            application_roles: z.ZodOptional<z.ZodArray<z.ZodString>>;
        }, z.core.$strip>>>;
        observability: z.ZodOptional<z.ZodArray<z.ZodObject<{
            role_id: z.ZodString;
            organization_id: z.ZodString;
            all: z.ZodOptional<z.ZodBoolean>;
            project_ids: z.ZodOptional<z.ZodArray<z.ZodString>>;
            application_roles: z.ZodOptional<z.ZodArray<z.ZodString>>;
        }, z.core.$strip>>>;
        security: z.ZodOptional<z.ZodArray<z.ZodObject<{
            role_id: z.ZodString;
            organization_id: z.ZodString;
            all: z.ZodOptional<z.ZodBoolean>;
            project_ids: z.ZodOptional<z.ZodArray<z.ZodString>>;
            application_roles: z.ZodOptional<z.ZodArray<z.ZodString>>;
        }, z.core.$strip>>>;
        workplaceai: z.ZodOptional<z.ZodArray<z.ZodObject<{
            role_id: z.ZodString;
            organization_id: z.ZodString;
            all: z.ZodOptional<z.ZodBoolean>;
            project_ids: z.ZodOptional<z.ZodArray<z.ZodString>>;
            application_roles: z.ZodOptional<z.ZodArray<z.ZodString>>;
        }, z.core.$strip>>>;
    }, z.core.$strip>>;
}, z.core.$strip>;
export type RoleAssignments = z.infer<typeof RoleAssignments>;
export declare const ApiKeyResponse: z.ZodObject<{
    id: z.ZodString;
    user_id: z.ZodOptional<z.ZodString>;
    organization_id: z.ZodOptional<z.ZodString>;
    description: z.ZodString;
    key: z.ZodOptional<z.ZodString>;
    creation_date: z.ZodString;
    expiration_date: z.ZodOptional<z.ZodString>;
    role_assignments: z.ZodOptional<z.ZodObject<{
        platform: z.ZodOptional<z.ZodArray<z.ZodObject<{
            role_id: z.ZodString;
        }, z.core.$strip>>>;
        organization: z.ZodOptional<z.ZodArray<z.ZodObject<{
            role_id: z.ZodString;
            organization_id: z.ZodString;
            application_roles: z.ZodOptional<z.ZodArray<z.ZodString>>;
        }, z.core.$strip>>>;
        deployment: z.ZodOptional<z.ZodArray<z.ZodObject<{
            role_id: z.ZodString;
            organization_id: z.ZodString;
            all: z.ZodOptional<z.ZodBoolean>;
            deployment_ids: z.ZodOptional<z.ZodArray<z.ZodString>>;
            application_roles: z.ZodOptional<z.ZodArray<z.ZodString>>;
        }, z.core.$strip>>>;
        project: z.ZodOptional<z.ZodObject<{
            elasticsearch: z.ZodOptional<z.ZodArray<z.ZodObject<{
                role_id: z.ZodString;
                organization_id: z.ZodString;
                all: z.ZodOptional<z.ZodBoolean>;
                project_ids: z.ZodOptional<z.ZodArray<z.ZodString>>;
                application_roles: z.ZodOptional<z.ZodArray<z.ZodString>>;
            }, z.core.$strip>>>;
            observability: z.ZodOptional<z.ZodArray<z.ZodObject<{
                role_id: z.ZodString;
                organization_id: z.ZodString;
                all: z.ZodOptional<z.ZodBoolean>;
                project_ids: z.ZodOptional<z.ZodArray<z.ZodString>>;
                application_roles: z.ZodOptional<z.ZodArray<z.ZodString>>;
            }, z.core.$strip>>>;
            security: z.ZodOptional<z.ZodArray<z.ZodObject<{
                role_id: z.ZodString;
                organization_id: z.ZodString;
                all: z.ZodOptional<z.ZodBoolean>;
                project_ids: z.ZodOptional<z.ZodArray<z.ZodString>>;
                application_roles: z.ZodOptional<z.ZodArray<z.ZodString>>;
            }, z.core.$strip>>>;
            workplaceai: z.ZodOptional<z.ZodArray<z.ZodObject<{
                role_id: z.ZodString;
                organization_id: z.ZodString;
                all: z.ZodOptional<z.ZodBoolean>;
                project_ids: z.ZodOptional<z.ZodArray<z.ZodString>>;
                application_roles: z.ZodOptional<z.ZodArray<z.ZodString>>;
            }, z.core.$strip>>>;
        }, z.core.$strip>>;
    }, z.core.$strip>>;
}, z.core.$strip>;
export type ApiKeyResponse = z.infer<typeof ApiKeyResponse>;
export declare const ApiKeysResponse: z.ZodObject<{
    keys: z.ZodArray<z.ZodObject<{
        id: z.ZodString;
        user_id: z.ZodOptional<z.ZodString>;
        organization_id: z.ZodOptional<z.ZodString>;
        description: z.ZodString;
        key: z.ZodOptional<z.ZodString>;
        creation_date: z.ZodString;
        expiration_date: z.ZodOptional<z.ZodString>;
        role_assignments: z.ZodOptional<z.ZodObject<{
            platform: z.ZodOptional<z.ZodArray<z.ZodObject<{
                role_id: z.ZodString;
            }, z.core.$strip>>>;
            organization: z.ZodOptional<z.ZodArray<z.ZodObject<{
                role_id: z.ZodString;
                organization_id: z.ZodString;
                application_roles: z.ZodOptional<z.ZodArray<z.ZodString>>;
            }, z.core.$strip>>>;
            deployment: z.ZodOptional<z.ZodArray<z.ZodObject<{
                role_id: z.ZodString;
                organization_id: z.ZodString;
                all: z.ZodOptional<z.ZodBoolean>;
                deployment_ids: z.ZodOptional<z.ZodArray<z.ZodString>>;
                application_roles: z.ZodOptional<z.ZodArray<z.ZodString>>;
            }, z.core.$strip>>>;
            project: z.ZodOptional<z.ZodObject<{
                elasticsearch: z.ZodOptional<z.ZodArray<z.ZodObject<{
                    role_id: z.ZodString;
                    organization_id: z.ZodString;
                    all: z.ZodOptional<z.ZodBoolean>;
                    project_ids: z.ZodOptional<z.ZodArray<z.ZodString>>;
                    application_roles: z.ZodOptional<z.ZodArray<z.ZodString>>;
                }, z.core.$strip>>>;
                observability: z.ZodOptional<z.ZodArray<z.ZodObject<{
                    role_id: z.ZodString;
                    organization_id: z.ZodString;
                    all: z.ZodOptional<z.ZodBoolean>;
                    project_ids: z.ZodOptional<z.ZodArray<z.ZodString>>;
                    application_roles: z.ZodOptional<z.ZodArray<z.ZodString>>;
                }, z.core.$strip>>>;
                security: z.ZodOptional<z.ZodArray<z.ZodObject<{
                    role_id: z.ZodString;
                    organization_id: z.ZodString;
                    all: z.ZodOptional<z.ZodBoolean>;
                    project_ids: z.ZodOptional<z.ZodArray<z.ZodString>>;
                    application_roles: z.ZodOptional<z.ZodArray<z.ZodString>>;
                }, z.core.$strip>>>;
                workplaceai: z.ZodOptional<z.ZodArray<z.ZodObject<{
                    role_id: z.ZodString;
                    organization_id: z.ZodString;
                    all: z.ZodOptional<z.ZodBoolean>;
                    project_ids: z.ZodOptional<z.ZodArray<z.ZodString>>;
                    application_roles: z.ZodOptional<z.ZodArray<z.ZodString>>;
                }, z.core.$strip>>>;
            }, z.core.$strip>>;
        }, z.core.$strip>>;
    }, z.core.$strip>>;
    next_page: z.ZodOptional<z.ZodString>;
}, z.core.$strip>;
export type ApiKeysResponse = z.infer<typeof ApiKeysResponse>;
//# sourceMappingURL=get_api_keys.d.ts.map