/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */
/*
 * This file was automatically generated by elastic/elastic-client-generator-js.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source open api file,
 * and elastic/elastic-client-generator-js to regenerate this file again.
 */
/* eslint-disable @typescript-eslint/no-redeclare */
import { z } from 'zod';
export const TrafficFilterClaimedLinkIdInfo = z.object({
    link_id: z.string().optional(),
    azure_endpoint_name: z.string().optional(),
    azure_endpoint_guid: z.string().optional(),
    region: z.string()
}).meta({ id: 'TrafficFilterClaimedLinkIdInfo' });
export const TrafficFilterClaimedLinkIds = z.object({
    claimed_link_ids: z.array(TrafficFilterClaimedLinkIdInfo)
}).meta({ id: 'TrafficFilterClaimedLinkIds' });
//# sourceMappingURL=get_traffic_filter_claimed_link_ids.js.map