/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */
/*
 * This file was automatically generated by elastic/elastic-client-generator-js.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source open api file,
 * and elastic/elastic-client-generator-js to regenerate this file again.
 */
/* eslint-disable @typescript-eslint/no-redeclare */
import { z } from 'zod';
export const ProjectRoleAssignment = z.object({
    role_id: z.string(),
    organization_id: z.string(),
    all: z.boolean().optional(),
    project_ids: z.array(z.string()).optional(),
    application_roles: z.array(z.string()).optional()
}).meta({ id: 'ProjectRoleAssignment' });
export const DeploymentRoleAssignment = z.object({
    role_id: z.string(),
    organization_id: z.string(),
    all: z.boolean().optional(),
    deployment_ids: z.array(z.string()).optional(),
    application_roles: z.array(z.string()).optional()
}).meta({ id: 'DeploymentRoleAssignment' });
export const OrganizationRoleAssignment = z.object({
    role_id: z.string(),
    organization_id: z.string(),
    application_roles: z.array(z.string()).optional()
}).meta({ id: 'OrganizationRoleAssignment' });
export const PlatformRoleAssignment = z.object({
    role_id: z.string()
}).meta({ id: 'PlatformRoleAssignment' });
export const ProjectRoleAssignments = z.object({
    elasticsearch: z.array(ProjectRoleAssignment).optional(),
    observability: z.array(ProjectRoleAssignment).optional(),
    security: z.array(ProjectRoleAssignment).optional(),
    workplaceai: z.array(ProjectRoleAssignment).optional()
}).meta({ id: 'ProjectRoleAssignments' });
export const RoleAssignments = z.object({
    platform: z.array(PlatformRoleAssignment).optional(),
    organization: z.array(OrganizationRoleAssignment).optional(),
    deployment: z.array(DeploymentRoleAssignment).optional(),
    project: ProjectRoleAssignments.optional()
}).meta({ id: 'RoleAssignments' });
export const OrganizationMembership = z.object({
    organization_id: z.string(),
    user_id: z.string(),
    name: z.string().optional(),
    email: z.string().optional(),
    member_since: z.string(),
    role_assignments: RoleAssignments.optional()
}).meta({ id: 'OrganizationMembership' });
export const OrganizationMemberships = z.object({
    members: z.array(OrganizationMembership)
}).meta({ id: 'OrganizationMemberships' });
//# sourceMappingURL=list_organization_members.js.map