/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */
export const esManifest = [
    { id: 'async-search.delete', name: 'delete', namespace: 'async-search', description: 'Delete an async search.', namespaceFile: 'async_search_delete' },
    { id: 'async-search.get', name: 'get', namespace: 'async-search', description: 'Get async search results.', namespaceFile: 'async_search_get' },
    { id: 'async-search.status', name: 'status', namespace: 'async-search', description: 'Get the async search status.', namespaceFile: 'async_search_status' },
    { id: 'async-search.submit', name: 'submit', namespace: 'async-search', description: 'Run an async search.', namespaceFile: 'async_search_submit' },
    { id: 'bulk', name: 'bulk', namespace: null, description: 'Bulk index or delete documents.', namespaceFile: 'bulk' },
    { id: 'cancel_reindex', name: 'cancel-reindex', namespace: null, description: 'Cancel an ongoing reindex task.', namespaceFile: 'cancel_reindex' },
    { id: 'cat.aliases', name: 'aliases', namespace: 'cat', description: 'Get aliases.', namespaceFile: 'cat_aliases' },
    { id: 'cat.allocation', name: 'allocation', namespace: 'cat', description: 'Get shard allocation information.', namespaceFile: 'cat_allocation' },
    { id: 'cat.circuit_breaker', name: 'circuit-breaker', namespace: 'cat', description: 'Get circuit breakers statistics.', namespaceFile: 'cat_circuit_breaker' },
    { id: 'cat.component_templates', name: 'component-templates', namespace: 'cat', description: 'Get component templates.', namespaceFile: 'cat_component_templates' },
    { id: 'cat.count', name: 'count', namespace: 'cat', description: 'Get a document count.', namespaceFile: 'cat_count' },
    { id: 'cat.fielddata', name: 'fielddata', namespace: 'cat', description: 'Get field data cache information.', namespaceFile: 'cat_fielddata' },
    { id: 'cat.health', name: 'health', namespace: 'cat', description: 'Get the cluster health status.', namespaceFile: 'cat_health' },
    { id: 'cat.help', name: 'help', namespace: 'cat', description: 'Get CAT help.', namespaceFile: 'cat_help' },
    { id: 'cat.indices', name: 'indices', namespace: 'cat', description: 'Get index information.', namespaceFile: 'cat_indices' },
    { id: 'cat.master', name: 'master', namespace: 'cat', description: 'Get master node information.', namespaceFile: 'cat_master' },
    { id: 'cat.ml_data_frame_analytics', name: 'ml-data-frame-analytics', namespace: 'cat', description: 'Get data frame analytics jobs.', namespaceFile: 'cat_ml_data_frame_analytics' },
    { id: 'cat.ml_datafeeds', name: 'ml-datafeeds', namespace: 'cat', description: 'Get datafeeds.', namespaceFile: 'cat_ml_datafeeds' },
    { id: 'cat.ml_jobs', name: 'ml-jobs', namespace: 'cat', description: 'Get anomaly detection jobs.', namespaceFile: 'cat_ml_jobs' },
    { id: 'cat.ml_trained_models', name: 'ml-trained-models', namespace: 'cat', description: 'Get trained models.', namespaceFile: 'cat_ml_trained_models' },
    { id: 'cat.nodeattrs', name: 'nodeattrs', namespace: 'cat', description: 'Get node attribute information.', namespaceFile: 'cat_nodeattrs' },
    { id: 'cat.nodes', name: 'nodes', namespace: 'cat', description: 'Get node information.', namespaceFile: 'cat_nodes' },
    { id: 'cat.pending_tasks', name: 'pending-tasks', namespace: 'cat', description: 'Get pending task information.', namespaceFile: 'cat_pending_tasks' },
    { id: 'cat.plugins', name: 'plugins', namespace: 'cat', description: 'Get plugin information.', namespaceFile: 'cat_plugins' },
    { id: 'cat.recovery', name: 'recovery', namespace: 'cat', description: 'Get shard recovery information.', namespaceFile: 'cat_recovery' },
    { id: 'cat.repositories', name: 'repositories', namespace: 'cat', description: 'Get snapshot repository information.', namespaceFile: 'cat_repositories' },
    { id: 'cat.segments', name: 'segments', namespace: 'cat', description: 'Get segment information.', namespaceFile: 'cat_segments' },
    { id: 'cat.shards', name: 'shards', namespace: 'cat', description: 'Get shard information.', namespaceFile: 'cat_shards' },
    { id: 'cat.snapshots', name: 'snapshots', namespace: 'cat', description: 'Get snapshot information.', namespaceFile: 'cat_snapshots' },
    { id: 'cat.tasks', name: 'tasks', namespace: 'cat', description: 'Get task information.', namespaceFile: 'cat_tasks' },
    { id: 'cat.templates', name: 'templates', namespace: 'cat', description: 'Get index template information.', namespaceFile: 'cat_templates' },
    { id: 'cat.thread_pool', name: 'thread-pool', namespace: 'cat', description: 'Get thread pool statistics.', namespaceFile: 'cat_thread_pool' },
    { id: 'cat.transforms', name: 'transforms', namespace: 'cat', description: 'Get transform information.', namespaceFile: 'cat_transforms' },
    { id: 'ccr.delete_auto_follow_pattern', name: 'delete-auto-follow-pattern', namespace: 'ccr', description: 'Delete auto-follow patterns.', namespaceFile: 'ccr_delete_auto_follow_pattern' },
    { id: 'ccr.follow', name: 'follow', namespace: 'ccr', description: 'Create a follower.', namespaceFile: 'ccr_follow' },
    { id: 'ccr.follow_info', name: 'follow-info', namespace: 'ccr', description: 'Get follower information.', namespaceFile: 'ccr_follow_info' },
    { id: 'ccr.follow_stats', name: 'follow-stats', namespace: 'ccr', description: 'Get follower stats.', namespaceFile: 'ccr_follow_stats' },
    { id: 'ccr.forget_follower', name: 'forget-follower', namespace: 'ccr', description: 'Forget a follower.', namespaceFile: 'ccr_forget_follower' },
    { id: 'ccr.get_auto_follow_pattern', name: 'get-auto-follow-pattern', namespace: 'ccr', description: 'Get auto-follow patterns.', namespaceFile: 'ccr_get_auto_follow_pattern' },
    { id: 'ccr.pause_auto_follow_pattern', name: 'pause-auto-follow-pattern', namespace: 'ccr', description: 'Pause an auto-follow pattern.', namespaceFile: 'ccr_pause_auto_follow_pattern' },
    { id: 'ccr.pause_follow', name: 'pause-follow', namespace: 'ccr', description: 'Pause a follower.', namespaceFile: 'ccr_pause_follow' },
    { id: 'ccr.put_auto_follow_pattern', name: 'put-auto-follow-pattern', namespace: 'ccr', description: 'Create or update auto-follow patterns.', namespaceFile: 'ccr_put_auto_follow_pattern' },
    { id: 'ccr.resume_auto_follow_pattern', name: 'resume-auto-follow-pattern', namespace: 'ccr', description: 'Resume an auto-follow pattern.', namespaceFile: 'ccr_resume_auto_follow_pattern' },
    { id: 'ccr.resume_follow', name: 'resume-follow', namespace: 'ccr', description: 'Resume a follower.', namespaceFile: 'ccr_resume_follow' },
    { id: 'ccr.stats', name: 'stats', namespace: 'ccr', description: 'Get cross-cluster replication stats.', namespaceFile: 'ccr_stats' },
    { id: 'ccr.unfollow', name: 'unfollow', namespace: 'ccr', description: 'Unfollow an index.', namespaceFile: 'ccr_unfollow' },
    { id: 'clear_scroll', name: 'clear-scroll', namespace: null, description: 'Clear a scrolling search.', namespaceFile: 'clear_scroll' },
    { id: 'close_point_in_time', name: 'close-point-in-time', namespace: null, description: 'Close a point in time.', namespaceFile: 'close_point_in_time' },
    { id: 'cluster.allocation_explain', name: 'allocation-explain', namespace: 'cluster', description: 'Explain the shard allocations.', namespaceFile: 'cluster_allocation_explain' },
    { id: 'cluster.delete_component_template', name: 'delete-component-template', namespace: 'cluster', description: 'Delete component templates.', namespaceFile: 'cluster_delete_component_template' },
    { id: 'cluster.delete_voting_config_exclusions', name: 'delete-voting-config-exclusions', namespace: 'cluster', description: 'Clear cluster voting config exclusions.', namespaceFile: 'cluster_delete_voting_config_exclusions' },
    { id: 'cluster.exists_component_template', name: 'exists-component-template', namespace: 'cluster', description: 'Check component templates.', namespaceFile: 'cluster_exists_component_template' },
    { id: 'cluster.get_component_template', name: 'get-component-template', namespace: 'cluster', description: 'Get component templates.', namespaceFile: 'cluster_get_component_template' },
    { id: 'cluster.get_settings', name: 'get-settings', namespace: 'cluster', description: 'Get cluster-wide settings.', namespaceFile: 'cluster_get_settings' },
    { id: 'cluster.health', name: 'health', namespace: 'cluster', description: 'Get the cluster health status.', namespaceFile: 'cluster_health' },
    { id: 'cluster.info', name: 'info', namespace: 'cluster', description: 'Get cluster info.', namespaceFile: 'cluster_info' },
    { id: 'cluster.pending_tasks', name: 'pending-tasks', namespace: 'cluster', description: 'Get the pending cluster tasks.', namespaceFile: 'cluster_pending_tasks' },
    { id: 'cluster.post_voting_config_exclusions', name: 'post-voting-config-exclusions', namespace: 'cluster', description: 'Update voting configuration exclusions.', namespaceFile: 'cluster_post_voting_config_exclusions' },
    { id: 'cluster.put_component_template', name: 'put-component-template', namespace: 'cluster', description: 'Create or update a component template.', namespaceFile: 'cluster_put_component_template' },
    { id: 'cluster.put_settings', name: 'put-settings', namespace: 'cluster', description: 'Update the cluster settings.', namespaceFile: 'cluster_put_settings' },
    { id: 'cluster.remote_info', name: 'remote-info', namespace: 'cluster', description: 'Get remote cluster information.', namespaceFile: 'cluster_remote_info' },
    { id: 'cluster.reroute', name: 'reroute', namespace: 'cluster', description: 'Reroute the cluster.', namespaceFile: 'cluster_reroute' },
    { id: 'cluster.state', name: 'state', namespace: 'cluster', description: 'Get the cluster state.', namespaceFile: 'cluster_state' },
    { id: 'cluster.stats', name: 'stats', namespace: 'cluster', description: 'Get cluster statistics.', namespaceFile: 'cluster.stats' },
    { id: 'connector.check_in', name: 'check-in', namespace: 'connector', description: 'Check in a connector.', namespaceFile: 'connector_check_in' },
    { id: 'connector.delete', name: 'delete', namespace: 'connector', description: 'Delete a connector.', namespaceFile: 'connector_delete' },
    { id: 'connector.get', name: 'get', namespace: 'connector', description: 'Get a connector.', namespaceFile: 'connector_get' },
    { id: 'connector.list', name: 'list', namespace: 'connector', description: 'Get all connectors.', namespaceFile: 'connector_list' },
    { id: 'connector.post', name: 'post', namespace: 'connector', description: 'Create a connector.', namespaceFile: 'connector_post' },
    { id: 'connector.put', name: 'put', namespace: 'connector', description: 'Create or update a connector.', namespaceFile: 'connector_put' },
    { id: 'connector.sync_job_cancel', name: 'sync-job-cancel', namespace: 'connector', description: 'Cancel a connector sync job.', namespaceFile: 'connector_sync_job_cancel' },
    { id: 'connector.sync_job_check_in', name: 'sync-job-check-in', namespace: 'connector', description: 'Check in a connector sync job.', namespaceFile: 'connector_sync_job_check_in' },
    { id: 'connector.sync_job_claim', name: 'sync-job-claim', namespace: 'connector', description: 'Claim a connector sync job.', namespaceFile: 'connector_sync_job_claim' },
    { id: 'connector.sync_job_delete', name: 'sync-job-delete', namespace: 'connector', description: 'Delete a connector sync job.', namespaceFile: 'connector_sync_job_delete' },
    { id: 'connector.sync_job_error', name: 'sync-job-error', namespace: 'connector', description: 'Set a connector sync job error.', namespaceFile: 'connector_sync_job_error' },
    { id: 'connector.sync_job_get', name: 'sync-job-get', namespace: 'connector', description: 'Get a connector sync job.', namespaceFile: 'connector_sync_job_get' },
    { id: 'connector.sync_job_list', name: 'sync-job-list', namespace: 'connector', description: 'Get all connector sync jobs.', namespaceFile: 'connector_sync_job_list' },
    { id: 'connector.sync_job_post', name: 'sync-job-post', namespace: 'connector', description: 'Create a connector sync job.', namespaceFile: 'connector_sync_job_post' },
    { id: 'connector.sync_job_update_stats', name: 'sync-job-update-stats', namespace: 'connector', description: 'Set the connector sync job stats.', namespaceFile: 'connector_sync_job_update_stats' },
    { id: 'connector.update_active_filtering', name: 'update-active-filtering', namespace: 'connector', description: 'Activate the connector draft filter.', namespaceFile: 'connector_update_active_filtering' },
    { id: 'connector.update_api_key_id', name: 'update-api-key-id', namespace: 'connector', description: 'Update the connector API key ID.', namespaceFile: 'connector_update_api_key_id' },
    { id: 'connector.update_configuration', name: 'update-configuration', namespace: 'connector', description: 'Update the connector configuration.', namespaceFile: 'connector_update_configuration' },
    { id: 'connector.update_error', name: 'update-error', namespace: 'connector', description: 'Update the connector error field.', namespaceFile: 'connector_update_error' },
    { id: 'connector.update_features', name: 'update-features', namespace: 'connector', description: 'Update the connector features.', namespaceFile: 'connector_update_features' },
    { id: 'connector.update_filtering', name: 'update-filtering', namespace: 'connector', description: 'Update the connector filtering.', namespaceFile: 'connector_update_filtering' },
    { id: 'connector.update_filtering_validation', name: 'update-filtering-validation', namespace: 'connector', description: 'Update the connector draft filtering validation.', namespaceFile: 'connector_update_filtering_validation' },
    { id: 'connector.update_index_name', name: 'update-index-name', namespace: 'connector', description: 'Update the connector index name.', namespaceFile: 'connector_update_index_name' },
    { id: 'connector.update_name', name: 'update-name', namespace: 'connector', description: 'Update the connector name and description.', namespaceFile: 'connector_update_name' },
    { id: 'connector.update_native', name: 'update-native', namespace: 'connector', description: 'Update the connector is_native flag.', namespaceFile: 'connector_update_native' },
    { id: 'connector.update_pipeline', name: 'update-pipeline', namespace: 'connector', description: 'Update the connector pipeline.', namespaceFile: 'connector_update_pipeline' },
    { id: 'connector.update_scheduling', name: 'update-scheduling', namespace: 'connector', description: 'Update the connector scheduling.', namespaceFile: 'connector_update_scheduling' },
    { id: 'connector.update_service_type', name: 'update-service-type', namespace: 'connector', description: 'Update the connector service type.', namespaceFile: 'connector_update_service_type' },
    { id: 'connector.update_status', name: 'update-status', namespace: 'connector', description: 'Update the connector status.', namespaceFile: 'connector_update_status' },
    { id: 'count', name: 'count', namespace: null, description: 'Count search results.', namespaceFile: 'count' },
    { id: 'create', name: 'create', namespace: null, description: 'Create a new document in the index.', namespaceFile: 'create' },
    { id: 'dangling-indices.delete_dangling_index', name: 'delete-dangling-index', namespace: 'dangling-indices', description: 'Delete a dangling index.', namespaceFile: 'dangling_indices_delete_dangling_index' },
    { id: 'dangling-indices.import_dangling_index', name: 'import-dangling-index', namespace: 'dangling-indices', description: 'Import a dangling index.', namespaceFile: 'dangling_indices_import_dangling_index' },
    { id: 'dangling-indices.list_dangling_indices', name: 'list-dangling-indices', namespace: 'dangling-indices', description: 'Get the dangling indices.', namespaceFile: 'dangling_indices_list_dangling_indices' },
    { id: 'delete', name: 'delete', namespace: null, description: 'Delete a document.', namespaceFile: 'delete' },
    { id: 'delete_by_query', name: 'delete-by-query', namespace: null, description: 'Delete documents.', namespaceFile: 'delete_by_query' },
    { id: 'delete_by_query_rethrottle', name: 'delete-by-query-rethrottle', namespace: null, description: 'Throttle a delete by query operation.', namespaceFile: 'delete_by_query_rethrottle' },
    { id: 'delete_script', name: 'delete-script', namespace: null, description: 'Delete a script or search template.', namespaceFile: 'delete_script' },
    { id: 'enrich.delete_policy', name: 'delete-policy', namespace: 'enrich', description: 'Delete an enrich policy.', namespaceFile: 'enrich_delete_policy' },
    { id: 'enrich.execute_policy', name: 'execute-policy', namespace: 'enrich', description: 'Run an enrich policy.', namespaceFile: 'enrich_execute_policy' },
    { id: 'enrich.get_policy', name: 'get-policy', namespace: 'enrich', description: 'Get an enrich policy.', namespaceFile: 'enrich_get_policy' },
    { id: 'enrich.put_policy', name: 'put-policy', namespace: 'enrich', description: 'Create an enrich policy.', namespaceFile: 'enrich_put_policy' },
    { id: 'enrich.stats', name: 'stats', namespace: 'enrich', description: 'Get enrich stats.', namespaceFile: 'enrich_stats' },
    { id: 'eql.delete', name: 'delete', namespace: 'eql', description: 'Delete an async EQL search.', namespaceFile: 'eql_delete' },
    { id: 'eql.get', name: 'get', namespace: 'eql', description: 'Get async EQL search results.', namespaceFile: 'eql_get' },
    { id: 'eql.get_status', name: 'get-status', namespace: 'eql', description: 'Get the async EQL status.', namespaceFile: 'eql_get_status' },
    { id: 'eql.search', name: 'search', namespace: 'eql', description: 'Get EQL search results.', namespaceFile: 'eql_search' },
    { id: 'esql.async_query', name: 'async-query', namespace: 'esql', description: 'Run an async ES|QL query.', namespaceFile: 'esql_async_query' },
    { id: 'esql.async_query_delete', name: 'async-query-delete', namespace: 'esql', description: 'Delete an async ES|QL query.', namespaceFile: 'esql_async_query_delete' },
    { id: 'esql.async_query_get', name: 'async-query-get', namespace: 'esql', description: 'Get async ES|QL query results.', namespaceFile: 'esql_async_query_get' },
    { id: 'esql.async_query_stop', name: 'async-query-stop', namespace: 'esql', description: 'Stop async ES|QL query.', namespaceFile: 'esql_async_query_stop' },
    { id: 'esql.delete_view', name: 'delete-view', namespace: 'esql', description: 'Delete an ES|QL view.', namespaceFile: 'esql_delete_view' },
    { id: 'esql.get_query', name: 'get-query', namespace: 'esql', description: 'Get a specific running ES|QL query information.', namespaceFile: 'esql_get_query' },
    { id: 'esql.get_view', name: 'get-view', namespace: 'esql', description: 'Get an ES|QL view.', namespaceFile: 'esql_get_view' },
    { id: 'esql.list_queries', name: 'list-queries', namespace: 'esql', description: 'Get running ES|QL queries information.', namespaceFile: 'esql_list_queries' },
    { id: 'esql.put_view', name: 'put-view', namespace: 'esql', description: 'Create or update an ES|QL view.', namespaceFile: 'esql_put_view' },
    { id: 'esql.query', name: 'query', namespace: 'esql', description: 'Run an ES|QL query.', namespaceFile: 'esql_query' },
    { id: 'exists', name: 'exists', namespace: null, description: 'Check a document.', namespaceFile: 'exists' },
    { id: 'exists_source', name: 'exists-source', namespace: null, description: 'Check for a document source.', namespaceFile: 'exists_source' },
    { id: 'explain', name: 'explain', namespace: null, description: 'Explain a document match result.', namespaceFile: 'explain' },
    { id: 'features.get_features', name: 'get-features', namespace: 'features', description: 'Get the features.', namespaceFile: 'features_get_features' },
    { id: 'features.reset_features', name: 'reset-features', namespace: 'features', description: 'Reset the features.', namespaceFile: 'features_reset_features' },
    { id: 'field_caps', name: 'field-caps', namespace: null, description: 'Get the field capabilities.', namespaceFile: 'field_caps' },
    { id: 'fleet.global_checkpoints', name: 'global-checkpoints', namespace: 'fleet', description: 'Get global checkpoints.', namespaceFile: 'fleet_global_checkpoints' },
    { id: 'fleet.msearch', name: 'msearch', namespace: 'fleet', description: 'Run multiple Fleet searches.', namespaceFile: 'fleet_msearch' },
    { id: 'fleet.search', name: 'search', namespace: 'fleet', description: 'Run a Fleet search.', namespaceFile: 'fleet_search' },
    { id: 'get', name: 'get', namespace: null, description: 'Get a document by its ID.', namespaceFile: 'get' },
    { id: 'get_reindex', name: 'get-reindex', namespace: null, description: 'Get the status and progress of a specific reindex task.', namespaceFile: 'get_reindex' },
    { id: 'get_script', name: 'get-script', namespace: null, description: 'Get a script or search template.', namespaceFile: 'get_script' },
    { id: 'get_script_context', name: 'get-script-context', namespace: null, description: 'Get script contexts.', namespaceFile: 'get_script_context' },
    { id: 'get_script_languages', name: 'get-script-languages', namespace: null, description: 'Get script languages.', namespaceFile: 'get_script_languages' },
    { id: 'get_source', name: 'get-source', namespace: null, description: "Get a document's source.", namespaceFile: 'get_source' },
    { id: 'graph.explore', name: 'explore', namespace: 'graph', description: 'Explore graph analytics.', namespaceFile: 'graph_explore' },
    { id: 'health_report', name: 'health-report', namespace: null, description: 'Get the cluster health.', namespaceFile: 'health_report' },
    { id: 'ilm.delete_lifecycle', name: 'delete-lifecycle', namespace: 'ilm', description: 'Delete a lifecycle policy.', namespaceFile: 'ilm.delete_lifecycle' },
    { id: 'ilm.explain_lifecycle', name: 'explain-lifecycle', namespace: 'ilm', description: 'Explain the lifecycle state.', namespaceFile: 'ilm_explain_lifecycle' },
    { id: 'ilm.get_lifecycle', name: 'get-lifecycle', namespace: 'ilm', description: 'Get lifecycle policies.', namespaceFile: 'ilm.get_lifecycle' },
    { id: 'ilm.get_status', name: 'get-status', namespace: 'ilm', description: 'Get the ILM status.', namespaceFile: 'ilm_get_status' },
    { id: 'ilm.migrate_to_data_tiers', name: 'migrate-to-data-tiers', namespace: 'ilm', description: 'Migrate to data tiers routing.', namespaceFile: 'ilm_migrate_to_data_tiers' },
    { id: 'ilm.move_to_step', name: 'move-to-step', namespace: 'ilm', description: 'Move to a lifecycle step.', namespaceFile: 'ilm_move_to_step' },
    { id: 'ilm.put_lifecycle', name: 'put-lifecycle', namespace: 'ilm', description: 'Create or update a lifecycle policy.', namespaceFile: 'ilm.put_lifecycle' },
    { id: 'ilm.remove_policy', name: 'remove-policy', namespace: 'ilm', description: 'Remove policies from an index.', namespaceFile: 'ilm_remove_policy' },
    { id: 'ilm.retry', name: 'retry', namespace: 'ilm', description: 'Retry a policy.', namespaceFile: 'ilm_retry' },
    { id: 'ilm.start', name: 'start', namespace: 'ilm', description: 'Start the ILM plugin.', namespaceFile: 'ilm_start' },
    { id: 'ilm.stop', name: 'stop', namespace: 'ilm', description: 'Stop the ILM plugin.', namespaceFile: 'ilm_stop' },
    { id: 'index', name: 'index', namespace: null, description: 'Create or update a document in an index.', namespaceFile: 'index' },
    { id: 'indices.add_block', name: 'add-block', namespace: 'indices', description: 'Add an index block.', namespaceFile: 'indices_add_block' },
    { id: 'indices.analyze', name: 'analyze', namespace: 'indices', description: 'Get tokens from text analysis.', namespaceFile: 'indices_analyze' },
    { id: 'indices.cancel_migrate_reindex', name: 'cancel-migrate-reindex', namespace: 'indices', description: 'Cancel a migration reindex operation.', namespaceFile: 'indices_cancel_migrate_reindex' },
    { id: 'indices.clear_cache', name: 'clear-cache', namespace: 'indices', description: 'Clear the cache.', namespaceFile: 'indices_clear_cache' },
    { id: 'indices.clone', name: 'clone', namespace: 'indices', description: 'Clone an index.', namespaceFile: 'indices_clone' },
    { id: 'indices.close', name: 'close', namespace: 'indices', description: 'Close an index.', namespaceFile: 'indices_close' },
    { id: 'indices.create', name: 'create', namespace: 'indices', description: 'Create an index.', namespaceFile: 'indices_create' },
    { id: 'indices.create_data_stream', name: 'create-data-stream', namespace: 'indices', description: 'Create a data stream.', namespaceFile: 'indices_create_data_stream' },
    { id: 'indices.create_from', name: 'create-from', namespace: 'indices', description: 'Create an index from a source index.', namespaceFile: 'indices_create_from' },
    { id: 'indices.data_streams_stats', name: 'data-streams-stats', namespace: 'indices', description: 'Get data stream stats.', namespaceFile: 'indices_data_streams_stats' },
    { id: 'indices.delete', name: 'delete', namespace: 'indices', description: 'Delete indices.', namespaceFile: 'indices_delete' },
    { id: 'indices.delete_alias', name: 'delete-alias', namespace: 'indices', description: 'Delete an alias.', namespaceFile: 'indices_delete_alias' },
    { id: 'indices.delete_data_lifecycle', name: 'delete-data-lifecycle', namespace: 'indices', description: 'Delete data stream lifecycles.', namespaceFile: 'indices_delete_data_lifecycle' },
    { id: 'indices.delete_data_stream', name: 'delete-data-stream', namespace: 'indices', description: 'Delete data streams.', namespaceFile: 'indices_delete_data_stream' },
    { id: 'indices.delete_data_stream_options', name: 'delete-data-stream-options', namespace: 'indices', description: 'Delete data stream options.', namespaceFile: 'indices_delete_data_stream_options' },
    { id: 'indices.delete_index_template', name: 'delete-index-template', namespace: 'indices', description: 'Delete an index template.', namespaceFile: 'indices_delete_index_template' },
    { id: 'indices.delete_template', name: 'delete-template', namespace: 'indices', description: 'Delete a legacy index template.', namespaceFile: 'indices_delete_template' },
    { id: 'indices.disk_usage', name: 'disk-usage', namespace: 'indices', description: 'Analyze the index disk usage.', namespaceFile: 'indices_disk_usage' },
    { id: 'indices.downsample', name: 'downsample', namespace: 'indices', description: 'Downsample an index.', namespaceFile: 'indices_downsample' },
    { id: 'indices.exists', name: 'exists', namespace: 'indices', description: 'Check indices.', namespaceFile: 'indices_exists' },
    { id: 'indices.exists_alias', name: 'exists-alias', namespace: 'indices', description: 'Check aliases.', namespaceFile: 'indices_exists_alias' },
    { id: 'indices.exists_index_template', name: 'exists-index-template', namespace: 'indices', description: 'Check index templates.', namespaceFile: 'indices_exists_index_template' },
    { id: 'indices.exists_template', name: 'exists-template', namespace: 'indices', description: 'Check existence of index templates.', namespaceFile: 'indices_exists_template' },
    { id: 'indices.explain_data_lifecycle', name: 'explain-data-lifecycle', namespace: 'indices', description: 'Get the status for a data stream lifecycle.', namespaceFile: 'indices_explain_data_lifecycle' },
    { id: 'indices.field_usage_stats', name: 'field-usage-stats', namespace: 'indices', description: 'Get field usage stats.', namespaceFile: 'indices_field_usage_stats' },
    { id: 'indices.flush', name: 'flush', namespace: 'indices', description: 'Flush data streams or indices.', namespaceFile: 'indices_flush' },
    { id: 'indices.forcemerge', name: 'forcemerge', namespace: 'indices', description: 'Force a merge.', namespaceFile: 'indices_forcemerge' },
    { id: 'indices.get', name: 'get', namespace: 'indices', description: 'Get index information.', namespaceFile: 'indices_get' },
    { id: 'indices.get_alias', name: 'get-alias', namespace: 'indices', description: 'Get aliases.', namespaceFile: 'indices_get_alias' },
    { id: 'indices.get_data_lifecycle', name: 'get-data-lifecycle', namespace: 'indices', description: 'Get data stream lifecycles.', namespaceFile: 'indices_get_data_lifecycle' },
    { id: 'indices.get_data_lifecycle_stats', name: 'get-data-lifecycle-stats', namespace: 'indices', description: 'Get data stream lifecycle stats.', namespaceFile: 'indices_get_data_lifecycle_stats' },
    { id: 'indices.get_data_stream', name: 'get-data-stream', namespace: 'indices', description: 'Get data streams.', namespaceFile: 'indices_get_data_stream' },
    { id: 'indices.get_data_stream_mappings', name: 'get-data-stream-mappings', namespace: 'indices', description: 'Get data stream mappings.', namespaceFile: 'indices_get_data_stream_mappings' },
    { id: 'indices.get_data_stream_options', name: 'get-data-stream-options', namespace: 'indices', description: 'Get data stream options.', namespaceFile: 'indices_get_data_stream_options' },
    { id: 'indices.get_data_stream_settings', name: 'get-data-stream-settings', namespace: 'indices', description: 'Get data stream settings.', namespaceFile: 'indices_get_data_stream_settings' },
    { id: 'indices.get_field_mapping', name: 'get-field-mapping', namespace: 'indices', description: 'Get mapping definitions.', namespaceFile: 'indices_get_field_mapping' },
    { id: 'indices.get_index_template', name: 'get-index-template', namespace: 'indices', description: 'Get index templates.', namespaceFile: 'indices_get_index_template' },
    { id: 'indices.get_mapping', name: 'get-mapping', namespace: 'indices', description: 'Get mapping definitions.', namespaceFile: 'indices_get_mapping' },
    { id: 'indices.get_migrate_reindex_status', name: 'get-migrate-reindex-status', namespace: 'indices', description: 'Get the migration reindexing status.', namespaceFile: 'indices_get_migrate_reindex_status' },
    { id: 'indices.get_settings', name: 'get-settings', namespace: 'indices', description: 'Get index settings.', namespaceFile: 'indices_get_settings' },
    { id: 'indices.get_template', name: 'get-template', namespace: 'indices', description: 'Get legacy index templates.', namespaceFile: 'indices_get_template' },
    { id: 'indices.migrate_reindex', name: 'migrate-reindex', namespace: 'indices', description: 'Reindex legacy backing indices.', namespaceFile: 'indices_migrate_reindex' },
    { id: 'indices.migrate_to_data_stream', name: 'migrate-to-data-stream', namespace: 'indices', description: 'Convert an index alias to a data stream.', namespaceFile: 'indices_migrate_to_data_stream' },
    { id: 'indices.modify_data_stream', name: 'modify-data-stream', namespace: 'indices', description: 'Update data streams.', namespaceFile: 'indices_modify_data_stream' },
    { id: 'indices.open', name: 'open', namespace: 'indices', description: 'Open a closed index.', namespaceFile: 'indices_open' },
    { id: 'indices.promote_data_stream', name: 'promote-data-stream', namespace: 'indices', description: 'Promote a data stream.', namespaceFile: 'indices_promote_data_stream' },
    { id: 'indices.put_alias', name: 'put-alias', namespace: 'indices', description: 'Create or update an alias.', namespaceFile: 'indices_put_alias' },
    { id: 'indices.put_data_lifecycle', name: 'put-data-lifecycle', namespace: 'indices', description: 'Update data stream lifecycles.', namespaceFile: 'indices_put_data_lifecycle' },
    { id: 'indices.put_data_stream_mappings', name: 'put-data-stream-mappings', namespace: 'indices', description: 'Update data stream mappings.', namespaceFile: 'indices_put_data_stream_mappings' },
    { id: 'indices.put_data_stream_options', name: 'put-data-stream-options', namespace: 'indices', description: 'Update data stream options.', namespaceFile: 'indices_put_data_stream_options' },
    { id: 'indices.put_data_stream_settings', name: 'put-data-stream-settings', namespace: 'indices', description: 'Update data stream settings.', namespaceFile: 'indices_put_data_stream_settings' },
    { id: 'indices.put_index_template', name: 'put-index-template', namespace: 'indices', description: 'Create or update an index template.', namespaceFile: 'indices_put_index_template' },
    { id: 'indices.put_mapping', name: 'put-mapping', namespace: 'indices', description: 'Update field mappings.', namespaceFile: 'indices_put_mapping' },
    { id: 'indices.put_settings', name: 'put-settings', namespace: 'indices', description: 'Update index settings.', namespaceFile: 'indices_put_settings' },
    { id: 'indices.put_template', name: 'put-template', namespace: 'indices', description: 'Create or update a legacy index template.', namespaceFile: 'indices_put_template' },
    { id: 'indices.recovery', name: 'recovery', namespace: 'indices', description: 'Get index recovery information.', namespaceFile: 'indices_recovery' },
    { id: 'indices.refresh', name: 'refresh', namespace: 'indices', description: 'Refresh an index.', namespaceFile: 'indices_refresh' },
    { id: 'indices.reload_search_analyzers', name: 'reload-search-analyzers', namespace: 'indices', description: 'Reload search analyzers.', namespaceFile: 'indices_reload_search_analyzers' },
    { id: 'indices.remove_block', name: 'remove-block', namespace: 'indices', description: 'Remove an index block.', namespaceFile: 'indices_remove_block' },
    { id: 'indices.resolve_cluster', name: 'resolve-cluster', namespace: 'indices', description: 'Resolve the cluster.', namespaceFile: 'indices_resolve_cluster' },
    { id: 'indices.resolve_index', name: 'resolve-index', namespace: 'indices', description: 'Resolve indices.', namespaceFile: 'indices_resolve_index' },
    { id: 'indices.rollover', name: 'rollover', namespace: 'indices', description: 'Roll over to a new index.', namespaceFile: 'indices_rollover' },
    { id: 'indices.segments', name: 'segments', namespace: 'indices', description: 'Get index segments.', namespaceFile: 'indices_segments' },
    { id: 'indices.shard_stores', name: 'shard-stores', namespace: 'indices', description: 'Get index shard stores.', namespaceFile: 'indices_shard_stores' },
    { id: 'indices.shrink', name: 'shrink', namespace: 'indices', description: 'Shrink an index.', namespaceFile: 'indices_shrink' },
    { id: 'indices.simulate_index_template', name: 'simulate-index-template', namespace: 'indices', description: 'Simulate an index.', namespaceFile: 'indices_simulate_index_template' },
    { id: 'indices.simulate_template', name: 'simulate-template', namespace: 'indices', description: 'Simulate an index template.', namespaceFile: 'indices_simulate_template' },
    { id: 'indices.split', name: 'split', namespace: 'indices', description: 'Split an index.', namespaceFile: 'indices_split' },
    { id: 'indices.stats', name: 'stats', namespace: 'indices', description: 'Get index statistics.', namespaceFile: 'indices_stats' },
    { id: 'indices.update_aliases', name: 'update-aliases', namespace: 'indices', description: 'Create or update an alias.', namespaceFile: 'indices_update_aliases' },
    { id: 'indices.validate_query', name: 'validate-query', namespace: 'indices', description: 'Validate a query.', namespaceFile: 'indices_validate_query' },
    { id: 'inference.chat_completion_unified', name: 'chat-completion-unified', namespace: 'inference', description: 'Perform chat completion inference on the service.', namespaceFile: 'inference_chat_completion_unified' },
    { id: 'inference.completion', name: 'completion', namespace: 'inference', description: 'Perform completion inference on the service.', namespaceFile: 'inference_completion' },
    { id: 'inference.delete', name: 'delete', namespace: 'inference', description: 'Delete an inference endpoint.', namespaceFile: 'inference_delete' },
    { id: 'inference.embedding', name: 'embedding', namespace: 'inference', description: 'Perform dense embedding inference on the service.', namespaceFile: 'inference_embedding' },
    { id: 'inference.get', name: 'get', namespace: 'inference', description: 'Get an inference endpoint.', namespaceFile: 'inference_get' },
    { id: 'inference.inference', name: 'inference', namespace: 'inference', description: 'Perform inference on the service.', namespaceFile: 'inference_inference' },
    { id: 'inference.put', name: 'put', namespace: 'inference', description: 'Create an inference endpoint.', namespaceFile: 'inference_put' },
    { id: 'inference.put_ai21', name: 'put-ai21', namespace: 'inference', description: 'Create a AI21 inference endpoint.', namespaceFile: 'inference_put_ai21' },
    { id: 'inference.put_alibabacloud', name: 'put-alibabacloud', namespace: 'inference', description: 'Create an AlibabaCloud AI Search inference endpoint.', namespaceFile: 'inference_put_alibabacloud' },
    { id: 'inference.put_amazonbedrock', name: 'put-amazonbedrock', namespace: 'inference', description: 'Create an Amazon Bedrock inference endpoint.', namespaceFile: 'inference_put_amazonbedrock' },
    { id: 'inference.put_amazonsagemaker', name: 'put-amazonsagemaker', namespace: 'inference', description: 'Create an Amazon SageMaker inference endpoint.', namespaceFile: 'inference_put_amazonsagemaker' },
    { id: 'inference.put_anthropic', name: 'put-anthropic', namespace: 'inference', description: 'Create an Anthropic inference endpoint.', namespaceFile: 'inference_put_anthropic' },
    { id: 'inference.put_azureaistudio', name: 'put-azureaistudio', namespace: 'inference', description: 'Create an Azure AI studio inference endpoint.', namespaceFile: 'inference_put_azureaistudio' },
    { id: 'inference.put_azureopenai', name: 'put-azureopenai', namespace: 'inference', description: 'Create an Azure OpenAI inference endpoint.', namespaceFile: 'inference_put_azureopenai' },
    { id: 'inference.put_cohere', name: 'put-cohere', namespace: 'inference', description: 'Create a Cohere inference endpoint.', namespaceFile: 'inference_put_cohere' },
    { id: 'inference.put_contextualai', name: 'put-contextualai', namespace: 'inference', description: 'Create an Contextual AI inference endpoint.', namespaceFile: 'inference_put_contextualai' },
    { id: 'inference.put_custom', name: 'put-custom', namespace: 'inference', description: 'Create a custom inference endpoint.', namespaceFile: 'inference_put_custom' },
    { id: 'inference.put_deepseek', name: 'put-deepseek', namespace: 'inference', description: 'Create a DeepSeek inference endpoint.', namespaceFile: 'inference_put_deepseek' },
    { id: 'inference.put_elasticsearch', name: 'put-elasticsearch', namespace: 'inference', description: 'Create an Elasticsearch inference endpoint.', namespaceFile: 'inference_put_elasticsearch' },
    { id: 'inference.put_elser', name: 'put-elser', namespace: 'inference', description: 'Create an ELSER inference endpoint.', namespaceFile: 'inference_put_elser' },
    { id: 'inference.put_fireworksai', name: 'put-fireworksai', namespace: 'inference', description: 'Create a Fireworks AI inference endpoint.', namespaceFile: 'inference_put_fireworksai' },
    { id: 'inference.put_googleaistudio', name: 'put-googleaistudio', namespace: 'inference', description: 'Create an Google AI Studio inference endpoint.', namespaceFile: 'inference_put_googleaistudio' },
    { id: 'inference.put_googlevertexai', name: 'put-googlevertexai', namespace: 'inference', description: 'Create a Google Vertex AI inference endpoint.', namespaceFile: 'inference_put_googlevertexai' },
    { id: 'inference.put_groq', name: 'put-groq', namespace: 'inference', description: 'Create a Groq inference endpoint.', namespaceFile: 'inference_put_groq' },
    { id: 'inference.put_hugging_face', name: 'put-hugging-face', namespace: 'inference', description: 'Create a Hugging Face inference endpoint.', namespaceFile: 'inference_put_hugging_face' },
    { id: 'inference.put_jinaai', name: 'put-jinaai', namespace: 'inference', description: 'Create an JinaAI inference endpoint.', namespaceFile: 'inference_put_jinaai' },
    { id: 'inference.put_llama', name: 'put-llama', namespace: 'inference', description: 'Create a Llama inference endpoint.', namespaceFile: 'inference_put_llama' },
    { id: 'inference.put_mistral', name: 'put-mistral', namespace: 'inference', description: 'Create a Mistral inference endpoint.', namespaceFile: 'inference_put_mistral' },
    { id: 'inference.put_nvidia', name: 'put-nvidia', namespace: 'inference', description: 'Create an Nvidia inference endpoint.', namespaceFile: 'inference_put_nvidia' },
    { id: 'inference.put_openai', name: 'put-openai', namespace: 'inference', description: 'Create an OpenAI inference endpoint.', namespaceFile: 'inference_put_openai' },
    { id: 'inference.put_openshift_ai', name: 'put-openshift-ai', namespace: 'inference', description: 'Create an OpenShift AI inference endpoint.', namespaceFile: 'inference_put_openshift_ai' },
    { id: 'inference.put_voyageai', name: 'put-voyageai', namespace: 'inference', description: 'Create a VoyageAI inference endpoint.', namespaceFile: 'inference_put_voyageai' },
    { id: 'inference.put_watsonx', name: 'put-watsonx', namespace: 'inference', description: 'Create a Watsonx inference endpoint.', namespaceFile: 'inference_put_watsonx' },
    { id: 'inference.rerank', name: 'rerank', namespace: 'inference', description: 'Perform reranking inference on the service.', namespaceFile: 'inference_rerank' },
    { id: 'inference.sparse_embedding', name: 'sparse-embedding', namespace: 'inference', description: 'Perform sparse embedding inference on the service.', namespaceFile: 'inference_sparse_embedding' },
    { id: 'inference.stream_completion', name: 'stream-completion', namespace: 'inference', description: 'Perform streaming completion inference on the service.', namespaceFile: 'inference_stream_completion' },
    { id: 'inference.text_embedding', name: 'text-embedding', namespace: 'inference', description: 'Perform text embedding inference on the service.', namespaceFile: 'inference_text_embedding' },
    { id: 'inference.update', name: 'update', namespace: 'inference', description: 'Update an inference endpoint.', namespaceFile: 'inference_update' },
    { id: 'info', name: 'info', namespace: null, description: 'Get cluster info.', namespaceFile: 'info' },
    { id: 'ingest.delete_geoip_database', name: 'delete-geoip-database', namespace: 'ingest', description: 'Delete GeoIP database configurations.', namespaceFile: 'ingest_delete_geoip_database' },
    { id: 'ingest.delete_ip_location_database', name: 'delete-ip-location-database', namespace: 'ingest', description: 'Delete IP geolocation database configurations.', namespaceFile: 'ingest_delete_ip_location_database' },
    { id: 'ingest.delete_pipeline', name: 'delete-pipeline', namespace: 'ingest', description: 'Delete pipelines.', namespaceFile: 'ingest_delete_pipeline' },
    { id: 'ingest.geo_ip_stats', name: 'geo-ip-stats', namespace: 'ingest', description: 'Get GeoIP statistics.', namespaceFile: 'ingest_geo_ip_stats' },
    { id: 'ingest.get_geoip_database', name: 'get-geoip-database', namespace: 'ingest', description: 'Get GeoIP database configurations.', namespaceFile: 'ingest_get_geoip_database' },
    { id: 'ingest.get_ip_location_database', name: 'get-ip-location-database', namespace: 'ingest', description: 'Get IP geolocation database configurations.', namespaceFile: 'ingest_get_ip_location_database' },
    { id: 'ingest.get_pipeline', name: 'get-pipeline', namespace: 'ingest', description: 'Get pipelines.', namespaceFile: 'ingest_get_pipeline' },
    { id: 'ingest.processor_grok', name: 'processor-grok', namespace: 'ingest', description: 'Run a grok processor.', namespaceFile: 'ingest_processor_grok' },
    { id: 'ingest.put_geoip_database', name: 'put-geoip-database', namespace: 'ingest', description: 'Create or update a GeoIP database configuration.', namespaceFile: 'ingest_put_geoip_database' },
    { id: 'ingest.put_ip_location_database', name: 'put-ip-location-database', namespace: 'ingest', description: 'Create or update an IP geolocation database configuration.', namespaceFile: 'ingest_put_ip_location_database' },
    { id: 'ingest.put_pipeline', name: 'put-pipeline', namespace: 'ingest', description: 'Create or update a pipeline.', namespaceFile: 'ingest_put_pipeline' },
    { id: 'ingest.simulate', name: 'simulate', namespace: 'ingest', description: 'Simulate a pipeline.', namespaceFile: 'ingest_simulate' },
    { id: 'license.delete', name: 'delete', namespace: 'license', description: 'Delete the license.', namespaceFile: 'license_delete' },
    { id: 'license.get', name: 'get', namespace: 'license', description: 'Get license information.', namespaceFile: 'license_get' },
    { id: 'license.get_basic_status', name: 'get-basic-status', namespace: 'license', description: 'Get the basic license status.', namespaceFile: 'license_get_basic_status' },
    { id: 'license.get_trial_status', name: 'get-trial-status', namespace: 'license', description: 'Get the trial status.', namespaceFile: 'license_get_trial_status' },
    { id: 'license.post', name: 'post', namespace: 'license', description: 'Update the license.', namespaceFile: 'license_post' },
    { id: 'license.post_start_basic', name: 'post-start-basic', namespace: 'license', description: 'Start a basic license.', namespaceFile: 'license_post_start_basic' },
    { id: 'license.post_start_trial', name: 'post-start-trial', namespace: 'license', description: 'Start a trial.', namespaceFile: 'license_post_start_trial' },
    { id: 'list_reindex', name: 'list-reindex', namespace: null, description: 'Get information about all currently running reindex tasks.', namespaceFile: 'list_reindex' },
    { id: 'logstash.delete_pipeline', name: 'delete-pipeline', namespace: 'logstash', description: 'Delete a Logstash pipeline.', namespaceFile: 'logstash_delete_pipeline' },
    { id: 'logstash.get_pipeline', name: 'get-pipeline', namespace: 'logstash', description: 'Get Logstash pipelines.', namespaceFile: 'logstash_get_pipeline' },
    { id: 'logstash.put_pipeline', name: 'put-pipeline', namespace: 'logstash', description: 'Create or update a Logstash pipeline.', namespaceFile: 'logstash_put_pipeline' },
    { id: 'mget', name: 'mget', namespace: null, description: 'Get multiple documents.', namespaceFile: 'mget' },
    { id: 'migration.deprecations', name: 'deprecations', namespace: 'migration', description: 'Get deprecation information.', namespaceFile: 'migration_deprecations' },
    { id: 'migration.get_feature_upgrade_status', name: 'get-feature-upgrade-status', namespace: 'migration', description: 'Get feature migration information.', namespaceFile: 'migration_get_feature_upgrade_status' },
    { id: 'migration.post_feature_upgrade', name: 'post-feature-upgrade', namespace: 'migration', description: 'Start the feature migration.', namespaceFile: 'migration_post_feature_upgrade' },
    { id: 'ml.clear_trained_model_deployment_cache', name: 'clear-trained-model-deployment-cache', namespace: 'ml', description: 'Clear trained model deployment cache.', namespaceFile: 'ml_clear_trained_model_deployment_cache' },
    { id: 'ml.close_job', name: 'close-job', namespace: 'ml', description: 'Close anomaly detection jobs.', namespaceFile: 'ml_close_job' },
    { id: 'ml.delete_calendar', name: 'delete-calendar', namespace: 'ml', description: 'Delete a calendar.', namespaceFile: 'ml_delete_calendar' },
    { id: 'ml.delete_calendar_event', name: 'delete-calendar-event', namespace: 'ml', description: 'Delete events from a calendar.', namespaceFile: 'ml_delete_calendar_event' },
    { id: 'ml.delete_calendar_job', name: 'delete-calendar-job', namespace: 'ml', description: 'Delete anomaly jobs from a calendar.', namespaceFile: 'ml_delete_calendar_job' },
    { id: 'ml.delete_data_frame_analytics', name: 'delete-data-frame-analytics', namespace: 'ml', description: 'Delete a data frame analytics job.', namespaceFile: 'ml_delete_data_frame_analytics' },
    { id: 'ml.delete_datafeed', name: 'delete-datafeed', namespace: 'ml', description: 'Delete a datafeed.', namespaceFile: 'ml_delete_datafeed' },
    { id: 'ml.delete_expired_data', name: 'delete-expired-data', namespace: 'ml', description: 'Delete expired ML data.', namespaceFile: 'ml_delete_expired_data' },
    { id: 'ml.delete_filter', name: 'delete-filter', namespace: 'ml', description: 'Delete a filter.', namespaceFile: 'ml_delete_filter' },
    { id: 'ml.delete_forecast', name: 'delete-forecast', namespace: 'ml', description: 'Delete forecasts from a job.', namespaceFile: 'ml_delete_forecast' },
    { id: 'ml.delete_job', name: 'delete-job', namespace: 'ml', description: 'Delete an anomaly detection job.', namespaceFile: 'ml_delete_job' },
    { id: 'ml.delete_model_snapshot', name: 'delete-model-snapshot', namespace: 'ml', description: 'Delete a model snapshot.', namespaceFile: 'ml_delete_model_snapshot' },
    { id: 'ml.delete_trained_model', name: 'delete-trained-model', namespace: 'ml', description: 'Delete an unreferenced trained model.', namespaceFile: 'ml_delete_trained_model' },
    { id: 'ml.delete_trained_model_alias', name: 'delete-trained-model-alias', namespace: 'ml', description: 'Delete a trained model alias.', namespaceFile: 'ml_delete_trained_model_alias' },
    { id: 'ml.estimate_model_memory', name: 'estimate-model-memory', namespace: 'ml', description: 'Estimate job model memory usage.', namespaceFile: 'ml_estimate_model_memory' },
    { id: 'ml.evaluate_data_frame', name: 'evaluate-data-frame', namespace: 'ml', description: 'Evaluate data frame analytics.', namespaceFile: 'ml_evaluate_data_frame' },
    { id: 'ml.explain_data_frame_analytics', name: 'explain-data-frame-analytics', namespace: 'ml', description: 'Explain data frame analytics config.', namespaceFile: 'ml_explain_data_frame_analytics' },
    { id: 'ml.flush_job', name: 'flush-job', namespace: 'ml', description: 'Force buffered data to be processed.', namespaceFile: 'ml_flush_job' },
    { id: 'ml.forecast', name: 'forecast', namespace: 'ml', description: 'Predict future behavior of a time series.', namespaceFile: 'ml_forecast' },
    { id: 'ml.get_buckets', name: 'get-buckets', namespace: 'ml', description: 'Get anomaly detection job results for buckets.', namespaceFile: 'ml_get_buckets' },
    { id: 'ml.get_calendar_events', name: 'get-calendar-events', namespace: 'ml', description: 'Get info about events in calendars.', namespaceFile: 'ml_get_calendar_events' },
    { id: 'ml.get_calendars', name: 'get-calendars', namespace: 'ml', description: 'Get calendar configuration info.', namespaceFile: 'ml_get_calendars' },
    { id: 'ml.get_categories', name: 'get-categories', namespace: 'ml', description: 'Get anomaly detection job results for categories.', namespaceFile: 'ml_get_categories' },
    { id: 'ml.get_data_frame_analytics', name: 'get-data-frame-analytics', namespace: 'ml', description: 'Get data frame analytics job configuration info.', namespaceFile: 'ml_get_data_frame_analytics' },
    { id: 'ml.get_data_frame_analytics_stats', name: 'get-data-frame-analytics-stats', namespace: 'ml', description: 'Get data frame analytics job stats.', namespaceFile: 'ml_get_data_frame_analytics_stats' },
    { id: 'ml.get_datafeed_stats', name: 'get-datafeed-stats', namespace: 'ml', description: 'Get datafeed stats.', namespaceFile: 'ml_get_datafeed_stats' },
    { id: 'ml.get_datafeeds', name: 'get-datafeeds', namespace: 'ml', description: 'Get datafeeds configuration info.', namespaceFile: 'ml_get_datafeeds' },
    { id: 'ml.get_filters', name: 'get-filters', namespace: 'ml', description: 'Get filters.', namespaceFile: 'ml_get_filters' },
    { id: 'ml.get_influencers', name: 'get-influencers', namespace: 'ml', description: 'Get anomaly detection job results for influencers.', namespaceFile: 'ml_get_influencers' },
    { id: 'ml.get_job_stats', name: 'get-job-stats', namespace: 'ml', description: 'Get anomaly detection job stats.', namespaceFile: 'ml_get_job_stats' },
    { id: 'ml.get_jobs', name: 'get-jobs', namespace: 'ml', description: 'Get anomaly detection jobs configuration info.', namespaceFile: 'ml_get_jobs' },
    { id: 'ml.get_memory_stats', name: 'get-memory-stats', namespace: 'ml', description: 'Get machine learning memory usage info.', namespaceFile: 'ml_get_memory_stats' },
    { id: 'ml.get_model_snapshot_upgrade_stats', name: 'get-model-snapshot-upgrade-stats', namespace: 'ml', description: 'Get anomaly detection job model snapshot upgrade usage info.', namespaceFile: 'ml_get_model_snapshot_upgrade_stats' },
    { id: 'ml.get_model_snapshots', name: 'get-model-snapshots', namespace: 'ml', description: 'Get model snapshots info.', namespaceFile: 'ml_get_model_snapshots' },
    { id: 'ml.get_overall_buckets', name: 'get-overall-buckets', namespace: 'ml', description: 'Get overall bucket results.', namespaceFile: 'ml_get_overall_buckets' },
    { id: 'ml.get_records', name: 'get-records', namespace: 'ml', description: 'Get anomaly records for an anomaly detection job.', namespaceFile: 'ml_get_records' },
    { id: 'ml.get_trained_models', name: 'get-trained-models', namespace: 'ml', description: 'Get trained model configuration info.', namespaceFile: 'ml_get_trained_models' },
    { id: 'ml.get_trained_models_stats', name: 'get-trained-models-stats', namespace: 'ml', description: 'Get trained models usage info.', namespaceFile: 'ml_get_trained_models_stats' },
    { id: 'ml.infer_trained_model', name: 'infer-trained-model', namespace: 'ml', description: 'Evaluate a trained model.', namespaceFile: 'ml_infer_trained_model' },
    { id: 'ml.info', name: 'info', namespace: 'ml', description: 'Get machine learning information.', namespaceFile: 'ml_info' },
    { id: 'ml.open_job', name: 'open-job', namespace: 'ml', description: 'Open anomaly detection jobs.', namespaceFile: 'ml_open_job' },
    { id: 'ml.post_calendar_events', name: 'post-calendar-events', namespace: 'ml', description: 'Add scheduled events to the calendar.', namespaceFile: 'ml_post_calendar_events' },
    { id: 'ml.post_data', name: 'post-data', namespace: 'ml', description: 'Send data to an anomaly detection job for analysis.', namespaceFile: 'ml_post_data' },
    { id: 'ml.preview_data_frame_analytics', name: 'preview-data-frame-analytics', namespace: 'ml', description: 'Preview features used by data frame analytics.', namespaceFile: 'ml_preview_data_frame_analytics' },
    { id: 'ml.preview_datafeed', name: 'preview-datafeed', namespace: 'ml', description: 'Preview a datafeed.', namespaceFile: 'ml_preview_datafeed' },
    { id: 'ml.put_calendar', name: 'put-calendar', namespace: 'ml', description: 'Create a calendar.', namespaceFile: 'ml_put_calendar' },
    { id: 'ml.put_calendar_job', name: 'put-calendar-job', namespace: 'ml', description: 'Add anomaly detection job to calendar.', namespaceFile: 'ml_put_calendar_job' },
    { id: 'ml.put_data_frame_analytics', name: 'put-data-frame-analytics', namespace: 'ml', description: 'Create a data frame analytics job.', namespaceFile: 'ml_put_data_frame_analytics' },
    { id: 'ml.put_datafeed', name: 'put-datafeed', namespace: 'ml', description: 'Create a datafeed.', namespaceFile: 'ml_put_datafeed' },
    { id: 'ml.put_filter', name: 'put-filter', namespace: 'ml', description: 'Create a filter.', namespaceFile: 'ml_put_filter' },
    { id: 'ml.put_job', name: 'put-job', namespace: 'ml', description: 'Create an anomaly detection job.', namespaceFile: 'ml_put_job' },
    { id: 'ml.put_trained_model', name: 'put-trained-model', namespace: 'ml', description: 'Create a trained model.', namespaceFile: 'ml_put_trained_model' },
    { id: 'ml.put_trained_model_alias', name: 'put-trained-model-alias', namespace: 'ml', description: 'Create or update a trained model alias.', namespaceFile: 'ml_put_trained_model_alias' },
    { id: 'ml.put_trained_model_definition_part', name: 'put-trained-model-definition-part', namespace: 'ml', description: 'Create part of a trained model definition.', namespaceFile: 'ml_put_trained_model_definition_part' },
    { id: 'ml.put_trained_model_vocabulary', name: 'put-trained-model-vocabulary', namespace: 'ml', description: 'Create a trained model vocabulary.', namespaceFile: 'ml_put_trained_model_vocabulary' },
    { id: 'ml.reset_job', name: 'reset-job', namespace: 'ml', description: 'Reset an anomaly detection job.', namespaceFile: 'ml_reset_job' },
    { id: 'ml.revert_model_snapshot', name: 'revert-model-snapshot', namespace: 'ml', description: 'Revert to a snapshot.', namespaceFile: 'ml_revert_model_snapshot' },
    { id: 'ml.set_upgrade_mode', name: 'set-upgrade-mode', namespace: 'ml', description: 'Set upgrade_mode for ML indices.', namespaceFile: 'ml_set_upgrade_mode' },
    { id: 'ml.start_data_frame_analytics', name: 'start-data-frame-analytics', namespace: 'ml', description: 'Start a data frame analytics job.', namespaceFile: 'ml_start_data_frame_analytics' },
    { id: 'ml.start_datafeed', name: 'start-datafeed', namespace: 'ml', description: 'Start datafeeds.', namespaceFile: 'ml_start_datafeed' },
    { id: 'ml.start_trained_model_deployment', name: 'start-trained-model-deployment', namespace: 'ml', description: 'Start a trained model deployment.', namespaceFile: 'ml_start_trained_model_deployment' },
    { id: 'ml.stop_data_frame_analytics', name: 'stop-data-frame-analytics', namespace: 'ml', description: 'Stop data frame analytics jobs.', namespaceFile: 'ml_stop_data_frame_analytics' },
    { id: 'ml.stop_datafeed', name: 'stop-datafeed', namespace: 'ml', description: 'Stop datafeeds.', namespaceFile: 'ml_stop_datafeed' },
    { id: 'ml.stop_trained_model_deployment', name: 'stop-trained-model-deployment', namespace: 'ml', description: 'Stop a trained model deployment.', namespaceFile: 'ml_stop_trained_model_deployment' },
    { id: 'ml.update_data_frame_analytics', name: 'update-data-frame-analytics', namespace: 'ml', description: 'Update a data frame analytics job.', namespaceFile: 'ml_update_data_frame_analytics' },
    { id: 'ml.update_datafeed', name: 'update-datafeed', namespace: 'ml', description: 'Update a datafeed.', namespaceFile: 'ml_update_datafeed' },
    { id: 'ml.update_filter', name: 'update-filter', namespace: 'ml', description: 'Update a filter.', namespaceFile: 'ml_update_filter' },
    { id: 'ml.update_job', name: 'update-job', namespace: 'ml', description: 'Update an anomaly detection job.', namespaceFile: 'ml_update_job' },
    { id: 'ml.update_model_snapshot', name: 'update-model-snapshot', namespace: 'ml', description: 'Update a snapshot.', namespaceFile: 'ml_update_model_snapshot' },
    { id: 'ml.update_trained_model_deployment', name: 'update-trained-model-deployment', namespace: 'ml', description: 'Update a trained model deployment.', namespaceFile: 'ml_update_trained_model_deployment' },
    { id: 'ml.upgrade_job_snapshot', name: 'upgrade-job-snapshot', namespace: 'ml', description: 'Upgrade a snapshot.', namespaceFile: 'ml_upgrade_job_snapshot' },
    { id: 'msearch', name: 'msearch', namespace: null, description: 'Run multiple searches.', namespaceFile: 'msearch' },
    { id: 'msearch_template', name: 'msearch-template', namespace: null, description: 'Run multiple templated searches.', namespaceFile: 'msearch_template' },
    { id: 'mtermvectors', name: 'mtermvectors', namespace: null, description: 'Get multiple term vectors.', namespaceFile: 'mtermvectors' },
    { id: 'nodes.clear_repositories_metering_archive', name: 'clear-repositories-metering-archive', namespace: 'nodes', description: 'Clear the archived repositories metering.', namespaceFile: 'nodes_clear_repositories_metering_archive' },
    { id: 'nodes.get_repositories_metering_info', name: 'get-repositories-metering-info', namespace: 'nodes', description: 'Get cluster repositories metering.', namespaceFile: 'nodes_get_repositories_metering_info' },
    { id: 'nodes.hot_threads', name: 'hot-threads', namespace: 'nodes', description: 'Get the hot threads for nodes.', namespaceFile: 'nodes_hot_threads' },
    { id: 'nodes.info', name: 'info', namespace: 'nodes', description: 'Get node information.', namespaceFile: 'nodes_info' },
    { id: 'nodes.reload_secure_settings', name: 'reload-secure-settings', namespace: 'nodes', description: 'Reload the keystore on nodes in the cluster.', namespaceFile: 'nodes_reload_secure_settings' },
    { id: 'nodes.stats', name: 'stats', namespace: 'nodes', description: 'Get node statistics.', namespaceFile: 'nodes_stats' },
    { id: 'nodes.usage', name: 'usage', namespace: 'nodes', description: 'Get feature usage information.', namespaceFile: 'nodes_usage' },
    { id: 'open_point_in_time', name: 'open-point-in-time', namespace: null, description: 'Open a point in time.', namespaceFile: 'open_point_in_time' },
    { id: 'ping', name: 'ping', namespace: null, description: 'Ping the cluster.', namespaceFile: 'ping' },
    { id: 'project.create_many_routing', name: 'create-many-routing', namespace: 'project', description: 'Create or update project routing expressions.', namespaceFile: 'project_create_many_routing' },
    { id: 'project.create_routing', name: 'create-routing', namespace: 'project', description: 'Create or update a project routing expression.', namespaceFile: 'project_create_routing' },
    { id: 'project.delete_routing', name: 'delete-routing', namespace: 'project', description: 'Delete a project routing expression.', namespaceFile: 'project_delete_routing' },
    { id: 'project.get_many_routing', name: 'get-many-routing', namespace: 'project', description: 'Get project routing expressions.', namespaceFile: 'project_get_many_routing' },
    { id: 'project.get_routing', name: 'get-routing', namespace: 'project', description: 'Get a project routing expression.', namespaceFile: 'project_get_routing' },
    { id: 'project.tags', name: 'tags', namespace: 'project', description: 'Get tags.', namespaceFile: 'project_tags' },
    { id: 'put_script', name: 'put-script', namespace: null, description: 'Create or update a script or search template.', namespaceFile: 'put_script' },
    { id: 'query-rules.delete_rule', name: 'delete-rule', namespace: 'query-rules', description: 'Delete a query rule.', namespaceFile: 'query_rules_delete_rule' },
    { id: 'query-rules.delete_ruleset', name: 'delete-ruleset', namespace: 'query-rules', description: 'Delete a query ruleset.', namespaceFile: 'query_rules_delete_ruleset' },
    { id: 'query-rules.get_rule', name: 'get-rule', namespace: 'query-rules', description: 'Get a query rule.', namespaceFile: 'query_rules_get_rule' },
    { id: 'query-rules.get_ruleset', name: 'get-ruleset', namespace: 'query-rules', description: 'Get a query ruleset.', namespaceFile: 'query_rules_get_ruleset' },
    { id: 'query-rules.list_rulesets', name: 'list-rulesets', namespace: 'query-rules', description: 'Get all query rulesets.', namespaceFile: 'query_rules_list_rulesets' },
    { id: 'query-rules.put_rule', name: 'put-rule', namespace: 'query-rules', description: 'Create or update a query rule.', namespaceFile: 'query_rules_put_rule' },
    { id: 'query-rules.put_ruleset', name: 'put-ruleset', namespace: 'query-rules', description: 'Create or update a query ruleset.', namespaceFile: 'query_rules_put_ruleset' },
    { id: 'query-rules.test', name: 'test', namespace: 'query-rules', description: 'Test a query ruleset.', namespaceFile: 'query_rules_test' },
    { id: 'rank_eval', name: 'rank-eval', namespace: null, description: 'Evaluate ranked search results.', namespaceFile: 'rank_eval' },
    { id: 'reindex', name: 'reindex', namespace: null, description: 'Reindex documents.', namespaceFile: 'reindex' },
    { id: 'reindex_rethrottle', name: 'reindex-rethrottle', namespace: null, description: 'Throttle a reindex operation.', namespaceFile: 'reindex_rethrottle' },
    { id: 'render_search_template', name: 'render-search-template', namespace: null, description: 'Render a search template.', namespaceFile: 'render_search_template' },
    { id: 'rollup.delete_job', name: 'delete-job', namespace: 'rollup', description: 'Delete a rollup job.', namespaceFile: 'rollup_delete_job' },
    { id: 'rollup.get_jobs', name: 'get-jobs', namespace: 'rollup', description: 'Get rollup job information.', namespaceFile: 'rollup_get_jobs' },
    { id: 'rollup.get_rollup_caps', name: 'get-rollup-caps', namespace: 'rollup', description: 'Get the rollup job capabilities.', namespaceFile: 'rollup_get_rollup_caps' },
    { id: 'rollup.get_rollup_index_caps', name: 'get-rollup-index-caps', namespace: 'rollup', description: 'Get the rollup index capabilities.', namespaceFile: 'rollup_get_rollup_index_caps' },
    { id: 'rollup.put_job', name: 'put-job', namespace: 'rollup', description: 'Create a rollup job.', namespaceFile: 'rollup_put_job' },
    { id: 'rollup.rollup_search', name: 'rollup-search', namespace: 'rollup', description: 'Search rolled-up data.', namespaceFile: 'rollup_rollup_search' },
    { id: 'rollup.start_job', name: 'start-job', namespace: 'rollup', description: 'Start rollup jobs.', namespaceFile: 'rollup_start_job' },
    { id: 'rollup.stop_job', name: 'stop-job', namespace: 'rollup', description: 'Stop rollup jobs.', namespaceFile: 'rollup_stop_job' },
    { id: 'scripts_painless_execute', name: 'scripts-painless-execute', namespace: null, description: 'Run a script.', namespaceFile: 'scripts_painless_execute' },
    { id: 'scroll', name: 'scroll', namespace: null, description: 'Run a scrolling search.', namespaceFile: 'scroll' },
    { id: 'search', name: 'search', namespace: null, description: 'Run a search.', namespaceFile: 'search' },
    { id: 'search-application.delete', name: 'delete', namespace: 'search-application', description: 'Delete a search application.', namespaceFile: 'search_application_delete' },
    { id: 'search-application.delete_behavioral_analytics', name: 'delete-behavioral-analytics', namespace: 'search-application', description: 'Delete a behavioral analytics collection.', namespaceFile: 'search_application_delete_behavioral_analytics' },
    { id: 'search-application.get', name: 'get', namespace: 'search-application', description: 'Get search application details.', namespaceFile: 'search_application_get' },
    { id: 'search-application.get_behavioral_analytics', name: 'get-behavioral-analytics', namespace: 'search-application', description: 'Get behavioral analytics collections.', namespaceFile: 'search_application_get_behavioral_analytics' },
    { id: 'search-application.list', name: 'list', namespace: 'search-application', description: 'Get search applications.', namespaceFile: 'search_application_list' },
    { id: 'search-application.post_behavioral_analytics_event', name: 'post-behavioral-analytics-event', namespace: 'search-application', description: 'Create a behavioral analytics collection event.', namespaceFile: 'search_application_post_behavioral_analytics_event' },
    { id: 'search-application.put', name: 'put', namespace: 'search-application', description: 'Create or update a search application.', namespaceFile: 'search_application_put' },
    { id: 'search-application.put_behavioral_analytics', name: 'put-behavioral-analytics', namespace: 'search-application', description: 'Create a behavioral analytics collection.', namespaceFile: 'search_application_put_behavioral_analytics' },
    { id: 'search-application.render_query', name: 'render-query', namespace: 'search-application', description: 'Render a search application query.', namespaceFile: 'search_application_render_query' },
    { id: 'search-application.search', name: 'search', namespace: 'search-application', description: 'Run a search application search.', namespaceFile: 'search_application_search' },
    { id: 'search_mvt', name: 'search-mvt', namespace: null, description: 'Search a vector tile.', namespaceFile: 'search_mvt' },
    { id: 'search_shards', name: 'search-shards', namespace: null, description: 'Get the search shards.', namespaceFile: 'search_shards' },
    { id: 'search_template', name: 'search-template', namespace: null, description: 'Run a search with a search template.', namespaceFile: 'search_template' },
    { id: 'searchable-snapshots.cache_stats', name: 'cache-stats', namespace: 'searchable-snapshots', description: 'Get cache statistics.', namespaceFile: 'searchable_snapshots_cache_stats' },
    { id: 'searchable-snapshots.clear_cache', name: 'clear-cache', namespace: 'searchable-snapshots', description: 'Clear the cache.', namespaceFile: 'searchable_snapshots_clear_cache' },
    { id: 'searchable-snapshots.mount', name: 'mount', namespace: 'searchable-snapshots', description: 'Mount a snapshot.', namespaceFile: 'searchable_snapshots_mount' },
    { id: 'searchable-snapshots.stats', name: 'stats', namespace: 'searchable-snapshots', description: 'Get searchable snapshot statistics.', namespaceFile: 'searchable_snapshots_stats' },
    { id: 'security.activate_user_profile', name: 'activate-user-profile', namespace: 'security', description: 'Activate a user profile.', namespaceFile: 'security_activate_user_profile' },
    { id: 'security.authenticate', name: 'authenticate', namespace: 'security', description: 'Authenticate a user.', namespaceFile: 'security_authenticate' },
    { id: 'security.bulk_delete_role', name: 'bulk-delete-role', namespace: 'security', description: 'Bulk delete roles.', namespaceFile: 'security_bulk_delete_role' },
    { id: 'security.bulk_put_role', name: 'bulk-put-role', namespace: 'security', description: 'Bulk create or update roles.', namespaceFile: 'security_bulk_put_role' },
    { id: 'security.bulk_update_api_keys', name: 'bulk-update-api-keys', namespace: 'security', description: 'Bulk update API keys.', namespaceFile: 'security_bulk_update_api_keys' },
    { id: 'security.change_password', name: 'change-password', namespace: 'security', description: 'Change passwords.', namespaceFile: 'security_change_password' },
    { id: 'security.clear_api_key_cache', name: 'clear-api-key-cache', namespace: 'security', description: 'Clear the API key cache.', namespaceFile: 'security_clear_api_key_cache' },
    { id: 'security.clear_cached_privileges', name: 'clear-cached-privileges', namespace: 'security', description: 'Clear the privileges cache.', namespaceFile: 'security_clear_cached_privileges' },
    { id: 'security.clear_cached_realms', name: 'clear-cached-realms', namespace: 'security', description: 'Clear the user cache.', namespaceFile: 'security_clear_cached_realms' },
    { id: 'security.clear_cached_roles', name: 'clear-cached-roles', namespace: 'security', description: 'Clear the roles cache.', namespaceFile: 'security_clear_cached_roles' },
    { id: 'security.clear_cached_service_tokens', name: 'clear-cached-service-tokens', namespace: 'security', description: 'Clear service account token caches.', namespaceFile: 'security_clear_cached_service_tokens' },
    { id: 'security.clone_api_key', name: 'clone-api-key', namespace: 'security', description: 'Clone an API key.', namespaceFile: 'security_clone_api_key' },
    { id: 'security.create_api_key', name: 'create-api-key', namespace: 'security', description: 'Create an API key.', namespaceFile: 'security_create_api_key' },
    { id: 'security.create_cross_cluster_api_key', name: 'create-cross-cluster-api-key', namespace: 'security', description: 'Create a cross-cluster API key.', namespaceFile: 'security_create_cross_cluster_api_key' },
    { id: 'security.create_service_token', name: 'create-service-token', namespace: 'security', description: 'Create a service account token.', namespaceFile: 'security_create_service_token' },
    { id: 'security.delegate_pki', name: 'delegate-pki', namespace: 'security', description: 'Delegate PKI authentication.', namespaceFile: 'security_delegate_pki' },
    { id: 'security.delete_privileges', name: 'delete-privileges', namespace: 'security', description: 'Delete application privileges.', namespaceFile: 'security_delete_privileges' },
    { id: 'security.delete_role', name: 'delete-role', namespace: 'security', description: 'Delete roles.', namespaceFile: 'security_delete_role' },
    { id: 'security.delete_role_mapping', name: 'delete-role-mapping', namespace: 'security', description: 'Delete role mappings.', namespaceFile: 'security_delete_role_mapping' },
    { id: 'security.delete_service_token', name: 'delete-service-token', namespace: 'security', description: 'Delete service account tokens.', namespaceFile: 'security_delete_service_token' },
    { id: 'security.delete_user', name: 'delete-user', namespace: 'security', description: 'Delete users.', namespaceFile: 'security_delete_user' },
    { id: 'security.disable_user', name: 'disable-user', namespace: 'security', description: 'Disable users.', namespaceFile: 'security_disable_user' },
    { id: 'security.disable_user_profile', name: 'disable-user-profile', namespace: 'security', description: 'Disable a user profile.', namespaceFile: 'security_disable_user_profile' },
    { id: 'security.enable_user', name: 'enable-user', namespace: 'security', description: 'Enable users.', namespaceFile: 'security_enable_user' },
    { id: 'security.enable_user_profile', name: 'enable-user-profile', namespace: 'security', description: 'Enable a user profile.', namespaceFile: 'security_enable_user_profile' },
    { id: 'security.enroll_kibana', name: 'enroll-kibana', namespace: 'security', description: 'Enroll Kibana.', namespaceFile: 'security_enroll_kibana' },
    { id: 'security.enroll_node', name: 'enroll-node', namespace: 'security', description: 'Enroll a node.', namespaceFile: 'security_enroll_node' },
    { id: 'security.get_api_key', name: 'get-api-key', namespace: 'security', description: 'Get API key information.', namespaceFile: 'security_get_api_key' },
    { id: 'security.get_builtin_privileges', name: 'get-builtin-privileges', namespace: 'security', description: 'Get builtin privileges.', namespaceFile: 'security_get_builtin_privileges' },
    { id: 'security.get_privileges', name: 'get-privileges', namespace: 'security', description: 'Get application privileges.', namespaceFile: 'security_get_privileges' },
    { id: 'security.get_role', name: 'get-role', namespace: 'security', description: 'Get roles.', namespaceFile: 'security_get_role' },
    { id: 'security.get_role_mapping', name: 'get-role-mapping', namespace: 'security', description: 'Get role mappings.', namespaceFile: 'security_get_role_mapping' },
    { id: 'security.get_service_accounts', name: 'get-service-accounts', namespace: 'security', description: 'Get service accounts.', namespaceFile: 'security_get_service_accounts' },
    { id: 'security.get_service_credentials', name: 'get-service-credentials', namespace: 'security', description: 'Get service account credentials.', namespaceFile: 'security_get_service_credentials' },
    { id: 'security.get_settings', name: 'get-settings', namespace: 'security', description: 'Get security index settings.', namespaceFile: 'security_get_settings' },
    { id: 'security.get_stats', name: 'get-stats', namespace: 'security', description: 'Get security stats.', namespaceFile: 'security_get_stats' },
    { id: 'security.get_token', name: 'get-token', namespace: 'security', description: 'Get a token.', namespaceFile: 'security_get_token' },
    { id: 'security.get_user', name: 'get-user', namespace: 'security', description: 'Get users.', namespaceFile: 'security_get_user' },
    { id: 'security.get_user_privileges', name: 'get-user-privileges', namespace: 'security', description: 'Get user privileges.', namespaceFile: 'security_get_user_privileges' },
    { id: 'security.get_user_profile', name: 'get-user-profile', namespace: 'security', description: 'Get a user profile.', namespaceFile: 'security_get_user_profile' },
    { id: 'security.grant_api_key', name: 'grant-api-key', namespace: 'security', description: 'Grant an API key.', namespaceFile: 'security_grant_api_key' },
    { id: 'security.has_privileges', name: 'has-privileges', namespace: 'security', description: 'Check user privileges.', namespaceFile: 'security_has_privileges' },
    { id: 'security.has_privileges_user_profile', name: 'has-privileges-user-profile', namespace: 'security', description: 'Check user profile privileges.', namespaceFile: 'security_has_privileges_user_profile' },
    { id: 'security.invalidate_api_key', name: 'invalidate-api-key', namespace: 'security', description: 'Invalidate API keys.', namespaceFile: 'security_invalidate_api_key' },
    { id: 'security.invalidate_token', name: 'invalidate-token', namespace: 'security', description: 'Invalidate a token.', namespaceFile: 'security_invalidate_token' },
    { id: 'security.oidc_authenticate', name: 'oidc-authenticate', namespace: 'security', description: 'Authenticate OpenID Connect.', namespaceFile: 'security_oidc_authenticate' },
    { id: 'security.oidc_logout', name: 'oidc-logout', namespace: 'security', description: 'Logout of OpenID Connect.', namespaceFile: 'security_oidc_logout' },
    { id: 'security.oidc_prepare_authentication', name: 'oidc-prepare-authentication', namespace: 'security', description: 'Prepare OpenID connect authentication.', namespaceFile: 'security_oidc_prepare_authentication' },
    { id: 'security.put_privileges', name: 'put-privileges', namespace: 'security', description: 'Create or update application privileges.', namespaceFile: 'security_put_privileges' },
    { id: 'security.put_role', name: 'put-role', namespace: 'security', description: 'Create or update roles.', namespaceFile: 'security_put_role' },
    { id: 'security.put_role_mapping', name: 'put-role-mapping', namespace: 'security', description: 'Create or update role mappings.', namespaceFile: 'security_put_role_mapping' },
    { id: 'security.put_user', name: 'put-user', namespace: 'security', description: 'Create or update users.', namespaceFile: 'security_put_user' },
    { id: 'security.query_api_keys', name: 'query-api-keys', namespace: 'security', description: 'Find API keys with a query.', namespaceFile: 'security_query_api_keys' },
    { id: 'security.query_role', name: 'query-role', namespace: 'security', description: 'Find roles with a query.', namespaceFile: 'security_query_role' },
    { id: 'security.query_user', name: 'query-user', namespace: 'security', description: 'Find users with a query.', namespaceFile: 'security_query_user' },
    { id: 'security.saml_authenticate', name: 'saml-authenticate', namespace: 'security', description: 'Authenticate SAML.', namespaceFile: 'security_saml_authenticate' },
    { id: 'security.saml_complete_logout', name: 'saml-complete-logout', namespace: 'security', description: 'Logout of SAML completely.', namespaceFile: 'security_saml_complete_logout' },
    { id: 'security.saml_invalidate', name: 'saml-invalidate', namespace: 'security', description: 'Invalidate SAML.', namespaceFile: 'security_saml_invalidate' },
    { id: 'security.saml_logout', name: 'saml-logout', namespace: 'security', description: 'Logout of SAML.', namespaceFile: 'security_saml_logout' },
    { id: 'security.saml_prepare_authentication', name: 'saml-prepare-authentication', namespace: 'security', description: 'Prepare SAML authentication.', namespaceFile: 'security_saml_prepare_authentication' },
    { id: 'security.saml_service_provider_metadata', name: 'saml-service-provider-metadata', namespace: 'security', description: 'Create SAML service provider metadata.', namespaceFile: 'security_saml_service_provider_metadata' },
    { id: 'security.suggest_user_profiles', name: 'suggest-user-profiles', namespace: 'security', description: 'Suggest a user profile.', namespaceFile: 'security_suggest_user_profiles' },
    { id: 'security.update_api_key', name: 'update-api-key', namespace: 'security', description: 'Update an API key.', namespaceFile: 'security_update_api_key' },
    { id: 'security.update_cross_cluster_api_key', name: 'update-cross-cluster-api-key', namespace: 'security', description: 'Update a cross-cluster API key.', namespaceFile: 'security_update_cross_cluster_api_key' },
    { id: 'security.update_settings', name: 'update-settings', namespace: 'security', description: 'Update security index settings.', namespaceFile: 'security_update_settings' },
    { id: 'security.update_user_profile_data', name: 'update-user-profile-data', namespace: 'security', description: 'Update user profile data.', namespaceFile: 'security_update_user_profile_data' },
    { id: 'simulate.ingest', name: 'ingest', namespace: 'simulate', description: 'Simulate data ingestion.', namespaceFile: 'simulate_ingest' },
    { id: 'slm.delete_lifecycle', name: 'delete-lifecycle', namespace: 'slm', description: 'Delete a policy.', namespaceFile: 'slm_delete_lifecycle' },
    { id: 'slm.execute_lifecycle', name: 'execute-lifecycle', namespace: 'slm', description: 'Run a policy.', namespaceFile: 'slm_execute_lifecycle' },
    { id: 'slm.execute_retention', name: 'execute-retention', namespace: 'slm', description: 'Run a retention policy.', namespaceFile: 'slm_execute_retention' },
    { id: 'slm.get_lifecycle', name: 'get-lifecycle', namespace: 'slm', description: 'Get policy information.', namespaceFile: 'slm_get_lifecycle' },
    { id: 'slm.get_stats', name: 'get-stats', namespace: 'slm', description: 'Get snapshot lifecycle management statistics.', namespaceFile: 'slm_get_stats' },
    { id: 'slm.get_status', name: 'get-status', namespace: 'slm', description: 'Get the snapshot lifecycle management status.', namespaceFile: 'slm_get_status' },
    { id: 'slm.put_lifecycle', name: 'put-lifecycle', namespace: 'slm', description: 'Create or update a policy.', namespaceFile: 'slm_put_lifecycle' },
    { id: 'slm.start', name: 'start', namespace: 'slm', description: 'Start snapshot lifecycle management.', namespaceFile: 'slm_start' },
    { id: 'slm.stop', name: 'stop', namespace: 'slm', description: 'Stop snapshot lifecycle management.', namespaceFile: 'slm_stop' },
    { id: 'snapshot.cleanup_repository', name: 'cleanup-repository', namespace: 'snapshot', description: 'Clean up the snapshot repository.', namespaceFile: 'snapshot.cleanup_repository' },
    { id: 'snapshot.clone', name: 'clone', namespace: 'snapshot', description: 'Clone a snapshot.', namespaceFile: 'snapshot_clone' },
    { id: 'snapshot.create', name: 'create', namespace: 'snapshot', description: 'Create a snapshot.', namespaceFile: 'snapshot_create' },
    { id: 'snapshot.create_repository', name: 'create-repository', namespace: 'snapshot', description: 'Create or update a snapshot repository.', namespaceFile: 'snapshot.create_repository' },
    { id: 'snapshot.delete', name: 'delete', namespace: 'snapshot', description: 'Delete snapshots.', namespaceFile: 'snapshot_delete' },
    { id: 'snapshot.delete_repository', name: 'delete-repository', namespace: 'snapshot', description: 'Delete snapshot repositories.', namespaceFile: 'snapshot.delete_repository' },
    { id: 'snapshot.get', name: 'get', namespace: 'snapshot', description: 'Get snapshot information.', namespaceFile: 'snapshot_get' },
    { id: 'snapshot.get_repository', name: 'get-repository', namespace: 'snapshot', description: 'Get snapshot repository information.', namespaceFile: 'snapshot.get_repository' },
    { id: 'snapshot.repository_analyze', name: 'repository-analyze', namespace: 'snapshot', description: 'Analyze a snapshot repository.', namespaceFile: 'snapshot.repository_analyze' },
    { id: 'snapshot.repository_verify_integrity', name: 'repository-verify-integrity', namespace: 'snapshot', description: 'Verify the repository integrity.', namespaceFile: 'snapshot.repository_verify_integrity' },
    { id: 'snapshot.restore', name: 'restore', namespace: 'snapshot', description: 'Restore a snapshot.', namespaceFile: 'snapshot_restore' },
    { id: 'snapshot.status', name: 'status', namespace: 'snapshot', description: 'Get the snapshot status.', namespaceFile: 'snapshot_status' },
    { id: 'snapshot.verify_repository', name: 'verify-repository', namespace: 'snapshot', description: 'Verify a snapshot repository.', namespaceFile: 'snapshot.verify_repository' },
    { id: 'sql.clear_cursor', name: 'clear-cursor', namespace: 'sql', description: 'Clear an SQL search cursor.', namespaceFile: 'sql_clear_cursor' },
    { id: 'sql.delete_async', name: 'delete-async', namespace: 'sql', description: 'Delete an async SQL search.', namespaceFile: 'sql_delete_async' },
    { id: 'sql.get_async', name: 'get-async', namespace: 'sql', description: 'Get async SQL search results.', namespaceFile: 'sql_get_async' },
    { id: 'sql.get_async_status', name: 'get-async-status', namespace: 'sql', description: 'Get the async SQL search status.', namespaceFile: 'sql_get_async_status' },
    { id: 'sql.query', name: 'query', namespace: 'sql', description: 'Get SQL search results.', namespaceFile: 'sql_query' },
    { id: 'sql.translate', name: 'translate', namespace: 'sql', description: 'Translate SQL into Elasticsearch queries.', namespaceFile: 'sql_translate' },
    { id: 'ssl.certificates', name: 'certificates', namespace: 'ssl', description: 'Get SSL certificates.', namespaceFile: 'ssl_certificates' },
    { id: 'streams.logs_disable', name: 'logs-disable', namespace: 'streams', description: 'Disable a named stream.', namespaceFile: 'streams_logs_disable' },
    { id: 'streams.logs_enable', name: 'logs-enable', namespace: 'streams', description: 'Enable a named stream.', namespaceFile: 'streams_logs_enable' },
    { id: 'streams.status', name: 'status', namespace: 'streams', description: 'Get the status of streams.', namespaceFile: 'streams_status' },
    { id: 'synonyms.delete_synonym', name: 'delete-synonym', namespace: 'synonyms', description: 'Delete a synonym set.', namespaceFile: 'synonyms_delete_synonym' },
    { id: 'synonyms.delete_synonym_rule', name: 'delete-synonym-rule', namespace: 'synonyms', description: 'Delete a synonym rule.', namespaceFile: 'synonyms_delete_synonym_rule' },
    { id: 'synonyms.get_synonym', name: 'get-synonym', namespace: 'synonyms', description: 'Get a synonym set.', namespaceFile: 'synonyms_get_synonym' },
    { id: 'synonyms.get_synonym_rule', name: 'get-synonym-rule', namespace: 'synonyms', description: 'Get a synonym rule.', namespaceFile: 'synonyms_get_synonym_rule' },
    { id: 'synonyms.get_synonyms_sets', name: 'get-synonyms-sets', namespace: 'synonyms', description: 'Get all synonym sets.', namespaceFile: 'synonyms_get_synonyms_sets' },
    { id: 'synonyms.put_synonym', name: 'put-synonym', namespace: 'synonyms', description: 'Create or update a synonym set.', namespaceFile: 'synonyms_put_synonym' },
    { id: 'synonyms.put_synonym_rule', name: 'put-synonym-rule', namespace: 'synonyms', description: 'Create or update a synonym rule.', namespaceFile: 'synonyms_put_synonym_rule' },
    { id: 'tasks.cancel', name: 'cancel', namespace: 'tasks', description: 'Cancel a task.', namespaceFile: 'tasks_cancel' },
    { id: 'tasks.get', name: 'get', namespace: 'tasks', description: 'Get task information.', namespaceFile: 'tasks_get' },
    { id: 'tasks.list', name: 'list', namespace: 'tasks', description: 'Get all tasks.', namespaceFile: 'tasks_list' },
    { id: 'terms_enum', name: 'terms-enum', namespace: null, description: 'Get terms in an index.', namespaceFile: 'terms_enum' },
    { id: 'termvectors', name: 'termvectors', namespace: null, description: 'Get term vector information.', namespaceFile: 'termvectors' },
    { id: 'text-structure.find_field_structure', name: 'find-field-structure', namespace: 'text-structure', description: 'Find the structure of a text field.', namespaceFile: 'text_structure_find_field_structure' },
    { id: 'text-structure.find_message_structure', name: 'find-message-structure', namespace: 'text-structure', description: 'Find the structure of text messages.', namespaceFile: 'text_structure_find_message_structure' },
    { id: 'text-structure.find_structure', name: 'find-structure', namespace: 'text-structure', description: 'Find the structure of a text file.', namespaceFile: 'text_structure_find_structure' },
    { id: 'text-structure.test_grok_pattern', name: 'test-grok-pattern', namespace: 'text-structure', description: 'Test a Grok pattern.', namespaceFile: 'text_structure_test_grok_pattern' },
    { id: 'transform.delete_transform', name: 'delete-transform', namespace: 'transform', description: 'Delete a transform.', namespaceFile: 'transform_delete_transform' },
    { id: 'transform.get_node_stats', name: 'get-node-stats', namespace: 'transform', description: 'Get node stats.', namespaceFile: 'transform_get_node_stats' },
    { id: 'transform.get_transform', name: 'get-transform', namespace: 'transform', description: 'Get transforms.', namespaceFile: 'transform_get_transform' },
    { id: 'transform.get_transform_stats', name: 'get-transform-stats', namespace: 'transform', description: 'Get transform stats.', namespaceFile: 'transform_get_transform_stats' },
    { id: 'transform.preview_transform', name: 'preview-transform', namespace: 'transform', description: 'Preview a transform.', namespaceFile: 'transform_preview_transform' },
    { id: 'transform.put_transform', name: 'put-transform', namespace: 'transform', description: 'Create a transform.', namespaceFile: 'transform_put_transform' },
    { id: 'transform.reset_transform', name: 'reset-transform', namespace: 'transform', description: 'Reset a transform.', namespaceFile: 'transform_reset_transform' },
    { id: 'transform.schedule_now_transform', name: 'schedule-now-transform', namespace: 'transform', description: 'Schedule a transform to start now.', namespaceFile: 'transform_schedule_now_transform' },
    { id: 'transform.set_upgrade_mode', name: 'set-upgrade-mode', namespace: 'transform', description: 'Set upgrade_mode for transform indices.', namespaceFile: 'transform_set_upgrade_mode' },
    { id: 'transform.start_transform', name: 'start-transform', namespace: 'transform', description: 'Start a transform.', namespaceFile: 'transform_start_transform' },
    { id: 'transform.stop_transform', name: 'stop-transform', namespace: 'transform', description: 'Stop transforms.', namespaceFile: 'transform_stop_transform' },
    { id: 'transform.update_transform', name: 'update-transform', namespace: 'transform', description: 'Update a transform.', namespaceFile: 'transform_update_transform' },
    { id: 'transform.upgrade_transforms', name: 'upgrade-transforms', namespace: 'transform', description: 'Upgrade all transforms.', namespaceFile: 'transform_upgrade_transforms' },
    { id: 'update', name: 'update', namespace: null, description: 'Update a document.', namespaceFile: 'update' },
    { id: 'update_by_query', name: 'update-by-query', namespace: null, description: 'Update documents.', namespaceFile: 'update_by_query' },
    { id: 'update_by_query_rethrottle', name: 'update-by-query-rethrottle', namespace: null, description: 'Throttle an update by query operation.', namespaceFile: 'update_by_query_rethrottle' },
    { id: 'watcher.ack_watch', name: 'ack-watch', namespace: 'watcher', description: 'Acknowledge a watch.', namespaceFile: 'watcher_ack_watch' },
    { id: 'watcher.activate_watch', name: 'activate-watch', namespace: 'watcher', description: 'Activate a watch.', namespaceFile: 'watcher_activate_watch' },
    { id: 'watcher.deactivate_watch', name: 'deactivate-watch', namespace: 'watcher', description: 'Deactivate a watch.', namespaceFile: 'watcher_deactivate_watch' },
    { id: 'watcher.delete_watch', name: 'delete-watch', namespace: 'watcher', description: 'Delete a watch.', namespaceFile: 'watcher_delete_watch' },
    { id: 'watcher.execute_watch', name: 'execute-watch', namespace: 'watcher', description: 'Run a watch.', namespaceFile: 'watcher_execute_watch' },
    { id: 'watcher.get_settings', name: 'get-settings', namespace: 'watcher', description: 'Get Watcher index settings.', namespaceFile: 'watcher_get_settings' },
    { id: 'watcher.get_watch', name: 'get-watch', namespace: 'watcher', description: 'Get a watch.', namespaceFile: 'watcher_get_watch' },
    { id: 'watcher.put_watch', name: 'put-watch', namespace: 'watcher', description: 'Create or update a watch.', namespaceFile: 'watcher_put_watch' },
    { id: 'watcher.query_watches', name: 'query-watches', namespace: 'watcher', description: 'Query watches.', namespaceFile: 'watcher_query_watches' },
    { id: 'watcher.start', name: 'start', namespace: 'watcher', description: 'Start the watch service.', namespaceFile: 'watcher_start' },
    { id: 'watcher.stats', name: 'stats', namespace: 'watcher', description: 'Get Watcher statistics.', namespaceFile: 'watcher_stats' },
    { id: 'watcher.stop', name: 'stop', namespace: 'watcher', description: 'Stop the watch service.', namespaceFile: 'watcher_stop' },
    { id: 'watcher.update_settings', name: 'update-settings', namespace: 'watcher', description: 'Update Watcher index settings.', namespaceFile: 'watcher_update_settings' },
    { id: 'xpack.info', name: 'info', namespace: 'xpack', description: 'Get information.', namespaceFile: 'xpack_info' },
    { id: 'xpack.usage', name: 'usage', namespace: 'xpack', description: 'Get usage information.', namespaceFile: 'xpack_usage' },
];
//# sourceMappingURL=manifest.js.map