/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */
/*
 * This file was automatically generated by elastic/elastic-client-generator-js.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source open api file,
 * and elastic/elastic-client-generator-js to regenerate this file again.
 */
/* eslint-disable @typescript-eslint/no-redeclare */
import { z } from 'zod';
export const Security_Exceptions_API_ExceptionListItemType = z.enum(['simple']).meta({ id: 'Security_Exceptions_API_ExceptionListItemType' });
export const Security_Exceptions_API_ExceptionListItemTags = z.array(z.string()).meta({ id: 'Security_Exceptions_API_ExceptionListItemTags' });
export const Security_Exceptions_API_ExceptionListOsType = z.enum(['linux', 'macos', 'windows']).meta({ id: 'Security_Exceptions_API_ExceptionListOsType' });
export const Security_Exceptions_API_ExceptionNamespaceType = z.enum(['agnostic', 'single']).meta({ id: 'Security_Exceptions_API_ExceptionNamespaceType' });
export const Security_Exceptions_API_ExceptionListItemName = z.string().meta({ id: 'Security_Exceptions_API_ExceptionListItemName' });
export const Security_Exceptions_API_ExceptionListItemMeta = z.record(z.string(), z.unknown()).meta({ id: 'Security_Exceptions_API_ExceptionListItemMeta' });
export const Security_Exceptions_API_ExceptionListHumanId = z.string().meta({ id: 'Security_Exceptions_API_ExceptionListHumanId' });
export const Security_Exceptions_API_ExceptionListItemHumanId = z.string().meta({ id: 'Security_Exceptions_API_ExceptionListItemHumanId' });
export const Security_Exceptions_API_ExceptionListItemId = z.string().meta({ id: 'Security_Exceptions_API_ExceptionListItemId' });
export const Security_Exceptions_API_ExceptionListItemExpireTime = z.string().meta({ id: 'Security_Exceptions_API_ExceptionListItemExpireTime' });
export const Security_Exceptions_API_NonEmptyString = z.string().meta({ id: 'Security_Exceptions_API_NonEmptyString' });
export const Security_Exceptions_API_ExceptionListItemEntryOperator = z.enum(['excluded', 'included']).meta({ id: 'Security_Exceptions_API_ExceptionListItemEntryOperator' });
export const Security_Exceptions_API_ListType = z.enum(['binary', 'boolean', 'byte', 'date', 'date_nanos', 'date_range', 'double', 'double_range', 'float', 'float_range', 'geo_point', 'geo_shape', 'half_float', 'integer', 'integer_range', 'ip', 'ip_range', 'keyword', 'long', 'long_range', 'shape', 'short', 'text']).meta({ id: 'Security_Exceptions_API_ListType' });
export const Security_Exceptions_API_ListId = z.string().meta({ id: 'Security_Exceptions_API_ListId' });
export const Security_Exceptions_API_ExceptionListItemDescription = z.string().meta({ id: 'Security_Exceptions_API_ExceptionListItemDescription' });
export const Security_Exceptions_API_EndpointArtifactTags = z.array(z.string()).meta({ id: 'Security_Exceptions_API_EndpointArtifactTags' });
export const Security_Exceptions_API_BlocklistHashOrPathEntry = z.object({
    field: z.enum(['file.hash.md5', 'file.hash.sha1', 'file.hash.sha256', 'file.path', 'file.path.caseless']),
    operator: z.enum(['included']),
    type: z.enum(['match_any']),
    value: z.array(z.string())
}).meta({ id: 'Security_Exceptions_API_BlocklistHashOrPathEntry' });
export const Security_Exceptions_API_BlocklistWindowsCodeSignatureEntry = z.object({
    entries: z.array(z.object({
        field: z.enum(['subject_name']),
        operator: z.enum(['included']),
        type: z.enum(['match', 'match_any']),
        value: z.union([z.string(), z.array(z.string())])
    })),
    field: z.enum(['file.Ext.code_signature']),
    type: z.enum(['nested'])
}).meta({ id: 'Security_Exceptions_API_BlocklistWindowsCodeSignatureEntry' });
export const Security_Exceptions_API_TrustedAppPathEntry = z.object({
    field: z.enum(['process.executable.caseless']),
    operator: z.enum(['included']),
    type: z.enum(['match', 'wildcard']),
    value: z.string()
}).meta({ id: 'Security_Exceptions_API_TrustedAppPathEntry' });
export const Security_Exceptions_API_TrustedAppHashEntry = z.object({
    field: z.enum(['process.hash.md5', 'process.hash.sha1', 'process.hash.sha256']),
    operator: z.enum(['included']),
    type: z.enum(['match']),
    value: z.string()
}).meta({ id: 'Security_Exceptions_API_TrustedAppHashEntry' });
export const Security_Exceptions_API_TrustedAppMacCodeSignatureEntry = z.object({
    entries: z.array(z.union([z.object({
            field: z.enum(['subject_name']),
            operator: z.enum(['included']),
            type: z.enum(['match']),
            value: z.string()
        }), z.object({
            field: z.enum(['trusted']),
            operator: z.enum(['included']),
            type: z.enum(['match']),
            value: z.enum(['true'])
        })])),
    field: z.enum(['process.code_signature']),
    type: z.enum(['nested'])
}).meta({ id: 'Security_Exceptions_API_TrustedAppMacCodeSignatureEntry' });
export const Security_Exceptions_API_TrustedAppWindowsCodeSignatureEntry = z.object({
    entries: z.array(z.union([z.object({
            field: z.enum(['subject_name']),
            operator: z.enum(['included']),
            type: z.enum(['match']),
            value: z.string()
        }), z.object({
            field: z.enum(['trusted']),
            operator: z.enum(['included']),
            type: z.enum(['match']),
            value: z.enum(['true'])
        })])),
    field: z.enum(['process.Ext.code_signature']),
    type: z.enum(['nested'])
}).meta({ id: 'Security_Exceptions_API_TrustedAppWindowsCodeSignatureEntry' });
export const Security_Exceptions_API_ExceptionListItemOsTypeArray = z.array(Security_Exceptions_API_ExceptionListOsType).meta({ id: 'Security_Exceptions_API_ExceptionListItemOsTypeArray' });
export const Security_Exceptions_API_ExceptionListItemComment = z.object({
    comment: Security_Exceptions_API_NonEmptyString,
    created_at: z.string(),
    created_by: Security_Exceptions_API_NonEmptyString,
    id: Security_Exceptions_API_NonEmptyString,
    updated_at: z.string().optional(),
    updated_by: Security_Exceptions_API_NonEmptyString.optional()
}).meta({ id: 'Security_Exceptions_API_ExceptionListItemComment' });
export const Security_Exceptions_API_CreateExceptionListItemComment = z.object({
    comment: Security_Exceptions_API_NonEmptyString
}).meta({ id: 'Security_Exceptions_API_CreateExceptionListItemComment' });
export const Security_Exceptions_API_ExceptionListItemEntryMatchWildcard = z.object({
    field: Security_Exceptions_API_NonEmptyString,
    operator: Security_Exceptions_API_ExceptionListItemEntryOperator,
    type: z.enum(['wildcard']),
    value: Security_Exceptions_API_NonEmptyString
}).meta({ id: 'Security_Exceptions_API_ExceptionListItemEntryMatchWildcard' });
export const Security_Exceptions_API_ExceptionListItemEntryExists = z.object({
    field: Security_Exceptions_API_NonEmptyString,
    operator: Security_Exceptions_API_ExceptionListItemEntryOperator,
    type: z.enum(['exists'])
}).meta({ id: 'Security_Exceptions_API_ExceptionListItemEntryExists' });
export const Security_Exceptions_API_ExceptionListItemEntryMatchAny = z.object({
    field: Security_Exceptions_API_NonEmptyString,
    operator: Security_Exceptions_API_ExceptionListItemEntryOperator,
    type: z.enum(['match_any']),
    value: z.array(Security_Exceptions_API_NonEmptyString)
}).meta({ id: 'Security_Exceptions_API_ExceptionListItemEntryMatchAny' });
export const Security_Exceptions_API_ExceptionListItemEntryMatch = z.object({
    field: Security_Exceptions_API_NonEmptyString,
    operator: Security_Exceptions_API_ExceptionListItemEntryOperator,
    type: z.enum(['match']),
    value: Security_Exceptions_API_NonEmptyString
}).meta({ id: 'Security_Exceptions_API_ExceptionListItemEntryMatch' });
export const Security_Exceptions_API_ExceptionListItemEntryList = z.object({
    field: Security_Exceptions_API_NonEmptyString,
    list: z.object({
        id: Security_Exceptions_API_ListId,
        type: Security_Exceptions_API_ListType
    }),
    operator: Security_Exceptions_API_ExceptionListItemEntryOperator,
    type: z.enum(['list'])
}).meta({ id: 'Security_Exceptions_API_ExceptionListItemEntryList' });
export const Security_Exceptions_API_HostIsolationProperties = z.object({
    entries: z.array(z.object({
        field: z.enum(['destination.ip']),
        operator: z.enum(['included']),
        type: z.enum(['match']),
        value: z.string()
    })).optional(),
    list_id: z.enum(['endpoint_host_isolation_exceptions']),
    os_types: z.array(z.enum(['windows', 'linux', 'macos'])).optional(),
    tags: Security_Exceptions_API_EndpointArtifactTags.optional()
}).meta({ id: 'Security_Exceptions_API_HostIsolationProperties' });
export const Security_Exceptions_API_TrustedDevicesWindowsMacProperties = z.object({
    entries: z.array(z.object({
        field: z.enum(['device.serial_number', 'device.type', 'host.name', 'device.vendor.name', 'device.vendor.id', 'device.product.id', 'device.product.name']),
        operator: z.enum(['included']),
        type: z.enum(['match', 'wildcard', 'match_any']),
        value: z.union([z.string(), z.array(z.string())])
    })).optional(),
    list_id: z.enum(['endpoint_trusted_devices']),
    os_types: z.array(z.enum(['windows', 'macos'])).optional(),
    tags: Security_Exceptions_API_EndpointArtifactTags.optional()
}).meta({ id: 'Security_Exceptions_API_TrustedDevicesWindowsMacProperties' });
export const Security_Exceptions_API_TrustedDevicesMacProperties = z.object({
    entries: z.array(z.object({
        field: z.enum(['device.serial_number', 'device.type', 'host.name', 'device.vendor.name', 'device.vendor.id', 'device.product.id', 'device.product.name']),
        operator: z.enum(['included']),
        type: z.enum(['match', 'wildcard', 'match_any']),
        value: z.union([z.string(), z.array(z.string())])
    })).optional(),
    list_id: z.enum(['endpoint_trusted_devices']),
    os_types: z.array(z.enum(['macos'])).optional(),
    tags: Security_Exceptions_API_EndpointArtifactTags.optional()
}).meta({ id: 'Security_Exceptions_API_TrustedDevicesMacProperties' });
export const Security_Exceptions_API_TrustedDevicesWindowsProperties = z.object({
    entries: z.array(z.object({
        field: z.enum(['device.serial_number', 'device.type', 'host.name', 'device.vendor.name', 'device.vendor.id', 'device.product.id', 'device.product.name', 'user.name']),
        operator: z.enum(['included']),
        type: z.enum(['match', 'wildcard', 'match_any']),
        value: z.union([z.string(), z.array(z.string())])
    })).optional(),
    list_id: z.enum(['endpoint_trusted_devices']),
    os_types: z.array(z.enum(['windows'])).optional(),
    tags: Security_Exceptions_API_EndpointArtifactTags.optional()
}).meta({ id: 'Security_Exceptions_API_TrustedDevicesWindowsProperties' });
export const Security_Exceptions_API_BlocklistMacProperties = z.object({
    entries: z.array(Security_Exceptions_API_BlocklistHashOrPathEntry).optional(),
    list_id: z.enum(['endpoint_blocklists']),
    os_types: z.array(z.enum(['macos'])).optional(),
    tags: Security_Exceptions_API_EndpointArtifactTags.optional()
}).meta({ id: 'Security_Exceptions_API_BlocklistMacProperties' });
export const Security_Exceptions_API_BlocklistLinuxProperties = z.object({
    entries: z.array(Security_Exceptions_API_BlocklistHashOrPathEntry).optional(),
    list_id: z.enum(['endpoint_blocklists']),
    os_types: z.array(z.enum(['linux'])).optional(),
    tags: Security_Exceptions_API_EndpointArtifactTags.optional()
}).meta({ id: 'Security_Exceptions_API_BlocklistLinuxProperties' });
export const Security_Exceptions_API_BlocklistWindowsProperties = z.object({
    entries: z.array(z.union([Security_Exceptions_API_BlocklistHashOrPathEntry, Security_Exceptions_API_BlocklistWindowsCodeSignatureEntry])).optional(),
    list_id: z.enum(['endpoint_blocklists']),
    os_types: z.array(z.enum(['windows'])).optional(),
    tags: Security_Exceptions_API_EndpointArtifactTags.optional()
}).meta({ id: 'Security_Exceptions_API_BlocklistWindowsProperties' });
export const Security_Exceptions_API_TrustedAppsLinuxProperties = z.object({
    entries: z.array(z.union([Security_Exceptions_API_TrustedAppHashEntry, Security_Exceptions_API_TrustedAppPathEntry])).optional(),
    list_id: z.enum(['endpoint_trusted_apps']),
    os_types: z.array(z.enum(['linux'])).optional(),
    tags: Security_Exceptions_API_EndpointArtifactTags.optional()
}).meta({ id: 'Security_Exceptions_API_TrustedAppsLinuxProperties' });
export const Security_Exceptions_API_TrustedAppsMacProperties = z.object({
    entries: z.array(z.union([Security_Exceptions_API_TrustedAppHashEntry, Security_Exceptions_API_TrustedAppPathEntry, Security_Exceptions_API_TrustedAppMacCodeSignatureEntry])).optional(),
    list_id: z.enum(['endpoint_trusted_apps']),
    os_types: z.array(z.enum(['macos'])).optional(),
    tags: Security_Exceptions_API_EndpointArtifactTags.optional()
}).meta({ id: 'Security_Exceptions_API_TrustedAppsMacProperties' });
export const Security_Exceptions_API_TrustedAppsWindowsProperties = z.object({
    entries: z.array(z.union([Security_Exceptions_API_TrustedAppHashEntry, Security_Exceptions_API_TrustedAppPathEntry, Security_Exceptions_API_TrustedAppWindowsCodeSignatureEntry])).optional(),
    list_id: z.enum(['endpoint_trusted_apps']),
    os_types: z.array(z.enum(['windows'])).optional(),
    tags: Security_Exceptions_API_EndpointArtifactTags.optional()
}).meta({ id: 'Security_Exceptions_API_TrustedAppsWindowsProperties' });
export const Security_Exceptions_API_ExceptionListItemCommentArray = z.array(Security_Exceptions_API_ExceptionListItemComment).meta({ id: 'Security_Exceptions_API_ExceptionListItemCommentArray' });
export const Security_Exceptions_API_CreateExceptionListItemCommentArray = z.array(Security_Exceptions_API_CreateExceptionListItemComment).meta({ id: 'Security_Exceptions_API_CreateExceptionListItemCommentArray' });
export const Security_Exceptions_API_ExceptionListItemEntryNestedEntryItem = z.union([Security_Exceptions_API_ExceptionListItemEntryMatch, Security_Exceptions_API_ExceptionListItemEntryMatchAny, Security_Exceptions_API_ExceptionListItemEntryExists]).meta({ id: 'Security_Exceptions_API_ExceptionListItemEntryNestedEntryItem' });
export const Security_Exceptions_API_CreateExceptionListItemBase = z.object({
    comments: Security_Exceptions_API_CreateExceptionListItemCommentArray.optional(),
    description: Security_Exceptions_API_ExceptionListItemDescription,
    expire_time: Security_Exceptions_API_ExceptionListItemExpireTime.optional(),
    item_id: Security_Exceptions_API_ExceptionListItemHumanId.optional(),
    meta: Security_Exceptions_API_ExceptionListItemMeta.optional(),
    name: Security_Exceptions_API_ExceptionListItemName,
    namespace_type: Security_Exceptions_API_ExceptionNamespaceType.optional(),
    type: Security_Exceptions_API_ExceptionListItemType
}).meta({ id: 'Security_Exceptions_API_CreateExceptionListItemBase' });
export const Security_Exceptions_API_ExceptionListItemEntryNested = z.object({
    entries: z.array(Security_Exceptions_API_ExceptionListItemEntryNestedEntryItem),
    field: Security_Exceptions_API_NonEmptyString,
    type: z.enum(['nested'])
}).meta({ id: 'Security_Exceptions_API_ExceptionListItemEntryNested' });
export const Security_Exceptions_API_CreateExceptionListItemBlocklistMac = Security_Exceptions_API_CreateExceptionListItemBase.merge(Security_Exceptions_API_BlocklistMacProperties).meta({ id: 'Security_Exceptions_API_CreateExceptionListItemBlocklistMac' });
export const Security_Exceptions_API_CreateExceptionListItemBlocklistLinux = Security_Exceptions_API_CreateExceptionListItemBase.merge(Security_Exceptions_API_BlocklistLinuxProperties).meta({ id: 'Security_Exceptions_API_CreateExceptionListItemBlocklistLinux' });
export const Security_Exceptions_API_CreateExceptionListItemBlocklistWindows = Security_Exceptions_API_CreateExceptionListItemBase.merge(Security_Exceptions_API_BlocklistWindowsProperties).meta({ id: 'Security_Exceptions_API_CreateExceptionListItemBlocklistWindows' });
export const Security_Exceptions_API_CreateExceptionListItemHostIsolation = Security_Exceptions_API_CreateExceptionListItemBase.merge(Security_Exceptions_API_HostIsolationProperties).meta({ id: 'Security_Exceptions_API_CreateExceptionListItemHostIsolation' });
export const Security_Exceptions_API_CreateExceptionListItemTrustedDevicesWindowsMac = Security_Exceptions_API_CreateExceptionListItemBase.merge(Security_Exceptions_API_TrustedDevicesWindowsMacProperties).meta({ id: 'Security_Exceptions_API_CreateExceptionListItemTrustedDevicesWindowsMac' });
export const Security_Exceptions_API_CreateExceptionListItemTrustedDevicesMac = Security_Exceptions_API_CreateExceptionListItemBase.merge(Security_Exceptions_API_TrustedDevicesMacProperties).meta({ id: 'Security_Exceptions_API_CreateExceptionListItemTrustedDevicesMac' });
export const Security_Exceptions_API_CreateExceptionListItemTrustedDevicesWindows = Security_Exceptions_API_CreateExceptionListItemBase.merge(Security_Exceptions_API_TrustedDevicesWindowsProperties).meta({ id: 'Security_Exceptions_API_CreateExceptionListItemTrustedDevicesWindows' });
export const Security_Exceptions_API_CreateExceptionListItemTrustedAppsLinux = Security_Exceptions_API_CreateExceptionListItemBase.merge(Security_Exceptions_API_TrustedAppsLinuxProperties).meta({ id: 'Security_Exceptions_API_CreateExceptionListItemTrustedAppsLinux' });
export const Security_Exceptions_API_CreateExceptionListItemTrustedAppsMac = Security_Exceptions_API_CreateExceptionListItemBase.merge(Security_Exceptions_API_TrustedAppsMacProperties).meta({ id: 'Security_Exceptions_API_CreateExceptionListItemTrustedAppsMac' });
export const Security_Exceptions_API_CreateExceptionListItemTrustedAppsWindows = Security_Exceptions_API_CreateExceptionListItemBase.merge(Security_Exceptions_API_TrustedAppsWindowsProperties).meta({ id: 'Security_Exceptions_API_CreateExceptionListItemTrustedAppsWindows' });
export const Security_Exceptions_API_ExceptionListItemEntry = z.discriminatedUnion('type', [Security_Exceptions_API_ExceptionListItemEntryMatch, Security_Exceptions_API_ExceptionListItemEntryMatchAny, Security_Exceptions_API_ExceptionListItemEntryList, Security_Exceptions_API_ExceptionListItemEntryExists, Security_Exceptions_API_ExceptionListItemEntryNested, Security_Exceptions_API_ExceptionListItemEntryMatchWildcard]).meta({ id: 'Security_Exceptions_API_ExceptionListItemEntry' });
export const Security_Exceptions_API_ExceptionListItemEntryArray = z.array(Security_Exceptions_API_ExceptionListItemEntry).meta({ id: 'Security_Exceptions_API_ExceptionListItemEntryArray' });
export const Security_Exceptions_API_ExceptionListItem = z.object({
    _version: z.string().optional(),
    comments: Security_Exceptions_API_ExceptionListItemCommentArray,
    created_at: z.string(),
    created_by: z.string(),
    description: Security_Exceptions_API_ExceptionListItemDescription,
    entries: Security_Exceptions_API_ExceptionListItemEntryArray,
    expire_time: Security_Exceptions_API_ExceptionListItemExpireTime.optional(),
    id: Security_Exceptions_API_ExceptionListItemId,
    item_id: Security_Exceptions_API_ExceptionListItemHumanId,
    list_id: Security_Exceptions_API_ExceptionListHumanId,
    meta: Security_Exceptions_API_ExceptionListItemMeta.optional(),
    name: Security_Exceptions_API_ExceptionListItemName,
    namespace_type: Security_Exceptions_API_ExceptionNamespaceType,
    os_types: Security_Exceptions_API_ExceptionListItemOsTypeArray.optional(),
    tags: Security_Exceptions_API_ExceptionListItemTags.optional(),
    tie_breaker_id: z.string(),
    type: Security_Exceptions_API_ExceptionListItemType,
    updated_at: z.string(),
    updated_by: z.string()
}).meta({ id: 'Security_Exceptions_API_ExceptionListItem' });
export const Security_Exceptions_API_EventFiltersProperties = z.object({
    entries: Security_Exceptions_API_ExceptionListItemEntryArray.optional(),
    list_id: z.enum(['endpoint_event_filters']),
    os_types: Security_Exceptions_API_ExceptionListItemOsTypeArray.optional(),
    tags: Security_Exceptions_API_EndpointArtifactTags.optional()
}).meta({ id: 'Security_Exceptions_API_EventFiltersProperties' });
export const Security_Exceptions_API_EndpointListProperties = z.object({
    entries: Security_Exceptions_API_ExceptionListItemEntryArray.optional(),
    list_id: z.enum(['endpoint_list']),
    os_types: Security_Exceptions_API_ExceptionListItemOsTypeArray.optional(),
    tags: Security_Exceptions_API_EndpointArtifactTags.optional()
}).meta({ id: 'Security_Exceptions_API_EndpointListProperties' });
export const Security_Exceptions_API_CreateExceptionListItemGeneric = Security_Exceptions_API_CreateExceptionListItemBase.merge(z.object({
    entries: Security_Exceptions_API_ExceptionListItemEntryArray,
    list_id: Security_Exceptions_API_ExceptionListHumanId,
    os_types: Security_Exceptions_API_ExceptionListItemOsTypeArray.optional(),
    tags: Security_Exceptions_API_ExceptionListItemTags.optional()
})).meta({ id: 'Security_Exceptions_API_CreateExceptionListItemGeneric' });
export const Security_Exceptions_API_CreateExceptionListItemEventFilters = Security_Exceptions_API_CreateExceptionListItemBase.merge(Security_Exceptions_API_EventFiltersProperties).meta({ id: 'Security_Exceptions_API_CreateExceptionListItemEventFilters' });
export const Security_Exceptions_API_CreateExceptionListItemEndpointList = Security_Exceptions_API_CreateExceptionListItemBase.merge(Security_Exceptions_API_EndpointListProperties).meta({ id: 'Security_Exceptions_API_CreateExceptionListItemEndpointList' });
export const CreateExceptionListItemRequest = z.union([Security_Exceptions_API_CreateExceptionListItemGeneric, Security_Exceptions_API_CreateExceptionListItemEndpointList, Security_Exceptions_API_CreateExceptionListItemTrustedAppsWindows, Security_Exceptions_API_CreateExceptionListItemTrustedAppsMac, Security_Exceptions_API_CreateExceptionListItemTrustedAppsLinux, Security_Exceptions_API_CreateExceptionListItemTrustedDevicesWindows, Security_Exceptions_API_CreateExceptionListItemTrustedDevicesMac, Security_Exceptions_API_CreateExceptionListItemTrustedDevicesWindowsMac, Security_Exceptions_API_CreateExceptionListItemEventFilters, Security_Exceptions_API_CreateExceptionListItemHostIsolation, Security_Exceptions_API_CreateExceptionListItemBlocklistWindows, Security_Exceptions_API_CreateExceptionListItemBlocklistLinux, Security_Exceptions_API_CreateExceptionListItemBlocklistMac]).meta({ id: 'CreateExceptionListItemRequest' });
//# sourceMappingURL=create_exception_list_item.js.map