import { z } from 'zod';
export declare const Security_Lists_API_ListVersion: z.ZodNumber;
export type Security_Lists_API_ListVersion = z.infer<typeof Security_Lists_API_ListVersion>;
export declare const Security_Lists_API_ListType: z.ZodEnum<{
    boolean: "boolean";
    text: "text";
    date: "date";
    long: "long";
    integer: "integer";
    double: "double";
    float: "float";
    ip: "ip";
    keyword: "keyword";
    geo_point: "geo_point";
    geo_shape: "geo_shape";
    byte: "byte";
    binary: "binary";
    short: "short";
    shape: "shape";
    date_nanos: "date_nanos";
    date_range: "date_range";
    double_range: "double_range";
    float_range: "float_range";
    half_float: "half_float";
    integer_range: "integer_range";
    ip_range: "ip_range";
    long_range: "long_range";
}>;
export type Security_Lists_API_ListType = z.infer<typeof Security_Lists_API_ListType>;
export declare const Security_Lists_API_ListName: z.ZodString;
export type Security_Lists_API_ListName = z.infer<typeof Security_Lists_API_ListName>;
export declare const Security_Lists_API_ListMetadata: z.ZodRecord<z.ZodString, z.ZodUnknown>;
export type Security_Lists_API_ListMetadata = z.infer<typeof Security_Lists_API_ListMetadata>;
export declare const Security_Lists_API_ListId: z.ZodString;
export type Security_Lists_API_ListId = z.infer<typeof Security_Lists_API_ListId>;
export declare const Security_Lists_API_ListDescription: z.ZodString;
export type Security_Lists_API_ListDescription = z.infer<typeof Security_Lists_API_ListDescription>;
export declare const Security_Lists_API_ListVersionId: z.ZodString;
export type Security_Lists_API_ListVersionId = z.infer<typeof Security_Lists_API_ListVersionId>;
export declare const Security_Lists_API_List: z.ZodObject<{
    _version: z.ZodOptional<z.ZodString>;
    '@timestamp': z.ZodOptional<z.ZodString>;
    created_at: z.ZodString;
    created_by: z.ZodString;
    description: z.ZodString;
    id: z.ZodString;
    immutable: z.ZodBoolean;
    meta: z.ZodOptional<z.ZodRecord<z.ZodString, z.ZodUnknown>>;
    name: z.ZodString;
    tie_breaker_id: z.ZodString;
    type: z.ZodEnum<{
        boolean: "boolean";
        text: "text";
        date: "date";
        long: "long";
        integer: "integer";
        double: "double";
        float: "float";
        ip: "ip";
        keyword: "keyword";
        geo_point: "geo_point";
        geo_shape: "geo_shape";
        byte: "byte";
        binary: "binary";
        short: "short";
        shape: "shape";
        date_nanos: "date_nanos";
        date_range: "date_range";
        double_range: "double_range";
        float_range: "float_range";
        half_float: "half_float";
        integer_range: "integer_range";
        ip_range: "ip_range";
        long_range: "long_range";
    }>;
    updated_at: z.ZodString;
    updated_by: z.ZodString;
    version: z.ZodNumber;
}, z.core.$strip>;
export type Security_Lists_API_List = z.infer<typeof Security_Lists_API_List>;
export declare const CreateListRequest: z.ZodObject<{
    description: z.ZodString;
    id: z.ZodOptional<z.ZodString>;
    meta: z.ZodOptional<z.ZodRecord<z.ZodString, z.ZodUnknown>>;
    name: z.ZodString;
    type: z.ZodEnum<{
        boolean: "boolean";
        text: "text";
        date: "date";
        long: "long";
        integer: "integer";
        double: "double";
        float: "float";
        ip: "ip";
        keyword: "keyword";
        geo_point: "geo_point";
        geo_shape: "geo_shape";
        byte: "byte";
        binary: "binary";
        short: "short";
        shape: "shape";
        date_nanos: "date_nanos";
        date_range: "date_range";
        double_range: "double_range";
        float_range: "float_range";
        half_float: "half_float";
        integer_range: "integer_range";
        ip_range: "ip_range";
        long_range: "long_range";
    }>;
    version: z.ZodOptional<z.ZodNumber>;
}, z.core.$strip>;
export type CreateListRequest = z.infer<typeof CreateListRequest>;
//# sourceMappingURL=create_list.d.ts.map