/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */
/*
 * This file was automatically generated by elastic/elastic-client-generator-js.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source open api file,
 * and elastic/elastic-client-generator-js to regenerate this file again.
 */
/* eslint-disable @typescript-eslint/no-redeclare */
import { z } from 'zod';
export const Kibana_HTTP_APIs_kbn_as_code_meta = z.object({
    created_at: z.string().optional(),
    created_by: z.string().optional(),
    managed: z.boolean().optional(),
    owner: z.string().optional(),
    updated_at: z.string().optional(),
    updated_by: z.string().optional(),
    version: z.string().optional()
}).meta({ id: 'Kibana_HTTP_APIs_kbn_as_code_meta' });
export const Kibana_HTTP_APIs_kbn_tags_attributes = z.object({
    color: z.string(),
    description: z.string().optional(),
    name: z.string()
}).meta({ id: 'Kibana_HTTP_APIs_kbn_tags_attributes' });
export const GetTagsIdResponse = z.object({
    data: Kibana_HTTP_APIs_kbn_tags_attributes,
    id: z.string(),
    meta: Kibana_HTTP_APIs_kbn_as_code_meta
}).meta({ id: 'GetTagsIdResponse' });
//# sourceMappingURL=get_tags_id.js.map