/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */
/*
 * This file was automatically generated by elastic/elastic-client-generator-js.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source open api file,
 * and elastic/elastic-client-generator-js to regenerate this file again.
 */
/* eslint-disable @typescript-eslint/no-redeclare */
import { z } from 'zod';
export const Kibana_HTTP_APIs_category_summary_item = z.object({
    count: z.number(),
    id: z.string(),
    parent_id: z.string().optional(),
    parent_title: z.string().optional(),
    title: z.string()
}).meta({ id: 'Kibana_HTTP_APIs_category_summary_item' });
export const Kibana_HTTP_APIs_get_categories_response = z.object({
    items: z.array(Kibana_HTTP_APIs_category_summary_item)
}).meta({ id: 'Kibana_HTTP_APIs_get_categories_response' });
//# sourceMappingURL=get_fleet_epm_categories.js.map