/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */
/*
 * This file was automatically generated by elastic/elastic-client-generator-js.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source open api file,
 * and elastic/elastic-client-generator-js to regenerate this file again.
 */
/* eslint-disable @typescript-eslint/no-redeclare */
import { z } from 'zod';
export const GetFleetAgentStatusResponse = z.object({
    results: z.object({
        active: z.number(),
        all: z.number(),
        error: z.number(),
        events: z.number(),
        inactive: z.number(),
        offline: z.number(),
        online: z.number(),
        orphaned: z.number().optional(),
        other: z.number(),
        unenrolled: z.number(),
        uninstalled: z.number().optional(),
        updating: z.number()
    })
}).meta({ id: 'GetFleetAgentStatusResponse' });
//# sourceMappingURL=get_fleet_agent_status.js.map