/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */
/*
 * This file was automatically generated by elastic/elastic-client-generator-js.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source open api file,
 * and elastic/elastic-client-generator-js to regenerate this file again.
 */
/* eslint-disable @typescript-eslint/no-redeclare */
import { z } from 'zod';
export const Kibana_HTTP_APIs_backfill_response = z.object({
    created_at: z.string(),
    duration: z.string(),
    enabled: z.boolean(),
    end: z.string().optional(),
    id: z.string(),
    initiator: z.enum(['user', 'system']),
    initiator_id: z.string().optional(),
    rule: z.object({
        api_key_created_by_user: z.boolean().nullable().optional(),
        api_key_owner: z.string().nullable().optional(),
        consumer: z.string(),
        created_at: z.string(),
        created_by: z.string().nullable().optional(),
        enabled: z.boolean(),
        id: z.string(),
        name: z.string(),
        params: z.record(z.string(), z.unknown().nullable()),
        revision: z.number(),
        rule_type_id: z.string(),
        schedule: z.object({
            interval: z.string()
        }),
        tags: z.array(z.string()),
        updated_at: z.string(),
        updated_by: z.string().nullable().optional()
    }),
    schedule: z.array(z.object({
        interval: z.string(),
        run_at: z.string(),
        status: z.enum(['complete', 'pending', 'running', 'error', 'timeout'])
    })),
    space_id: z.string(),
    start: z.string(),
    status: z.enum(['complete', 'pending', 'running', 'error', 'timeout'])
}).meta({ id: 'Kibana_HTTP_APIs_backfill_response' });
//# sourceMappingURL=get_alerting_rules_backfill_id.js.map