import { z } from 'zod';
export declare const Security_Entity_Analytics_API_EntityRiskLevels: z.ZodEnum<{
    Unknown: "Unknown";
    Low: "Low";
    Moderate: "Moderate";
    High: "High";
    Critical: "Critical";
}>;
export type Security_Entity_Analytics_API_EntityRiskLevels = z.infer<typeof Security_Entity_Analytics_API_EntityRiskLevels>;
export declare const Security_Entity_Analytics_API_EngineMetadata: z.ZodObject<{
    Type: z.ZodString;
}, z.core.$strip>;
export type Security_Entity_Analytics_API_EngineMetadata = z.infer<typeof Security_Entity_Analytics_API_EngineMetadata>;
export declare const Security_Entity_Analytics_API_AssetCriticalityLevel: z.ZodEnum<{
    low_impact: "low_impact";
    medium_impact: "medium_impact";
    high_impact: "high_impact";
    extreme_impact: "extreme_impact";
}>;
export type Security_Entity_Analytics_API_AssetCriticalityLevel = z.infer<typeof Security_Entity_Analytics_API_AssetCriticalityLevel>;
export declare const Security_Entity_Analytics_API_RiskScoreInput: z.ZodObject<{
    category: z.ZodString;
    contribution_score: z.ZodOptional<z.ZodNumber>;
    description: z.ZodString;
    entity_id: z.ZodOptional<z.ZodString>;
    id: z.ZodString;
    index: z.ZodString;
    risk_score: z.ZodOptional<z.ZodNumber>;
    timestamp: z.ZodOptional<z.ZodString>;
}, z.core.$strip>;
export type Security_Entity_Analytics_API_RiskScoreInput = z.infer<typeof Security_Entity_Analytics_API_RiskScoreInput>;
export declare const Security_Entity_Analytics_API_InspectQuery: z.ZodObject<{
    dsl: z.ZodArray<z.ZodString>;
    response: z.ZodArray<z.ZodString>;
}, z.core.$strip>;
export type Security_Entity_Analytics_API_InspectQuery = z.infer<typeof Security_Entity_Analytics_API_InspectQuery>;
export declare const Security_Entity_Analytics_API_EntityField: z.ZodObject<{
    attributes: z.ZodOptional<z.ZodObject<{
        asset: z.ZodOptional<z.ZodBoolean>;
        managed: z.ZodOptional<z.ZodBoolean>;
        mfa_enabled: z.ZodOptional<z.ZodBoolean>;
        privileged: z.ZodOptional<z.ZodBoolean>;
    }, z.core.$strip>>;
    behaviors: z.ZodOptional<z.ZodObject<{
        brute_force_victim: z.ZodOptional<z.ZodBoolean>;
        new_country_login: z.ZodOptional<z.ZodBoolean>;
        used_usb_device: z.ZodOptional<z.ZodBoolean>;
    }, z.core.$strip>>;
    EngineMetadata: z.ZodOptional<z.ZodObject<{
        Type: z.ZodString;
    }, z.core.$strip>>;
    id: z.ZodString;
    lifecycle: z.ZodOptional<z.ZodObject<{
        first_seen: z.ZodOptional<z.ZodString>;
        last_activity: z.ZodOptional<z.ZodString>;
        last_seen: z.ZodOptional<z.ZodString>;
    }, z.core.$strip>>;
    name: z.ZodOptional<z.ZodString>;
    relationships: z.ZodOptional<z.ZodObject<{
        accessed_frequently_by: z.ZodOptional<z.ZodArray<z.ZodString>>;
        accesses_frequently: z.ZodOptional<z.ZodArray<z.ZodString>>;
        accesses_infrequently: z.ZodOptional<z.ZodArray<z.ZodString>>;
        communicates_with: z.ZodOptional<z.ZodArray<z.ZodString>>;
        dependent_of: z.ZodOptional<z.ZodArray<z.ZodString>>;
        depends_on: z.ZodOptional<z.ZodArray<z.ZodString>>;
        owned_by: z.ZodOptional<z.ZodArray<z.ZodString>>;
        owns: z.ZodOptional<z.ZodArray<z.ZodString>>;
        supervised_by: z.ZodOptional<z.ZodArray<z.ZodString>>;
        supervises: z.ZodOptional<z.ZodArray<z.ZodString>>;
    }, z.core.$strip>>;
    risk: z.ZodOptional<z.ZodObject<{
        calculated_level: z.ZodOptional<z.ZodEnum<{
            Unknown: "Unknown";
            Low: "Low";
            Moderate: "Moderate";
            High: "High";
            Critical: "Critical";
        }>>;
        calculated_score: z.ZodOptional<z.ZodNumber>;
        calculated_score_norm: z.ZodOptional<z.ZodNumber>;
    }, z.core.$strip>>;
    source: z.ZodOptional<z.ZodString>;
    sub_type: z.ZodOptional<z.ZodString>;
    type: z.ZodOptional<z.ZodString>;
}, z.core.$strip>;
export type Security_Entity_Analytics_API_EntityField = z.infer<typeof Security_Entity_Analytics_API_EntityField>;
export declare const Security_Entity_Analytics_API_Asset: z.ZodObject<{
    business_unit: z.ZodOptional<z.ZodString>;
    criticality: z.ZodOptional<z.ZodEnum<{
        low_impact: "low_impact";
        medium_impact: "medium_impact";
        high_impact: "high_impact";
        extreme_impact: "extreme_impact";
    }>>;
    environment: z.ZodOptional<z.ZodString>;
    id: z.ZodOptional<z.ZodString>;
    model: z.ZodOptional<z.ZodString>;
    name: z.ZodOptional<z.ZodString>;
    owner: z.ZodOptional<z.ZodString>;
    serial_number: z.ZodOptional<z.ZodString>;
    vendor: z.ZodOptional<z.ZodString>;
}, z.core.$strip>;
export type Security_Entity_Analytics_API_Asset = z.infer<typeof Security_Entity_Analytics_API_Asset>;
export declare const Security_Entity_Analytics_API_EntityRiskScoreRecord: z.ZodObject<{
    '@timestamp': z.ZodString;
    calculated_level: z.ZodEnum<{
        Unknown: "Unknown";
        Low: "Low";
        Moderate: "Moderate";
        High: "High";
        Critical: "Critical";
    }>;
    calculated_score: z.ZodNumber;
    calculated_score_norm: z.ZodNumber;
    calculation_run_id: z.ZodOptional<z.ZodString>;
    category_1_count: z.ZodNumber;
    category_1_score: z.ZodNumber;
    category_2_count: z.ZodOptional<z.ZodNumber>;
    category_2_score: z.ZodOptional<z.ZodNumber>;
    criticality_level: z.ZodOptional<z.ZodEnum<{
        low_impact: "low_impact";
        medium_impact: "medium_impact";
        high_impact: "high_impact";
        extreme_impact: "extreme_impact";
    }>>;
    criticality_modifier: z.ZodOptional<z.ZodNumber>;
    id_field: z.ZodString;
    id_value: z.ZodString;
    inputs: z.ZodArray<z.ZodObject<{
        category: z.ZodString;
        contribution_score: z.ZodOptional<z.ZodNumber>;
        description: z.ZodString;
        entity_id: z.ZodOptional<z.ZodString>;
        id: z.ZodString;
        index: z.ZodString;
        risk_score: z.ZodOptional<z.ZodNumber>;
        timestamp: z.ZodOptional<z.ZodString>;
    }, z.core.$strip>>;
    modifiers: z.ZodOptional<z.ZodArray<z.ZodObject<{
        contribution: z.ZodNumber;
        metadata: z.ZodOptional<z.ZodRecord<z.ZodString, z.ZodUnknown>>;
        modifier_value: z.ZodOptional<z.ZodNumber>;
        subtype: z.ZodOptional<z.ZodString>;
        type: z.ZodString;
    }, z.core.$strip>>>;
    notes: z.ZodArray<z.ZodString>;
    related_entities: z.ZodOptional<z.ZodArray<z.ZodObject<{
        entity_id: z.ZodOptional<z.ZodString>;
        relationship_type: z.ZodOptional<z.ZodString>;
    }, z.core.$strip>>>;
    score_type: z.ZodOptional<z.ZodEnum<{
        base: "base";
        propagated: "propagated";
        resolution: "resolution";
    }>>;
}, z.core.$strip>;
export type Security_Entity_Analytics_API_EntityRiskScoreRecord = z.infer<typeof Security_Entity_Analytics_API_EntityRiskScoreRecord>;
export declare const Security_Entity_Analytics_API_GenericEntity: z.ZodObject<{
    '@timestamp': z.ZodOptional<z.ZodString>;
    asset: z.ZodOptional<z.ZodObject<{
        business_unit: z.ZodOptional<z.ZodString>;
        criticality: z.ZodOptional<z.ZodEnum<{
            low_impact: "low_impact";
            medium_impact: "medium_impact";
            high_impact: "high_impact";
            extreme_impact: "extreme_impact";
        }>>;
        environment: z.ZodOptional<z.ZodString>;
        id: z.ZodOptional<z.ZodString>;
        model: z.ZodOptional<z.ZodString>;
        name: z.ZodOptional<z.ZodString>;
        owner: z.ZodOptional<z.ZodString>;
        serial_number: z.ZodOptional<z.ZodString>;
        vendor: z.ZodOptional<z.ZodString>;
    }, z.core.$strip>>;
    entity: z.ZodObject<{
        attributes: z.ZodOptional<z.ZodObject<{
            asset: z.ZodOptional<z.ZodBoolean>;
            managed: z.ZodOptional<z.ZodBoolean>;
            mfa_enabled: z.ZodOptional<z.ZodBoolean>;
            privileged: z.ZodOptional<z.ZodBoolean>;
        }, z.core.$strip>>;
        behaviors: z.ZodOptional<z.ZodObject<{
            brute_force_victim: z.ZodOptional<z.ZodBoolean>;
            new_country_login: z.ZodOptional<z.ZodBoolean>;
            used_usb_device: z.ZodOptional<z.ZodBoolean>;
        }, z.core.$strip>>;
        EngineMetadata: z.ZodOptional<z.ZodObject<{
            Type: z.ZodString;
        }, z.core.$strip>>;
        id: z.ZodString;
        lifecycle: z.ZodOptional<z.ZodObject<{
            first_seen: z.ZodOptional<z.ZodString>;
            last_activity: z.ZodOptional<z.ZodString>;
            last_seen: z.ZodOptional<z.ZodString>;
        }, z.core.$strip>>;
        name: z.ZodOptional<z.ZodString>;
        relationships: z.ZodOptional<z.ZodObject<{
            accessed_frequently_by: z.ZodOptional<z.ZodArray<z.ZodString>>;
            accesses_frequently: z.ZodOptional<z.ZodArray<z.ZodString>>;
            accesses_infrequently: z.ZodOptional<z.ZodArray<z.ZodString>>;
            communicates_with: z.ZodOptional<z.ZodArray<z.ZodString>>;
            dependent_of: z.ZodOptional<z.ZodArray<z.ZodString>>;
            depends_on: z.ZodOptional<z.ZodArray<z.ZodString>>;
            owned_by: z.ZodOptional<z.ZodArray<z.ZodString>>;
            owns: z.ZodOptional<z.ZodArray<z.ZodString>>;
            supervised_by: z.ZodOptional<z.ZodArray<z.ZodString>>;
            supervises: z.ZodOptional<z.ZodArray<z.ZodString>>;
        }, z.core.$strip>>;
        risk: z.ZodOptional<z.ZodObject<{
            calculated_level: z.ZodOptional<z.ZodEnum<{
                Unknown: "Unknown";
                Low: "Low";
                Moderate: "Moderate";
                High: "High";
                Critical: "Critical";
            }>>;
            calculated_score: z.ZodOptional<z.ZodNumber>;
            calculated_score_norm: z.ZodOptional<z.ZodNumber>;
        }, z.core.$strip>>;
        source: z.ZodOptional<z.ZodString>;
        sub_type: z.ZodOptional<z.ZodString>;
        type: z.ZodOptional<z.ZodString>;
    }, z.core.$strip>;
}, z.core.$strip>;
export type Security_Entity_Analytics_API_GenericEntity = z.infer<typeof Security_Entity_Analytics_API_GenericEntity>;
export declare const Security_Entity_Analytics_API_ServiceEntity: z.ZodObject<{
    '@timestamp': z.ZodOptional<z.ZodString>;
    asset: z.ZodOptional<z.ZodObject<{
        business_unit: z.ZodOptional<z.ZodString>;
        criticality: z.ZodOptional<z.ZodEnum<{
            low_impact: "low_impact";
            medium_impact: "medium_impact";
            high_impact: "high_impact";
            extreme_impact: "extreme_impact";
        }>>;
        environment: z.ZodOptional<z.ZodString>;
        id: z.ZodOptional<z.ZodString>;
        model: z.ZodOptional<z.ZodString>;
        name: z.ZodOptional<z.ZodString>;
        owner: z.ZodOptional<z.ZodString>;
        serial_number: z.ZodOptional<z.ZodString>;
        vendor: z.ZodOptional<z.ZodString>;
    }, z.core.$strip>>;
    entity: z.ZodObject<{
        attributes: z.ZodOptional<z.ZodObject<{
            asset: z.ZodOptional<z.ZodBoolean>;
            managed: z.ZodOptional<z.ZodBoolean>;
            mfa_enabled: z.ZodOptional<z.ZodBoolean>;
            privileged: z.ZodOptional<z.ZodBoolean>;
        }, z.core.$strip>>;
        behaviors: z.ZodOptional<z.ZodObject<{
            brute_force_victim: z.ZodOptional<z.ZodBoolean>;
            new_country_login: z.ZodOptional<z.ZodBoolean>;
            used_usb_device: z.ZodOptional<z.ZodBoolean>;
        }, z.core.$strip>>;
        EngineMetadata: z.ZodOptional<z.ZodObject<{
            Type: z.ZodString;
        }, z.core.$strip>>;
        id: z.ZodString;
        lifecycle: z.ZodOptional<z.ZodObject<{
            first_seen: z.ZodOptional<z.ZodString>;
            last_activity: z.ZodOptional<z.ZodString>;
            last_seen: z.ZodOptional<z.ZodString>;
        }, z.core.$strip>>;
        name: z.ZodOptional<z.ZodString>;
        relationships: z.ZodOptional<z.ZodObject<{
            accessed_frequently_by: z.ZodOptional<z.ZodArray<z.ZodString>>;
            accesses_frequently: z.ZodOptional<z.ZodArray<z.ZodString>>;
            accesses_infrequently: z.ZodOptional<z.ZodArray<z.ZodString>>;
            communicates_with: z.ZodOptional<z.ZodArray<z.ZodString>>;
            dependent_of: z.ZodOptional<z.ZodArray<z.ZodString>>;
            depends_on: z.ZodOptional<z.ZodArray<z.ZodString>>;
            owned_by: z.ZodOptional<z.ZodArray<z.ZodString>>;
            owns: z.ZodOptional<z.ZodArray<z.ZodString>>;
            supervised_by: z.ZodOptional<z.ZodArray<z.ZodString>>;
            supervises: z.ZodOptional<z.ZodArray<z.ZodString>>;
        }, z.core.$strip>>;
        risk: z.ZodOptional<z.ZodObject<{
            calculated_level: z.ZodOptional<z.ZodEnum<{
                Unknown: "Unknown";
                Low: "Low";
                Moderate: "Moderate";
                High: "High";
                Critical: "Critical";
            }>>;
            calculated_score: z.ZodOptional<z.ZodNumber>;
            calculated_score_norm: z.ZodOptional<z.ZodNumber>;
        }, z.core.$strip>>;
        source: z.ZodOptional<z.ZodString>;
        sub_type: z.ZodOptional<z.ZodString>;
        type: z.ZodOptional<z.ZodString>;
    }, z.core.$strip>;
    event: z.ZodOptional<z.ZodObject<{
        ingested: z.ZodOptional<z.ZodString>;
    }, z.core.$strip>>;
    service: z.ZodOptional<z.ZodObject<{
        entity: z.ZodOptional<z.ZodObject<{
            attributes: z.ZodOptional<z.ZodObject<{
                asset: z.ZodOptional<z.ZodBoolean>;
                managed: z.ZodOptional<z.ZodBoolean>;
                mfa_enabled: z.ZodOptional<z.ZodBoolean>;
                privileged: z.ZodOptional<z.ZodBoolean>;
            }, z.core.$strip>>;
            behaviors: z.ZodOptional<z.ZodObject<{
                brute_force_victim: z.ZodOptional<z.ZodBoolean>;
                new_country_login: z.ZodOptional<z.ZodBoolean>;
                used_usb_device: z.ZodOptional<z.ZodBoolean>;
            }, z.core.$strip>>;
            EngineMetadata: z.ZodOptional<z.ZodObject<{
                Type: z.ZodString;
            }, z.core.$strip>>;
            id: z.ZodString;
            lifecycle: z.ZodOptional<z.ZodObject<{
                first_seen: z.ZodOptional<z.ZodString>;
                last_activity: z.ZodOptional<z.ZodString>;
                last_seen: z.ZodOptional<z.ZodString>;
            }, z.core.$strip>>;
            name: z.ZodOptional<z.ZodString>;
            relationships: z.ZodOptional<z.ZodObject<{
                accessed_frequently_by: z.ZodOptional<z.ZodArray<z.ZodString>>;
                accesses_frequently: z.ZodOptional<z.ZodArray<z.ZodString>>;
                accesses_infrequently: z.ZodOptional<z.ZodArray<z.ZodString>>;
                communicates_with: z.ZodOptional<z.ZodArray<z.ZodString>>;
                dependent_of: z.ZodOptional<z.ZodArray<z.ZodString>>;
                depends_on: z.ZodOptional<z.ZodArray<z.ZodString>>;
                owned_by: z.ZodOptional<z.ZodArray<z.ZodString>>;
                owns: z.ZodOptional<z.ZodArray<z.ZodString>>;
                supervised_by: z.ZodOptional<z.ZodArray<z.ZodString>>;
                supervises: z.ZodOptional<z.ZodArray<z.ZodString>>;
            }, z.core.$strip>>;
            risk: z.ZodOptional<z.ZodObject<{
                calculated_level: z.ZodOptional<z.ZodEnum<{
                    Unknown: "Unknown";
                    Low: "Low";
                    Moderate: "Moderate";
                    High: "High";
                    Critical: "Critical";
                }>>;
                calculated_score: z.ZodOptional<z.ZodNumber>;
                calculated_score_norm: z.ZodOptional<z.ZodNumber>;
            }, z.core.$strip>>;
            source: z.ZodOptional<z.ZodString>;
            sub_type: z.ZodOptional<z.ZodString>;
            type: z.ZodOptional<z.ZodString>;
        }, z.core.$strip>>;
        name: z.ZodString;
        risk: z.ZodOptional<z.ZodObject<{
            '@timestamp': z.ZodString;
            calculated_level: z.ZodEnum<{
                Unknown: "Unknown";
                Low: "Low";
                Moderate: "Moderate";
                High: "High";
                Critical: "Critical";
            }>;
            calculated_score: z.ZodNumber;
            calculated_score_norm: z.ZodNumber;
            calculation_run_id: z.ZodOptional<z.ZodString>;
            category_1_count: z.ZodNumber;
            category_1_score: z.ZodNumber;
            category_2_count: z.ZodOptional<z.ZodNumber>;
            category_2_score: z.ZodOptional<z.ZodNumber>;
            criticality_level: z.ZodOptional<z.ZodEnum<{
                low_impact: "low_impact";
                medium_impact: "medium_impact";
                high_impact: "high_impact";
                extreme_impact: "extreme_impact";
            }>>;
            criticality_modifier: z.ZodOptional<z.ZodNumber>;
            id_field: z.ZodString;
            id_value: z.ZodString;
            inputs: z.ZodArray<z.ZodObject<{
                category: z.ZodString;
                contribution_score: z.ZodOptional<z.ZodNumber>;
                description: z.ZodString;
                entity_id: z.ZodOptional<z.ZodString>;
                id: z.ZodString;
                index: z.ZodString;
                risk_score: z.ZodOptional<z.ZodNumber>;
                timestamp: z.ZodOptional<z.ZodString>;
            }, z.core.$strip>>;
            modifiers: z.ZodOptional<z.ZodArray<z.ZodObject<{
                contribution: z.ZodNumber;
                metadata: z.ZodOptional<z.ZodRecord<z.ZodString, z.ZodUnknown>>;
                modifier_value: z.ZodOptional<z.ZodNumber>;
                subtype: z.ZodOptional<z.ZodString>;
                type: z.ZodString;
            }, z.core.$strip>>>;
            notes: z.ZodArray<z.ZodString>;
            related_entities: z.ZodOptional<z.ZodArray<z.ZodObject<{
                entity_id: z.ZodOptional<z.ZodString>;
                relationship_type: z.ZodOptional<z.ZodString>;
            }, z.core.$strip>>>;
            score_type: z.ZodOptional<z.ZodEnum<{
                base: "base";
                propagated: "propagated";
                resolution: "resolution";
            }>>;
        }, z.core.$strip>>;
    }, z.core.$strip>>;
}, z.core.$strip>;
export type Security_Entity_Analytics_API_ServiceEntity = z.infer<typeof Security_Entity_Analytics_API_ServiceEntity>;
export declare const Security_Entity_Analytics_API_HostEntity: z.ZodObject<{
    '@timestamp': z.ZodOptional<z.ZodString>;
    asset: z.ZodOptional<z.ZodObject<{
        business_unit: z.ZodOptional<z.ZodString>;
        criticality: z.ZodOptional<z.ZodEnum<{
            low_impact: "low_impact";
            medium_impact: "medium_impact";
            high_impact: "high_impact";
            extreme_impact: "extreme_impact";
        }>>;
        environment: z.ZodOptional<z.ZodString>;
        id: z.ZodOptional<z.ZodString>;
        model: z.ZodOptional<z.ZodString>;
        name: z.ZodOptional<z.ZodString>;
        owner: z.ZodOptional<z.ZodString>;
        serial_number: z.ZodOptional<z.ZodString>;
        vendor: z.ZodOptional<z.ZodString>;
    }, z.core.$strip>>;
    entity: z.ZodObject<{
        attributes: z.ZodOptional<z.ZodObject<{
            asset: z.ZodOptional<z.ZodBoolean>;
            managed: z.ZodOptional<z.ZodBoolean>;
            mfa_enabled: z.ZodOptional<z.ZodBoolean>;
            privileged: z.ZodOptional<z.ZodBoolean>;
        }, z.core.$strip>>;
        behaviors: z.ZodOptional<z.ZodObject<{
            brute_force_victim: z.ZodOptional<z.ZodBoolean>;
            new_country_login: z.ZodOptional<z.ZodBoolean>;
            used_usb_device: z.ZodOptional<z.ZodBoolean>;
        }, z.core.$strip>>;
        EngineMetadata: z.ZodOptional<z.ZodObject<{
            Type: z.ZodString;
        }, z.core.$strip>>;
        id: z.ZodString;
        lifecycle: z.ZodOptional<z.ZodObject<{
            first_seen: z.ZodOptional<z.ZodString>;
            last_activity: z.ZodOptional<z.ZodString>;
            last_seen: z.ZodOptional<z.ZodString>;
        }, z.core.$strip>>;
        name: z.ZodOptional<z.ZodString>;
        relationships: z.ZodOptional<z.ZodObject<{
            accessed_frequently_by: z.ZodOptional<z.ZodArray<z.ZodString>>;
            accesses_frequently: z.ZodOptional<z.ZodArray<z.ZodString>>;
            accesses_infrequently: z.ZodOptional<z.ZodArray<z.ZodString>>;
            communicates_with: z.ZodOptional<z.ZodArray<z.ZodString>>;
            dependent_of: z.ZodOptional<z.ZodArray<z.ZodString>>;
            depends_on: z.ZodOptional<z.ZodArray<z.ZodString>>;
            owned_by: z.ZodOptional<z.ZodArray<z.ZodString>>;
            owns: z.ZodOptional<z.ZodArray<z.ZodString>>;
            supervised_by: z.ZodOptional<z.ZodArray<z.ZodString>>;
            supervises: z.ZodOptional<z.ZodArray<z.ZodString>>;
        }, z.core.$strip>>;
        risk: z.ZodOptional<z.ZodObject<{
            calculated_level: z.ZodOptional<z.ZodEnum<{
                Unknown: "Unknown";
                Low: "Low";
                Moderate: "Moderate";
                High: "High";
                Critical: "Critical";
            }>>;
            calculated_score: z.ZodOptional<z.ZodNumber>;
            calculated_score_norm: z.ZodOptional<z.ZodNumber>;
        }, z.core.$strip>>;
        source: z.ZodOptional<z.ZodString>;
        sub_type: z.ZodOptional<z.ZodString>;
        type: z.ZodOptional<z.ZodString>;
    }, z.core.$strip>;
    event: z.ZodOptional<z.ZodObject<{
        ingested: z.ZodOptional<z.ZodString>;
    }, z.core.$strip>>;
    host: z.ZodOptional<z.ZodObject<{
        architecture: z.ZodOptional<z.ZodArray<z.ZodString>>;
        domain: z.ZodOptional<z.ZodArray<z.ZodString>>;
        entity: z.ZodOptional<z.ZodObject<{
            attributes: z.ZodOptional<z.ZodObject<{
                asset: z.ZodOptional<z.ZodBoolean>;
                managed: z.ZodOptional<z.ZodBoolean>;
                mfa_enabled: z.ZodOptional<z.ZodBoolean>;
                privileged: z.ZodOptional<z.ZodBoolean>;
            }, z.core.$strip>>;
            behaviors: z.ZodOptional<z.ZodObject<{
                brute_force_victim: z.ZodOptional<z.ZodBoolean>;
                new_country_login: z.ZodOptional<z.ZodBoolean>;
                used_usb_device: z.ZodOptional<z.ZodBoolean>;
            }, z.core.$strip>>;
            EngineMetadata: z.ZodOptional<z.ZodObject<{
                Type: z.ZodString;
            }, z.core.$strip>>;
            id: z.ZodString;
            lifecycle: z.ZodOptional<z.ZodObject<{
                first_seen: z.ZodOptional<z.ZodString>;
                last_activity: z.ZodOptional<z.ZodString>;
                last_seen: z.ZodOptional<z.ZodString>;
            }, z.core.$strip>>;
            name: z.ZodOptional<z.ZodString>;
            relationships: z.ZodOptional<z.ZodObject<{
                accessed_frequently_by: z.ZodOptional<z.ZodArray<z.ZodString>>;
                accesses_frequently: z.ZodOptional<z.ZodArray<z.ZodString>>;
                accesses_infrequently: z.ZodOptional<z.ZodArray<z.ZodString>>;
                communicates_with: z.ZodOptional<z.ZodArray<z.ZodString>>;
                dependent_of: z.ZodOptional<z.ZodArray<z.ZodString>>;
                depends_on: z.ZodOptional<z.ZodArray<z.ZodString>>;
                owned_by: z.ZodOptional<z.ZodArray<z.ZodString>>;
                owns: z.ZodOptional<z.ZodArray<z.ZodString>>;
                supervised_by: z.ZodOptional<z.ZodArray<z.ZodString>>;
                supervises: z.ZodOptional<z.ZodArray<z.ZodString>>;
            }, z.core.$strip>>;
            risk: z.ZodOptional<z.ZodObject<{
                calculated_level: z.ZodOptional<z.ZodEnum<{
                    Unknown: "Unknown";
                    Low: "Low";
                    Moderate: "Moderate";
                    High: "High";
                    Critical: "Critical";
                }>>;
                calculated_score: z.ZodOptional<z.ZodNumber>;
                calculated_score_norm: z.ZodOptional<z.ZodNumber>;
            }, z.core.$strip>>;
            source: z.ZodOptional<z.ZodString>;
            sub_type: z.ZodOptional<z.ZodString>;
            type: z.ZodOptional<z.ZodString>;
        }, z.core.$strip>>;
        hostname: z.ZodOptional<z.ZodArray<z.ZodString>>;
        id: z.ZodOptional<z.ZodArray<z.ZodString>>;
        ip: z.ZodOptional<z.ZodArray<z.ZodString>>;
        mac: z.ZodOptional<z.ZodArray<z.ZodString>>;
        name: z.ZodString;
        os: z.ZodOptional<z.ZodObject<{
            family: z.ZodOptional<z.ZodString>;
            full: z.ZodOptional<z.ZodString>;
            kernel: z.ZodOptional<z.ZodString>;
            name: z.ZodOptional<z.ZodUnion<readonly [z.ZodString, z.ZodArray<z.ZodString>]>>;
            platform: z.ZodOptional<z.ZodString>;
            type: z.ZodOptional<z.ZodUnion<readonly [z.ZodString, z.ZodArray<z.ZodString>]>>;
            version: z.ZodOptional<z.ZodString>;
        }, z.core.$strip>>;
        risk: z.ZodOptional<z.ZodObject<{
            '@timestamp': z.ZodString;
            calculated_level: z.ZodEnum<{
                Unknown: "Unknown";
                Low: "Low";
                Moderate: "Moderate";
                High: "High";
                Critical: "Critical";
            }>;
            calculated_score: z.ZodNumber;
            calculated_score_norm: z.ZodNumber;
            calculation_run_id: z.ZodOptional<z.ZodString>;
            category_1_count: z.ZodNumber;
            category_1_score: z.ZodNumber;
            category_2_count: z.ZodOptional<z.ZodNumber>;
            category_2_score: z.ZodOptional<z.ZodNumber>;
            criticality_level: z.ZodOptional<z.ZodEnum<{
                low_impact: "low_impact";
                medium_impact: "medium_impact";
                high_impact: "high_impact";
                extreme_impact: "extreme_impact";
            }>>;
            criticality_modifier: z.ZodOptional<z.ZodNumber>;
            id_field: z.ZodString;
            id_value: z.ZodString;
            inputs: z.ZodArray<z.ZodObject<{
                category: z.ZodString;
                contribution_score: z.ZodOptional<z.ZodNumber>;
                description: z.ZodString;
                entity_id: z.ZodOptional<z.ZodString>;
                id: z.ZodString;
                index: z.ZodString;
                risk_score: z.ZodOptional<z.ZodNumber>;
                timestamp: z.ZodOptional<z.ZodString>;
            }, z.core.$strip>>;
            modifiers: z.ZodOptional<z.ZodArray<z.ZodObject<{
                contribution: z.ZodNumber;
                metadata: z.ZodOptional<z.ZodRecord<z.ZodString, z.ZodUnknown>>;
                modifier_value: z.ZodOptional<z.ZodNumber>;
                subtype: z.ZodOptional<z.ZodString>;
                type: z.ZodString;
            }, z.core.$strip>>>;
            notes: z.ZodArray<z.ZodString>;
            related_entities: z.ZodOptional<z.ZodArray<z.ZodObject<{
                entity_id: z.ZodOptional<z.ZodString>;
                relationship_type: z.ZodOptional<z.ZodString>;
            }, z.core.$strip>>>;
            score_type: z.ZodOptional<z.ZodEnum<{
                base: "base";
                propagated: "propagated";
                resolution: "resolution";
            }>>;
        }, z.core.$strip>>;
        type: z.ZodOptional<z.ZodArray<z.ZodString>>;
    }, z.core.$strip>>;
}, z.core.$strip>;
export type Security_Entity_Analytics_API_HostEntity = z.infer<typeof Security_Entity_Analytics_API_HostEntity>;
export declare const Security_Entity_Analytics_API_UserEntity: z.ZodObject<{
    '@timestamp': z.ZodOptional<z.ZodString>;
    asset: z.ZodOptional<z.ZodObject<{
        business_unit: z.ZodOptional<z.ZodString>;
        criticality: z.ZodOptional<z.ZodEnum<{
            low_impact: "low_impact";
            medium_impact: "medium_impact";
            high_impact: "high_impact";
            extreme_impact: "extreme_impact";
        }>>;
        environment: z.ZodOptional<z.ZodString>;
        id: z.ZodOptional<z.ZodString>;
        model: z.ZodOptional<z.ZodString>;
        name: z.ZodOptional<z.ZodString>;
        owner: z.ZodOptional<z.ZodString>;
        serial_number: z.ZodOptional<z.ZodString>;
        vendor: z.ZodOptional<z.ZodString>;
    }, z.core.$strip>>;
    entity: z.ZodObject<{
        attributes: z.ZodOptional<z.ZodObject<{
            asset: z.ZodOptional<z.ZodBoolean>;
            managed: z.ZodOptional<z.ZodBoolean>;
            mfa_enabled: z.ZodOptional<z.ZodBoolean>;
            privileged: z.ZodOptional<z.ZodBoolean>;
        }, z.core.$strip>>;
        behaviors: z.ZodOptional<z.ZodObject<{
            brute_force_victim: z.ZodOptional<z.ZodBoolean>;
            new_country_login: z.ZodOptional<z.ZodBoolean>;
            used_usb_device: z.ZodOptional<z.ZodBoolean>;
        }, z.core.$strip>>;
        EngineMetadata: z.ZodOptional<z.ZodObject<{
            Type: z.ZodString;
        }, z.core.$strip>>;
        id: z.ZodString;
        lifecycle: z.ZodOptional<z.ZodObject<{
            first_seen: z.ZodOptional<z.ZodString>;
            last_activity: z.ZodOptional<z.ZodString>;
            last_seen: z.ZodOptional<z.ZodString>;
        }, z.core.$strip>>;
        name: z.ZodOptional<z.ZodString>;
        relationships: z.ZodOptional<z.ZodObject<{
            accessed_frequently_by: z.ZodOptional<z.ZodArray<z.ZodString>>;
            accesses_frequently: z.ZodOptional<z.ZodArray<z.ZodString>>;
            accesses_infrequently: z.ZodOptional<z.ZodArray<z.ZodString>>;
            communicates_with: z.ZodOptional<z.ZodArray<z.ZodString>>;
            dependent_of: z.ZodOptional<z.ZodArray<z.ZodString>>;
            depends_on: z.ZodOptional<z.ZodArray<z.ZodString>>;
            owned_by: z.ZodOptional<z.ZodArray<z.ZodString>>;
            owns: z.ZodOptional<z.ZodArray<z.ZodString>>;
            supervised_by: z.ZodOptional<z.ZodArray<z.ZodString>>;
            supervises: z.ZodOptional<z.ZodArray<z.ZodString>>;
        }, z.core.$strip>>;
        risk: z.ZodOptional<z.ZodObject<{
            calculated_level: z.ZodOptional<z.ZodEnum<{
                Unknown: "Unknown";
                Low: "Low";
                Moderate: "Moderate";
                High: "High";
                Critical: "Critical";
            }>>;
            calculated_score: z.ZodOptional<z.ZodNumber>;
            calculated_score_norm: z.ZodOptional<z.ZodNumber>;
        }, z.core.$strip>>;
        source: z.ZodOptional<z.ZodString>;
        sub_type: z.ZodOptional<z.ZodString>;
        type: z.ZodOptional<z.ZodString>;
    }, z.core.$strip>;
    event: z.ZodOptional<z.ZodObject<{
        ingested: z.ZodOptional<z.ZodString>;
    }, z.core.$strip>>;
    user: z.ZodOptional<z.ZodObject<{
        domain: z.ZodOptional<z.ZodArray<z.ZodString>>;
        email: z.ZodOptional<z.ZodArray<z.ZodString>>;
        full_name: z.ZodOptional<z.ZodArray<z.ZodString>>;
        hash: z.ZodOptional<z.ZodArray<z.ZodString>>;
        id: z.ZodOptional<z.ZodArray<z.ZodString>>;
        name: z.ZodString;
        risk: z.ZodOptional<z.ZodObject<{
            '@timestamp': z.ZodString;
            calculated_level: z.ZodEnum<{
                Unknown: "Unknown";
                Low: "Low";
                Moderate: "Moderate";
                High: "High";
                Critical: "Critical";
            }>;
            calculated_score: z.ZodNumber;
            calculated_score_norm: z.ZodNumber;
            calculation_run_id: z.ZodOptional<z.ZodString>;
            category_1_count: z.ZodNumber;
            category_1_score: z.ZodNumber;
            category_2_count: z.ZodOptional<z.ZodNumber>;
            category_2_score: z.ZodOptional<z.ZodNumber>;
            criticality_level: z.ZodOptional<z.ZodEnum<{
                low_impact: "low_impact";
                medium_impact: "medium_impact";
                high_impact: "high_impact";
                extreme_impact: "extreme_impact";
            }>>;
            criticality_modifier: z.ZodOptional<z.ZodNumber>;
            id_field: z.ZodString;
            id_value: z.ZodString;
            inputs: z.ZodArray<z.ZodObject<{
                category: z.ZodString;
                contribution_score: z.ZodOptional<z.ZodNumber>;
                description: z.ZodString;
                entity_id: z.ZodOptional<z.ZodString>;
                id: z.ZodString;
                index: z.ZodString;
                risk_score: z.ZodOptional<z.ZodNumber>;
                timestamp: z.ZodOptional<z.ZodString>;
            }, z.core.$strip>>;
            modifiers: z.ZodOptional<z.ZodArray<z.ZodObject<{
                contribution: z.ZodNumber;
                metadata: z.ZodOptional<z.ZodRecord<z.ZodString, z.ZodUnknown>>;
                modifier_value: z.ZodOptional<z.ZodNumber>;
                subtype: z.ZodOptional<z.ZodString>;
                type: z.ZodString;
            }, z.core.$strip>>>;
            notes: z.ZodArray<z.ZodString>;
            related_entities: z.ZodOptional<z.ZodArray<z.ZodObject<{
                entity_id: z.ZodOptional<z.ZodString>;
                relationship_type: z.ZodOptional<z.ZodString>;
            }, z.core.$strip>>>;
            score_type: z.ZodOptional<z.ZodEnum<{
                base: "base";
                propagated: "propagated";
                resolution: "resolution";
            }>>;
        }, z.core.$strip>>;
        roles: z.ZodOptional<z.ZodArray<z.ZodString>>;
    }, z.core.$strip>>;
}, z.core.$strip>;
export type Security_Entity_Analytics_API_UserEntity = z.infer<typeof Security_Entity_Analytics_API_UserEntity>;
export declare const Security_Entity_Analytics_API_Entity: z.ZodUnion<readonly [z.ZodObject<{
    '@timestamp': z.ZodOptional<z.ZodString>;
    asset: z.ZodOptional<z.ZodObject<{
        business_unit: z.ZodOptional<z.ZodString>;
        criticality: z.ZodOptional<z.ZodEnum<{
            low_impact: "low_impact";
            medium_impact: "medium_impact";
            high_impact: "high_impact";
            extreme_impact: "extreme_impact";
        }>>;
        environment: z.ZodOptional<z.ZodString>;
        id: z.ZodOptional<z.ZodString>;
        model: z.ZodOptional<z.ZodString>;
        name: z.ZodOptional<z.ZodString>;
        owner: z.ZodOptional<z.ZodString>;
        serial_number: z.ZodOptional<z.ZodString>;
        vendor: z.ZodOptional<z.ZodString>;
    }, z.core.$strip>>;
    entity: z.ZodObject<{
        attributes: z.ZodOptional<z.ZodObject<{
            asset: z.ZodOptional<z.ZodBoolean>;
            managed: z.ZodOptional<z.ZodBoolean>;
            mfa_enabled: z.ZodOptional<z.ZodBoolean>;
            privileged: z.ZodOptional<z.ZodBoolean>;
        }, z.core.$strip>>;
        behaviors: z.ZodOptional<z.ZodObject<{
            brute_force_victim: z.ZodOptional<z.ZodBoolean>;
            new_country_login: z.ZodOptional<z.ZodBoolean>;
            used_usb_device: z.ZodOptional<z.ZodBoolean>;
        }, z.core.$strip>>;
        EngineMetadata: z.ZodOptional<z.ZodObject<{
            Type: z.ZodString;
        }, z.core.$strip>>;
        id: z.ZodString;
        lifecycle: z.ZodOptional<z.ZodObject<{
            first_seen: z.ZodOptional<z.ZodString>;
            last_activity: z.ZodOptional<z.ZodString>;
            last_seen: z.ZodOptional<z.ZodString>;
        }, z.core.$strip>>;
        name: z.ZodOptional<z.ZodString>;
        relationships: z.ZodOptional<z.ZodObject<{
            accessed_frequently_by: z.ZodOptional<z.ZodArray<z.ZodString>>;
            accesses_frequently: z.ZodOptional<z.ZodArray<z.ZodString>>;
            accesses_infrequently: z.ZodOptional<z.ZodArray<z.ZodString>>;
            communicates_with: z.ZodOptional<z.ZodArray<z.ZodString>>;
            dependent_of: z.ZodOptional<z.ZodArray<z.ZodString>>;
            depends_on: z.ZodOptional<z.ZodArray<z.ZodString>>;
            owned_by: z.ZodOptional<z.ZodArray<z.ZodString>>;
            owns: z.ZodOptional<z.ZodArray<z.ZodString>>;
            supervised_by: z.ZodOptional<z.ZodArray<z.ZodString>>;
            supervises: z.ZodOptional<z.ZodArray<z.ZodString>>;
        }, z.core.$strip>>;
        risk: z.ZodOptional<z.ZodObject<{
            calculated_level: z.ZodOptional<z.ZodEnum<{
                Unknown: "Unknown";
                Low: "Low";
                Moderate: "Moderate";
                High: "High";
                Critical: "Critical";
            }>>;
            calculated_score: z.ZodOptional<z.ZodNumber>;
            calculated_score_norm: z.ZodOptional<z.ZodNumber>;
        }, z.core.$strip>>;
        source: z.ZodOptional<z.ZodString>;
        sub_type: z.ZodOptional<z.ZodString>;
        type: z.ZodOptional<z.ZodString>;
    }, z.core.$strip>;
    event: z.ZodOptional<z.ZodObject<{
        ingested: z.ZodOptional<z.ZodString>;
    }, z.core.$strip>>;
    user: z.ZodOptional<z.ZodObject<{
        domain: z.ZodOptional<z.ZodArray<z.ZodString>>;
        email: z.ZodOptional<z.ZodArray<z.ZodString>>;
        full_name: z.ZodOptional<z.ZodArray<z.ZodString>>;
        hash: z.ZodOptional<z.ZodArray<z.ZodString>>;
        id: z.ZodOptional<z.ZodArray<z.ZodString>>;
        name: z.ZodString;
        risk: z.ZodOptional<z.ZodObject<{
            '@timestamp': z.ZodString;
            calculated_level: z.ZodEnum<{
                Unknown: "Unknown";
                Low: "Low";
                Moderate: "Moderate";
                High: "High";
                Critical: "Critical";
            }>;
            calculated_score: z.ZodNumber;
            calculated_score_norm: z.ZodNumber;
            calculation_run_id: z.ZodOptional<z.ZodString>;
            category_1_count: z.ZodNumber;
            category_1_score: z.ZodNumber;
            category_2_count: z.ZodOptional<z.ZodNumber>;
            category_2_score: z.ZodOptional<z.ZodNumber>;
            criticality_level: z.ZodOptional<z.ZodEnum<{
                low_impact: "low_impact";
                medium_impact: "medium_impact";
                high_impact: "high_impact";
                extreme_impact: "extreme_impact";
            }>>;
            criticality_modifier: z.ZodOptional<z.ZodNumber>;
            id_field: z.ZodString;
            id_value: z.ZodString;
            inputs: z.ZodArray<z.ZodObject<{
                category: z.ZodString;
                contribution_score: z.ZodOptional<z.ZodNumber>;
                description: z.ZodString;
                entity_id: z.ZodOptional<z.ZodString>;
                id: z.ZodString;
                index: z.ZodString;
                risk_score: z.ZodOptional<z.ZodNumber>;
                timestamp: z.ZodOptional<z.ZodString>;
            }, z.core.$strip>>;
            modifiers: z.ZodOptional<z.ZodArray<z.ZodObject<{
                contribution: z.ZodNumber;
                metadata: z.ZodOptional<z.ZodRecord<z.ZodString, z.ZodUnknown>>;
                modifier_value: z.ZodOptional<z.ZodNumber>;
                subtype: z.ZodOptional<z.ZodString>;
                type: z.ZodString;
            }, z.core.$strip>>>;
            notes: z.ZodArray<z.ZodString>;
            related_entities: z.ZodOptional<z.ZodArray<z.ZodObject<{
                entity_id: z.ZodOptional<z.ZodString>;
                relationship_type: z.ZodOptional<z.ZodString>;
            }, z.core.$strip>>>;
            score_type: z.ZodOptional<z.ZodEnum<{
                base: "base";
                propagated: "propagated";
                resolution: "resolution";
            }>>;
        }, z.core.$strip>>;
        roles: z.ZodOptional<z.ZodArray<z.ZodString>>;
    }, z.core.$strip>>;
}, z.core.$strip>, z.ZodObject<{
    '@timestamp': z.ZodOptional<z.ZodString>;
    asset: z.ZodOptional<z.ZodObject<{
        business_unit: z.ZodOptional<z.ZodString>;
        criticality: z.ZodOptional<z.ZodEnum<{
            low_impact: "low_impact";
            medium_impact: "medium_impact";
            high_impact: "high_impact";
            extreme_impact: "extreme_impact";
        }>>;
        environment: z.ZodOptional<z.ZodString>;
        id: z.ZodOptional<z.ZodString>;
        model: z.ZodOptional<z.ZodString>;
        name: z.ZodOptional<z.ZodString>;
        owner: z.ZodOptional<z.ZodString>;
        serial_number: z.ZodOptional<z.ZodString>;
        vendor: z.ZodOptional<z.ZodString>;
    }, z.core.$strip>>;
    entity: z.ZodObject<{
        attributes: z.ZodOptional<z.ZodObject<{
            asset: z.ZodOptional<z.ZodBoolean>;
            managed: z.ZodOptional<z.ZodBoolean>;
            mfa_enabled: z.ZodOptional<z.ZodBoolean>;
            privileged: z.ZodOptional<z.ZodBoolean>;
        }, z.core.$strip>>;
        behaviors: z.ZodOptional<z.ZodObject<{
            brute_force_victim: z.ZodOptional<z.ZodBoolean>;
            new_country_login: z.ZodOptional<z.ZodBoolean>;
            used_usb_device: z.ZodOptional<z.ZodBoolean>;
        }, z.core.$strip>>;
        EngineMetadata: z.ZodOptional<z.ZodObject<{
            Type: z.ZodString;
        }, z.core.$strip>>;
        id: z.ZodString;
        lifecycle: z.ZodOptional<z.ZodObject<{
            first_seen: z.ZodOptional<z.ZodString>;
            last_activity: z.ZodOptional<z.ZodString>;
            last_seen: z.ZodOptional<z.ZodString>;
        }, z.core.$strip>>;
        name: z.ZodOptional<z.ZodString>;
        relationships: z.ZodOptional<z.ZodObject<{
            accessed_frequently_by: z.ZodOptional<z.ZodArray<z.ZodString>>;
            accesses_frequently: z.ZodOptional<z.ZodArray<z.ZodString>>;
            accesses_infrequently: z.ZodOptional<z.ZodArray<z.ZodString>>;
            communicates_with: z.ZodOptional<z.ZodArray<z.ZodString>>;
            dependent_of: z.ZodOptional<z.ZodArray<z.ZodString>>;
            depends_on: z.ZodOptional<z.ZodArray<z.ZodString>>;
            owned_by: z.ZodOptional<z.ZodArray<z.ZodString>>;
            owns: z.ZodOptional<z.ZodArray<z.ZodString>>;
            supervised_by: z.ZodOptional<z.ZodArray<z.ZodString>>;
            supervises: z.ZodOptional<z.ZodArray<z.ZodString>>;
        }, z.core.$strip>>;
        risk: z.ZodOptional<z.ZodObject<{
            calculated_level: z.ZodOptional<z.ZodEnum<{
                Unknown: "Unknown";
                Low: "Low";
                Moderate: "Moderate";
                High: "High";
                Critical: "Critical";
            }>>;
            calculated_score: z.ZodOptional<z.ZodNumber>;
            calculated_score_norm: z.ZodOptional<z.ZodNumber>;
        }, z.core.$strip>>;
        source: z.ZodOptional<z.ZodString>;
        sub_type: z.ZodOptional<z.ZodString>;
        type: z.ZodOptional<z.ZodString>;
    }, z.core.$strip>;
    event: z.ZodOptional<z.ZodObject<{
        ingested: z.ZodOptional<z.ZodString>;
    }, z.core.$strip>>;
    host: z.ZodOptional<z.ZodObject<{
        architecture: z.ZodOptional<z.ZodArray<z.ZodString>>;
        domain: z.ZodOptional<z.ZodArray<z.ZodString>>;
        entity: z.ZodOptional<z.ZodObject<{
            attributes: z.ZodOptional<z.ZodObject<{
                asset: z.ZodOptional<z.ZodBoolean>;
                managed: z.ZodOptional<z.ZodBoolean>;
                mfa_enabled: z.ZodOptional<z.ZodBoolean>;
                privileged: z.ZodOptional<z.ZodBoolean>;
            }, z.core.$strip>>;
            behaviors: z.ZodOptional<z.ZodObject<{
                brute_force_victim: z.ZodOptional<z.ZodBoolean>;
                new_country_login: z.ZodOptional<z.ZodBoolean>;
                used_usb_device: z.ZodOptional<z.ZodBoolean>;
            }, z.core.$strip>>;
            EngineMetadata: z.ZodOptional<z.ZodObject<{
                Type: z.ZodString;
            }, z.core.$strip>>;
            id: z.ZodString;
            lifecycle: z.ZodOptional<z.ZodObject<{
                first_seen: z.ZodOptional<z.ZodString>;
                last_activity: z.ZodOptional<z.ZodString>;
                last_seen: z.ZodOptional<z.ZodString>;
            }, z.core.$strip>>;
            name: z.ZodOptional<z.ZodString>;
            relationships: z.ZodOptional<z.ZodObject<{
                accessed_frequently_by: z.ZodOptional<z.ZodArray<z.ZodString>>;
                accesses_frequently: z.ZodOptional<z.ZodArray<z.ZodString>>;
                accesses_infrequently: z.ZodOptional<z.ZodArray<z.ZodString>>;
                communicates_with: z.ZodOptional<z.ZodArray<z.ZodString>>;
                dependent_of: z.ZodOptional<z.ZodArray<z.ZodString>>;
                depends_on: z.ZodOptional<z.ZodArray<z.ZodString>>;
                owned_by: z.ZodOptional<z.ZodArray<z.ZodString>>;
                owns: z.ZodOptional<z.ZodArray<z.ZodString>>;
                supervised_by: z.ZodOptional<z.ZodArray<z.ZodString>>;
                supervises: z.ZodOptional<z.ZodArray<z.ZodString>>;
            }, z.core.$strip>>;
            risk: z.ZodOptional<z.ZodObject<{
                calculated_level: z.ZodOptional<z.ZodEnum<{
                    Unknown: "Unknown";
                    Low: "Low";
                    Moderate: "Moderate";
                    High: "High";
                    Critical: "Critical";
                }>>;
                calculated_score: z.ZodOptional<z.ZodNumber>;
                calculated_score_norm: z.ZodOptional<z.ZodNumber>;
            }, z.core.$strip>>;
            source: z.ZodOptional<z.ZodString>;
            sub_type: z.ZodOptional<z.ZodString>;
            type: z.ZodOptional<z.ZodString>;
        }, z.core.$strip>>;
        hostname: z.ZodOptional<z.ZodArray<z.ZodString>>;
        id: z.ZodOptional<z.ZodArray<z.ZodString>>;
        ip: z.ZodOptional<z.ZodArray<z.ZodString>>;
        mac: z.ZodOptional<z.ZodArray<z.ZodString>>;
        name: z.ZodString;
        os: z.ZodOptional<z.ZodObject<{
            family: z.ZodOptional<z.ZodString>;
            full: z.ZodOptional<z.ZodString>;
            kernel: z.ZodOptional<z.ZodString>;
            name: z.ZodOptional<z.ZodUnion<readonly [z.ZodString, z.ZodArray<z.ZodString>]>>;
            platform: z.ZodOptional<z.ZodString>;
            type: z.ZodOptional<z.ZodUnion<readonly [z.ZodString, z.ZodArray<z.ZodString>]>>;
            version: z.ZodOptional<z.ZodString>;
        }, z.core.$strip>>;
        risk: z.ZodOptional<z.ZodObject<{
            '@timestamp': z.ZodString;
            calculated_level: z.ZodEnum<{
                Unknown: "Unknown";
                Low: "Low";
                Moderate: "Moderate";
                High: "High";
                Critical: "Critical";
            }>;
            calculated_score: z.ZodNumber;
            calculated_score_norm: z.ZodNumber;
            calculation_run_id: z.ZodOptional<z.ZodString>;
            category_1_count: z.ZodNumber;
            category_1_score: z.ZodNumber;
            category_2_count: z.ZodOptional<z.ZodNumber>;
            category_2_score: z.ZodOptional<z.ZodNumber>;
            criticality_level: z.ZodOptional<z.ZodEnum<{
                low_impact: "low_impact";
                medium_impact: "medium_impact";
                high_impact: "high_impact";
                extreme_impact: "extreme_impact";
            }>>;
            criticality_modifier: z.ZodOptional<z.ZodNumber>;
            id_field: z.ZodString;
            id_value: z.ZodString;
            inputs: z.ZodArray<z.ZodObject<{
                category: z.ZodString;
                contribution_score: z.ZodOptional<z.ZodNumber>;
                description: z.ZodString;
                entity_id: z.ZodOptional<z.ZodString>;
                id: z.ZodString;
                index: z.ZodString;
                risk_score: z.ZodOptional<z.ZodNumber>;
                timestamp: z.ZodOptional<z.ZodString>;
            }, z.core.$strip>>;
            modifiers: z.ZodOptional<z.ZodArray<z.ZodObject<{
                contribution: z.ZodNumber;
                metadata: z.ZodOptional<z.ZodRecord<z.ZodString, z.ZodUnknown>>;
                modifier_value: z.ZodOptional<z.ZodNumber>;
                subtype: z.ZodOptional<z.ZodString>;
                type: z.ZodString;
            }, z.core.$strip>>>;
            notes: z.ZodArray<z.ZodString>;
            related_entities: z.ZodOptional<z.ZodArray<z.ZodObject<{
                entity_id: z.ZodOptional<z.ZodString>;
                relationship_type: z.ZodOptional<z.ZodString>;
            }, z.core.$strip>>>;
            score_type: z.ZodOptional<z.ZodEnum<{
                base: "base";
                propagated: "propagated";
                resolution: "resolution";
            }>>;
        }, z.core.$strip>>;
        type: z.ZodOptional<z.ZodArray<z.ZodString>>;
    }, z.core.$strip>>;
}, z.core.$strip>, z.ZodObject<{
    '@timestamp': z.ZodOptional<z.ZodString>;
    asset: z.ZodOptional<z.ZodObject<{
        business_unit: z.ZodOptional<z.ZodString>;
        criticality: z.ZodOptional<z.ZodEnum<{
            low_impact: "low_impact";
            medium_impact: "medium_impact";
            high_impact: "high_impact";
            extreme_impact: "extreme_impact";
        }>>;
        environment: z.ZodOptional<z.ZodString>;
        id: z.ZodOptional<z.ZodString>;
        model: z.ZodOptional<z.ZodString>;
        name: z.ZodOptional<z.ZodString>;
        owner: z.ZodOptional<z.ZodString>;
        serial_number: z.ZodOptional<z.ZodString>;
        vendor: z.ZodOptional<z.ZodString>;
    }, z.core.$strip>>;
    entity: z.ZodObject<{
        attributes: z.ZodOptional<z.ZodObject<{
            asset: z.ZodOptional<z.ZodBoolean>;
            managed: z.ZodOptional<z.ZodBoolean>;
            mfa_enabled: z.ZodOptional<z.ZodBoolean>;
            privileged: z.ZodOptional<z.ZodBoolean>;
        }, z.core.$strip>>;
        behaviors: z.ZodOptional<z.ZodObject<{
            brute_force_victim: z.ZodOptional<z.ZodBoolean>;
            new_country_login: z.ZodOptional<z.ZodBoolean>;
            used_usb_device: z.ZodOptional<z.ZodBoolean>;
        }, z.core.$strip>>;
        EngineMetadata: z.ZodOptional<z.ZodObject<{
            Type: z.ZodString;
        }, z.core.$strip>>;
        id: z.ZodString;
        lifecycle: z.ZodOptional<z.ZodObject<{
            first_seen: z.ZodOptional<z.ZodString>;
            last_activity: z.ZodOptional<z.ZodString>;
            last_seen: z.ZodOptional<z.ZodString>;
        }, z.core.$strip>>;
        name: z.ZodOptional<z.ZodString>;
        relationships: z.ZodOptional<z.ZodObject<{
            accessed_frequently_by: z.ZodOptional<z.ZodArray<z.ZodString>>;
            accesses_frequently: z.ZodOptional<z.ZodArray<z.ZodString>>;
            accesses_infrequently: z.ZodOptional<z.ZodArray<z.ZodString>>;
            communicates_with: z.ZodOptional<z.ZodArray<z.ZodString>>;
            dependent_of: z.ZodOptional<z.ZodArray<z.ZodString>>;
            depends_on: z.ZodOptional<z.ZodArray<z.ZodString>>;
            owned_by: z.ZodOptional<z.ZodArray<z.ZodString>>;
            owns: z.ZodOptional<z.ZodArray<z.ZodString>>;
            supervised_by: z.ZodOptional<z.ZodArray<z.ZodString>>;
            supervises: z.ZodOptional<z.ZodArray<z.ZodString>>;
        }, z.core.$strip>>;
        risk: z.ZodOptional<z.ZodObject<{
            calculated_level: z.ZodOptional<z.ZodEnum<{
                Unknown: "Unknown";
                Low: "Low";
                Moderate: "Moderate";
                High: "High";
                Critical: "Critical";
            }>>;
            calculated_score: z.ZodOptional<z.ZodNumber>;
            calculated_score_norm: z.ZodOptional<z.ZodNumber>;
        }, z.core.$strip>>;
        source: z.ZodOptional<z.ZodString>;
        sub_type: z.ZodOptional<z.ZodString>;
        type: z.ZodOptional<z.ZodString>;
    }, z.core.$strip>;
    event: z.ZodOptional<z.ZodObject<{
        ingested: z.ZodOptional<z.ZodString>;
    }, z.core.$strip>>;
    service: z.ZodOptional<z.ZodObject<{
        entity: z.ZodOptional<z.ZodObject<{
            attributes: z.ZodOptional<z.ZodObject<{
                asset: z.ZodOptional<z.ZodBoolean>;
                managed: z.ZodOptional<z.ZodBoolean>;
                mfa_enabled: z.ZodOptional<z.ZodBoolean>;
                privileged: z.ZodOptional<z.ZodBoolean>;
            }, z.core.$strip>>;
            behaviors: z.ZodOptional<z.ZodObject<{
                brute_force_victim: z.ZodOptional<z.ZodBoolean>;
                new_country_login: z.ZodOptional<z.ZodBoolean>;
                used_usb_device: z.ZodOptional<z.ZodBoolean>;
            }, z.core.$strip>>;
            EngineMetadata: z.ZodOptional<z.ZodObject<{
                Type: z.ZodString;
            }, z.core.$strip>>;
            id: z.ZodString;
            lifecycle: z.ZodOptional<z.ZodObject<{
                first_seen: z.ZodOptional<z.ZodString>;
                last_activity: z.ZodOptional<z.ZodString>;
                last_seen: z.ZodOptional<z.ZodString>;
            }, z.core.$strip>>;
            name: z.ZodOptional<z.ZodString>;
            relationships: z.ZodOptional<z.ZodObject<{
                accessed_frequently_by: z.ZodOptional<z.ZodArray<z.ZodString>>;
                accesses_frequently: z.ZodOptional<z.ZodArray<z.ZodString>>;
                accesses_infrequently: z.ZodOptional<z.ZodArray<z.ZodString>>;
                communicates_with: z.ZodOptional<z.ZodArray<z.ZodString>>;
                dependent_of: z.ZodOptional<z.ZodArray<z.ZodString>>;
                depends_on: z.ZodOptional<z.ZodArray<z.ZodString>>;
                owned_by: z.ZodOptional<z.ZodArray<z.ZodString>>;
                owns: z.ZodOptional<z.ZodArray<z.ZodString>>;
                supervised_by: z.ZodOptional<z.ZodArray<z.ZodString>>;
                supervises: z.ZodOptional<z.ZodArray<z.ZodString>>;
            }, z.core.$strip>>;
            risk: z.ZodOptional<z.ZodObject<{
                calculated_level: z.ZodOptional<z.ZodEnum<{
                    Unknown: "Unknown";
                    Low: "Low";
                    Moderate: "Moderate";
                    High: "High";
                    Critical: "Critical";
                }>>;
                calculated_score: z.ZodOptional<z.ZodNumber>;
                calculated_score_norm: z.ZodOptional<z.ZodNumber>;
            }, z.core.$strip>>;
            source: z.ZodOptional<z.ZodString>;
            sub_type: z.ZodOptional<z.ZodString>;
            type: z.ZodOptional<z.ZodString>;
        }, z.core.$strip>>;
        name: z.ZodString;
        risk: z.ZodOptional<z.ZodObject<{
            '@timestamp': z.ZodString;
            calculated_level: z.ZodEnum<{
                Unknown: "Unknown";
                Low: "Low";
                Moderate: "Moderate";
                High: "High";
                Critical: "Critical";
            }>;
            calculated_score: z.ZodNumber;
            calculated_score_norm: z.ZodNumber;
            calculation_run_id: z.ZodOptional<z.ZodString>;
            category_1_count: z.ZodNumber;
            category_1_score: z.ZodNumber;
            category_2_count: z.ZodOptional<z.ZodNumber>;
            category_2_score: z.ZodOptional<z.ZodNumber>;
            criticality_level: z.ZodOptional<z.ZodEnum<{
                low_impact: "low_impact";
                medium_impact: "medium_impact";
                high_impact: "high_impact";
                extreme_impact: "extreme_impact";
            }>>;
            criticality_modifier: z.ZodOptional<z.ZodNumber>;
            id_field: z.ZodString;
            id_value: z.ZodString;
            inputs: z.ZodArray<z.ZodObject<{
                category: z.ZodString;
                contribution_score: z.ZodOptional<z.ZodNumber>;
                description: z.ZodString;
                entity_id: z.ZodOptional<z.ZodString>;
                id: z.ZodString;
                index: z.ZodString;
                risk_score: z.ZodOptional<z.ZodNumber>;
                timestamp: z.ZodOptional<z.ZodString>;
            }, z.core.$strip>>;
            modifiers: z.ZodOptional<z.ZodArray<z.ZodObject<{
                contribution: z.ZodNumber;
                metadata: z.ZodOptional<z.ZodRecord<z.ZodString, z.ZodUnknown>>;
                modifier_value: z.ZodOptional<z.ZodNumber>;
                subtype: z.ZodOptional<z.ZodString>;
                type: z.ZodString;
            }, z.core.$strip>>>;
            notes: z.ZodArray<z.ZodString>;
            related_entities: z.ZodOptional<z.ZodArray<z.ZodObject<{
                entity_id: z.ZodOptional<z.ZodString>;
                relationship_type: z.ZodOptional<z.ZodString>;
            }, z.core.$strip>>>;
            score_type: z.ZodOptional<z.ZodEnum<{
                base: "base";
                propagated: "propagated";
                resolution: "resolution";
            }>>;
        }, z.core.$strip>>;
    }, z.core.$strip>>;
}, z.core.$strip>, z.ZodObject<{
    '@timestamp': z.ZodOptional<z.ZodString>;
    asset: z.ZodOptional<z.ZodObject<{
        business_unit: z.ZodOptional<z.ZodString>;
        criticality: z.ZodOptional<z.ZodEnum<{
            low_impact: "low_impact";
            medium_impact: "medium_impact";
            high_impact: "high_impact";
            extreme_impact: "extreme_impact";
        }>>;
        environment: z.ZodOptional<z.ZodString>;
        id: z.ZodOptional<z.ZodString>;
        model: z.ZodOptional<z.ZodString>;
        name: z.ZodOptional<z.ZodString>;
        owner: z.ZodOptional<z.ZodString>;
        serial_number: z.ZodOptional<z.ZodString>;
        vendor: z.ZodOptional<z.ZodString>;
    }, z.core.$strip>>;
    entity: z.ZodObject<{
        attributes: z.ZodOptional<z.ZodObject<{
            asset: z.ZodOptional<z.ZodBoolean>;
            managed: z.ZodOptional<z.ZodBoolean>;
            mfa_enabled: z.ZodOptional<z.ZodBoolean>;
            privileged: z.ZodOptional<z.ZodBoolean>;
        }, z.core.$strip>>;
        behaviors: z.ZodOptional<z.ZodObject<{
            brute_force_victim: z.ZodOptional<z.ZodBoolean>;
            new_country_login: z.ZodOptional<z.ZodBoolean>;
            used_usb_device: z.ZodOptional<z.ZodBoolean>;
        }, z.core.$strip>>;
        EngineMetadata: z.ZodOptional<z.ZodObject<{
            Type: z.ZodString;
        }, z.core.$strip>>;
        id: z.ZodString;
        lifecycle: z.ZodOptional<z.ZodObject<{
            first_seen: z.ZodOptional<z.ZodString>;
            last_activity: z.ZodOptional<z.ZodString>;
            last_seen: z.ZodOptional<z.ZodString>;
        }, z.core.$strip>>;
        name: z.ZodOptional<z.ZodString>;
        relationships: z.ZodOptional<z.ZodObject<{
            accessed_frequently_by: z.ZodOptional<z.ZodArray<z.ZodString>>;
            accesses_frequently: z.ZodOptional<z.ZodArray<z.ZodString>>;
            accesses_infrequently: z.ZodOptional<z.ZodArray<z.ZodString>>;
            communicates_with: z.ZodOptional<z.ZodArray<z.ZodString>>;
            dependent_of: z.ZodOptional<z.ZodArray<z.ZodString>>;
            depends_on: z.ZodOptional<z.ZodArray<z.ZodString>>;
            owned_by: z.ZodOptional<z.ZodArray<z.ZodString>>;
            owns: z.ZodOptional<z.ZodArray<z.ZodString>>;
            supervised_by: z.ZodOptional<z.ZodArray<z.ZodString>>;
            supervises: z.ZodOptional<z.ZodArray<z.ZodString>>;
        }, z.core.$strip>>;
        risk: z.ZodOptional<z.ZodObject<{
            calculated_level: z.ZodOptional<z.ZodEnum<{
                Unknown: "Unknown";
                Low: "Low";
                Moderate: "Moderate";
                High: "High";
                Critical: "Critical";
            }>>;
            calculated_score: z.ZodOptional<z.ZodNumber>;
            calculated_score_norm: z.ZodOptional<z.ZodNumber>;
        }, z.core.$strip>>;
        source: z.ZodOptional<z.ZodString>;
        sub_type: z.ZodOptional<z.ZodString>;
        type: z.ZodOptional<z.ZodString>;
    }, z.core.$strip>;
}, z.core.$strip>]>;
export type Security_Entity_Analytics_API_Entity = z.infer<typeof Security_Entity_Analytics_API_Entity>;
export declare const ListEntitiesResponse: z.ZodObject<{
    inspect: z.ZodOptional<z.ZodObject<{
        dsl: z.ZodArray<z.ZodString>;
        response: z.ZodArray<z.ZodString>;
    }, z.core.$strip>>;
    page: z.ZodNumber;
    per_page: z.ZodNumber;
    records: z.ZodArray<z.ZodUnion<readonly [z.ZodObject<{
        '@timestamp': z.ZodOptional<z.ZodString>;
        asset: z.ZodOptional<z.ZodObject<{
            business_unit: z.ZodOptional<z.ZodString>;
            criticality: z.ZodOptional<z.ZodEnum<{
                low_impact: "low_impact";
                medium_impact: "medium_impact";
                high_impact: "high_impact";
                extreme_impact: "extreme_impact";
            }>>;
            environment: z.ZodOptional<z.ZodString>;
            id: z.ZodOptional<z.ZodString>;
            model: z.ZodOptional<z.ZodString>;
            name: z.ZodOptional<z.ZodString>;
            owner: z.ZodOptional<z.ZodString>;
            serial_number: z.ZodOptional<z.ZodString>;
            vendor: z.ZodOptional<z.ZodString>;
        }, z.core.$strip>>;
        entity: z.ZodObject<{
            attributes: z.ZodOptional<z.ZodObject<{
                asset: z.ZodOptional<z.ZodBoolean>;
                managed: z.ZodOptional<z.ZodBoolean>;
                mfa_enabled: z.ZodOptional<z.ZodBoolean>;
                privileged: z.ZodOptional<z.ZodBoolean>;
            }, z.core.$strip>>;
            behaviors: z.ZodOptional<z.ZodObject<{
                brute_force_victim: z.ZodOptional<z.ZodBoolean>;
                new_country_login: z.ZodOptional<z.ZodBoolean>;
                used_usb_device: z.ZodOptional<z.ZodBoolean>;
            }, z.core.$strip>>;
            EngineMetadata: z.ZodOptional<z.ZodObject<{
                Type: z.ZodString;
            }, z.core.$strip>>;
            id: z.ZodString;
            lifecycle: z.ZodOptional<z.ZodObject<{
                first_seen: z.ZodOptional<z.ZodString>;
                last_activity: z.ZodOptional<z.ZodString>;
                last_seen: z.ZodOptional<z.ZodString>;
            }, z.core.$strip>>;
            name: z.ZodOptional<z.ZodString>;
            relationships: z.ZodOptional<z.ZodObject<{
                accessed_frequently_by: z.ZodOptional<z.ZodArray<z.ZodString>>;
                accesses_frequently: z.ZodOptional<z.ZodArray<z.ZodString>>;
                accesses_infrequently: z.ZodOptional<z.ZodArray<z.ZodString>>;
                communicates_with: z.ZodOptional<z.ZodArray<z.ZodString>>;
                dependent_of: z.ZodOptional<z.ZodArray<z.ZodString>>;
                depends_on: z.ZodOptional<z.ZodArray<z.ZodString>>;
                owned_by: z.ZodOptional<z.ZodArray<z.ZodString>>;
                owns: z.ZodOptional<z.ZodArray<z.ZodString>>;
                supervised_by: z.ZodOptional<z.ZodArray<z.ZodString>>;
                supervises: z.ZodOptional<z.ZodArray<z.ZodString>>;
            }, z.core.$strip>>;
            risk: z.ZodOptional<z.ZodObject<{
                calculated_level: z.ZodOptional<z.ZodEnum<{
                    Unknown: "Unknown";
                    Low: "Low";
                    Moderate: "Moderate";
                    High: "High";
                    Critical: "Critical";
                }>>;
                calculated_score: z.ZodOptional<z.ZodNumber>;
                calculated_score_norm: z.ZodOptional<z.ZodNumber>;
            }, z.core.$strip>>;
            source: z.ZodOptional<z.ZodString>;
            sub_type: z.ZodOptional<z.ZodString>;
            type: z.ZodOptional<z.ZodString>;
        }, z.core.$strip>;
        event: z.ZodOptional<z.ZodObject<{
            ingested: z.ZodOptional<z.ZodString>;
        }, z.core.$strip>>;
        user: z.ZodOptional<z.ZodObject<{
            domain: z.ZodOptional<z.ZodArray<z.ZodString>>;
            email: z.ZodOptional<z.ZodArray<z.ZodString>>;
            full_name: z.ZodOptional<z.ZodArray<z.ZodString>>;
            hash: z.ZodOptional<z.ZodArray<z.ZodString>>;
            id: z.ZodOptional<z.ZodArray<z.ZodString>>;
            name: z.ZodString;
            risk: z.ZodOptional<z.ZodObject<{
                '@timestamp': z.ZodString;
                calculated_level: z.ZodEnum<{
                    Unknown: "Unknown";
                    Low: "Low";
                    Moderate: "Moderate";
                    High: "High";
                    Critical: "Critical";
                }>;
                calculated_score: z.ZodNumber;
                calculated_score_norm: z.ZodNumber;
                calculation_run_id: z.ZodOptional<z.ZodString>;
                category_1_count: z.ZodNumber;
                category_1_score: z.ZodNumber;
                category_2_count: z.ZodOptional<z.ZodNumber>;
                category_2_score: z.ZodOptional<z.ZodNumber>;
                criticality_level: z.ZodOptional<z.ZodEnum<{
                    low_impact: "low_impact";
                    medium_impact: "medium_impact";
                    high_impact: "high_impact";
                    extreme_impact: "extreme_impact";
                }>>;
                criticality_modifier: z.ZodOptional<z.ZodNumber>;
                id_field: z.ZodString;
                id_value: z.ZodString;
                inputs: z.ZodArray<z.ZodObject<{
                    category: z.ZodString;
                    contribution_score: z.ZodOptional<z.ZodNumber>;
                    description: z.ZodString;
                    entity_id: z.ZodOptional<z.ZodString>;
                    id: z.ZodString;
                    index: z.ZodString;
                    risk_score: z.ZodOptional<z.ZodNumber>;
                    timestamp: z.ZodOptional<z.ZodString>;
                }, z.core.$strip>>;
                modifiers: z.ZodOptional<z.ZodArray<z.ZodObject<{
                    contribution: z.ZodNumber;
                    metadata: z.ZodOptional<z.ZodRecord<z.ZodString, z.ZodUnknown>>;
                    modifier_value: z.ZodOptional<z.ZodNumber>;
                    subtype: z.ZodOptional<z.ZodString>;
                    type: z.ZodString;
                }, z.core.$strip>>>;
                notes: z.ZodArray<z.ZodString>;
                related_entities: z.ZodOptional<z.ZodArray<z.ZodObject<{
                    entity_id: z.ZodOptional<z.ZodString>;
                    relationship_type: z.ZodOptional<z.ZodString>;
                }, z.core.$strip>>>;
                score_type: z.ZodOptional<z.ZodEnum<{
                    base: "base";
                    propagated: "propagated";
                    resolution: "resolution";
                }>>;
            }, z.core.$strip>>;
            roles: z.ZodOptional<z.ZodArray<z.ZodString>>;
        }, z.core.$strip>>;
    }, z.core.$strip>, z.ZodObject<{
        '@timestamp': z.ZodOptional<z.ZodString>;
        asset: z.ZodOptional<z.ZodObject<{
            business_unit: z.ZodOptional<z.ZodString>;
            criticality: z.ZodOptional<z.ZodEnum<{
                low_impact: "low_impact";
                medium_impact: "medium_impact";
                high_impact: "high_impact";
                extreme_impact: "extreme_impact";
            }>>;
            environment: z.ZodOptional<z.ZodString>;
            id: z.ZodOptional<z.ZodString>;
            model: z.ZodOptional<z.ZodString>;
            name: z.ZodOptional<z.ZodString>;
            owner: z.ZodOptional<z.ZodString>;
            serial_number: z.ZodOptional<z.ZodString>;
            vendor: z.ZodOptional<z.ZodString>;
        }, z.core.$strip>>;
        entity: z.ZodObject<{
            attributes: z.ZodOptional<z.ZodObject<{
                asset: z.ZodOptional<z.ZodBoolean>;
                managed: z.ZodOptional<z.ZodBoolean>;
                mfa_enabled: z.ZodOptional<z.ZodBoolean>;
                privileged: z.ZodOptional<z.ZodBoolean>;
            }, z.core.$strip>>;
            behaviors: z.ZodOptional<z.ZodObject<{
                brute_force_victim: z.ZodOptional<z.ZodBoolean>;
                new_country_login: z.ZodOptional<z.ZodBoolean>;
                used_usb_device: z.ZodOptional<z.ZodBoolean>;
            }, z.core.$strip>>;
            EngineMetadata: z.ZodOptional<z.ZodObject<{
                Type: z.ZodString;
            }, z.core.$strip>>;
            id: z.ZodString;
            lifecycle: z.ZodOptional<z.ZodObject<{
                first_seen: z.ZodOptional<z.ZodString>;
                last_activity: z.ZodOptional<z.ZodString>;
                last_seen: z.ZodOptional<z.ZodString>;
            }, z.core.$strip>>;
            name: z.ZodOptional<z.ZodString>;
            relationships: z.ZodOptional<z.ZodObject<{
                accessed_frequently_by: z.ZodOptional<z.ZodArray<z.ZodString>>;
                accesses_frequently: z.ZodOptional<z.ZodArray<z.ZodString>>;
                accesses_infrequently: z.ZodOptional<z.ZodArray<z.ZodString>>;
                communicates_with: z.ZodOptional<z.ZodArray<z.ZodString>>;
                dependent_of: z.ZodOptional<z.ZodArray<z.ZodString>>;
                depends_on: z.ZodOptional<z.ZodArray<z.ZodString>>;
                owned_by: z.ZodOptional<z.ZodArray<z.ZodString>>;
                owns: z.ZodOptional<z.ZodArray<z.ZodString>>;
                supervised_by: z.ZodOptional<z.ZodArray<z.ZodString>>;
                supervises: z.ZodOptional<z.ZodArray<z.ZodString>>;
            }, z.core.$strip>>;
            risk: z.ZodOptional<z.ZodObject<{
                calculated_level: z.ZodOptional<z.ZodEnum<{
                    Unknown: "Unknown";
                    Low: "Low";
                    Moderate: "Moderate";
                    High: "High";
                    Critical: "Critical";
                }>>;
                calculated_score: z.ZodOptional<z.ZodNumber>;
                calculated_score_norm: z.ZodOptional<z.ZodNumber>;
            }, z.core.$strip>>;
            source: z.ZodOptional<z.ZodString>;
            sub_type: z.ZodOptional<z.ZodString>;
            type: z.ZodOptional<z.ZodString>;
        }, z.core.$strip>;
        event: z.ZodOptional<z.ZodObject<{
            ingested: z.ZodOptional<z.ZodString>;
        }, z.core.$strip>>;
        host: z.ZodOptional<z.ZodObject<{
            architecture: z.ZodOptional<z.ZodArray<z.ZodString>>;
            domain: z.ZodOptional<z.ZodArray<z.ZodString>>;
            entity: z.ZodOptional<z.ZodObject<{
                attributes: z.ZodOptional<z.ZodObject<{
                    asset: z.ZodOptional<z.ZodBoolean>;
                    managed: z.ZodOptional<z.ZodBoolean>;
                    mfa_enabled: z.ZodOptional<z.ZodBoolean>;
                    privileged: z.ZodOptional<z.ZodBoolean>;
                }, z.core.$strip>>;
                behaviors: z.ZodOptional<z.ZodObject<{
                    brute_force_victim: z.ZodOptional<z.ZodBoolean>;
                    new_country_login: z.ZodOptional<z.ZodBoolean>;
                    used_usb_device: z.ZodOptional<z.ZodBoolean>;
                }, z.core.$strip>>;
                EngineMetadata: z.ZodOptional<z.ZodObject<{
                    Type: z.ZodString;
                }, z.core.$strip>>;
                id: z.ZodString;
                lifecycle: z.ZodOptional<z.ZodObject<{
                    first_seen: z.ZodOptional<z.ZodString>;
                    last_activity: z.ZodOptional<z.ZodString>;
                    last_seen: z.ZodOptional<z.ZodString>;
                }, z.core.$strip>>;
                name: z.ZodOptional<z.ZodString>;
                relationships: z.ZodOptional<z.ZodObject<{
                    accessed_frequently_by: z.ZodOptional<z.ZodArray<z.ZodString>>;
                    accesses_frequently: z.ZodOptional<z.ZodArray<z.ZodString>>;
                    accesses_infrequently: z.ZodOptional<z.ZodArray<z.ZodString>>;
                    communicates_with: z.ZodOptional<z.ZodArray<z.ZodString>>;
                    dependent_of: z.ZodOptional<z.ZodArray<z.ZodString>>;
                    depends_on: z.ZodOptional<z.ZodArray<z.ZodString>>;
                    owned_by: z.ZodOptional<z.ZodArray<z.ZodString>>;
                    owns: z.ZodOptional<z.ZodArray<z.ZodString>>;
                    supervised_by: z.ZodOptional<z.ZodArray<z.ZodString>>;
                    supervises: z.ZodOptional<z.ZodArray<z.ZodString>>;
                }, z.core.$strip>>;
                risk: z.ZodOptional<z.ZodObject<{
                    calculated_level: z.ZodOptional<z.ZodEnum<{
                        Unknown: "Unknown";
                        Low: "Low";
                        Moderate: "Moderate";
                        High: "High";
                        Critical: "Critical";
                    }>>;
                    calculated_score: z.ZodOptional<z.ZodNumber>;
                    calculated_score_norm: z.ZodOptional<z.ZodNumber>;
                }, z.core.$strip>>;
                source: z.ZodOptional<z.ZodString>;
                sub_type: z.ZodOptional<z.ZodString>;
                type: z.ZodOptional<z.ZodString>;
            }, z.core.$strip>>;
            hostname: z.ZodOptional<z.ZodArray<z.ZodString>>;
            id: z.ZodOptional<z.ZodArray<z.ZodString>>;
            ip: z.ZodOptional<z.ZodArray<z.ZodString>>;
            mac: z.ZodOptional<z.ZodArray<z.ZodString>>;
            name: z.ZodString;
            os: z.ZodOptional<z.ZodObject<{
                family: z.ZodOptional<z.ZodString>;
                full: z.ZodOptional<z.ZodString>;
                kernel: z.ZodOptional<z.ZodString>;
                name: z.ZodOptional<z.ZodUnion<readonly [z.ZodString, z.ZodArray<z.ZodString>]>>;
                platform: z.ZodOptional<z.ZodString>;
                type: z.ZodOptional<z.ZodUnion<readonly [z.ZodString, z.ZodArray<z.ZodString>]>>;
                version: z.ZodOptional<z.ZodString>;
            }, z.core.$strip>>;
            risk: z.ZodOptional<z.ZodObject<{
                '@timestamp': z.ZodString;
                calculated_level: z.ZodEnum<{
                    Unknown: "Unknown";
                    Low: "Low";
                    Moderate: "Moderate";
                    High: "High";
                    Critical: "Critical";
                }>;
                calculated_score: z.ZodNumber;
                calculated_score_norm: z.ZodNumber;
                calculation_run_id: z.ZodOptional<z.ZodString>;
                category_1_count: z.ZodNumber;
                category_1_score: z.ZodNumber;
                category_2_count: z.ZodOptional<z.ZodNumber>;
                category_2_score: z.ZodOptional<z.ZodNumber>;
                criticality_level: z.ZodOptional<z.ZodEnum<{
                    low_impact: "low_impact";
                    medium_impact: "medium_impact";
                    high_impact: "high_impact";
                    extreme_impact: "extreme_impact";
                }>>;
                criticality_modifier: z.ZodOptional<z.ZodNumber>;
                id_field: z.ZodString;
                id_value: z.ZodString;
                inputs: z.ZodArray<z.ZodObject<{
                    category: z.ZodString;
                    contribution_score: z.ZodOptional<z.ZodNumber>;
                    description: z.ZodString;
                    entity_id: z.ZodOptional<z.ZodString>;
                    id: z.ZodString;
                    index: z.ZodString;
                    risk_score: z.ZodOptional<z.ZodNumber>;
                    timestamp: z.ZodOptional<z.ZodString>;
                }, z.core.$strip>>;
                modifiers: z.ZodOptional<z.ZodArray<z.ZodObject<{
                    contribution: z.ZodNumber;
                    metadata: z.ZodOptional<z.ZodRecord<z.ZodString, z.ZodUnknown>>;
                    modifier_value: z.ZodOptional<z.ZodNumber>;
                    subtype: z.ZodOptional<z.ZodString>;
                    type: z.ZodString;
                }, z.core.$strip>>>;
                notes: z.ZodArray<z.ZodString>;
                related_entities: z.ZodOptional<z.ZodArray<z.ZodObject<{
                    entity_id: z.ZodOptional<z.ZodString>;
                    relationship_type: z.ZodOptional<z.ZodString>;
                }, z.core.$strip>>>;
                score_type: z.ZodOptional<z.ZodEnum<{
                    base: "base";
                    propagated: "propagated";
                    resolution: "resolution";
                }>>;
            }, z.core.$strip>>;
            type: z.ZodOptional<z.ZodArray<z.ZodString>>;
        }, z.core.$strip>>;
    }, z.core.$strip>, z.ZodObject<{
        '@timestamp': z.ZodOptional<z.ZodString>;
        asset: z.ZodOptional<z.ZodObject<{
            business_unit: z.ZodOptional<z.ZodString>;
            criticality: z.ZodOptional<z.ZodEnum<{
                low_impact: "low_impact";
                medium_impact: "medium_impact";
                high_impact: "high_impact";
                extreme_impact: "extreme_impact";
            }>>;
            environment: z.ZodOptional<z.ZodString>;
            id: z.ZodOptional<z.ZodString>;
            model: z.ZodOptional<z.ZodString>;
            name: z.ZodOptional<z.ZodString>;
            owner: z.ZodOptional<z.ZodString>;
            serial_number: z.ZodOptional<z.ZodString>;
            vendor: z.ZodOptional<z.ZodString>;
        }, z.core.$strip>>;
        entity: z.ZodObject<{
            attributes: z.ZodOptional<z.ZodObject<{
                asset: z.ZodOptional<z.ZodBoolean>;
                managed: z.ZodOptional<z.ZodBoolean>;
                mfa_enabled: z.ZodOptional<z.ZodBoolean>;
                privileged: z.ZodOptional<z.ZodBoolean>;
            }, z.core.$strip>>;
            behaviors: z.ZodOptional<z.ZodObject<{
                brute_force_victim: z.ZodOptional<z.ZodBoolean>;
                new_country_login: z.ZodOptional<z.ZodBoolean>;
                used_usb_device: z.ZodOptional<z.ZodBoolean>;
            }, z.core.$strip>>;
            EngineMetadata: z.ZodOptional<z.ZodObject<{
                Type: z.ZodString;
            }, z.core.$strip>>;
            id: z.ZodString;
            lifecycle: z.ZodOptional<z.ZodObject<{
                first_seen: z.ZodOptional<z.ZodString>;
                last_activity: z.ZodOptional<z.ZodString>;
                last_seen: z.ZodOptional<z.ZodString>;
            }, z.core.$strip>>;
            name: z.ZodOptional<z.ZodString>;
            relationships: z.ZodOptional<z.ZodObject<{
                accessed_frequently_by: z.ZodOptional<z.ZodArray<z.ZodString>>;
                accesses_frequently: z.ZodOptional<z.ZodArray<z.ZodString>>;
                accesses_infrequently: z.ZodOptional<z.ZodArray<z.ZodString>>;
                communicates_with: z.ZodOptional<z.ZodArray<z.ZodString>>;
                dependent_of: z.ZodOptional<z.ZodArray<z.ZodString>>;
                depends_on: z.ZodOptional<z.ZodArray<z.ZodString>>;
                owned_by: z.ZodOptional<z.ZodArray<z.ZodString>>;
                owns: z.ZodOptional<z.ZodArray<z.ZodString>>;
                supervised_by: z.ZodOptional<z.ZodArray<z.ZodString>>;
                supervises: z.ZodOptional<z.ZodArray<z.ZodString>>;
            }, z.core.$strip>>;
            risk: z.ZodOptional<z.ZodObject<{
                calculated_level: z.ZodOptional<z.ZodEnum<{
                    Unknown: "Unknown";
                    Low: "Low";
                    Moderate: "Moderate";
                    High: "High";
                    Critical: "Critical";
                }>>;
                calculated_score: z.ZodOptional<z.ZodNumber>;
                calculated_score_norm: z.ZodOptional<z.ZodNumber>;
            }, z.core.$strip>>;
            source: z.ZodOptional<z.ZodString>;
            sub_type: z.ZodOptional<z.ZodString>;
            type: z.ZodOptional<z.ZodString>;
        }, z.core.$strip>;
        event: z.ZodOptional<z.ZodObject<{
            ingested: z.ZodOptional<z.ZodString>;
        }, z.core.$strip>>;
        service: z.ZodOptional<z.ZodObject<{
            entity: z.ZodOptional<z.ZodObject<{
                attributes: z.ZodOptional<z.ZodObject<{
                    asset: z.ZodOptional<z.ZodBoolean>;
                    managed: z.ZodOptional<z.ZodBoolean>;
                    mfa_enabled: z.ZodOptional<z.ZodBoolean>;
                    privileged: z.ZodOptional<z.ZodBoolean>;
                }, z.core.$strip>>;
                behaviors: z.ZodOptional<z.ZodObject<{
                    brute_force_victim: z.ZodOptional<z.ZodBoolean>;
                    new_country_login: z.ZodOptional<z.ZodBoolean>;
                    used_usb_device: z.ZodOptional<z.ZodBoolean>;
                }, z.core.$strip>>;
                EngineMetadata: z.ZodOptional<z.ZodObject<{
                    Type: z.ZodString;
                }, z.core.$strip>>;
                id: z.ZodString;
                lifecycle: z.ZodOptional<z.ZodObject<{
                    first_seen: z.ZodOptional<z.ZodString>;
                    last_activity: z.ZodOptional<z.ZodString>;
                    last_seen: z.ZodOptional<z.ZodString>;
                }, z.core.$strip>>;
                name: z.ZodOptional<z.ZodString>;
                relationships: z.ZodOptional<z.ZodObject<{
                    accessed_frequently_by: z.ZodOptional<z.ZodArray<z.ZodString>>;
                    accesses_frequently: z.ZodOptional<z.ZodArray<z.ZodString>>;
                    accesses_infrequently: z.ZodOptional<z.ZodArray<z.ZodString>>;
                    communicates_with: z.ZodOptional<z.ZodArray<z.ZodString>>;
                    dependent_of: z.ZodOptional<z.ZodArray<z.ZodString>>;
                    depends_on: z.ZodOptional<z.ZodArray<z.ZodString>>;
                    owned_by: z.ZodOptional<z.ZodArray<z.ZodString>>;
                    owns: z.ZodOptional<z.ZodArray<z.ZodString>>;
                    supervised_by: z.ZodOptional<z.ZodArray<z.ZodString>>;
                    supervises: z.ZodOptional<z.ZodArray<z.ZodString>>;
                }, z.core.$strip>>;
                risk: z.ZodOptional<z.ZodObject<{
                    calculated_level: z.ZodOptional<z.ZodEnum<{
                        Unknown: "Unknown";
                        Low: "Low";
                        Moderate: "Moderate";
                        High: "High";
                        Critical: "Critical";
                    }>>;
                    calculated_score: z.ZodOptional<z.ZodNumber>;
                    calculated_score_norm: z.ZodOptional<z.ZodNumber>;
                }, z.core.$strip>>;
                source: z.ZodOptional<z.ZodString>;
                sub_type: z.ZodOptional<z.ZodString>;
                type: z.ZodOptional<z.ZodString>;
            }, z.core.$strip>>;
            name: z.ZodString;
            risk: z.ZodOptional<z.ZodObject<{
                '@timestamp': z.ZodString;
                calculated_level: z.ZodEnum<{
                    Unknown: "Unknown";
                    Low: "Low";
                    Moderate: "Moderate";
                    High: "High";
                    Critical: "Critical";
                }>;
                calculated_score: z.ZodNumber;
                calculated_score_norm: z.ZodNumber;
                calculation_run_id: z.ZodOptional<z.ZodString>;
                category_1_count: z.ZodNumber;
                category_1_score: z.ZodNumber;
                category_2_count: z.ZodOptional<z.ZodNumber>;
                category_2_score: z.ZodOptional<z.ZodNumber>;
                criticality_level: z.ZodOptional<z.ZodEnum<{
                    low_impact: "low_impact";
                    medium_impact: "medium_impact";
                    high_impact: "high_impact";
                    extreme_impact: "extreme_impact";
                }>>;
                criticality_modifier: z.ZodOptional<z.ZodNumber>;
                id_field: z.ZodString;
                id_value: z.ZodString;
                inputs: z.ZodArray<z.ZodObject<{
                    category: z.ZodString;
                    contribution_score: z.ZodOptional<z.ZodNumber>;
                    description: z.ZodString;
                    entity_id: z.ZodOptional<z.ZodString>;
                    id: z.ZodString;
                    index: z.ZodString;
                    risk_score: z.ZodOptional<z.ZodNumber>;
                    timestamp: z.ZodOptional<z.ZodString>;
                }, z.core.$strip>>;
                modifiers: z.ZodOptional<z.ZodArray<z.ZodObject<{
                    contribution: z.ZodNumber;
                    metadata: z.ZodOptional<z.ZodRecord<z.ZodString, z.ZodUnknown>>;
                    modifier_value: z.ZodOptional<z.ZodNumber>;
                    subtype: z.ZodOptional<z.ZodString>;
                    type: z.ZodString;
                }, z.core.$strip>>>;
                notes: z.ZodArray<z.ZodString>;
                related_entities: z.ZodOptional<z.ZodArray<z.ZodObject<{
                    entity_id: z.ZodOptional<z.ZodString>;
                    relationship_type: z.ZodOptional<z.ZodString>;
                }, z.core.$strip>>>;
                score_type: z.ZodOptional<z.ZodEnum<{
                    base: "base";
                    propagated: "propagated";
                    resolution: "resolution";
                }>>;
            }, z.core.$strip>>;
        }, z.core.$strip>>;
    }, z.core.$strip>, z.ZodObject<{
        '@timestamp': z.ZodOptional<z.ZodString>;
        asset: z.ZodOptional<z.ZodObject<{
            business_unit: z.ZodOptional<z.ZodString>;
            criticality: z.ZodOptional<z.ZodEnum<{
                low_impact: "low_impact";
                medium_impact: "medium_impact";
                high_impact: "high_impact";
                extreme_impact: "extreme_impact";
            }>>;
            environment: z.ZodOptional<z.ZodString>;
            id: z.ZodOptional<z.ZodString>;
            model: z.ZodOptional<z.ZodString>;
            name: z.ZodOptional<z.ZodString>;
            owner: z.ZodOptional<z.ZodString>;
            serial_number: z.ZodOptional<z.ZodString>;
            vendor: z.ZodOptional<z.ZodString>;
        }, z.core.$strip>>;
        entity: z.ZodObject<{
            attributes: z.ZodOptional<z.ZodObject<{
                asset: z.ZodOptional<z.ZodBoolean>;
                managed: z.ZodOptional<z.ZodBoolean>;
                mfa_enabled: z.ZodOptional<z.ZodBoolean>;
                privileged: z.ZodOptional<z.ZodBoolean>;
            }, z.core.$strip>>;
            behaviors: z.ZodOptional<z.ZodObject<{
                brute_force_victim: z.ZodOptional<z.ZodBoolean>;
                new_country_login: z.ZodOptional<z.ZodBoolean>;
                used_usb_device: z.ZodOptional<z.ZodBoolean>;
            }, z.core.$strip>>;
            EngineMetadata: z.ZodOptional<z.ZodObject<{
                Type: z.ZodString;
            }, z.core.$strip>>;
            id: z.ZodString;
            lifecycle: z.ZodOptional<z.ZodObject<{
                first_seen: z.ZodOptional<z.ZodString>;
                last_activity: z.ZodOptional<z.ZodString>;
                last_seen: z.ZodOptional<z.ZodString>;
            }, z.core.$strip>>;
            name: z.ZodOptional<z.ZodString>;
            relationships: z.ZodOptional<z.ZodObject<{
                accessed_frequently_by: z.ZodOptional<z.ZodArray<z.ZodString>>;
                accesses_frequently: z.ZodOptional<z.ZodArray<z.ZodString>>;
                accesses_infrequently: z.ZodOptional<z.ZodArray<z.ZodString>>;
                communicates_with: z.ZodOptional<z.ZodArray<z.ZodString>>;
                dependent_of: z.ZodOptional<z.ZodArray<z.ZodString>>;
                depends_on: z.ZodOptional<z.ZodArray<z.ZodString>>;
                owned_by: z.ZodOptional<z.ZodArray<z.ZodString>>;
                owns: z.ZodOptional<z.ZodArray<z.ZodString>>;
                supervised_by: z.ZodOptional<z.ZodArray<z.ZodString>>;
                supervises: z.ZodOptional<z.ZodArray<z.ZodString>>;
            }, z.core.$strip>>;
            risk: z.ZodOptional<z.ZodObject<{
                calculated_level: z.ZodOptional<z.ZodEnum<{
                    Unknown: "Unknown";
                    Low: "Low";
                    Moderate: "Moderate";
                    High: "High";
                    Critical: "Critical";
                }>>;
                calculated_score: z.ZodOptional<z.ZodNumber>;
                calculated_score_norm: z.ZodOptional<z.ZodNumber>;
            }, z.core.$strip>>;
            source: z.ZodOptional<z.ZodString>;
            sub_type: z.ZodOptional<z.ZodString>;
            type: z.ZodOptional<z.ZodString>;
        }, z.core.$strip>;
    }, z.core.$strip>]>>;
    total: z.ZodNumber;
}, z.core.$strip>;
export type ListEntitiesResponse = z.infer<typeof ListEntitiesResponse>;
//# sourceMappingURL=list_entities.d.ts.map