import { z } from 'zod';
export declare const Security_Lists_API_ListItemValue: z.ZodString;
export type Security_Lists_API_ListItemValue = z.infer<typeof Security_Lists_API_ListItemValue>;
export declare const Security_Lists_API_ListType: z.ZodEnum<{
    boolean: "boolean";
    text: "text";
    date: "date";
    long: "long";
    integer: "integer";
    double: "double";
    float: "float";
    ip: "ip";
    keyword: "keyword";
    geo_point: "geo_point";
    geo_shape: "geo_shape";
    byte: "byte";
    binary: "binary";
    short: "short";
    shape: "shape";
    date_nanos: "date_nanos";
    date_range: "date_range";
    double_range: "double_range";
    float_range: "float_range";
    half_float: "half_float";
    integer_range: "integer_range";
    ip_range: "ip_range";
    long_range: "long_range";
}>;
export type Security_Lists_API_ListType = z.infer<typeof Security_Lists_API_ListType>;
export declare const Security_Lists_API_ListItemMetadata: z.ZodRecord<z.ZodString, z.ZodUnknown>;
export type Security_Lists_API_ListItemMetadata = z.infer<typeof Security_Lists_API_ListItemMetadata>;
export declare const Security_Lists_API_ListId: z.ZodString;
export type Security_Lists_API_ListId = z.infer<typeof Security_Lists_API_ListId>;
export declare const Security_Lists_API_ListItemId: z.ZodString;
export type Security_Lists_API_ListItemId = z.infer<typeof Security_Lists_API_ListItemId>;
export declare const Security_Lists_API_ListVersionId: z.ZodString;
export type Security_Lists_API_ListVersionId = z.infer<typeof Security_Lists_API_ListVersionId>;
export declare const Security_Lists_API_ListItem: z.ZodObject<{
    _version: z.ZodOptional<z.ZodString>;
    '@timestamp': z.ZodOptional<z.ZodString>;
    created_at: z.ZodString;
    created_by: z.ZodString;
    id: z.ZodString;
    list_id: z.ZodString;
    meta: z.ZodOptional<z.ZodRecord<z.ZodString, z.ZodUnknown>>;
    tie_breaker_id: z.ZodString;
    type: z.ZodEnum<{
        boolean: "boolean";
        text: "text";
        date: "date";
        long: "long";
        integer: "integer";
        double: "double";
        float: "float";
        ip: "ip";
        keyword: "keyword";
        geo_point: "geo_point";
        geo_shape: "geo_shape";
        byte: "byte";
        binary: "binary";
        short: "short";
        shape: "shape";
        date_nanos: "date_nanos";
        date_range: "date_range";
        double_range: "double_range";
        float_range: "float_range";
        half_float: "half_float";
        integer_range: "integer_range";
        ip_range: "ip_range";
        long_range: "long_range";
    }>;
    updated_at: z.ZodString;
    updated_by: z.ZodString;
    value: z.ZodString;
}, z.core.$strip>;
export type Security_Lists_API_ListItem = z.infer<typeof Security_Lists_API_ListItem>;
export declare const PatchListItemRequest: z.ZodObject<{
    _version: z.ZodOptional<z.ZodString>;
    id: z.ZodString;
    meta: z.ZodOptional<z.ZodRecord<z.ZodString, z.ZodUnknown>>;
    refresh: z.ZodOptional<z.ZodEnum<{
        true: "true";
        false: "false";
        wait_for: "wait_for";
    }>>;
    value: z.ZodOptional<z.ZodString>;
}, z.core.$strip>;
export type PatchListItemRequest = z.infer<typeof PatchListItemRequest>;
//# sourceMappingURL=patch_list_item.d.ts.map