/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */
/*
 * This file was automatically generated by elastic/elastic-client-generator-js.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source open api file,
 * and elastic/elastic-client-generator-js to regenerate this file again.
 */
/* eslint-disable @typescript-eslint/no-redeclare */
import { z } from 'zod';
export const Kibana_HTTP_APIs_bulk_rollback_packages_response = z.object({
    taskId: z.string()
}).meta({ id: 'Kibana_HTTP_APIs_bulk_rollback_packages_response' });
export const Kibana_HTTP_APIs_bulk_rollback_packages_request = z.object({
    packages: z.array(z.object({
        name: z.string()
    }))
}).meta({ id: 'Kibana_HTTP_APIs_bulk_rollback_packages_request' });
//# sourceMappingURL=post_fleet_epm_packages_bulk_rollback.js.map