/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */
/*
 * This file was automatically generated by elastic/elastic-client-generator-js.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source open api file,
 * and elastic/elastic-client-generator-js to regenerate this file again.
 */
/* eslint-disable @typescript-eslint/no-redeclare */
import { z } from 'zod';
export const PostFleetAgentsBulkUpdateAgentTagsRequest = z.object({
    agents: z.union([z.array(z.string()), z.string()]),
    batchSize: z.number().optional(),
    includeInactive: z.boolean().optional(),
    tagsToAdd: z.array(z.string()).optional(),
    tagsToRemove: z.array(z.string()).optional()
}).meta({ id: 'PostFleetAgentsBulkUpdateAgentTagsRequest' });
export const PostFleetAgentsBulkUpdateAgentTagsResponse = z.object({
    actionId: z.string()
}).meta({ id: 'PostFleetAgentsBulkUpdateAgentTagsResponse' });
//# sourceMappingURL=post_fleet_agents_bulk_update_agent_tags.js.map