/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */
/*
 * This file was automatically generated by elastic/elastic-client-generator-js.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source open api file,
 * and elastic/elastic-client-generator-js to regenerate this file again.
 */
/* eslint-disable @typescript-eslint/no-redeclare */
import { z } from 'zod';
export const PostFleetAgentsBulkRequestDiagnosticsRequest = z.object({
    additional_metrics: z.array(z.enum(['CPU'])).optional(),
    agents: z.union([z.array(z.string()), z.string()]),
    batchSize: z.number().optional()
}).meta({ id: 'PostFleetAgentsBulkRequestDiagnosticsRequest' });
export const PostFleetAgentsBulkRequestDiagnosticsResponse = z.object({
    actionId: z.string()
}).meta({ id: 'PostFleetAgentsBulkRequestDiagnosticsResponse' });
//# sourceMappingURL=post_fleet_agents_bulk_request_diagnostics.js.map