/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */
/*
 * This file was automatically generated by elastic/elastic-client-generator-js.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source open api file,
 * and elastic/elastic-client-generator-js to regenerate this file again.
 */
/* eslint-disable @typescript-eslint/no-redeclare */
import { z } from 'zod';
export const Kibana_HTTP_APIs_action_message_response = z.object({
    message: z.string()
}).meta({ id: 'Kibana_HTTP_APIs_action_message_response' });
export const Kibana_HTTP_APIs_action_id_response = z.object({
    actionId: z.string()
}).meta({ id: 'Kibana_HTTP_APIs_action_id_response' });
export const PostFleetAgentsAgentidPrivilegeLevelChangeRequest = z.object({
    user_info: z.object({
        groupname: z.string().optional(),
        password: z.string().optional(),
        username: z.string().optional()
    }).optional()
}).nullable().meta({ id: 'PostFleetAgentsAgentidPrivilegeLevelChangeRequest' });
export const PostFleetAgentsAgentidPrivilegeLevelChangeResponse = z.union([Kibana_HTTP_APIs_action_id_response, Kibana_HTTP_APIs_action_message_response]).meta({ id: 'PostFleetAgentsAgentidPrivilegeLevelChangeResponse' });
//# sourceMappingURL=post_fleet_agents_agentid_privilege_level_change.js.map