/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */
/*
 * This file was automatically generated by elastic/elastic-client-generator-js.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source open api file,
 * and elastic/elastic-client-generator-js to regenerate this file again.
 */
/* eslint-disable @typescript-eslint/no-redeclare */
import { z } from 'zod';
export const PostFleetAgentsBulkReassignRequest = z.object({
    agents: z.union([z.array(z.string()), z.string()]),
    batchSize: z.number().optional(),
    includeInactive: z.boolean().optional(),
    policy_id: z.string()
}).meta({ id: 'PostFleetAgentsBulkReassignRequest' });
export const PostFleetAgentsBulkReassignResponse = z.object({
    actionId: z.string()
}).meta({ id: 'PostFleetAgentsBulkReassignResponse' });
//# sourceMappingURL=post_fleet_agents_bulk_reassign.js.map