import { z } from 'zod';
export declare const PostSecurityEntityStoreEntitiesEntitytypeRequest: z.ZodUnion<readonly [z.ZodObject<{
    '@timestamp': z.ZodOptional<z.ZodString>;
    asset: z.ZodOptional<z.ZodObject<{
        business_unit: z.ZodOptional<z.ZodString>;
        criticality: z.ZodOptional<z.ZodUnion<readonly [z.ZodEnum<{
            low_impact: "low_impact";
            medium_impact: "medium_impact";
            high_impact: "high_impact";
            extreme_impact: "extreme_impact";
        }>, z.ZodNullable<z.ZodUnknown>]>>;
        environment: z.ZodOptional<z.ZodString>;
        id: z.ZodOptional<z.ZodString>;
        model: z.ZodOptional<z.ZodString>;
        name: z.ZodOptional<z.ZodString>;
        owner: z.ZodOptional<z.ZodString>;
        serial_number: z.ZodOptional<z.ZodString>;
        vendor: z.ZodOptional<z.ZodString>;
    }, z.core.$strip>>;
    entity: z.ZodOptional<z.ZodObject<{
        attributes: z.ZodOptional<z.ZodObject<{
            asset: z.ZodOptional<z.ZodBoolean>;
            known_redirects: z.ZodOptional<z.ZodArray<z.ZodString>>;
            managed: z.ZodOptional<z.ZodBoolean>;
            mfa_enabled: z.ZodOptional<z.ZodBoolean>;
            oauth_consent_restriction: z.ZodOptional<z.ZodString>;
            permissions: z.ZodOptional<z.ZodArray<z.ZodString>>;
            storage_class: z.ZodOptional<z.ZodString>;
            watchlists: z.ZodOptional<z.ZodArray<z.ZodString>>;
        }, z.core.$strip>>;
        behaviors: z.ZodOptional<z.ZodObject<{
            anomaly_job_ids: z.ZodOptional<z.ZodArray<z.ZodString>>;
            rule_names: z.ZodOptional<z.ZodArray<z.ZodString>>;
        }, z.core.$strip>>;
        EngineMetadata: z.ZodOptional<z.ZodObject<{
            Type: z.ZodOptional<z.ZodString>;
        }, z.core.$strip>>;
        id: z.ZodOptional<z.ZodString>;
        lifecycle: z.ZodOptional<z.ZodObject<{
            first_seen: z.ZodOptional<z.ZodString>;
            last_activity: z.ZodOptional<z.ZodString>;
            last_seen: z.ZodOptional<z.ZodString>;
        }, z.core.$strip>>;
        name: z.ZodOptional<z.ZodString>;
        relationships: z.ZodOptional<z.ZodObject<{
            accesses_frequently: z.ZodOptional<z.ZodObject<{
                ids: z.ZodOptional<z.ZodArray<z.ZodString>>;
                raw_identifiers: z.ZodOptional<z.ZodObject<{
                    'entity.id': z.ZodOptional<z.ZodArray<z.ZodString>>;
                    'host.id': z.ZodOptional<z.ZodArray<z.ZodString>>;
                    'host.name': z.ZodOptional<z.ZodArray<z.ZodString>>;
                    'service.name': z.ZodOptional<z.ZodArray<z.ZodString>>;
                    'user.email': z.ZodOptional<z.ZodArray<z.ZodString>>;
                    'user.id': z.ZodOptional<z.ZodArray<z.ZodString>>;
                    'user.name': z.ZodOptional<z.ZodArray<z.ZodString>>;
                }, z.core.$strip>>;
            }, z.core.$strip>>;
            accesses_infrequently: z.ZodOptional<z.ZodObject<{
                ids: z.ZodOptional<z.ZodArray<z.ZodString>>;
                raw_identifiers: z.ZodOptional<z.ZodObject<{
                    'entity.id': z.ZodOptional<z.ZodArray<z.ZodString>>;
                    'host.id': z.ZodOptional<z.ZodArray<z.ZodString>>;
                    'host.name': z.ZodOptional<z.ZodArray<z.ZodString>>;
                    'service.name': z.ZodOptional<z.ZodArray<z.ZodString>>;
                    'user.email': z.ZodOptional<z.ZodArray<z.ZodString>>;
                    'user.id': z.ZodOptional<z.ZodArray<z.ZodString>>;
                    'user.name': z.ZodOptional<z.ZodArray<z.ZodString>>;
                }, z.core.$strip>>;
            }, z.core.$strip>>;
            administers: z.ZodOptional<z.ZodObject<{
                ids: z.ZodOptional<z.ZodArray<z.ZodString>>;
                raw_identifiers: z.ZodOptional<z.ZodObject<{
                    'entity.id': z.ZodOptional<z.ZodArray<z.ZodString>>;
                    'host.id': z.ZodOptional<z.ZodArray<z.ZodString>>;
                    'host.name': z.ZodOptional<z.ZodArray<z.ZodString>>;
                    'service.name': z.ZodOptional<z.ZodArray<z.ZodString>>;
                    'user.email': z.ZodOptional<z.ZodArray<z.ZodString>>;
                    'user.id': z.ZodOptional<z.ZodArray<z.ZodString>>;
                    'user.name': z.ZodOptional<z.ZodArray<z.ZodString>>;
                }, z.core.$strip>>;
            }, z.core.$strip>>;
            communicates_with: z.ZodOptional<z.ZodObject<{
                ids: z.ZodOptional<z.ZodArray<z.ZodString>>;
                raw_identifiers: z.ZodOptional<z.ZodObject<{
                    'entity.id': z.ZodOptional<z.ZodArray<z.ZodString>>;
                    'host.id': z.ZodOptional<z.ZodArray<z.ZodString>>;
                    'host.name': z.ZodOptional<z.ZodArray<z.ZodString>>;
                    'service.name': z.ZodOptional<z.ZodArray<z.ZodString>>;
                    'user.email': z.ZodOptional<z.ZodArray<z.ZodString>>;
                    'user.id': z.ZodOptional<z.ZodArray<z.ZodString>>;
                    'user.name': z.ZodOptional<z.ZodArray<z.ZodString>>;
                }, z.core.$strip>>;
            }, z.core.$strip>>;
            depends_on: z.ZodOptional<z.ZodObject<{
                ids: z.ZodOptional<z.ZodArray<z.ZodString>>;
                raw_identifiers: z.ZodOptional<z.ZodObject<{
                    'entity.id': z.ZodOptional<z.ZodArray<z.ZodString>>;
                    'host.id': z.ZodOptional<z.ZodArray<z.ZodString>>;
                    'host.name': z.ZodOptional<z.ZodArray<z.ZodString>>;
                    'service.name': z.ZodOptional<z.ZodArray<z.ZodString>>;
                    'user.email': z.ZodOptional<z.ZodArray<z.ZodString>>;
                    'user.id': z.ZodOptional<z.ZodArray<z.ZodString>>;
                    'user.name': z.ZodOptional<z.ZodArray<z.ZodString>>;
                }, z.core.$strip>>;
            }, z.core.$strip>>;
            owns: z.ZodOptional<z.ZodObject<{
                ids: z.ZodOptional<z.ZodArray<z.ZodString>>;
                raw_identifiers: z.ZodOptional<z.ZodObject<{
                    'entity.id': z.ZodOptional<z.ZodArray<z.ZodString>>;
                    'host.id': z.ZodOptional<z.ZodArray<z.ZodString>>;
                    'host.name': z.ZodOptional<z.ZodArray<z.ZodString>>;
                    'service.name': z.ZodOptional<z.ZodArray<z.ZodString>>;
                    'user.email': z.ZodOptional<z.ZodArray<z.ZodString>>;
                    'user.id': z.ZodOptional<z.ZodArray<z.ZodString>>;
                    'user.name': z.ZodOptional<z.ZodArray<z.ZodString>>;
                }, z.core.$strip>>;
            }, z.core.$strip>>;
            owns_inferred: z.ZodOptional<z.ZodObject<{
                ids: z.ZodOptional<z.ZodArray<z.ZodString>>;
                raw_identifiers: z.ZodOptional<z.ZodObject<{
                    'entity.id': z.ZodOptional<z.ZodArray<z.ZodString>>;
                    'host.id': z.ZodOptional<z.ZodArray<z.ZodString>>;
                    'host.name': z.ZodOptional<z.ZodArray<z.ZodString>>;
                    'service.name': z.ZodOptional<z.ZodArray<z.ZodString>>;
                    'user.email': z.ZodOptional<z.ZodArray<z.ZodString>>;
                    'user.id': z.ZodOptional<z.ZodArray<z.ZodString>>;
                    'user.name': z.ZodOptional<z.ZodArray<z.ZodString>>;
                }, z.core.$strip>>;
            }, z.core.$strip>>;
            resolution: z.ZodOptional<z.ZodObject<{
                resolved_to: z.ZodOptional<z.ZodString>;
                risk: z.ZodOptional<z.ZodObject<{
                    calculated_level: z.ZodOptional<z.ZodEnum<{
                        Unknown: "Unknown";
                        Low: "Low";
                        Moderate: "Moderate";
                        High: "High";
                        Critical: "Critical";
                    }>>;
                    calculated_score: z.ZodOptional<z.ZodNumber>;
                    calculated_score_norm: z.ZodOptional<z.ZodNumber>;
                }, z.core.$strip>>;
            }, z.core.$strip>>;
            supervises: z.ZodOptional<z.ZodObject<{
                ids: z.ZodOptional<z.ZodArray<z.ZodString>>;
                raw_identifiers: z.ZodOptional<z.ZodObject<{
                    'entity.id': z.ZodOptional<z.ZodArray<z.ZodString>>;
                    'host.id': z.ZodOptional<z.ZodArray<z.ZodString>>;
                    'host.name': z.ZodOptional<z.ZodArray<z.ZodString>>;
                    'service.name': z.ZodOptional<z.ZodArray<z.ZodString>>;
                    'user.email': z.ZodOptional<z.ZodArray<z.ZodString>>;
                    'user.id': z.ZodOptional<z.ZodArray<z.ZodString>>;
                    'user.name': z.ZodOptional<z.ZodArray<z.ZodString>>;
                }, z.core.$strip>>;
            }, z.core.$strip>>;
        }, z.core.$strip>>;
        risk: z.ZodOptional<z.ZodObject<{
            calculated_level: z.ZodOptional<z.ZodEnum<{
                Unknown: "Unknown";
                Low: "Low";
                Moderate: "Moderate";
                High: "High";
                Critical: "Critical";
            }>>;
            calculated_score: z.ZodOptional<z.ZodNumber>;
            calculated_score_norm: z.ZodOptional<z.ZodNumber>;
        }, z.core.$strip>>;
        schema_version: z.ZodOptional<z.ZodString>;
        source: z.ZodOptional<z.ZodArray<z.ZodString>>;
        sub_type: z.ZodOptional<z.ZodString>;
        type: z.ZodOptional<z.ZodString>;
        url: z.ZodOptional<z.ZodString>;
    }, z.core.$strip>>;
    event: z.ZodOptional<z.ZodObject<{
        ingested: z.ZodOptional<z.ZodString>;
    }, z.core.$strip>>;
    labels: z.ZodOptional<z.ZodObject<{}, z.core.$loose>>;
    tags: z.ZodOptional<z.ZodArray<z.ZodString>>;
    user: z.ZodOptional<z.ZodObject<{
        domain: z.ZodOptional<z.ZodArray<z.ZodString>>;
        email: z.ZodOptional<z.ZodArray<z.ZodString>>;
        full_name: z.ZodOptional<z.ZodArray<z.ZodString>>;
        hash: z.ZodOptional<z.ZodArray<z.ZodString>>;
        id: z.ZodOptional<z.ZodArray<z.ZodString>>;
        name: z.ZodOptional<z.ZodString>;
        risk: z.ZodOptional<z.ZodObject<{
            calculated_level: z.ZodOptional<z.ZodEnum<{
                Unknown: "Unknown";
                Low: "Low";
                Moderate: "Moderate";
                High: "High";
                Critical: "Critical";
            }>>;
            calculated_score: z.ZodOptional<z.ZodNumber>;
            calculated_score_norm: z.ZodOptional<z.ZodNumber>;
        }, z.core.$strip>>;
        roles: z.ZodOptional<z.ZodArray<z.ZodString>>;
    }, z.core.$strip>>;
}, z.core.$strip>, z.ZodObject<{
    '@timestamp': z.ZodOptional<z.ZodString>;
    asset: z.ZodOptional<z.ZodObject<{
        business_unit: z.ZodOptional<z.ZodString>;
        criticality: z.ZodOptional<z.ZodUnion<readonly [z.ZodEnum<{
            low_impact: "low_impact";
            medium_impact: "medium_impact";
            high_impact: "high_impact";
            extreme_impact: "extreme_impact";
        }>, z.ZodNullable<z.ZodUnknown>]>>;
        environment: z.ZodOptional<z.ZodString>;
        id: z.ZodOptional<z.ZodString>;
        model: z.ZodOptional<z.ZodString>;
        name: z.ZodOptional<z.ZodString>;
        owner: z.ZodOptional<z.ZodString>;
        serial_number: z.ZodOptional<z.ZodString>;
        vendor: z.ZodOptional<z.ZodString>;
    }, z.core.$strip>>;
    entity: z.ZodOptional<z.ZodObject<{
        attributes: z.ZodOptional<z.ZodObject<{
            asset: z.ZodOptional<z.ZodBoolean>;
            known_redirects: z.ZodOptional<z.ZodArray<z.ZodString>>;
            managed: z.ZodOptional<z.ZodBoolean>;
            mfa_enabled: z.ZodOptional<z.ZodBoolean>;
            oauth_consent_restriction: z.ZodOptional<z.ZodString>;
            permissions: z.ZodOptional<z.ZodArray<z.ZodString>>;
            storage_class: z.ZodOptional<z.ZodString>;
            watchlists: z.ZodOptional<z.ZodArray<z.ZodString>>;
        }, z.core.$strip>>;
        behaviors: z.ZodOptional<z.ZodObject<{
            anomaly_job_ids: z.ZodOptional<z.ZodArray<z.ZodString>>;
            rule_names: z.ZodOptional<z.ZodArray<z.ZodString>>;
        }, z.core.$strip>>;
        EngineMetadata: z.ZodOptional<z.ZodObject<{
            Type: z.ZodOptional<z.ZodString>;
        }, z.core.$strip>>;
        id: z.ZodOptional<z.ZodString>;
        lifecycle: z.ZodOptional<z.ZodObject<{
            first_seen: z.ZodOptional<z.ZodString>;
            last_activity: z.ZodOptional<z.ZodString>;
            last_seen: z.ZodOptional<z.ZodString>;
        }, z.core.$strip>>;
        name: z.ZodOptional<z.ZodString>;
        relationships: z.ZodOptional<z.ZodObject<{
            accesses_frequently: z.ZodOptional<z.ZodObject<{
                ids: z.ZodOptional<z.ZodArray<z.ZodString>>;
                raw_identifiers: z.ZodOptional<z.ZodObject<{
                    'entity.id': z.ZodOptional<z.ZodArray<z.ZodString>>;
                    'host.id': z.ZodOptional<z.ZodArray<z.ZodString>>;
                    'host.name': z.ZodOptional<z.ZodArray<z.ZodString>>;
                    'service.name': z.ZodOptional<z.ZodArray<z.ZodString>>;
                    'user.email': z.ZodOptional<z.ZodArray<z.ZodString>>;
                    'user.id': z.ZodOptional<z.ZodArray<z.ZodString>>;
                    'user.name': z.ZodOptional<z.ZodArray<z.ZodString>>;
                }, z.core.$strip>>;
            }, z.core.$strip>>;
            accesses_infrequently: z.ZodOptional<z.ZodObject<{
                ids: z.ZodOptional<z.ZodArray<z.ZodString>>;
                raw_identifiers: z.ZodOptional<z.ZodObject<{
                    'entity.id': z.ZodOptional<z.ZodArray<z.ZodString>>;
                    'host.id': z.ZodOptional<z.ZodArray<z.ZodString>>;
                    'host.name': z.ZodOptional<z.ZodArray<z.ZodString>>;
                    'service.name': z.ZodOptional<z.ZodArray<z.ZodString>>;
                    'user.email': z.ZodOptional<z.ZodArray<z.ZodString>>;
                    'user.id': z.ZodOptional<z.ZodArray<z.ZodString>>;
                    'user.name': z.ZodOptional<z.ZodArray<z.ZodString>>;
                }, z.core.$strip>>;
            }, z.core.$strip>>;
            administers: z.ZodOptional<z.ZodObject<{
                ids: z.ZodOptional<z.ZodArray<z.ZodString>>;
                raw_identifiers: z.ZodOptional<z.ZodObject<{
                    'entity.id': z.ZodOptional<z.ZodArray<z.ZodString>>;
                    'host.id': z.ZodOptional<z.ZodArray<z.ZodString>>;
                    'host.name': z.ZodOptional<z.ZodArray<z.ZodString>>;
                    'service.name': z.ZodOptional<z.ZodArray<z.ZodString>>;
                    'user.email': z.ZodOptional<z.ZodArray<z.ZodString>>;
                    'user.id': z.ZodOptional<z.ZodArray<z.ZodString>>;
                    'user.name': z.ZodOptional<z.ZodArray<z.ZodString>>;
                }, z.core.$strip>>;
            }, z.core.$strip>>;
            communicates_with: z.ZodOptional<z.ZodObject<{
                ids: z.ZodOptional<z.ZodArray<z.ZodString>>;
                raw_identifiers: z.ZodOptional<z.ZodObject<{
                    'entity.id': z.ZodOptional<z.ZodArray<z.ZodString>>;
                    'host.id': z.ZodOptional<z.ZodArray<z.ZodString>>;
                    'host.name': z.ZodOptional<z.ZodArray<z.ZodString>>;
                    'service.name': z.ZodOptional<z.ZodArray<z.ZodString>>;
                    'user.email': z.ZodOptional<z.ZodArray<z.ZodString>>;
                    'user.id': z.ZodOptional<z.ZodArray<z.ZodString>>;
                    'user.name': z.ZodOptional<z.ZodArray<z.ZodString>>;
                }, z.core.$strip>>;
            }, z.core.$strip>>;
            depends_on: z.ZodOptional<z.ZodObject<{
                ids: z.ZodOptional<z.ZodArray<z.ZodString>>;
                raw_identifiers: z.ZodOptional<z.ZodObject<{
                    'entity.id': z.ZodOptional<z.ZodArray<z.ZodString>>;
                    'host.id': z.ZodOptional<z.ZodArray<z.ZodString>>;
                    'host.name': z.ZodOptional<z.ZodArray<z.ZodString>>;
                    'service.name': z.ZodOptional<z.ZodArray<z.ZodString>>;
                    'user.email': z.ZodOptional<z.ZodArray<z.ZodString>>;
                    'user.id': z.ZodOptional<z.ZodArray<z.ZodString>>;
                    'user.name': z.ZodOptional<z.ZodArray<z.ZodString>>;
                }, z.core.$strip>>;
            }, z.core.$strip>>;
            owns: z.ZodOptional<z.ZodObject<{
                ids: z.ZodOptional<z.ZodArray<z.ZodString>>;
                raw_identifiers: z.ZodOptional<z.ZodObject<{
                    'entity.id': z.ZodOptional<z.ZodArray<z.ZodString>>;
                    'host.id': z.ZodOptional<z.ZodArray<z.ZodString>>;
                    'host.name': z.ZodOptional<z.ZodArray<z.ZodString>>;
                    'service.name': z.ZodOptional<z.ZodArray<z.ZodString>>;
                    'user.email': z.ZodOptional<z.ZodArray<z.ZodString>>;
                    'user.id': z.ZodOptional<z.ZodArray<z.ZodString>>;
                    'user.name': z.ZodOptional<z.ZodArray<z.ZodString>>;
                }, z.core.$strip>>;
            }, z.core.$strip>>;
            owns_inferred: z.ZodOptional<z.ZodObject<{
                ids: z.ZodOptional<z.ZodArray<z.ZodString>>;
                raw_identifiers: z.ZodOptional<z.ZodObject<{
                    'entity.id': z.ZodOptional<z.ZodArray<z.ZodString>>;
                    'host.id': z.ZodOptional<z.ZodArray<z.ZodString>>;
                    'host.name': z.ZodOptional<z.ZodArray<z.ZodString>>;
                    'service.name': z.ZodOptional<z.ZodArray<z.ZodString>>;
                    'user.email': z.ZodOptional<z.ZodArray<z.ZodString>>;
                    'user.id': z.ZodOptional<z.ZodArray<z.ZodString>>;
                    'user.name': z.ZodOptional<z.ZodArray<z.ZodString>>;
                }, z.core.$strip>>;
            }, z.core.$strip>>;
            resolution: z.ZodOptional<z.ZodObject<{
                resolved_to: z.ZodOptional<z.ZodString>;
                risk: z.ZodOptional<z.ZodObject<{
                    calculated_level: z.ZodOptional<z.ZodEnum<{
                        Unknown: "Unknown";
                        Low: "Low";
                        Moderate: "Moderate";
                        High: "High";
                        Critical: "Critical";
                    }>>;
                    calculated_score: z.ZodOptional<z.ZodNumber>;
                    calculated_score_norm: z.ZodOptional<z.ZodNumber>;
                }, z.core.$strip>>;
            }, z.core.$strip>>;
            supervises: z.ZodOptional<z.ZodObject<{
                ids: z.ZodOptional<z.ZodArray<z.ZodString>>;
                raw_identifiers: z.ZodOptional<z.ZodObject<{
                    'entity.id': z.ZodOptional<z.ZodArray<z.ZodString>>;
                    'host.id': z.ZodOptional<z.ZodArray<z.ZodString>>;
                    'host.name': z.ZodOptional<z.ZodArray<z.ZodString>>;
                    'service.name': z.ZodOptional<z.ZodArray<z.ZodString>>;
                    'user.email': z.ZodOptional<z.ZodArray<z.ZodString>>;
                    'user.id': z.ZodOptional<z.ZodArray<z.ZodString>>;
                    'user.name': z.ZodOptional<z.ZodArray<z.ZodString>>;
                }, z.core.$strip>>;
            }, z.core.$strip>>;
        }, z.core.$strip>>;
        risk: z.ZodOptional<z.ZodObject<{
            calculated_level: z.ZodOptional<z.ZodEnum<{
                Unknown: "Unknown";
                Low: "Low";
                Moderate: "Moderate";
                High: "High";
                Critical: "Critical";
            }>>;
            calculated_score: z.ZodOptional<z.ZodNumber>;
            calculated_score_norm: z.ZodOptional<z.ZodNumber>;
        }, z.core.$strip>>;
        schema_version: z.ZodOptional<z.ZodString>;
        source: z.ZodOptional<z.ZodArray<z.ZodString>>;
        sub_type: z.ZodOptional<z.ZodString>;
        type: z.ZodOptional<z.ZodString>;
        url: z.ZodOptional<z.ZodString>;
    }, z.core.$strip>>;
    event: z.ZodOptional<z.ZodObject<{
        ingested: z.ZodOptional<z.ZodString>;
    }, z.core.$strip>>;
    host: z.ZodOptional<z.ZodObject<{
        architecture: z.ZodOptional<z.ZodArray<z.ZodString>>;
        domain: z.ZodOptional<z.ZodArray<z.ZodString>>;
        hostname: z.ZodOptional<z.ZodArray<z.ZodString>>;
        id: z.ZodOptional<z.ZodArray<z.ZodString>>;
        ip: z.ZodOptional<z.ZodArray<z.ZodString>>;
        mac: z.ZodOptional<z.ZodArray<z.ZodString>>;
        name: z.ZodOptional<z.ZodString>;
        os: z.ZodOptional<z.ZodObject<{
            family: z.ZodOptional<z.ZodString>;
            full: z.ZodOptional<z.ZodString>;
            kernel: z.ZodOptional<z.ZodString>;
            name: z.ZodOptional<z.ZodUnion<readonly [z.ZodString, z.ZodArray<z.ZodString>]>>;
            platform: z.ZodOptional<z.ZodString>;
            type: z.ZodOptional<z.ZodUnion<readonly [z.ZodString, z.ZodArray<z.ZodString>]>>;
            version: z.ZodOptional<z.ZodString>;
        }, z.core.$strip>>;
        risk: z.ZodOptional<z.ZodObject<{
            calculated_level: z.ZodOptional<z.ZodEnum<{
                Unknown: "Unknown";
                Low: "Low";
                Moderate: "Moderate";
                High: "High";
                Critical: "Critical";
            }>>;
            calculated_score: z.ZodOptional<z.ZodNumber>;
            calculated_score_norm: z.ZodOptional<z.ZodNumber>;
        }, z.core.$strip>>;
        type: z.ZodOptional<z.ZodArray<z.ZodString>>;
    }, z.core.$strip>>;
    labels: z.ZodOptional<z.ZodObject<{}, z.core.$loose>>;
    tags: z.ZodOptional<z.ZodArray<z.ZodString>>;
}, z.core.$strip>, z.ZodObject<{
    '@timestamp': z.ZodOptional<z.ZodString>;
    asset: z.ZodOptional<z.ZodObject<{
        business_unit: z.ZodOptional<z.ZodString>;
        criticality: z.ZodOptional<z.ZodUnion<readonly [z.ZodEnum<{
            low_impact: "low_impact";
            medium_impact: "medium_impact";
            high_impact: "high_impact";
            extreme_impact: "extreme_impact";
        }>, z.ZodNullable<z.ZodUnknown>]>>;
        environment: z.ZodOptional<z.ZodString>;
        id: z.ZodOptional<z.ZodString>;
        model: z.ZodOptional<z.ZodString>;
        name: z.ZodOptional<z.ZodString>;
        owner: z.ZodOptional<z.ZodString>;
        serial_number: z.ZodOptional<z.ZodString>;
        vendor: z.ZodOptional<z.ZodString>;
    }, z.core.$strip>>;
    entity: z.ZodOptional<z.ZodObject<{
        attributes: z.ZodOptional<z.ZodObject<{
            asset: z.ZodOptional<z.ZodBoolean>;
            known_redirects: z.ZodOptional<z.ZodArray<z.ZodString>>;
            managed: z.ZodOptional<z.ZodBoolean>;
            mfa_enabled: z.ZodOptional<z.ZodBoolean>;
            oauth_consent_restriction: z.ZodOptional<z.ZodString>;
            permissions: z.ZodOptional<z.ZodArray<z.ZodString>>;
            storage_class: z.ZodOptional<z.ZodString>;
            watchlists: z.ZodOptional<z.ZodArray<z.ZodString>>;
        }, z.core.$strip>>;
        behaviors: z.ZodOptional<z.ZodObject<{
            anomaly_job_ids: z.ZodOptional<z.ZodArray<z.ZodString>>;
            rule_names: z.ZodOptional<z.ZodArray<z.ZodString>>;
        }, z.core.$strip>>;
        EngineMetadata: z.ZodOptional<z.ZodObject<{
            Type: z.ZodOptional<z.ZodString>;
        }, z.core.$strip>>;
        id: z.ZodOptional<z.ZodString>;
        lifecycle: z.ZodOptional<z.ZodObject<{
            first_seen: z.ZodOptional<z.ZodString>;
            last_activity: z.ZodOptional<z.ZodString>;
            last_seen: z.ZodOptional<z.ZodString>;
        }, z.core.$strip>>;
        name: z.ZodOptional<z.ZodString>;
        relationships: z.ZodOptional<z.ZodObject<{
            accesses_frequently: z.ZodOptional<z.ZodObject<{
                ids: z.ZodOptional<z.ZodArray<z.ZodString>>;
                raw_identifiers: z.ZodOptional<z.ZodObject<{
                    'entity.id': z.ZodOptional<z.ZodArray<z.ZodString>>;
                    'host.id': z.ZodOptional<z.ZodArray<z.ZodString>>;
                    'host.name': z.ZodOptional<z.ZodArray<z.ZodString>>;
                    'service.name': z.ZodOptional<z.ZodArray<z.ZodString>>;
                    'user.email': z.ZodOptional<z.ZodArray<z.ZodString>>;
                    'user.id': z.ZodOptional<z.ZodArray<z.ZodString>>;
                    'user.name': z.ZodOptional<z.ZodArray<z.ZodString>>;
                }, z.core.$strip>>;
            }, z.core.$strip>>;
            accesses_infrequently: z.ZodOptional<z.ZodObject<{
                ids: z.ZodOptional<z.ZodArray<z.ZodString>>;
                raw_identifiers: z.ZodOptional<z.ZodObject<{
                    'entity.id': z.ZodOptional<z.ZodArray<z.ZodString>>;
                    'host.id': z.ZodOptional<z.ZodArray<z.ZodString>>;
                    'host.name': z.ZodOptional<z.ZodArray<z.ZodString>>;
                    'service.name': z.ZodOptional<z.ZodArray<z.ZodString>>;
                    'user.email': z.ZodOptional<z.ZodArray<z.ZodString>>;
                    'user.id': z.ZodOptional<z.ZodArray<z.ZodString>>;
                    'user.name': z.ZodOptional<z.ZodArray<z.ZodString>>;
                }, z.core.$strip>>;
            }, z.core.$strip>>;
            administers: z.ZodOptional<z.ZodObject<{
                ids: z.ZodOptional<z.ZodArray<z.ZodString>>;
                raw_identifiers: z.ZodOptional<z.ZodObject<{
                    'entity.id': z.ZodOptional<z.ZodArray<z.ZodString>>;
                    'host.id': z.ZodOptional<z.ZodArray<z.ZodString>>;
                    'host.name': z.ZodOptional<z.ZodArray<z.ZodString>>;
                    'service.name': z.ZodOptional<z.ZodArray<z.ZodString>>;
                    'user.email': z.ZodOptional<z.ZodArray<z.ZodString>>;
                    'user.id': z.ZodOptional<z.ZodArray<z.ZodString>>;
                    'user.name': z.ZodOptional<z.ZodArray<z.ZodString>>;
                }, z.core.$strip>>;
            }, z.core.$strip>>;
            communicates_with: z.ZodOptional<z.ZodObject<{
                ids: z.ZodOptional<z.ZodArray<z.ZodString>>;
                raw_identifiers: z.ZodOptional<z.ZodObject<{
                    'entity.id': z.ZodOptional<z.ZodArray<z.ZodString>>;
                    'host.id': z.ZodOptional<z.ZodArray<z.ZodString>>;
                    'host.name': z.ZodOptional<z.ZodArray<z.ZodString>>;
                    'service.name': z.ZodOptional<z.ZodArray<z.ZodString>>;
                    'user.email': z.ZodOptional<z.ZodArray<z.ZodString>>;
                    'user.id': z.ZodOptional<z.ZodArray<z.ZodString>>;
                    'user.name': z.ZodOptional<z.ZodArray<z.ZodString>>;
                }, z.core.$strip>>;
            }, z.core.$strip>>;
            depends_on: z.ZodOptional<z.ZodObject<{
                ids: z.ZodOptional<z.ZodArray<z.ZodString>>;
                raw_identifiers: z.ZodOptional<z.ZodObject<{
                    'entity.id': z.ZodOptional<z.ZodArray<z.ZodString>>;
                    'host.id': z.ZodOptional<z.ZodArray<z.ZodString>>;
                    'host.name': z.ZodOptional<z.ZodArray<z.ZodString>>;
                    'service.name': z.ZodOptional<z.ZodArray<z.ZodString>>;
                    'user.email': z.ZodOptional<z.ZodArray<z.ZodString>>;
                    'user.id': z.ZodOptional<z.ZodArray<z.ZodString>>;
                    'user.name': z.ZodOptional<z.ZodArray<z.ZodString>>;
                }, z.core.$strip>>;
            }, z.core.$strip>>;
            owns: z.ZodOptional<z.ZodObject<{
                ids: z.ZodOptional<z.ZodArray<z.ZodString>>;
                raw_identifiers: z.ZodOptional<z.ZodObject<{
                    'entity.id': z.ZodOptional<z.ZodArray<z.ZodString>>;
                    'host.id': z.ZodOptional<z.ZodArray<z.ZodString>>;
                    'host.name': z.ZodOptional<z.ZodArray<z.ZodString>>;
                    'service.name': z.ZodOptional<z.ZodArray<z.ZodString>>;
                    'user.email': z.ZodOptional<z.ZodArray<z.ZodString>>;
                    'user.id': z.ZodOptional<z.ZodArray<z.ZodString>>;
                    'user.name': z.ZodOptional<z.ZodArray<z.ZodString>>;
                }, z.core.$strip>>;
            }, z.core.$strip>>;
            owns_inferred: z.ZodOptional<z.ZodObject<{
                ids: z.ZodOptional<z.ZodArray<z.ZodString>>;
                raw_identifiers: z.ZodOptional<z.ZodObject<{
                    'entity.id': z.ZodOptional<z.ZodArray<z.ZodString>>;
                    'host.id': z.ZodOptional<z.ZodArray<z.ZodString>>;
                    'host.name': z.ZodOptional<z.ZodArray<z.ZodString>>;
                    'service.name': z.ZodOptional<z.ZodArray<z.ZodString>>;
                    'user.email': z.ZodOptional<z.ZodArray<z.ZodString>>;
                    'user.id': z.ZodOptional<z.ZodArray<z.ZodString>>;
                    'user.name': z.ZodOptional<z.ZodArray<z.ZodString>>;
                }, z.core.$strip>>;
            }, z.core.$strip>>;
            resolution: z.ZodOptional<z.ZodObject<{
                resolved_to: z.ZodOptional<z.ZodString>;
                risk: z.ZodOptional<z.ZodObject<{
                    calculated_level: z.ZodOptional<z.ZodEnum<{
                        Unknown: "Unknown";
                        Low: "Low";
                        Moderate: "Moderate";
                        High: "High";
                        Critical: "Critical";
                    }>>;
                    calculated_score: z.ZodOptional<z.ZodNumber>;
                    calculated_score_norm: z.ZodOptional<z.ZodNumber>;
                }, z.core.$strip>>;
            }, z.core.$strip>>;
            supervises: z.ZodOptional<z.ZodObject<{
                ids: z.ZodOptional<z.ZodArray<z.ZodString>>;
                raw_identifiers: z.ZodOptional<z.ZodObject<{
                    'entity.id': z.ZodOptional<z.ZodArray<z.ZodString>>;
                    'host.id': z.ZodOptional<z.ZodArray<z.ZodString>>;
                    'host.name': z.ZodOptional<z.ZodArray<z.ZodString>>;
                    'service.name': z.ZodOptional<z.ZodArray<z.ZodString>>;
                    'user.email': z.ZodOptional<z.ZodArray<z.ZodString>>;
                    'user.id': z.ZodOptional<z.ZodArray<z.ZodString>>;
                    'user.name': z.ZodOptional<z.ZodArray<z.ZodString>>;
                }, z.core.$strip>>;
            }, z.core.$strip>>;
        }, z.core.$strip>>;
        risk: z.ZodOptional<z.ZodObject<{
            calculated_level: z.ZodOptional<z.ZodEnum<{
                Unknown: "Unknown";
                Low: "Low";
                Moderate: "Moderate";
                High: "High";
                Critical: "Critical";
            }>>;
            calculated_score: z.ZodOptional<z.ZodNumber>;
            calculated_score_norm: z.ZodOptional<z.ZodNumber>;
        }, z.core.$strip>>;
        schema_version: z.ZodOptional<z.ZodString>;
        source: z.ZodOptional<z.ZodArray<z.ZodString>>;
        sub_type: z.ZodOptional<z.ZodString>;
        type: z.ZodOptional<z.ZodString>;
        url: z.ZodOptional<z.ZodString>;
    }, z.core.$strip>>;
    event: z.ZodOptional<z.ZodObject<{
        ingested: z.ZodOptional<z.ZodString>;
    }, z.core.$strip>>;
    labels: z.ZodOptional<z.ZodObject<{}, z.core.$loose>>;
    service: z.ZodOptional<z.ZodObject<{
        address: z.ZodOptional<z.ZodString>;
        environment: z.ZodOptional<z.ZodString>;
        ephemeral_id: z.ZodOptional<z.ZodString>;
        id: z.ZodOptional<z.ZodString>;
        name: z.ZodOptional<z.ZodString>;
        node: z.ZodOptional<z.ZodObject<{
            name: z.ZodOptional<z.ZodString>;
            role: z.ZodOptional<z.ZodString>;
            roles: z.ZodOptional<z.ZodArray<z.ZodString>>;
        }, z.core.$strip>>;
        risk: z.ZodOptional<z.ZodObject<{
            calculated_level: z.ZodOptional<z.ZodEnum<{
                Unknown: "Unknown";
                Low: "Low";
                Moderate: "Moderate";
                High: "High";
                Critical: "Critical";
            }>>;
            calculated_score: z.ZodOptional<z.ZodNumber>;
            calculated_score_norm: z.ZodOptional<z.ZodNumber>;
        }, z.core.$strip>>;
        state: z.ZodOptional<z.ZodString>;
        type: z.ZodOptional<z.ZodString>;
        version: z.ZodOptional<z.ZodString>;
    }, z.core.$strip>>;
    tags: z.ZodOptional<z.ZodArray<z.ZodString>>;
}, z.core.$strip>, z.ZodObject<{
    '@timestamp': z.ZodOptional<z.ZodString>;
    asset: z.ZodOptional<z.ZodObject<{
        business_unit: z.ZodOptional<z.ZodString>;
        criticality: z.ZodOptional<z.ZodUnion<readonly [z.ZodEnum<{
            low_impact: "low_impact";
            medium_impact: "medium_impact";
            high_impact: "high_impact";
            extreme_impact: "extreme_impact";
        }>, z.ZodNullable<z.ZodUnknown>]>>;
        environment: z.ZodOptional<z.ZodString>;
        id: z.ZodOptional<z.ZodString>;
        model: z.ZodOptional<z.ZodString>;
        name: z.ZodOptional<z.ZodString>;
        owner: z.ZodOptional<z.ZodString>;
        serial_number: z.ZodOptional<z.ZodString>;
        vendor: z.ZodOptional<z.ZodString>;
    }, z.core.$strip>>;
    cloud: z.ZodOptional<z.ZodObject<{
        account: z.ZodOptional<z.ZodObject<{
            id: z.ZodOptional<z.ZodString>;
            name: z.ZodOptional<z.ZodString>;
        }, z.core.$strip>>;
        availability_zone: z.ZodOptional<z.ZodString>;
        instance: z.ZodOptional<z.ZodObject<{
            id: z.ZodOptional<z.ZodString>;
            name: z.ZodOptional<z.ZodString>;
        }, z.core.$strip>>;
        machine: z.ZodOptional<z.ZodObject<{
            type: z.ZodOptional<z.ZodString>;
        }, z.core.$strip>>;
        project: z.ZodOptional<z.ZodObject<{
            id: z.ZodOptional<z.ZodString>;
            name: z.ZodOptional<z.ZodString>;
        }, z.core.$strip>>;
        provider: z.ZodOptional<z.ZodString>;
        region: z.ZodOptional<z.ZodString>;
        service: z.ZodOptional<z.ZodObject<{
            name: z.ZodOptional<z.ZodString>;
        }, z.core.$strip>>;
    }, z.core.$strip>>;
    entity: z.ZodOptional<z.ZodObject<{
        attributes: z.ZodOptional<z.ZodObject<{
            asset: z.ZodOptional<z.ZodBoolean>;
            known_redirects: z.ZodOptional<z.ZodArray<z.ZodString>>;
            managed: z.ZodOptional<z.ZodBoolean>;
            mfa_enabled: z.ZodOptional<z.ZodBoolean>;
            oauth_consent_restriction: z.ZodOptional<z.ZodString>;
            permissions: z.ZodOptional<z.ZodArray<z.ZodString>>;
            storage_class: z.ZodOptional<z.ZodString>;
            watchlists: z.ZodOptional<z.ZodArray<z.ZodString>>;
        }, z.core.$strip>>;
        behaviors: z.ZodOptional<z.ZodObject<{
            anomaly_job_ids: z.ZodOptional<z.ZodArray<z.ZodString>>;
            rule_names: z.ZodOptional<z.ZodArray<z.ZodString>>;
        }, z.core.$strip>>;
        EngineMetadata: z.ZodOptional<z.ZodObject<{
            Type: z.ZodOptional<z.ZodString>;
        }, z.core.$strip>>;
        id: z.ZodOptional<z.ZodString>;
        lifecycle: z.ZodOptional<z.ZodObject<{
            first_seen: z.ZodOptional<z.ZodString>;
            last_activity: z.ZodOptional<z.ZodString>;
            last_seen: z.ZodOptional<z.ZodString>;
        }, z.core.$strip>>;
        name: z.ZodOptional<z.ZodString>;
        relationships: z.ZodOptional<z.ZodObject<{
            accesses_frequently: z.ZodOptional<z.ZodObject<{
                ids: z.ZodOptional<z.ZodArray<z.ZodString>>;
                raw_identifiers: z.ZodOptional<z.ZodObject<{
                    'entity.id': z.ZodOptional<z.ZodArray<z.ZodString>>;
                    'host.id': z.ZodOptional<z.ZodArray<z.ZodString>>;
                    'host.name': z.ZodOptional<z.ZodArray<z.ZodString>>;
                    'service.name': z.ZodOptional<z.ZodArray<z.ZodString>>;
                    'user.email': z.ZodOptional<z.ZodArray<z.ZodString>>;
                    'user.id': z.ZodOptional<z.ZodArray<z.ZodString>>;
                    'user.name': z.ZodOptional<z.ZodArray<z.ZodString>>;
                }, z.core.$strip>>;
            }, z.core.$strip>>;
            accesses_infrequently: z.ZodOptional<z.ZodObject<{
                ids: z.ZodOptional<z.ZodArray<z.ZodString>>;
                raw_identifiers: z.ZodOptional<z.ZodObject<{
                    'entity.id': z.ZodOptional<z.ZodArray<z.ZodString>>;
                    'host.id': z.ZodOptional<z.ZodArray<z.ZodString>>;
                    'host.name': z.ZodOptional<z.ZodArray<z.ZodString>>;
                    'service.name': z.ZodOptional<z.ZodArray<z.ZodString>>;
                    'user.email': z.ZodOptional<z.ZodArray<z.ZodString>>;
                    'user.id': z.ZodOptional<z.ZodArray<z.ZodString>>;
                    'user.name': z.ZodOptional<z.ZodArray<z.ZodString>>;
                }, z.core.$strip>>;
            }, z.core.$strip>>;
            administers: z.ZodOptional<z.ZodObject<{
                ids: z.ZodOptional<z.ZodArray<z.ZodString>>;
                raw_identifiers: z.ZodOptional<z.ZodObject<{
                    'entity.id': z.ZodOptional<z.ZodArray<z.ZodString>>;
                    'host.id': z.ZodOptional<z.ZodArray<z.ZodString>>;
                    'host.name': z.ZodOptional<z.ZodArray<z.ZodString>>;
                    'service.name': z.ZodOptional<z.ZodArray<z.ZodString>>;
                    'user.email': z.ZodOptional<z.ZodArray<z.ZodString>>;
                    'user.id': z.ZodOptional<z.ZodArray<z.ZodString>>;
                    'user.name': z.ZodOptional<z.ZodArray<z.ZodString>>;
                }, z.core.$strip>>;
            }, z.core.$strip>>;
            communicates_with: z.ZodOptional<z.ZodObject<{
                ids: z.ZodOptional<z.ZodArray<z.ZodString>>;
                raw_identifiers: z.ZodOptional<z.ZodObject<{
                    'entity.id': z.ZodOptional<z.ZodArray<z.ZodString>>;
                    'host.id': z.ZodOptional<z.ZodArray<z.ZodString>>;
                    'host.name': z.ZodOptional<z.ZodArray<z.ZodString>>;
                    'service.name': z.ZodOptional<z.ZodArray<z.ZodString>>;
                    'user.email': z.ZodOptional<z.ZodArray<z.ZodString>>;
                    'user.id': z.ZodOptional<z.ZodArray<z.ZodString>>;
                    'user.name': z.ZodOptional<z.ZodArray<z.ZodString>>;
                }, z.core.$strip>>;
            }, z.core.$strip>>;
            depends_on: z.ZodOptional<z.ZodObject<{
                ids: z.ZodOptional<z.ZodArray<z.ZodString>>;
                raw_identifiers: z.ZodOptional<z.ZodObject<{
                    'entity.id': z.ZodOptional<z.ZodArray<z.ZodString>>;
                    'host.id': z.ZodOptional<z.ZodArray<z.ZodString>>;
                    'host.name': z.ZodOptional<z.ZodArray<z.ZodString>>;
                    'service.name': z.ZodOptional<z.ZodArray<z.ZodString>>;
                    'user.email': z.ZodOptional<z.ZodArray<z.ZodString>>;
                    'user.id': z.ZodOptional<z.ZodArray<z.ZodString>>;
                    'user.name': z.ZodOptional<z.ZodArray<z.ZodString>>;
                }, z.core.$strip>>;
            }, z.core.$strip>>;
            owns: z.ZodOptional<z.ZodObject<{
                ids: z.ZodOptional<z.ZodArray<z.ZodString>>;
                raw_identifiers: z.ZodOptional<z.ZodObject<{
                    'entity.id': z.ZodOptional<z.ZodArray<z.ZodString>>;
                    'host.id': z.ZodOptional<z.ZodArray<z.ZodString>>;
                    'host.name': z.ZodOptional<z.ZodArray<z.ZodString>>;
                    'service.name': z.ZodOptional<z.ZodArray<z.ZodString>>;
                    'user.email': z.ZodOptional<z.ZodArray<z.ZodString>>;
                    'user.id': z.ZodOptional<z.ZodArray<z.ZodString>>;
                    'user.name': z.ZodOptional<z.ZodArray<z.ZodString>>;
                }, z.core.$strip>>;
            }, z.core.$strip>>;
            owns_inferred: z.ZodOptional<z.ZodObject<{
                ids: z.ZodOptional<z.ZodArray<z.ZodString>>;
                raw_identifiers: z.ZodOptional<z.ZodObject<{
                    'entity.id': z.ZodOptional<z.ZodArray<z.ZodString>>;
                    'host.id': z.ZodOptional<z.ZodArray<z.ZodString>>;
                    'host.name': z.ZodOptional<z.ZodArray<z.ZodString>>;
                    'service.name': z.ZodOptional<z.ZodArray<z.ZodString>>;
                    'user.email': z.ZodOptional<z.ZodArray<z.ZodString>>;
                    'user.id': z.ZodOptional<z.ZodArray<z.ZodString>>;
                    'user.name': z.ZodOptional<z.ZodArray<z.ZodString>>;
                }, z.core.$strip>>;
            }, z.core.$strip>>;
            resolution: z.ZodOptional<z.ZodObject<{
                resolved_to: z.ZodOptional<z.ZodString>;
                risk: z.ZodOptional<z.ZodObject<{
                    calculated_level: z.ZodOptional<z.ZodEnum<{
                        Unknown: "Unknown";
                        Low: "Low";
                        Moderate: "Moderate";
                        High: "High";
                        Critical: "Critical";
                    }>>;
                    calculated_score: z.ZodOptional<z.ZodNumber>;
                    calculated_score_norm: z.ZodOptional<z.ZodNumber>;
                }, z.core.$strip>>;
            }, z.core.$strip>>;
            supervises: z.ZodOptional<z.ZodObject<{
                ids: z.ZodOptional<z.ZodArray<z.ZodString>>;
                raw_identifiers: z.ZodOptional<z.ZodObject<{
                    'entity.id': z.ZodOptional<z.ZodArray<z.ZodString>>;
                    'host.id': z.ZodOptional<z.ZodArray<z.ZodString>>;
                    'host.name': z.ZodOptional<z.ZodArray<z.ZodString>>;
                    'service.name': z.ZodOptional<z.ZodArray<z.ZodString>>;
                    'user.email': z.ZodOptional<z.ZodArray<z.ZodString>>;
                    'user.id': z.ZodOptional<z.ZodArray<z.ZodString>>;
                    'user.name': z.ZodOptional<z.ZodArray<z.ZodString>>;
                }, z.core.$strip>>;
            }, z.core.$strip>>;
        }, z.core.$strip>>;
        risk: z.ZodOptional<z.ZodObject<{
            calculated_level: z.ZodOptional<z.ZodEnum<{
                Unknown: "Unknown";
                Low: "Low";
                Moderate: "Moderate";
                High: "High";
                Critical: "Critical";
            }>>;
            calculated_score: z.ZodOptional<z.ZodNumber>;
            calculated_score_norm: z.ZodOptional<z.ZodNumber>;
        }, z.core.$strip>>;
        schema_version: z.ZodOptional<z.ZodString>;
        source: z.ZodOptional<z.ZodArray<z.ZodString>>;
        sub_type: z.ZodOptional<z.ZodString>;
        type: z.ZodOptional<z.ZodString>;
        url: z.ZodOptional<z.ZodString>;
    }, z.core.$strip>>;
    event: z.ZodOptional<z.ZodObject<{
        ingested: z.ZodOptional<z.ZodString>;
    }, z.core.$strip>>;
    labels: z.ZodOptional<z.ZodObject<{}, z.core.$loose>>;
    orchestrator: z.ZodOptional<z.ZodObject<{
        api_version: z.ZodOptional<z.ZodString>;
        cluster: z.ZodOptional<z.ZodObject<{
            id: z.ZodOptional<z.ZodString>;
            name: z.ZodOptional<z.ZodString>;
            url: z.ZodOptional<z.ZodString>;
            version: z.ZodOptional<z.ZodString>;
        }, z.core.$strip>>;
        namespace: z.ZodOptional<z.ZodString>;
        organization: z.ZodOptional<z.ZodString>;
        resource: z.ZodOptional<z.ZodObject<{
            annotation: z.ZodOptional<z.ZodString>;
            id: z.ZodOptional<z.ZodString>;
            ip: z.ZodOptional<z.ZodString>;
            label: z.ZodOptional<z.ZodString>;
            name: z.ZodOptional<z.ZodString>;
            parent: z.ZodOptional<z.ZodObject<{
                type: z.ZodOptional<z.ZodString>;
            }, z.core.$strip>>;
            type: z.ZodOptional<z.ZodString>;
        }, z.core.$strip>>;
        type: z.ZodOptional<z.ZodString>;
    }, z.core.$strip>>;
    tags: z.ZodOptional<z.ZodArray<z.ZodString>>;
}, z.core.$strip>]>;
export type PostSecurityEntityStoreEntitiesEntitytypeRequest = z.infer<typeof PostSecurityEntityStoreEntitiesEntitytypeRequest>;
//# sourceMappingURL=post_security_entity_store_entities_entitytype.d.ts.map