/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */
/*
 * This file was automatically generated by elastic/elastic-client-generator-js.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source open api file,
 * and elastic/elastic-client-generator-js to regenerate this file again.
 */
/* eslint-disable @typescript-eslint/no-redeclare */
import { z } from 'zod';
export const Security_Entity_Analytics_API_PrivmonUserCsvUploadStats = z.object({
    failedOperations: z.number(),
    successfulOperations: z.number(),
    totalOperations: z.number(),
    uploaded: z.number()
}).meta({ id: 'Security_Entity_Analytics_API_PrivmonUserCsvUploadStats' });
export const Security_Entity_Analytics_API_PrivmonUserCsvUploadErrorItem = z.object({
    index: z.number().nullable(),
    message: z.string(),
    username: z.string().nullable()
}).meta({ id: 'Security_Entity_Analytics_API_PrivmonUserCsvUploadErrorItem' });
export const PrivmonBulkUploadUsersCSVResponse = z.object({
    errors: z.array(Security_Entity_Analytics_API_PrivmonUserCsvUploadErrorItem),
    stats: Security_Entity_Analytics_API_PrivmonUserCsvUploadStats
}).meta({ id: 'PrivmonBulkUploadUsersCSVResponse' });
//# sourceMappingURL=privmon_bulk_upload_users_csv.js.map