/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */
/*
 * This file was automatically generated by elastic/elastic-client-generator-js.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source open api file,
 * and elastic/elastic-client-generator-js to regenerate this file again.
 */
/* eslint-disable @typescript-eslint/no-redeclare */
import { z } from 'zod';
export const PutAgentBuilderAgentsIdAclRequest = z.object({
    entries: z.array(z.object({
        name: z.string(),
        role: z.enum(['user', 'editor', 'manager']),
        type: z.enum(['user'])
    }))
}).meta({ id: 'PutAgentBuilderAgentsIdAclRequest' });
//# sourceMappingURL=put_agent_builder_agents_id_acl.js.map