/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source open api file,
 * and elastic/elastic-client-generator-js to regenerate this file again.
 */

import { createRegistry } from '../../registry.ts'
import { kibanaManifest } from './manifest.ts'
import type { ApiRegistry, KbApiDefinition } from './types.ts'

async function loadDefinitions (namespaceFile: string): Promise<KbApiDefinition[]> {
  switch (namespaceFile) {
    case 'agent-builder': {
      const mod = await import('./apis/agent-builder.ts') as Record<string, unknown>
      return mod['agentBuilderDefinitions'] as KbApiDefinition[]
    }
    case 'alerting': {
      const mod = await import('./apis/alerting.ts') as Record<string, unknown>
      return mod['alertingDefinitions'] as KbApiDefinition[]
    }
    case 'apm-agent-configuration': {
      const mod = await import('./apis/apm-agent-configuration.ts') as Record<string, unknown>
      return mod['apmAgentConfigurationDefinitions'] as KbApiDefinition[]
    }
    case 'apm-agent-keys': {
      const mod = await import('./apis/apm-agent-keys.ts') as Record<string, unknown>
      return mod['apmAgentKeysDefinitions'] as KbApiDefinition[]
    }
    case 'apm-annotations': {
      const mod = await import('./apis/apm-annotations.ts') as Record<string, unknown>
      return mod['apmAnnotationsDefinitions'] as KbApiDefinition[]
    }
    case 'apm-server-schema': {
      const mod = await import('./apis/apm-server-schema.ts') as Record<string, unknown>
      return mod['apmServerSchemaDefinitions'] as KbApiDefinition[]
    }
    case 'connectors': {
      const mod = await import('./apis/connectors.ts') as Record<string, unknown>
      return mod['connectorsDefinitions'] as KbApiDefinition[]
    }
    case 'dashboards': {
      const mod = await import('./apis/dashboards.ts') as Record<string, unknown>
      return mod['dashboardsDefinitions'] as KbApiDefinition[]
    }
    case 'data-streams': {
      const mod = await import('./apis/data-streams.ts') as Record<string, unknown>
      return mod['dataStreamsDefinitions'] as KbApiDefinition[]
    }
    case 'data-views': {
      const mod = await import('./apis/data-views.ts') as Record<string, unknown>
      return mod['dataViewsDefinitions'] as KbApiDefinition[]
    }
    case 'elastic-agent-actions': {
      const mod = await import('./apis/elastic-agent-actions.ts') as Record<string, unknown>
      return mod['elasticAgentActionsDefinitions'] as KbApiDefinition[]
    }
    case 'elastic-agent-binary-download-sources': {
      const mod = await import('./apis/elastic-agent-binary-download-sources.ts') as Record<string, unknown>
      return mod['elasticAgentBinaryDownloadSourcesDefinitions'] as KbApiDefinition[]
    }
    case 'elastic-agent-policies': {
      const mod = await import('./apis/elastic-agent-policies.ts') as Record<string, unknown>
      return mod['elasticAgentPoliciesDefinitions'] as KbApiDefinition[]
    }
    case 'elastic-agent-status': {
      const mod = await import('./apis/elastic-agent-status.ts') as Record<string, unknown>
      return mod['elasticAgentStatusDefinitions'] as KbApiDefinition[]
    }
    case 'elastic-agents': {
      const mod = await import('./apis/elastic-agents.ts') as Record<string, unknown>
      return mod['elasticAgentsDefinitions'] as KbApiDefinition[]
    }
    case 'elastic-package-manager-epm': {
      const mod = await import('./apis/elastic-package-manager-epm.ts') as Record<string, unknown>
      return mod['elasticPackageManagerEpmDefinitions'] as KbApiDefinition[]
    }
    case 'fleet-agentless-policies': {
      const mod = await import('./apis/fleet-agentless-policies.ts') as Record<string, unknown>
      return mod['fleetAgentlessPoliciesDefinitions'] as KbApiDefinition[]
    }
    case 'fleet-cloud-connectors': {
      const mod = await import('./apis/fleet-cloud-connectors.ts') as Record<string, unknown>
      return mod['fleetCloudConnectorsDefinitions'] as KbApiDefinition[]
    }
    case 'fleet-enrollment-api-keys': {
      const mod = await import('./apis/fleet-enrollment-api-keys.ts') as Record<string, unknown>
      return mod['fleetEnrollmentApiKeysDefinitions'] as KbApiDefinition[]
    }
    case 'fleet-internals': {
      const mod = await import('./apis/fleet-internals.ts') as Record<string, unknown>
      return mod['fleetInternalsDefinitions'] as KbApiDefinition[]
    }
    case 'fleet-outputs': {
      const mod = await import('./apis/fleet-outputs.ts') as Record<string, unknown>
      return mod['fleetOutputsDefinitions'] as KbApiDefinition[]
    }
    case 'fleet-package-policies': {
      const mod = await import('./apis/fleet-package-policies.ts') as Record<string, unknown>
      return mod['fleetPackagePoliciesDefinitions'] as KbApiDefinition[]
    }
    case 'fleet-proxies': {
      const mod = await import('./apis/fleet-proxies.ts') as Record<string, unknown>
      return mod['fleetProxiesDefinitions'] as KbApiDefinition[]
    }
    case 'fleet-server-hosts': {
      const mod = await import('./apis/fleet-server-hosts.ts') as Record<string, unknown>
      return mod['fleetServerHostsDefinitions'] as KbApiDefinition[]
    }
    case 'fleet-service-tokens': {
      const mod = await import('./apis/fleet-service-tokens.ts') as Record<string, unknown>
      return mod['fleetServiceTokensDefinitions'] as KbApiDefinition[]
    }
    case 'fleet-uninstall-tokens': {
      const mod = await import('./apis/fleet-uninstall-tokens.ts') as Record<string, unknown>
      return mod['fleetUninstallTokensDefinitions'] as KbApiDefinition[]
    }
    case 'maintenance-window': {
      const mod = await import('./apis/maintenance-window.ts') as Record<string, unknown>
      return mod['maintenanceWindowDefinitions'] as KbApiDefinition[]
    }
    case 'message-signing-service': {
      const mod = await import('./apis/message-signing-service.ts') as Record<string, unknown>
      return mod['messageSigningServiceDefinitions'] as KbApiDefinition[]
    }
    case 'misc': {
      const mod = await import('./apis/misc.ts') as Record<string, unknown>
      return mod['miscDefinitions'] as KbApiDefinition[]
    }
    case 'ml': {
      const mod = await import('./apis/ml.ts') as Record<string, unknown>
      return mod['mlDefinitions'] as KbApiDefinition[]
    }
    case 'observabilityaiassistant': {
      const mod = await import('./apis/observabilityaiassistant.ts') as Record<string, unknown>
      return mod['observabilityaiassistantDefinitions'] as KbApiDefinition[]
    }
    case 'roles': {
      const mod = await import('./apis/roles.ts') as Record<string, unknown>
      return mod['rolesDefinitions'] as KbApiDefinition[]
    }
    case 'saved-objects': {
      const mod = await import('./apis/saved-objects.ts') as Record<string, unknown>
      return mod['savedObjectsDefinitions'] as KbApiDefinition[]
    }
    case 'security-ai-assistant-api': {
      const mod = await import('./apis/security-ai-assistant-api.ts') as Record<string, unknown>
      return mod['securityAiAssistantApiDefinitions'] as KbApiDefinition[]
    }
    case 'security-attack-discovery-api': {
      const mod = await import('./apis/security-attack-discovery-api.ts') as Record<string, unknown>
      return mod['securityAttackDiscoveryApiDefinitions'] as KbApiDefinition[]
    }
    case 'security-detections-api': {
      const mod = await import('./apis/security-detections-api.ts') as Record<string, unknown>
      return mod['securityDetectionsApiDefinitions'] as KbApiDefinition[]
    }
    case 'security-endpoint-exceptions-api': {
      const mod = await import('./apis/security-endpoint-exceptions-api.ts') as Record<string, unknown>
      return mod['securityEndpointExceptionsApiDefinitions'] as KbApiDefinition[]
    }
    case 'security-endpoint-management-api': {
      const mod = await import('./apis/security-endpoint-management-api.ts') as Record<string, unknown>
      return mod['securityEndpointManagementApiDefinitions'] as KbApiDefinition[]
    }
    case 'security-entity-analytics-api': {
      const mod = await import('./apis/security-entity-analytics-api.ts') as Record<string, unknown>
      return mod['securityEntityAnalyticsApiDefinitions'] as KbApiDefinition[]
    }
    case 'security-entity-store': {
      const mod = await import('./apis/security-entity-store.ts') as Record<string, unknown>
      return mod['securityEntityStoreDefinitions'] as KbApiDefinition[]
    }
    case 'security-exceptions-api': {
      const mod = await import('./apis/security-exceptions-api.ts') as Record<string, unknown>
      return mod['securityExceptionsApiDefinitions'] as KbApiDefinition[]
    }
    case 'security-lists-api': {
      const mod = await import('./apis/security-lists-api.ts') as Record<string, unknown>
      return mod['securityListsApiDefinitions'] as KbApiDefinition[]
    }
    case 'security-osquery-api': {
      const mod = await import('./apis/security-osquery-api.ts') as Record<string, unknown>
      return mod['securityOsqueryApiDefinitions'] as KbApiDefinition[]
    }
    case 'security-timeline-api': {
      const mod = await import('./apis/security-timeline-api.ts') as Record<string, unknown>
      return mod['securityTimelineApiDefinitions'] as KbApiDefinition[]
    }
    case 'slo': {
      const mod = await import('./apis/slo.ts') as Record<string, unknown>
      return mod['sloDefinitions'] as KbApiDefinition[]
    }
    case 'spaces': {
      const mod = await import('./apis/spaces.ts') as Record<string, unknown>
      return mod['spacesDefinitions'] as KbApiDefinition[]
    }
    case 'streams': {
      const mod = await import('./apis/streams.ts') as Record<string, unknown>
      return mod['streamsDefinitions'] as KbApiDefinition[]
    }
    case 'system': {
      const mod = await import('./apis/system.ts') as Record<string, unknown>
      return mod['systemDefinitions'] as KbApiDefinition[]
    }
    case 'tags': {
      const mod = await import('./apis/tags.ts') as Record<string, unknown>
      return mod['tagsDefinitions'] as KbApiDefinition[]
    }
    case 'task-manager': {
      const mod = await import('./apis/task-manager.ts') as Record<string, unknown>
      return mod['taskManagerDefinitions'] as KbApiDefinition[]
    }
    case 'visualizations': {
      const mod = await import('./apis/visualizations.ts') as Record<string, unknown>
      return mod['visualizationsDefinitions'] as KbApiDefinition[]
    }
    case 'workflows': {
      const mod = await import('./apis/workflows.ts') as Record<string, unknown>
      return mod['workflowsDefinitions'] as KbApiDefinition[]
    }
    default: return []
  }
}

export const kibanaRegistry: ApiRegistry = createRegistry(kibanaManifest, loadDefinitions)
