/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source open api file,
 * and elastic/elastic-client-generator-js to regenerate this file again.
 */

/* eslint-disable @typescript-eslint/no-redeclare */
import { z } from 'zod'

export const CreateTrafficFilterRequest = z.object({
  name: z.string(),
  description: z.string().optional(),
  type: z.enum(['ip', 'vpce', 'private_endpoint']),
  include_by_default: z.boolean().optional(),
  region: z.string(),
  rules: z.array(z.object({
    description: z.string().optional(),
    source: z.string().optional(),
    azure_endpoint_name: z.string().optional(),
    azure_endpoint_guid: z.string().optional()
  })).optional()
}).meta({ id: 'CreateTrafficFilterRequest' })
export type CreateTrafficFilterRequest = z.infer<typeof CreateTrafficFilterRequest>

export const CreateTrafficFilterResponse = z.object({
  id: z.string(),
  name: z.string(),
  description: z.string().optional(),
  type: z.enum(['ip', 'vpce', 'private_endpoint']),
  include_by_default: z.boolean(),
  region: z.string(),
  rules: z.array(z.object({
    description: z.string().optional(),
    source: z.string().optional(),
    azure_endpoint_name: z.string().optional(),
    azure_endpoint_guid: z.string().optional()
  }))
}).meta({ id: 'CreateTrafficFilterResponse' })
export type CreateTrafficFilterResponse = z.infer<typeof CreateTrafficFilterResponse>
