/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source open api file,
 * and elastic/elastic-client-generator-js to regenerate this file again.
 */

/* eslint-disable @typescript-eslint/no-redeclare */
import { z } from 'zod'

export const GetSecurityProjectResponse = z.intersection(z.object({
  id: z.string(),
  name: z.string(),
  alias: z.string(),
  region_id: z.string(),
  metadata: z.object({
    created_at: z.string(),
    created_by: z.string(),
    organization_id: z.string(),
    suspended_at: z.string().optional(),
    suspended_reason: z.string().optional(),
    tags: z.record(z.string(), z.string()).optional(),
    system_tags: z.record(z.string(), z.string()).optional()
  }),
  cloud_id: z.string(),
  traffic_filters: z.array(z.object({
    id: z.string()
  })).optional(),
  linked: z.object({
    projects: z.record(z.string(), z.object({
      status: z.enum(['enabled', 'suspended', 'deleted']),
      type: z.enum(['elasticsearch', 'observability', 'security', 'vectordb'])
    }))
  }).optional()
}), z.object({
  type: z.enum(['security']),
  endpoints: z.object({
    elasticsearch: z.string(),
    kibana: z.string(),
    ingest: z.string()
  }),
  private_endpoints: z.object({
    elasticsearch: z.string(),
    kibana: z.string(),
    ingest: z.string()
  }).optional(),
  search_lake: z.object({
    data_retention: z.object({
      max_retention_days: z.number().optional(),
      default_retention_days: z.number().optional()
    }).optional()
  }).optional(),
  admin_features_package: z.enum(['standard', 'enterprise']).optional(),
  product_types: z.array(z.object({
    product_line: z.enum(['security', 'cloud', 'endpoint']),
    product_tier: z.enum(['complete', 'essentials'])
  })).optional()
})).meta({ id: 'GetSecurityProjectResponse' })
export type GetSecurityProjectResponse = z.infer<typeof GetSecurityProjectResponse>
