/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source open api file,
 * and elastic/elastic-client-generator-js to regenerate this file again.
 */

import { createRegistry } from '../../registry.ts'
import { cloudManifest } from './manifest.ts'
import type { ApiRegistry, CloudApiDefinition } from './types.ts'

async function loadDefinitions (namespaceFile: string): Promise<CloudApiDefinition[]> {
  switch (namespaceFile) {
    case 'accounts': {
      const mod = await import('./apis/accounts.ts') as Record<string, unknown>
      return mod['accountsDefinitions'] as CloudApiDefinition[]
    }
    case 'authentication': {
      const mod = await import('./apis/authentication.ts') as Record<string, unknown>
      return mod['authenticationDefinitions'] as CloudApiDefinition[]
    }
    case 'billing-costs-analysis': {
      const mod = await import('./apis/billing-costs-analysis.ts') as Record<string, unknown>
      return mod['billingCostsAnalysisDefinitions'] as CloudApiDefinition[]
    }
    case 'deployment-templates': {
      const mod = await import('./apis/deployment-templates.ts') as Record<string, unknown>
      return mod['deploymentTemplatesDefinitions'] as CloudApiDefinition[]
    }
    case 'deployments': {
      const mod = await import('./apis/deployments.ts') as Record<string, unknown>
      return mod['deploymentsDefinitions'] as CloudApiDefinition[]
    }
    case 'deployments-traffic-filter': {
      const mod = await import('./apis/deployments-traffic-filter.ts') as Record<string, unknown>
      return mod['deploymentsTrafficFilterDefinitions'] as CloudApiDefinition[]
    }
    case 'extensions': {
      const mod = await import('./apis/extensions.ts') as Record<string, unknown>
      return mod['extensionsDefinitions'] as CloudApiDefinition[]
    }
    case 'organizations': {
      const mod = await import('./apis/organizations.ts') as Record<string, unknown>
      return mod['organizationsDefinitions'] as CloudApiDefinition[]
    }
    case 'stack': {
      const mod = await import('./apis/stack.ts') as Record<string, unknown>
      return mod['stackDefinitions'] as CloudApiDefinition[]
    }
    case 'trusted-environments': {
      const mod = await import('./apis/trusted-environments.ts') as Record<string, unknown>
      return mod['trustedEnvironmentsDefinitions'] as CloudApiDefinition[]
    }
    case 'user-role-assignments': {
      const mod = await import('./apis/user-role-assignments.ts') as Record<string, unknown>
      return mod['userRoleAssignmentsDefinitions'] as CloudApiDefinition[]
    }
    default: return []
  }
}

export const cloudRegistry: ApiRegistry = createRegistry(cloudManifest, loadDefinitions)
