/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */
/*
 * This file was automatically generated by elastic/elastic-client-generator-js.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source open api file,
 * and elastic/elastic-client-generator-js to regenerate this file again.
 */
import { createRegistry } from "../../registry.js";
import { kibanaManifest } from "./manifest.js";
async function loadDefinitions(namespaceFile) {
    switch (namespaceFile) {
        case 'agent-builder': {
            const mod = await import("./apis/agent-builder.js");
            return mod['agentBuilderDefinitions'];
        }
        case 'alerting': {
            const mod = await import("./apis/alerting.js");
            return mod['alertingDefinitions'];
        }
        case 'apm-agent-configuration': {
            const mod = await import("./apis/apm-agent-configuration.js");
            return mod['apmAgentConfigurationDefinitions'];
        }
        case 'apm-agent-keys': {
            const mod = await import("./apis/apm-agent-keys.js");
            return mod['apmAgentKeysDefinitions'];
        }
        case 'apm-annotations': {
            const mod = await import("./apis/apm-annotations.js");
            return mod['apmAnnotationsDefinitions'];
        }
        case 'apm-server-schema': {
            const mod = await import("./apis/apm-server-schema.js");
            return mod['apmServerSchemaDefinitions'];
        }
        case 'connectors': {
            const mod = await import("./apis/connectors.js");
            return mod['connectorsDefinitions'];
        }
        case 'dashboards': {
            const mod = await import("./apis/dashboards.js");
            return mod['dashboardsDefinitions'];
        }
        case 'data-streams': {
            const mod = await import("./apis/data-streams.js");
            return mod['dataStreamsDefinitions'];
        }
        case 'data-views': {
            const mod = await import("./apis/data-views.js");
            return mod['dataViewsDefinitions'];
        }
        case 'elastic-agent-actions': {
            const mod = await import("./apis/elastic-agent-actions.js");
            return mod['elasticAgentActionsDefinitions'];
        }
        case 'elastic-agent-binary-download-sources': {
            const mod = await import("./apis/elastic-agent-binary-download-sources.js");
            return mod['elasticAgentBinaryDownloadSourcesDefinitions'];
        }
        case 'elastic-agent-policies': {
            const mod = await import("./apis/elastic-agent-policies.js");
            return mod['elasticAgentPoliciesDefinitions'];
        }
        case 'elastic-agent-status': {
            const mod = await import("./apis/elastic-agent-status.js");
            return mod['elasticAgentStatusDefinitions'];
        }
        case 'elastic-agents': {
            const mod = await import("./apis/elastic-agents.js");
            return mod['elasticAgentsDefinitions'];
        }
        case 'elastic-package-manager-epm': {
            const mod = await import("./apis/elastic-package-manager-epm.js");
            return mod['elasticPackageManagerEpmDefinitions'];
        }
        case 'fleet-agentless-policies': {
            const mod = await import("./apis/fleet-agentless-policies.js");
            return mod['fleetAgentlessPoliciesDefinitions'];
        }
        case 'fleet-cloud-connectors': {
            const mod = await import("./apis/fleet-cloud-connectors.js");
            return mod['fleetCloudConnectorsDefinitions'];
        }
        case 'fleet-enrollment-api-keys': {
            const mod = await import("./apis/fleet-enrollment-api-keys.js");
            return mod['fleetEnrollmentApiKeysDefinitions'];
        }
        case 'fleet-internals': {
            const mod = await import("./apis/fleet-internals.js");
            return mod['fleetInternalsDefinitions'];
        }
        case 'fleet-outputs': {
            const mod = await import("./apis/fleet-outputs.js");
            return mod['fleetOutputsDefinitions'];
        }
        case 'fleet-package-policies': {
            const mod = await import("./apis/fleet-package-policies.js");
            return mod['fleetPackagePoliciesDefinitions'];
        }
        case 'fleet-proxies': {
            const mod = await import("./apis/fleet-proxies.js");
            return mod['fleetProxiesDefinitions'];
        }
        case 'fleet-server-hosts': {
            const mod = await import("./apis/fleet-server-hosts.js");
            return mod['fleetServerHostsDefinitions'];
        }
        case 'fleet-service-tokens': {
            const mod = await import("./apis/fleet-service-tokens.js");
            return mod['fleetServiceTokensDefinitions'];
        }
        case 'fleet-uninstall-tokens': {
            const mod = await import("./apis/fleet-uninstall-tokens.js");
            return mod['fleetUninstallTokensDefinitions'];
        }
        case 'maintenance-window': {
            const mod = await import("./apis/maintenance-window.js");
            return mod['maintenanceWindowDefinitions'];
        }
        case 'message-signing-service': {
            const mod = await import("./apis/message-signing-service.js");
            return mod['messageSigningServiceDefinitions'];
        }
        case 'misc': {
            const mod = await import("./apis/misc.js");
            return mod['miscDefinitions'];
        }
        case 'ml': {
            const mod = await import("./apis/ml.js");
            return mod['mlDefinitions'];
        }
        case 'observabilityaiassistant': {
            const mod = await import("./apis/observabilityaiassistant.js");
            return mod['observabilityaiassistantDefinitions'];
        }
        case 'roles': {
            const mod = await import("./apis/roles.js");
            return mod['rolesDefinitions'];
        }
        case 'saved-objects': {
            const mod = await import("./apis/saved-objects.js");
            return mod['savedObjectsDefinitions'];
        }
        case 'security-ai-assistant-api': {
            const mod = await import("./apis/security-ai-assistant-api.js");
            return mod['securityAiAssistantApiDefinitions'];
        }
        case 'security-attack-discovery-api': {
            const mod = await import("./apis/security-attack-discovery-api.js");
            return mod['securityAttackDiscoveryApiDefinitions'];
        }
        case 'security-detections-api': {
            const mod = await import("./apis/security-detections-api.js");
            return mod['securityDetectionsApiDefinitions'];
        }
        case 'security-endpoint-exceptions-api': {
            const mod = await import("./apis/security-endpoint-exceptions-api.js");
            return mod['securityEndpointExceptionsApiDefinitions'];
        }
        case 'security-endpoint-management-api': {
            const mod = await import("./apis/security-endpoint-management-api.js");
            return mod['securityEndpointManagementApiDefinitions'];
        }
        case 'security-entity-analytics-api': {
            const mod = await import("./apis/security-entity-analytics-api.js");
            return mod['securityEntityAnalyticsApiDefinitions'];
        }
        case 'security-entity-store': {
            const mod = await import("./apis/security-entity-store.js");
            return mod['securityEntityStoreDefinitions'];
        }
        case 'security-exceptions-api': {
            const mod = await import("./apis/security-exceptions-api.js");
            return mod['securityExceptionsApiDefinitions'];
        }
        case 'security-lists-api': {
            const mod = await import("./apis/security-lists-api.js");
            return mod['securityListsApiDefinitions'];
        }
        case 'security-osquery-api': {
            const mod = await import("./apis/security-osquery-api.js");
            return mod['securityOsqueryApiDefinitions'];
        }
        case 'security-timeline-api': {
            const mod = await import("./apis/security-timeline-api.js");
            return mod['securityTimelineApiDefinitions'];
        }
        case 'slo': {
            const mod = await import("./apis/slo.js");
            return mod['sloDefinitions'];
        }
        case 'spaces': {
            const mod = await import("./apis/spaces.js");
            return mod['spacesDefinitions'];
        }
        case 'streams': {
            const mod = await import("./apis/streams.js");
            return mod['streamsDefinitions'];
        }
        case 'system': {
            const mod = await import("./apis/system.js");
            return mod['systemDefinitions'];
        }
        case 'tags': {
            const mod = await import("./apis/tags.js");
            return mod['tagsDefinitions'];
        }
        case 'task-manager': {
            const mod = await import("./apis/task-manager.js");
            return mod['taskManagerDefinitions'];
        }
        case 'visualizations': {
            const mod = await import("./apis/visualizations.js");
            return mod['visualizationsDefinitions'];
        }
        case 'workflows': {
            const mod = await import("./apis/workflows.js");
            return mod['workflowsDefinitions'];
        }
        default: return [];
    }
}
export const kibanaRegistry = createRegistry(kibanaManifest, loadDefinitions);
//# sourceMappingURL=index.js.map