/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/* eslint-disable @typescript-eslint/no-redeclare */
import { z } from 'zod'

import { AcknowledgedResponseBase, Duration, Metadata, Name, VersionNumber } from './_types.js'
import { IndicesPutIndexTemplateIndexTemplateMapping } from './indices.put_index_template.js'

/**
 * Create or update a component template.
 *
 * Component templates are building blocks for constructing index templates that specify index mappings, settings, and aliases.
 *
 * An index template can be composed of multiple component templates.
 * To use a component template, specify it in an index template’s `composed_of` list.
 * Component templates are only applied to new data streams and indices as part of a matching index template.
 *
 * Settings and mappings specified directly in the index template or the create index request override any settings or mappings specified in a component template.
 *
 * Component templates are only used during index creation.
 * For data streams, this includes data stream creation and the creation of a stream’s backing indices.
 * Changes to component templates do not affect existing indices, including a stream’s backing indices.
 *
 * You can use C-style `/* *\/` block comments in component templates.
 * You can include comments anywhere in the request body except before the opening curly bracket.
 *
 * **Applying component templates**
 *
 * You cannot directly apply a component template to a data stream or index.
 * To be applied, a component template must be included in an index template's `composed_of` list.
 */
export const ClusterPutComponentTemplateRequest = z.object({
  name: z.lazy(() => Name).describe('Name of the component template to create. Elasticsearch includes the following built-in component templates: `logs-mappings`; `logs-settings`; `metrics-mappings`; `metrics-settings`;`synthetics-mapping`; `synthetics-settings`. Elastic Agent uses these templates to configure backing indices for its data streams. If you use Elastic Agent and want to overwrite one of these templates, set the `version` for your replacement template higher than the current version. If you don’t use Elastic Agent and want to disable all built-in component and index templates, set `stack.templates.enabled` to `false` using the cluster update settings API.').meta({ found_in: 'path' }),
  create: z.boolean().describe('If `true`, this request cannot replace or update existing component templates.').optional().meta({ found_in: 'query' }),
  cause: z.string().describe('User defined reason for create the component template.').optional().meta({ found_in: 'query' }),
  master_timeout: z.lazy(() => Duration).describe('Period to wait for a connection to the master node. If no response is received before the timeout expires, the request fails and returns an error.').optional().meta({ found_in: 'query' }),
  template: IndicesPutIndexTemplateIndexTemplateMapping.describe('The template to be applied which includes mappings, settings, or aliases configuration.').meta({ found_in: 'body' }),
  version: z.lazy(() => VersionNumber).describe('Version number used to manage component templates externally. This number isn\'t automatically generated or incremented by Elasticsearch. To unset a version, replace the template without specifying a version.').optional().meta({ found_in: 'body' }),
  _meta: z.lazy(() => Metadata).describe('Optional user metadata about the component template. It may have any contents. This map is not automatically generated by Elasticsearch. This information is stored in the cluster state, so keeping it short is preferable. To unset `_meta`, replace the template without specifying this information.').optional().meta({ found_in: 'body' }),
  deprecated: z.boolean().describe('Marks this index template as deprecated. When creating or updating a non-deprecated index template that uses deprecated components, Elasticsearch will emit a deprecation warning.').optional().meta({ found_in: 'body' })
}).meta({ id: 'ClusterPutComponentTemplateRequest' })
export type ClusterPutComponentTemplateRequest = z.infer<typeof ClusterPutComponentTemplateRequest>

export const ClusterPutComponentTemplateResponse = z.lazy(() => AcknowledgedResponseBase).meta({ id: 'ClusterPutComponentTemplateResponse' })
export type ClusterPutComponentTemplateResponse = z.infer<typeof ClusterPutComponentTemplateResponse>
