/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/* eslint-disable @typescript-eslint/no-redeclare */
import { z } from 'zod'

import { AcknowledgedResponseBase, Duration, IndexName, Name, VersionNumber, integer } from './_types.js'
import { MappingTypeMapping } from './_types.mapping.js'
import { IndicesAlias, IndicesIndexSettings } from './indices.js'

/**
 * Create or update a legacy index template.
 *
 * Index templates define settings, mappings, and aliases that can be applied automatically to new indices.
 * Elasticsearch applies templates to new indices based on an index pattern that matches the index name.
 *
 * IMPORTANT: This documentation is about legacy index templates, which are deprecated and will be replaced by the composable templates introduced in Elasticsearch 7.8.
 *
 * Composable templates always take precedence over legacy templates.
 * If no composable template matches a new index, matching legacy templates are applied according to their order.
 *
 * Index templates are only applied during index creation.
 * Changes to index templates do not affect existing indices.
 * Settings and mappings specified in create index API requests override any settings or mappings specified in an index template.
 *
 * You can use C-style `/* *\/` block comments in index templates.
 * You can include comments anywhere in the request body, except before the opening curly bracket.
 *
 * **Indices matching multiple templates**
 *
 * Multiple index templates can potentially match an index, in this case, both the settings and mappings are merged into the final configuration of the index.
 * The order of the merging can be controlled using the order parameter, with lower order being applied first, and higher orders overriding them.
 * NOTE: Multiple matching templates with the same order value will result in a non-deterministic merging order.
 * @deprecated
 */
export const IndicesPutTemplateRequest = z.object({
  name: z.lazy(() => Name).describe('The name of the template').meta({ found_in: 'path' }),
  create: z.boolean().describe('If true, this request cannot replace or update existing index templates.').optional().meta({ found_in: 'query' }),
  master_timeout: z.lazy(() => Duration).describe('Period to wait for a connection to the master node. If no response is received before the timeout expires, the request fails and returns an error.').optional().meta({ found_in: 'query' }),
  cause: z.string().describe('User defined reason for creating or updating the index template').optional().meta({ found_in: 'query' }),
  aliases: z.record(z.lazy(() => IndexName), z.lazy(() => IndicesAlias)).describe('Aliases for the index.').optional().meta({ found_in: 'body' }),
  index_patterns: z.union([z.string(), z.array(z.string())]).describe('Array of wildcard expressions used to match the names of indices during creation.').optional().meta({ found_in: 'body' }),
  mappings: z.lazy(() => MappingTypeMapping).describe('Mapping for fields in the index.').optional().meta({ found_in: 'body' }),
  order: z.lazy(() => integer).describe('Order in which Elasticsearch applies this template if index matches multiple templates. Templates with lower \'order\' values are merged first. Templates with higher \'order\' values are merged later, overriding templates with lower values.').optional().meta({ found_in: 'body' }),
  settings: z.lazy(() => IndicesIndexSettings).describe('Configuration options for the index.').optional().meta({ found_in: 'body' }),
  version: z.lazy(() => VersionNumber).describe('Version number used to manage index templates externally. This number is not automatically generated by Elasticsearch. To unset a version, replace the template without specifying one.').optional().meta({ found_in: 'body' })
}).meta({ id: 'IndicesPutTemplateRequest' })
export type IndicesPutTemplateRequest = z.infer<typeof IndicesPutTemplateRequest>

export const IndicesPutTemplateResponse = z.lazy(() => AcknowledgedResponseBase).meta({ id: 'IndicesPutTemplateResponse' })
export type IndicesPutTemplateResponse = z.infer<typeof IndicesPutTemplateResponse>
