/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/* eslint-disable @typescript-eslint/no-redeclare */
import { z } from 'zod'

import { Duration, Id, integer } from './_types.js'
import { InferenceRequestChatCompletion } from './inference.js'

/** The base reasoning detail that includes common fields across different types of reasoning details. */
export const InferenceBaseReasoningDetail = z.object({
  format: z.string().describe('The format of the reasoning detail.').optional(),
  id: z.string().describe('The identifier of the reasoning detail.').optional(),
  index: z.lazy(() => integer).describe('The index of the reasoning detail, which indicates its position in the sequence of reasoning details generated by the model.').optional()
}).meta({ id: 'InferenceBaseReasoningDetail' })
export type InferenceBaseReasoningDetail = z.infer<typeof InferenceBaseReasoningDetail>

/** The function called by the tool. */
export const InferenceChatCompletionToolCallFunction = z.object({
  arguments: z.string().describe('The arguments to call the function with, as a JSON string.').optional(),
  name: z.string().describe('The name of the function.').optional()
}).meta({ id: 'InferenceChatCompletionToolCallFunction' })
export type InferenceChatCompletionToolCallFunction = z.infer<typeof InferenceChatCompletionToolCallFunction>

/** A tool call generated by the model. */
export const InferenceChatCompletionToolCall = z.object({
  index: z.lazy(() => integer).describe('The index of the tool call in the list of tool calls generated by the model.'),
  id: z.string().describe('The identifier of the tool call.').optional(),
  function: InferenceChatCompletionToolCallFunction.describe('The function that the model called.').optional(),
  type: z.string().describe('The type of the tool call.')
}).meta({ id: 'InferenceChatCompletionToolCall' })
export type InferenceChatCompletionToolCall = z.infer<typeof InferenceChatCompletionToolCall>

/** The reasoning detail with encrypted reasoning data that may be redacted or protected. */
export const InferenceEncryptedReasoningDetail = z.object({
  ...InferenceBaseReasoningDetail.shape,
  type: z.literal('reasoning.encrypted'),
  data: z.string().describe('The encrypted reasoning data generated by the model, which may be redacted or protected based on the model\'s configuration and the nature of the reasoning information.')
}).meta({ id: 'InferenceEncryptedReasoningDetail' })
export type InferenceEncryptedReasoningDetail = z.infer<typeof InferenceEncryptedReasoningDetail>

/** The reasoning summary detail includes a high-level summary of the model's reasoning process. */
export const InferenceSummaryReasoningDetail = z.object({
  ...InferenceBaseReasoningDetail.shape,
  type: z.literal('reasoning.summary'),
  summary: z.string().describe('The summary of the reasoning process generated by the model, which provides an overview of the key points and conclusions reached during the reasoning process.')
}).meta({ id: 'InferenceSummaryReasoningDetail' })
export type InferenceSummaryReasoningDetail = z.infer<typeof InferenceSummaryReasoningDetail>

/** The reasoning text detail includes plaintext reasoning with optional signature verification. */
export const InferenceTextReasoningDetail = z.object({
  ...InferenceBaseReasoningDetail.shape,
  type: z.literal('reasoning.text'),
  signature: z.string().describe('The signature of the reasoning text, which can be used to verify the authenticity and integrity of the reasoning information provided by the model.').optional(),
  text: z.string().describe('The plaintext reasoning generated by the model, which provides a detailed explanation of the model\'s reasoning process in human-readable form.').optional()
}).meta({ id: 'InferenceTextReasoningDetail' })
export type InferenceTextReasoningDetail = z.infer<typeof InferenceTextReasoningDetail>

/**
 * Type representing the different types of reasoning details that can be included in the response from the model.
 * Currently supported only for `elastic` provider.
 */
export const InferenceReasoningDetail = z.union([InferenceEncryptedReasoningDetail, InferenceSummaryReasoningDetail, InferenceTextReasoningDetail]).meta({ id: 'InferenceReasoningDetail' })
export type InferenceReasoningDetail = z.infer<typeof InferenceReasoningDetail>

/** The message returned by the model. */
export const InferenceChatCompletionMessage = z.object({
  content: z.string().describe('The content of the message.').optional(),
  refusal: z.string().describe('The refusal message generated by the model.').optional(),
  role: z.string().describe('The role of the message author.').optional(),
  reasoning: z.string().describe('The reasoning generated by the model as plaintext. Currently supported only for the `elastic` provider.').optional(),
  tool_calls: z.array(InferenceChatCompletionToolCall).describe('The tool calls generated by the model.').optional(),
  reasoning_details: z.array(z.lazy(() => InferenceReasoningDetail)).describe('The reasoning details generated by the model as structured data. Currently supported only for the `elastic` provider.').optional()
}).meta({ id: 'InferenceChatCompletionMessage' })
export type InferenceChatCompletionMessage = z.infer<typeof InferenceChatCompletionMessage>

/** A single completion choice returned by the model. */
export const InferenceChatCompletionChoice = z.object({
  message: InferenceChatCompletionMessage.describe('The message generated by the model for this choice.'),
  finish_reason: z.string().describe('The reason the model stopped generating tokens. Common values are `stop` (natural stopping point) and `tool_calls` (the model called a tool). Omitted when the reason is not available.').optional(),
  index: z.lazy(() => integer).describe('The index of this choice in the list of choices.')
}).meta({ id: 'InferenceChatCompletionChoice' })
export type InferenceChatCompletionChoice = z.infer<typeof InferenceChatCompletionChoice>

/** Breakdown of tokens used in the request. */
export const InferenceChatCompletionCompletionTokensDetails = z.object({
  reasoning_tokens: z.lazy(() => integer).describe('The number of tokens used for reasoning by the model.').optional()
}).meta({ id: 'InferenceChatCompletionCompletionTokensDetails' })
export type InferenceChatCompletionCompletionTokensDetails = z.infer<typeof InferenceChatCompletionCompletionTokensDetails>

/** Breakdown of tokens used in the prompt. */
export const InferenceChatCompletionPromptTokensDetails = z.object({
  cached_tokens: z.lazy(() => integer).describe('The number of tokens that were cached from a previous request.').optional(),
  cache_write_tokens: z.lazy(() => integer).describe('The number of tokens written to the cache.').optional()
}).meta({ id: 'InferenceChatCompletionPromptTokensDetails' })
export type InferenceChatCompletionPromptTokensDetails = z.infer<typeof InferenceChatCompletionPromptTokensDetails>

/** Token usage statistics for the request. */
export const InferenceChatCompletionUsage = z.object({
  completion_tokens: z.lazy(() => integer).describe('The number of tokens in the generated completion.'),
  prompt_tokens: z.lazy(() => integer).describe('The number of tokens in the prompt.'),
  total_tokens: z.lazy(() => integer).describe('The total number of tokens used (prompt + completion).'),
  prompt_tokens_details: InferenceChatCompletionPromptTokensDetails.describe('Breakdown of the tokens used in the prompt. Omitted when no details are available.').optional(),
  completion_tokens_details: InferenceChatCompletionCompletionTokensDetails.describe('Breakdown of the tokens used in the completion. Omitted when no details are available.').optional()
}).meta({ id: 'InferenceChatCompletionUsage' })
export type InferenceChatCompletionUsage = z.infer<typeof InferenceChatCompletionUsage>

/** The response format for the non-streaming unified chat completion request. */
export const InferenceChatCompletionInferenceResult = z.object({
  id: z.string().describe('The unique identifier for the completion.'),
  choices: z.array(InferenceChatCompletionChoice).describe('The list of completion choices the model generated for the input message.').optional(),
  model: z.string().describe('The model used to generate the completion.'),
  object: z.string().describe('The object type.'),
  usage: InferenceChatCompletionUsage.describe('The token usage statistics for the completion request. Omitted when usage information is not available.').optional()
}).meta({ id: 'InferenceChatCompletionInferenceResult' })
export type InferenceChatCompletionInferenceResult = z.infer<typeof InferenceChatCompletionInferenceResult>

/**
 * Perform non-streaming chat completion inference on the service.
 *
 * The chat completion inference API enables rich responses for chat completion tasks.
 * It only works with the `chat_completion` task type.
 *
 * NOTE: The `chat_completion` task type supports both streaming and non-streaming.
 * The Chat completion inference API provides more comprehensive customization options through more fields and function calling support.
 * To determine whether a given inference service supports this task type, please see the page for that service.
 *
 * These services support non-streaming chat completion inference:
 * - AI21
 * - Azure OpenAI
 * - Deepseek
 * - Elastic
 * - FireworksAI
 * - Groq
 * - Huggingface
 * - IBMWatsonX
 * - Llama
 * - Mistral
 * - NVIDIA
 * - OpenAI
 * - OpenShiftAI
 */
export const InferenceNonStreamingChatCompletionRequest = z.object({
  inference_id: z.lazy(() => Id).describe('The inference Id').meta({ found_in: 'path' }),
  timeout: z.lazy(() => Duration).describe('Specifies the amount of time to wait for the inference request to complete.').optional().meta({ found_in: 'query' }),
  chat_completion_request: z.lazy(() => InferenceRequestChatCompletion).optional().meta({ found_in: 'body' })
}).meta({ id: 'InferenceNonStreamingChatCompletionRequest' })
export type InferenceNonStreamingChatCompletionRequest = z.infer<typeof InferenceNonStreamingChatCompletionRequest>

export const InferenceNonStreamingChatCompletionResponse = InferenceChatCompletionInferenceResult.meta({ id: 'InferenceNonStreamingChatCompletionResponse' })
export type InferenceNonStreamingChatCompletionResponse = z.infer<typeof InferenceNonStreamingChatCompletionResponse>
