/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/* eslint-disable @typescript-eslint/no-redeclare */
import { z } from 'zod'

import { integer } from './_types.js'

/**
 * Authenticate OpenID Connect.
 *
 * Exchange an OpenID Connect authentication response message for an Elasticsearch internal access token and refresh token that can be subsequently used for authentication.
 *
 * Elasticsearch exposes all the necessary OpenID Connect related functionality with the OpenID Connect APIs.
 * These APIs are used internally by Kibana in order to provide OpenID Connect based authentication, but can also be used by other, custom web applications or other clients.
 */
export const SecurityOidcAuthenticateRequest = z.object({
  nonce: z.string().describe('Associate a client session with an ID token and mitigate replay attacks. This value needs to be the same as the one that was provided to the `/_security/oidc/prepare` API or the one that was generated by Elasticsearch and included in the response to that call.').meta({ found_in: 'body' }),
  realm: z.string().describe('The name of the OpenID Connect realm. This property is useful in cases where multiple realms are defined.').optional().meta({ found_in: 'body' }),
  redirect_uri: z.string().describe('The URL to which the OpenID Connect Provider redirected the User Agent in response to an authentication request after a successful authentication. This URL must be provided as-is (URL encoded), taken from the body of the response or as the value of a location header in the response from the OpenID Connect Provider.').meta({ found_in: 'body' }),
  state: z.string().describe('Maintain state between the authentication request and the response. This value needs to be the same as the one that was provided to the `/_security/oidc/prepare` API or the one that was generated by Elasticsearch and included in the response to that call.').meta({ found_in: 'body' })
}).meta({ id: 'SecurityOidcAuthenticateRequest' })
export type SecurityOidcAuthenticateRequest = z.infer<typeof SecurityOidcAuthenticateRequest>

export const SecurityOidcAuthenticateResponse = z.object({
  access_token: z.string().describe('The Elasticsearch access token.'),
  expires_in: z.lazy(() => integer).describe('The duration (in seconds) of the tokens.'),
  refresh_token: z.string().describe('The Elasticsearch refresh token.'),
  type: z.string().describe('The type of token.')
}).meta({ id: 'SecurityOidcAuthenticateResponse' })
export type SecurityOidcAuthenticateResponse = z.infer<typeof SecurityOidcAuthenticateResponse>
