/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/* eslint-disable @typescript-eslint/no-redeclare */
import { z } from 'zod'

import { Duration, ExpandWildcards, Indices, Metadata, Name } from './_types.js'
import { SnapshotSnapshotInfo } from './snapshot.js'

/**
 * Create a snapshot.
 *
 * Take a snapshot of a cluster or of data streams and indices.
 */
export const SnapshotCreateRequest = z.object({
  repository: z.lazy(() => Name).describe('The name of the repository for the snapshot.').meta({ found_in: 'path' }),
  snapshot: z.lazy(() => Name).describe('The name of the snapshot. It supportes date math. It must be unique in the repository.').meta({ found_in: 'path' }),
  master_timeout: z.lazy(() => Duration).describe('The period to wait for a connection to the master node. If no response is received before the timeout expires, the request fails and returns an error.').optional().meta({ found_in: 'query' }),
  wait_for_completion: z.boolean().describe('If `true`, the request returns a response when the snapshot is complete. If `false`, the request returns a response when the snapshot initializes.').optional().meta({ found_in: 'query' }),
  expand_wildcards: z.lazy(() => ExpandWildcards).describe('Determines how wildcard patterns in the `indices` parameter match data streams and indices. It supports comma-separated values such as `open,hidden`.').optional().meta({ found_in: 'body' }),
  feature_states: z.array(z.string()).describe('The feature states to include in the snapshot. Each feature state includes one or more system indices containing related data. You can view a list of eligible features using the get features API. If `include_global_state` is `true`, all current feature states are included by default. If `include_global_state` is `false`, no feature states are included by default. Note that specifying an empty array will result in the default behavior. To exclude all feature states, regardless of the `include_global_state` value, specify an array with only the value `none` (`["none"]`).').optional().meta({ found_in: 'body' }),
  ignore_unavailable: z.boolean().describe('If `true`, the request ignores data streams and indices in `indices` that are missing or closed. If `false`, the request returns an error for any data stream or index that is missing or closed.').optional().meta({ found_in: 'body' }),
  include_global_state: z.boolean().describe('If `true`, the current cluster state is included in the snapshot. The cluster state includes persistent cluster settings, composable index templates, legacy index templates, ingest pipelines, and ILM policies. It also includes data stored in system indices, such as Watches and task records (configurable via `feature_states`).').optional().meta({ found_in: 'body' }),
  indices: z.lazy(() => Indices).describe('A comma-separated list of data streams and indices to include in the snapshot. It supports a multi-target syntax. The default is an empty array (`[]`), which includes all regular data streams and regular indices. To exclude all data streams and indices, use `-*`. You can\'t use this parameter to include or exclude system indices or system data streams from a snapshot. Use `feature_states` instead.').optional().meta({ found_in: 'body' }),
  metadata: z.lazy(() => Metadata).describe('Arbitrary metadata to the snapshot, such as a record of who took the snapshot, why it was taken, or any other useful data. It can have any contents but it must be less than 1024 bytes. This information is not automatically generated by Elasticsearch.').optional().meta({ found_in: 'body' }),
  partial: z.boolean().describe('If `true`, allows the snapshot to proceed even if some of the target shards are unavailable. In this case, the resulting snapshot will not contain snapshots of the unavailable target shards, and will report its state as `PARTIAL`. Additionally, if `true`, allows index metadata operations such as deletions while the snapshot is in progress. This is almost always preferable to failing the snapshot completely when a single shard is unavailable, and blocking index metadata operations. If `false`, the entire restore operation will fail if one or more indices included in the snapshot do not have all primary shards available, and index metadata operations such as deletions will be forbidden until the snapshot completes.').optional().meta({ found_in: 'body' })
}).meta({ id: 'SnapshotCreateRequest' })
export type SnapshotCreateRequest = z.infer<typeof SnapshotCreateRequest>

export const SnapshotCreateResponse = z.object({
  accepted: z.boolean().describe('Equals `true` if the snapshot was accepted. Present when the request had `wait_for_completion` set to `false`').optional(),
  snapshot: SnapshotSnapshotInfo.describe('Snapshot information. Present when the request had `wait_for_completion` set to `true`').optional()
}).meta({ id: 'SnapshotCreateResponse' })
export type SnapshotCreateResponse = z.infer<typeof SnapshotCreateResponse>
