/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source open api file,
 * and elastic/elastic-client-generator-js to regenerate this file again.
 */

import type { JsonSchemaObject } from '../../../json-schema.ts'
import _inputSchemaRaw from '../../../es/json/ccr.forget_follower.request.json' with { type: 'json' }
import type { EsApiDefinition } from '../types.ts'

const _inputSchema = _inputSchemaRaw as unknown as JsonSchemaObject

export const ccr_forget_follower_definitions: EsApiDefinition[] = [
  {
    name: 'forget-follower',
    namespace: 'ccr',
    description: 'Forget a follower.',
    method: 'POST',
    path: '/{index}/_ccr/forget_follower',
    destructive: true,
    input: _inputSchema,
  },
]
