/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source open api file,
 * and elastic/elastic-client-generator-js to regenerate this file again.
 */

import type { JsonSchemaObject } from '../../../json-schema.ts'
import _inputSchemaRaw from '../../json/ccr.resume_auto_follow_pattern.request.json' with { type: 'json' }
import type { EsApiDefinition } from '../types.ts'

const _inputSchema = _inputSchemaRaw as unknown as JsonSchemaObject

export const ccr_resume_auto_follow_pattern_definitions: EsApiDefinition[] = [
  {
    name: 'resume-auto-follow-pattern',
    namespace: 'ccr',
    description: 'Resume an auto-follow pattern.',
    method: 'POST',
    path: '/_ccr/auto_follow/{name}/resume',
    destructive: true,
    input: _inputSchema,
  },
]
