/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source open api file,
 * and elastic/elastic-client-generator-js to regenerate this file again.
 */

import type { JsonSchemaObject } from '../../../json-schema.ts'
import _inputSchemaRaw from '../../../es/json/close_point_in_time.request.json' with { type: 'json' }
import type { EsApiDefinition } from '../types.ts'

const _inputSchema = _inputSchemaRaw as unknown as JsonSchemaObject

export const close_point_in_time_definitions: EsApiDefinition[] = [
  {
    name: 'close-point-in-time',
    description: 'Close a point in time.',
    method: 'DELETE',
    path: '/_pit',
    destructive: true,
    input: _inputSchema,
  },
]
