/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source open api file,
 * and elastic/elastic-client-generator-js to regenerate this file again.
 */

import type { JsonSchemaObject } from '../../../json-schema.ts'
import _inputSchemaRaw from '../../json/connector.sync_job_check_in.request.json' with { type: 'json' }
import type { EsApiDefinition } from '../types.ts'

const _inputSchema = _inputSchemaRaw as unknown as JsonSchemaObject

export const connector_sync_job_check_in_definitions: EsApiDefinition[] = [
  {
    name: 'sync-job-check-in',
    namespace: 'connector',
    description: 'Check in a connector sync job.',
    method: 'PUT',
    path: '/_connector/_sync_job/{connector_sync_job_id}/_check_in',
    destructive: true,
    input: _inputSchema,
  },
]
