/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source open api file,
 * and elastic/elastic-client-generator-js to regenerate this file again.
 */

import type { JsonSchemaObject } from '../../../json-schema.ts'
import _inputSchemaRaw from '../../json/connector.get.request.json'
import type { EsApiDefinition } from '../types.ts'

const _inputSchema = _inputSchemaRaw as unknown as JsonSchemaObject

export const connector_get_definitions: EsApiDefinition[] = [
  {
    name: 'get',
    namespace: 'connector',
    description: 'Get a connector.',
    method: 'GET',
    path: '/_connector/{connector_id}',
    destructive: false,
    input: _inputSchema,
  },
]
