/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source open api file,
 * and elastic/elastic-client-generator-js to regenerate this file again.
 */

import type { JsonSchemaObject } from '../../../json-schema.ts'
import _inputSchemaRaw from '../../json/esql.put_view.request.json'
import type { EsApiDefinition } from '../types.ts'

const _inputSchema = _inputSchemaRaw as unknown as JsonSchemaObject

export const esql_put_view_definitions: EsApiDefinition[] = [
  {
    name: 'put-view',
    namespace: 'esql',
    description: 'Create or update an ES|QL view.',
    method: 'PUT',
    path: '/_query/view/{name}',
    destructive: true,
    input: _inputSchema,
  },
]
