/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source open api file,
 * and elastic/elastic-client-generator-js to regenerate this file again.
 */

import type { JsonSchemaObject } from '../../../json-schema.ts'
import _inputSchemaRaw from '../../json/get_reindex.request.json'
import type { EsApiDefinition } from '../types.ts'

const _inputSchema = _inputSchemaRaw as unknown as JsonSchemaObject

export const get_reindex_definitions: EsApiDefinition[] = [
  {
    name: 'get-reindex',
    description: 'Get the status and progress of a specific reindex task.',
    method: 'GET',
    path: '/_reindex/{task_id}',
    destructive: false,
    input: _inputSchema,
  },
]
