/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source open api file,
 * and elastic/elastic-client-generator-js to regenerate this file again.
 */

import type { JsonSchemaObject } from '../../../json-schema.ts'
import _inputSchemaRaw from '../../json/indices.delete_data_stream_options.request.json' with { type: 'json' }
import type { EsApiDefinition } from '../types.ts'

const _inputSchema = _inputSchemaRaw as unknown as JsonSchemaObject

export const indices_delete_data_stream_options_definitions: EsApiDefinition[] = [
  {
    name: 'delete-data-stream-options',
    namespace: 'indices',
    description: 'Delete data stream options.',
    method: 'DELETE',
    path: '/_data_stream/{name}/_options',
    destructive: true,
    input: _inputSchema,
  },
]
