/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source open api file,
 * and elastic/elastic-client-generator-js to regenerate this file again.
 */

import type { JsonSchemaObject } from '../../../json-schema.ts'
import _inputSchemaRaw from '../../json/indices.migrate_reindex.request.json'
import type { EsApiDefinition } from '../types.ts'

const _inputSchema = _inputSchemaRaw as unknown as JsonSchemaObject

export const indices_migrate_reindex_definitions: EsApiDefinition[] = [
  {
    name: 'migrate-reindex',
    namespace: 'indices',
    description: 'Reindex legacy backing indices.',
    method: 'POST',
    path: '/_migration/reindex',
    destructive: true,
    input: _inputSchema,
  },
]
