/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source open api file,
 * and elastic/elastic-client-generator-js to regenerate this file again.
 */

import type { JsonSchemaObject } from '../../../json-schema.ts'
import _inputSchemaRaw from '../../json/indices.clone.request.json'
import type { EsApiDefinition } from '../types.ts'

const _inputSchema = _inputSchemaRaw as unknown as JsonSchemaObject

export const indices_clone_definitions: EsApiDefinition[] = [
  {
    name: 'clone',
    namespace: 'indices',
    description: 'Clone an index.',
    method: 'PUT',
    path: '/{index}/_clone/{target}',
    destructive: true,
    input: _inputSchema,
  },
]
