/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source open api file,
 * and elastic/elastic-client-generator-js to regenerate this file again.
 */

import type { JsonSchemaObject } from '../../../json-schema.ts'
import _inputSchemaRaw from '../../../es/json/indices.migrate_to_data_stream.request.json' with { type: 'json' }
import type { EsApiDefinition } from '../types.ts'

const _inputSchema = _inputSchemaRaw as unknown as JsonSchemaObject

export const indices_migrate_to_data_stream_definitions: EsApiDefinition[] = [
  {
    name: 'migrate-to-data-stream',
    namespace: 'indices',
    description: 'Convert an index alias to a data stream.',
    method: 'POST',
    path: '/_data_stream/_migrate/{name}',
    destructive: true,
    input: _inputSchema,
  },
]
