/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source open api file,
 * and elastic/elastic-client-generator-js to regenerate this file again.
 */

import type { JsonSchemaObject } from '../../../json-schema.ts'
import _inputSchemaRaw from '../../json/inference.put_region_policy.request.json' with { type: 'json' }
import type { EsApiDefinition } from '../types.ts'

const _inputSchema = _inputSchemaRaw as unknown as JsonSchemaObject

export const inference_put_region_policy_definitions: EsApiDefinition[] = [
  {
    name: 'put-region-policy',
    namespace: 'inference',
    description: 'Create or update the inference region policy.',
    method: 'PUT',
    path: '/_inference/_region_policy',
    destructive: true,
    input: _inputSchema,
  },
]
