/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source open api file,
 * and elastic/elastic-client-generator-js to regenerate this file again.
 */

import type { JsonSchemaObject } from '../../../json-schema.ts'
import _inputSchemaRaw from '../../json/inference.put_amazonsagemaker.request.json'
import type { EsApiDefinition } from '../types.ts'

const _inputSchema = _inputSchemaRaw as unknown as JsonSchemaObject

export const inference_put_amazonsagemaker_definitions: EsApiDefinition[] = [
  {
    name: 'put-amazonsagemaker',
    namespace: 'inference',
    description: 'Create an Amazon SageMaker inference endpoint.',
    method: 'PUT',
    path: '/_inference/{task_type}/{amazonsagemaker_inference_id}',
    destructive: false,
    input: _inputSchema,
  },
]
