/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source open api file,
 * and elastic/elastic-client-generator-js to regenerate this file again.
 */

import { z } from 'zod'
import { LogstashGetPipelineRequest } from '../../../es/schemas/logstash.get_pipeline.ts'

import type { JsonSchemaObject } from '../../../json-schema.ts'
import type { EsApiDefinition } from '../types.ts'

const _rawSchema = z.toJSONSchema(LogstashGetPipelineRequest) as Record<string, unknown>
const _props = _rawSchema['properties'] as Record<string, Record<string, unknown>> | undefined
if (_props != null) {
  for (const prop of Object.values(_props)) {
    if (prop['found_in'] != null) { prop['x-found-in'] = prop['found_in']; delete prop['found_in'] }
  }
}
const _inputSchema = _rawSchema as JsonSchemaObject

export const logstash_get_pipeline_definitions: EsApiDefinition[] = [
  {
    name: 'get-pipeline',
    namespace: 'logstash',
    description: 'Get Logstash pipelines.',
    method: 'GET',
    path: '/_logstash/pipeline/{id}',
    input: _inputSchema,
  },
]
