/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source open api file,
 * and elastic/elastic-client-generator-js to regenerate this file again.
 */

import type { JsonSchemaObject } from '../../../json-schema.ts'
import _inputSchemaRaw from '../../../es/json/ml.get_data_frame_analytics_stats.request.json' with { type: 'json' }
import type { EsApiDefinition } from '../types.ts'

const _inputSchema = _inputSchemaRaw as unknown as JsonSchemaObject

export const ml_get_data_frame_analytics_stats_definitions: EsApiDefinition[] = [
  {
    name: 'get-data-frame-analytics-stats',
    namespace: 'ml',
    description: 'Get data frame analytics job stats.',
    method: 'GET',
    path: '/_ml/data_frame/analytics/{id}/_stats',
    destructive: false,
    input: _inputSchema,
  },
]
