/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source open api file,
 * and elastic/elastic-client-generator-js to regenerate this file again.
 */

import type { JsonSchemaObject } from '../../../json-schema.ts'
import _inputSchemaRaw from '../../../es/json/ml.put_trained_model_alias.request.json' with { type: 'json' }
import type { EsApiDefinition } from '../types.ts'

const _inputSchema = _inputSchemaRaw as unknown as JsonSchemaObject

export const ml_put_trained_model_alias_definitions: EsApiDefinition[] = [
  {
    name: 'put-trained-model-alias',
    namespace: 'ml',
    description: 'Create or update a trained model alias.',
    method: 'PUT',
    path: '/_ml/trained_models/{model_id}/model_aliases/{model_alias}',
    destructive: true,
    input: _inputSchema,
  },
]
