/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source open api file,
 * and elastic/elastic-client-generator-js to regenerate this file again.
 */

import { z } from 'zod'
import { MlPutFilterRequest } from '../../../es/schemas/ml_put_filter.ts'

import type { JsonSchemaObject } from '../../../json-schema.ts'
import type { EsApiDefinition } from '../types.ts'

const _rawSchema = z.toJSONSchema(MlPutFilterRequest) as Record<string, unknown>
const _props = _rawSchema['properties'] as Record<string, Record<string, unknown>> | undefined
if (_props != null) {
  for (const prop of Object.values(_props)) {
    if (prop['found_in'] != null) { prop['x-found-in'] = prop['found_in']; delete prop['found_in'] }
  }
}
const _inputSchema = _rawSchema as JsonSchemaObject

export const ml_put_filter_definitions: EsApiDefinition[] = [
  {
    name: 'put-filter',
    namespace: 'ml',
    description: 'Create a filter.',
    method: 'PUT',
    path: '/_ml/filters/{filter_id}',
    input: _inputSchema,
  },
]
