/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source open api file,
 * and elastic/elastic-client-generator-js to regenerate this file again.
 */

import type { JsonSchemaObject } from '../../../json-schema.ts'
import _inputSchemaRaw from '../../../es/json/project.delete_routing.request.json' with { type: 'json' }
import type { EsApiDefinition } from '../types.ts'

const _inputSchema = _inputSchemaRaw as unknown as JsonSchemaObject

export const project_delete_routing_definitions: EsApiDefinition[] = [
  {
    name: 'delete-routing',
    namespace: 'project',
    description: 'Delete a project routing expression.',
    method: 'DELETE',
    path: '/_project_routing/{name}',
    destructive: true,
    input: _inputSchema,
  },
]
