/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source open api file,
 * and elastic/elastic-client-generator-js to regenerate this file again.
 */

import type { JsonSchemaObject } from '../../../json-schema.ts'
import _inputSchemaRaw from '../../../es/json/render_search_template.request.json' with { type: 'json' }
import type { EsApiDefinition } from '../types.ts'

const _inputSchema = _inputSchemaRaw as unknown as JsonSchemaObject

export const render_search_template_definitions: EsApiDefinition[] = [
  {
    name: 'render-search-template',
    description: 'Render a search template.',
    method: 'GET',
    path: '/_render/template/{id}',
    destructive: false,
    input: _inputSchema,
  },
]
