/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source open api file,
 * and elastic/elastic-client-generator-js to regenerate this file again.
 */

import type { JsonSchemaObject } from '../../../json-schema.ts'
import _inputSchemaRaw from '../../../es/json/search_application.put_behavioral_analytics.request.json' with { type: 'json' }
import type { EsApiDefinition } from '../types.ts'

const _inputSchema = _inputSchemaRaw as unknown as JsonSchemaObject

export const search_application_put_behavioral_analytics_definitions: EsApiDefinition[] = [
  {
    name: 'put-behavioral-analytics',
    namespace: 'search-application',
    description: 'Create a behavioral analytics collection.',
    method: 'PUT',
    path: '/_application/analytics/{name}',
    destructive: false,
    input: _inputSchema,
  },
]
