/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source open api file,
 * and elastic/elastic-client-generator-js to regenerate this file again.
 */

import type { JsonSchemaObject } from '../../../json-schema.ts'
import _inputSchemaRaw from '../../json/security.put_role.request.json'
import type { EsApiDefinition } from '../types.ts'

const _inputSchema = _inputSchemaRaw as unknown as JsonSchemaObject

export const security_put_role_definitions: EsApiDefinition[] = [
  {
    name: 'put-role',
    namespace: 'security',
    description: 'Create or update roles.',
    method: 'PUT',
    path: '/_security/role/{name}',
    destructive: true,
    input: _inputSchema,
  },
]
