/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source open api file,
 * and elastic/elastic-client-generator-js to regenerate this file again.
 */

import type { JsonSchemaObject } from '../../../json-schema.ts'
import _inputSchemaRaw from '../../json/security.disable_user_profile.request.json' with { type: 'json' }
import type { EsApiDefinition } from '../types.ts'

const _inputSchema = _inputSchemaRaw as unknown as JsonSchemaObject

export const security_disable_user_profile_definitions: EsApiDefinition[] = [
  {
    name: 'disable-user-profile',
    namespace: 'security',
    description: 'Disable a user profile.',
    method: 'PUT',
    path: '/_security/profile/{uid}/_disable',
    destructive: true,
    input: _inputSchema,
  },
]
