/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source open api file,
 * and elastic/elastic-client-generator-js to regenerate this file again.
 */

import { z } from 'zod'
import { SecurityDeleteServiceTokenRequest } from '../../../es/schemas/security_delete_service_token.ts'

import type { JsonSchemaObject } from '../../../json-schema.ts'
import type { EsApiDefinition } from '../types.ts'

const _rawSchema = z.toJSONSchema(SecurityDeleteServiceTokenRequest) as Record<string, unknown>
const _props = _rawSchema['properties'] as Record<string, Record<string, unknown>> | undefined
if (_props != null) {
  for (const prop of Object.values(_props)) {
    if (prop['found_in'] != null) { prop['x-found-in'] = prop['found_in']; delete prop['found_in'] }
  }
}
const _inputSchema = _rawSchema as JsonSchemaObject

export const security_delete_service_token_definitions: EsApiDefinition[] = [
  {
    name: 'delete-service-token',
    namespace: 'security',
    description: 'Delete service account tokens.',
    method: 'DELETE',
    path: '/_security/service/{namespace}/{service}/credential/token/{name}',
    input: _inputSchema,
  },
]
