/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source open api file,
 * and elastic/elastic-client-generator-js to regenerate this file again.
 */

import type { JsonSchemaObject } from '../../../json-schema.ts'
import _inputSchemaRaw from '../../json/security.create_service_token.request.json'
import type { EsApiDefinition } from '../types.ts'

const _inputSchema = _inputSchemaRaw as unknown as JsonSchemaObject

export const security_create_service_token_definitions: EsApiDefinition[] = [
  {
    name: 'create-service-token',
    namespace: 'security',
    description: 'Create a service account token.',
    method: 'PUT',
    path: '/_security/service/{namespace}/{service}/credential/token/{name}',
    destructive: false,
    input: _inputSchema,
  },
]
