/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source open api file,
 * and elastic/elastic-client-generator-js to regenerate this file again.
 */

import type { JsonSchemaObject } from '../../../json-schema.ts'
import _inputSchemaRaw from '../../../es/json/security.get_api_key.request.json' with { type: 'json' }
import type { EsApiDefinition } from '../types.ts'

const _inputSchema = _inputSchemaRaw as unknown as JsonSchemaObject

export const security_get_api_key_definitions: EsApiDefinition[] = [
  {
    name: 'get-api-key',
    namespace: 'security',
    description: 'Get API key information.',
    method: 'GET',
    path: '/_security/api_key',
    destructive: false,
    input: _inputSchema,
  },
]
