/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source open api file,
 * and elastic/elastic-client-generator-js to regenerate this file again.
 */

import type { JsonSchemaObject } from '../../../json-schema.ts'
import _inputSchemaRaw from '../../json/security.clear_cached_privileges.request.json'
import type { EsApiDefinition } from '../types.ts'

const _inputSchema = _inputSchemaRaw as unknown as JsonSchemaObject

export const security_clear_cached_privileges_definitions: EsApiDefinition[] = [
  {
    name: 'clear-cached-privileges',
    namespace: 'security',
    description: 'Clear the privileges cache.',
    method: 'POST',
    path: '/_security/privilege/{application}/_clear_cache',
    destructive: true,
    input: _inputSchema,
  },
]
