/*
 * Copyright Elasticsearch B.V. and contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was automatically generated by elastic/elastic-client-generator-js.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source open api file,
 * and elastic/elastic-client-generator-js to regenerate this file again.
 */

import type { JsonSchemaObject } from '../../../json-schema.ts'
import _inputSchemaRaw from '../../json/slm.get_lifecycle.request.json' with { type: 'json' }
import type { EsApiDefinition } from '../types.ts'

const _inputSchema = _inputSchemaRaw as unknown as JsonSchemaObject

export const slm_get_lifecycle_definitions: EsApiDefinition[] = [
  {
    name: 'get-lifecycle',
    namespace: 'slm',
    description: 'Get policy information.',
    method: 'GET',
    path: '/_slm/policy/{policy_id}',
    destructive: false,
    input: _inputSchema,
  },
]
