name: Release

on:
  push:
    branches: [main]

permissions: {}

jobs:
  release-please:
    runs-on: ubuntu-latest
    outputs:
      release_created: ${{ steps.release.outputs.release_created }}
    permissions:
      id-token: write
    steps:
      - name: Fetch ephemeral Github token
        id: fetch-token
        uses: elastic/ci-gh-actions/fetch-github-token@2feb1c6f5086cf8e06f61ef35e275abed3456f7b # v1.5.3
        with:
          vault-instance: "ci-prod"
      - uses: googleapis/release-please-action@45996ed1f6d02564a971a2fa1b5860e934307cf7 # v5
        id: release
        with:
          config-file: .github/release-please-config.json
          manifest-file: .github/.release-please-manifest.json
          token: ${{ steps.fetch-token.outputs.token }}

  publish:
    needs: release-please
    if: ${{ needs.release-please.outputs.release_created == 'true' }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7
      - uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6
        with:
          persist-credentials: false
          node-version: 24
          registry-url: https://registry.npmjs.org
      - name: Install
        run: npm install
      - name: Build
        run: npm run build
      - name: Run tests
        run: npm test
      - name: Publish
        run: |
          VERSION=$(node -p "require('./package.json').version")
          if [[ "$VERSION" == *alpha* ]]; then TAG="--tag alpha"
          elif [[ "$VERSION" == *beta* ]]; then TAG="--tag beta"
          fi
          npm publish --provenance --access public $TAG
